src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>The first line of the address</description>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the address</description>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The postal City for Contact</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>The Zip Code or Postal Code</description>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <description>The State or Province for Postal address</description>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <description>Place to enter the verbatim from the caller</description>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>NA</fullName>
        <active>true</active>
        <businessProcess>Country Defaults</businessProcess>
        <description>NA Cases</description>
        <label>NA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Contact__c.object
<CustomObject>
    <description>Junction object between Case and Contact allowing multiple Contacts per Case.</description>
    <fields>
        <fullName>Case_Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true is the primary contact on the Case - can only be one, enforced via trigger</description>
        <inlineHelpText>If true is the primary contact on the Case - can only be one, enforced via trigger</inlineHelpText>
        <label>Case Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Contacts</relationshipLabel>
        <relationshipName>Case_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Contacts (*TBC*)</relationshipLabel>
        <relationshipName>Case_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Contact</label>
    <nameField>
        <displayFormat>CCON-{000000}</displayFormat>
        <label>Case Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                    <default>true</default>
                    <label>United States of America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_1__c</fullName>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_2__c</fullName>
        <label>Primary Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>This is the Country in the Mailing address</description>
        <label>Primary Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <label>Primary Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <label>Primary State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/classes/multipleContacts_test.cls
/*
 * CR47 Multiple Contacts 
 * christopher.macduff@accenture.com
 */ 
@isTest
public class multipleContacts_test {
    @testSetup
    static void setupData(){
        CustomSettingDataFactory.countryRegionSetup(); //Country/Region custom setting records
        
        Map<String, Id> rtMap = sf_GlobalUtilityClass.recordTypeMap;
        Account exAccount = new Account(
            RecordTypeId = rtMap.get('Household'),
            Address_Line_1__c = '1 Procter & Gamble Plaza',
			Address_Line_2__c = '',
			City__c = 'Cincinnati',
			State_Province__c = 'OH',
			Postal_Code__c = '45202',
			Country__c = 'United States of America',
            name = 'Test existing Consumer Account'
        );
        insert exAccount;
        
        Contact exCon = new Contact(
            RecordTypeId = rtMap.get('Consumer'),
            AccountId = exAccount.Id,
            FirstName = 'Ringo',
            LastName = 'Starr',
            Email = math.random()+'@pgdev.org',
            Primary_Address_Line_1__c = 'Procter & Gamble Plaza',
            Primary_Address_Line_2__c = '',
			Primary_City__c = 'Cincinnati',
			Primary_State_Province__c = 'OH',
			Primary_Postal_Code__c = '45202',            
			Primary_Country__c = 'United States of America'
        );
        insert exCon;
        
        List<Case> testCases = new List<Case>();
        
        Case testCase1 = new Case(
            RecordTypeId = rtMap.get('NA'),
            contactId = exCon.Id,
            accountId = exAccount.Id,
            Subject = 'Multiple Contact Test Case',
            Summary__c = 'Summary for the Multiple Contact Test Case',
            Priority = '3',
            Origin = 'Email'
        );
        testCases.add(testCase1);
        
		Case testCase2 = new Case(
            RecordTypeId = rtMap.get('NA'),
            Subject = 'Empty Case',
            Summary__c = 'Blank Cases with no Contact/Account',
            Priority = '3',
            Origin = 'Email'
        );
        testCases.add(testCase2);
        insert testCases;
    }

    /****************************************************************
     * Covers:                                                      *
     * Case.ContactId being manually updated with a Contact not     *
     * in the existing Case Contact list                            *
    ****************************************************************/ 
    @isTest
    static void updateCaseContactIdTest(){
        Case testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE ContactId != null LIMIT 1];
        Id origConId = testCase.ContactId;
        Contact newPrimCon = new Contact(
            lastName = 'A wild new primary Contact appears'
        );
        insert newPrimCon;

        testCase.ContactId = newPrimCon.Id;
        test.startTest();
            try{
                update testCase;
            }
            catch(exception e){
                //what to assert here...
            }
        test.stopTest();

        testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE Id = :testCase.Id];
        //Assert Case.ContactId has NOT changed
        system.assertEquals(origConId, testCase.ContactId);
    }

	/****************************************************************
     * Covers:														*
     * Multiple Primary test										*
	****************************************************************/ 
    @isTest
    static void multiplePrimaryTest(){
        Contact secCon = new Contact(
            lastName = 'A wild new primary Contact appears'
        );
        insert secCon;

        Case testCase = [SELECT Id, ContactId FROM Case WHERE Subject = 'Multiple Contact Test Case'];
        Contact primCon = [SELECT Id FROM Contact WHERE Id = :testCase.ContactId];
        
        List<Case_Contact__c> ccList = [SELECT Id, Contact__c, Case__c, Case_Primary_Contact__c FROM Case_Contact__c WHERE Case__c = :testCase.Id];
        system.assertEquals(1, ccList.size());

        Case_Contact__c newPrimCC = new Case_Contact__c(
            Contact__c = secCon.Id,
            Case__c = testCase.Id,
            Case_Primary_Contact__c = True
        );

        test.startTest();
            try{
                insert newPrimCC;
            }
            catch(Exception e){
                system.assert(e.getMessage().contains(system.label.More_than_one_primary_contact));
            }
        test.stopTest();

        system.assertEquals(1, [SELECT Count() FROM Case_Contact__c WHERE Case__c = :testCase.Id AND Case_Primary_Contact__c = True]);
    }   
    
	/****************************************************************
     * Covers:														*
     * Creating CC from site/API									*
	****************************************************************/ 
    @isTest
    static void createSiteCCTest(){
		Case testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE ContactId = null LIMIT 1];  
        Contact testCon = [SELECT Id, Name, AccountId, RecordTypeId FROM Contact WHERE LastName = 'Starr'];  
        
        test.startTest();
			caseContactHelper.createNewCC(testCase.Id, testCon.Id, True, True);
			Case_Contact__c primCC = [SELECT Id, Contact__c, Case__c, Case_Primary_Contact__c
                                  FROM Case_Contact__c WHERE Case__c = :testCase.Id AND Case_Primary_Contact__c = True LIMIT 1];
        
        	system.assertEquals(testCon.Id, primCC.Contact__c);
        test.stopTest();
    }
    
	/****************************************************************
     * Covers:														*
     * Changing ContactId directly On Case							*
	****************************************************************/ 
    @isTest
    static void changeCaseConTest(){
		Case testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE ContactId != null LIMIT 1];  
        Contact testCon = [SELECT Id, Name, AccountId, RecordTypeId FROM Contact WHERE LastName = 'Starr'];
		Case_Contact__c exPrimCC = [SELECT Id, Contact__c, Case__c, Case_Primary_Contact__c
                                  FROM Case_Contact__c WHERE Case__c = :testCase.Id AND Case_Primary_Contact__c = True LIMIT 1];
        
        Contact newCon = new Contact(
			RecordTypeId = testCon.RecordTypeId,
            AccountId = testCon.AccountId,
            FirstName = 'George	',
            LastName = 'Harrison',
            Email = math.random()+'@pgdev.org'
        );
        insert newCon;
        
        Case_Contact__c newPrimCC = new Case_Contact__c(
            Contact__c = newCon.Id,
            Case__c = testCase.Id,
            //Case_Primary_Contact__c = True//Two primaries at same time!
            Case_Primary_Contact__c = False
        );
        insert newPrimCC;
        
        test.startTest();
            testCase.ContactId = newCon.Id;
            update testCase;
            
            List<Case_Contact__c> caseCCs = new List<Case_Contact__c>([SELECT Id, Contact__c, Case__C, Case_Primary_Contact__c FROM Case_Contact__c WHERE Case__C = :testCase.Id]);
            system.debug(logginglevel.WARN, '!!!!!!!! caseCCs: '+caseCCs);
            system.assertEquals(2, caseCCs.size());
            
            newPrimCC = [SELECT Id, Contact__c, Case__c, Case_Primary_Contact__c
                                      FROM Case_Contact__c WHERE Id = :newPrimCC.Id];
            system.assertEquals(True, newPrimCC.Case_Primary_Contact__c);
            
            exPrimCC = [SELECT Id, Contact__c, Case__c, Case_Primary_Contact__c
                                      FROM Case_Contact__c WHERE Id = :exPrimCC.Id];
            system.assertEquals(False, exPrimCC.Case_Primary_Contact__c);        
		test.stopTest();
    }
    
	/****************************************************************
     * Covers:														*
     * Adding an existing Contact to a Case							*
	****************************************************************/ 
	@isTest
    static void addExistingContact(){
		Case testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE ContactId = null LIMIT 1];  
        Contact testCon = [SELECT Id, Name FROM Contact WHERE LastName = 'Starr'];
		PageReference pageRef = Page.sf_ContactInfo;
        Test.setCurrentPage(pageRef);
		ApexPages.StandardController sc = new ApexPages.StandardController (testCase);
        
        test.startTest();
			sf_ContactInfoController ctr = new sf_ContactInfoController (sc);
        	system.assertEquals(1, ctr.contactOptions.size());//Should always say "Add new Contact"
        	
        	ctr.contactInfo.lastName = 'Starr';
        	//ctr.checkExistingContact();//No point doing this doesn't return a result in apex test
        	system.debug(Logginglevel.WARN,'!!! existingContactList: '+ctr.existingContactList);
        	
        	ctr.selectedExistingContact = testCon.Id;
        	ctr.selectExistingContact();
        	testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE Id = :testCase.Id];  
        	system.assertEquals(testCon.Id, testCase.ContactId);
        
        test.stopTest();
    }
    
	/****************************************************************
     * Covers:														*
     * Opening ctr with existing Primary Contact					*
     * Creating new Prim Contact (changing primary at same time)	*
     * Creating new non-Prim Contact								*
	****************************************************************/ 
	@isTest
    static void addNewPrimaryConTest(){
        Case testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE ContactId != null LIMIT 1];
        system.assertEquals('Ringo Starr', testCase.Contact.Name);
		PageReference pageRef = Page.sf_ContactInfo;
        Test.setCurrentPage(pageRef);

		ApexPages.StandardController sc = new ApexPages.StandardController (testCase);
        
        test.startTest();
        	sf_ContactInfoController ctr = new sf_ContactInfoController (sc);
        	system.assertEquals(2, ctr.contactOptions.size());//Ringo plus "Add new Contact"
        	system.assertEquals('Starr',ctr.contactInfo.LastName);//Confirm page defaults to current Primary Contact
        
        	//Create and save a new prim Contact
        	ctr.selectedConId = 'newCon';//Select add a new Contact
        	ctr.setContactId();
        	ctr.contactInfo.firstName = 'Bob';
        	ctr.contactInfo.lastName = 'Marley';
        	ctr.contactInfo.email = 'bob.marley@pgdev.org';
        	ctr.isPrimary = True;
        	ctr.saveContact();
        
            testCase = [SELECT Id, ContactId, Contact.Name FROM Case WHERE Id = :testCase.Id];
            system.assertEquals('Bob Marley', testCase.Contact.Name);
        	system.assertEquals(3, ctr.contactOptions.size());//Ringo, Bob plus "Add new Contact"
        
        	//Create and a save a new non-prim Contact
        	ctr.selectedConId = 'newCon';//Select add a new Contact
        	ctr.setContactId();
        	ctr.setContactOptions();
        	system.assertEquals(null, ctr.contactInfo.Id); //Should be cleared
        
			ctr.contactInfo.firstName = 'Jimi';
        	ctr.contactInfo.lastName = 'Hendrix';
        	ctr.contactInfo.email = 'Jimi.Hendrix@pgdev.org';
        	ctr.isPrimary = false;
        	ctr.saveContact();
            system.debug(logginglevel.WARN, '********* ctr.contactOptions: '+ctr.contactOptions);
        	system.assertEquals(4, ctr.contactOptions.size());//Ringo, Bob, Jimi plus "Add new Contact"
        	
        test.stopTest();

        //Assert related Case_Contacts size is correct
        List<Case_Contact__c> caseCons = new List<Case_Contact__c>([SELECT Id, Case__c, Contact__c, Contact__r.Name, Case_Primary_Contact__c FROM Case_Contact__c WHERE Case__C = :testCase.Id]);
        system.assertEquals(3, caseCons.size());//Ringo, Bob, Jimi
        
        //Assert primary Case Contact is the same as the Case.ContactId
        testCase = [SELECT Id, ContactId FROM Case WHERE Id = :testCase.Id];
        Case_Contact__c primCaseCon = [SELECT Id, Case__c, Contact__c, Case_Primary_Contact__c FROM Case_Contact__c WHERE Case__C = :testCase.Id AND Case_Primary_Contact__c = True LIMIT 1];
        system.assertEquals(testCase.ContactId, primCaseCon.Contact__c);//Bob
    }

        
	/****************************************************************
     * Covers:														*
     * Unchecking isPrimary on ContactInfo page						*
	****************************************************************/ 
	@isTest
    static void uncheckIsPrimaryTest(){
        Case testCase = [SELECT Id FROM Case WHERE ContactId != null LIMIT 1];
		PageReference pageRef = Page.sf_ContactInfo;
        Test.setCurrentPage(pageRef);

		ApexPages.StandardController sc = new ApexPages.StandardController (testCase);
        sf_ContactInfoController ctr = new sf_ContactInfoController (sc);
        
        test.startTest();
        
			ctr.isPrimary = false;
        	ctr.saveContact();
        
			List<ApexPages.Message> msgs = new List<ApexPages.Message>(ApexPages.getMessages());
			system.assertEquals(1, msgs.size());//TODO: Assert correct message is received

        test.stopTest();   
    }

	/****************************************************************
     * Covers:														*
     * Removing primary on ContactInfo page							*
     ****************************************************************/     
	/*
    Moved to removeContact_Test
    @isTest
    static void removePrimaryTest(){
        Case testCase = [SELECT Id FROM Case WHERE ContactId != null LIMIT 1];
		PageReference pageRef = Page.sf_ContactInfo;
        Test.setCurrentPage(pageRef);

		ApexPages.StandardController sc = new ApexPages.StandardController (testCase);
        sf_ContactInfoController ctr = new sf_ContactInfoController (sc);
        
        test.startTest();
        
			ctr.removeContact();
			List<ApexPages.Message> msgs = new List<ApexPages.Message>(ApexPages.getMessages());
			system.assertEquals(1, msgs.size());//TODO: Assert correct message is received

        test.stopTest();   
    }*/

	/****************************************************************
     * Covers:														*
     * Removing non-primary on ContactInfo page						*
     ****************************************************************/    
    /*
    Moved to removeContact_Test  
	@isTest
    static void removeNonPrimaryTest(){
        Case testCase = [SELECT Id FROM Case WHERE ContactId != null LIMIT 1];
		PageReference pageRef = Page.sf_ContactInfo;
        Test.setCurrentPage(pageRef);

		ApexPages.StandardController sc = new ApexPages.StandardController (testCase);
        sf_ContactInfoController ctr = new sf_ContactInfoController (sc);
        
        test.startTest();
			//Create and a save a new non-prim Contact
        	ctr.selectedConId = 'newCon';//Select add a new Contact
        	ctr.setContactId();
        	system.assertEquals(null, ctr.contactInfo.Id); //Should be cleared
        
			ctr.contactInfo.firstName = 'Jimi';
        	ctr.contactInfo.lastName = 'Hendrix';
        	ctr.contactInfo.email = 'Jimi.Hendrix@pgdev.org';
        	ctr.isPrimary = false;
        	ctr.saveContact();
        	system.assertEquals(3, ctr.contactOptions.size());//Ringo, Jimi plus "Add new Contact"
        
			ctr.removeContact();
			
        	Case_Contact__c removedCaseCon = [SELECT Id, Contact_Status__c, Case_Primary_Contact__c FROM Case_Contact__c WHERE Case__C = :testCase.Id AND Case_Primary_Contact__c = False LIMIT 1];
        	system.assertEquals('Cancelled',removedCaseCon.Contact_Status__c);
        
        test.stopTest();
    }*/

}