src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address_Key__c</fullName>
        <externalId>true</externalId>
        <label>Address Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>The first line of the address</description>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the address</description>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <description>The third line of the address</description>
        <label>Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The postal City for Contact</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complete_Address__c</fullName>
        <description>This the complete address for a contact</description>
        <formula>UPPER(

Address_Line_1__c &amp; City__c &amp; State_Province__c &amp; Postal_Code__c &amp; TEXT (Country__c)
)</formula>
        <label>Complete Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>The Zip Code or Postal Code</description>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <description>The State or Province for Postal address</description>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Complete_Address__c</fullName>
        <description>This field is used in the Contact trigger when address is added or changed.</description>
        <formula>UPPER(
Primary_Address_Line_1__c &amp; Primary_City__c &amp; Primary_State_Province__c &amp; Primary_Postal_Code__c &amp;  Primary_Country__c
)</formula>
        <label>Complete Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_1__c</fullName>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_2__c</fullName>
        <label>Primary Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_3__c</fullName>
        <label>Primary Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>This is the Country in the Mailing address</description>
        <label>Primary Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <label>Primary Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <label>Primary State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/classes/sf_ContactAddressTriggerHelper.cls
/*
* @author: Oleg Rikkers
* @date: 05/13/2014
* @description: 
*   US442
* Acceptance Criteria:
    Create a new contact with new address a new account will be created and the contact will be associated to it
    Create a new contact with an existing address the contact will be associated to the existing account
    Modify an address on an existing contact with an address that doesn't exist a new account will be created and the contact associated to it
    Modify an address on an existing contact with an address that does exist the contact will be associated to that account


*/

public with sharing class sf_ContactAddressTriggerHelper {

    public static final map<string,Schema.RecordTypeInfo> AccountRecordTypeInfoByNameMap = Account.sObjectType.getDescribe().getRecordTypeInfosByName(); 
    public static final map<string,Schema.RecordTypeInfo> ContactRecordTypeInfoByNameMap = Contact.sObjectType.getDescribe().getRecordTypeInfosByName(); 
    
    public static void processNewContacts (List <Contact> contacts) {
        Map <String, Account> householdAddressMap = new Map <String, Account> ();
        Set <String> addressSet = new Set <String> ();
        List<Contact> consumerContacts = new List<Contact>();
        
        for (Contact c: contacts) {
            if(c.RecordTypeId != ContactRecordTypeInfoByNameMap.get('Business Contact').getRecordTypeId()){
                
                String addressKey = !String.isEmpty(c.Primary_Address_Line_1__c) ? c.Complete_Address__c : getContactCreatedDate(c);
                addressSet.add (addressKey);
                
                consumerContacts.add(c);
            }
        }

        //alm 1396
        System.debug(System.LoggingLevel.INFO, 'addressSet \n' + addressSet);
        String todayName = Datetime.now().format('YYYY-MM-dd');



        //get all accounts with addresses from contacts
        String householdRt = AccountRecordTypeInfoByNameMap.get('Household').getRecordTypeId();
        for (Account a: [SELECT Id
                                ,Complete_Address__c
                                ,Address_Line_1__c
                                ,Name 
                        FROM Account 
                        WHERE (Address_Key__c IN :addressSet 
                                OR Name = :todayName 
                                OR Name IN :addressSet)  
                        AND RecordTypeId = :householdRt]){

            String addressKey = !String.isEmpty(a.Address_Line_1__c) ? a.Complete_Address__c : a.Name;
            householdAddressMap.put (addressKey, a);
        }

        System.debug(System.LoggingLevel.INFO, 'householdAddressMap \n' + householdAddressMap);

        //in case there are no accounts for a specific address yet
        List <Account> newAccounts = new List <Account> ();

        //once accounts are inserted, these need to be reprocessed
        List <Contact> needAccountConList = new List <Contact> ();

        //go through contacts and see if anything matches 
        for (Integer i=0; i<consumerContacts.size(); i++) { // need to be able to remove elements from array
            Contact c = consumerContacts[i];
            String addressKey = !String.isEmpty(c.Primary_Address_Line_1__c) ? c.Complete_Address__c : getContactCreatedDate(c);
            
            System.debug(System.LoggingLevel.INFO, 'for consumerContacts addressKey \n' + addressKey);
            
            Account acc = householdAddressMap.get(addressKey);

            if (acc == null) { //need to create account
                Account a = createAccountFromContact (c);
                newAccounts.add (a);
                needAccountConList.add (c);
            } else{
                c.AccountId = acc.Id;
            }
        }

        //recursive 
        if (!newAccounts.isEmpty()) {
            try {
                Database.SaveResult[] srList = Database.insert(newAccounts, true);

                for (Database.SaveResult sr : srList) {
                    if (sr.isSuccess()) {
                        // Operation was successful, so get the ID of the record that was processed
                        System.debug(System.LoggingLevel.INFO, 'Successfully inserted account. Account ID: ' + sr.getId());
                    } else {
                    // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Account fields that affected this error: ' + err.getFields());
                        }
                    }
                }
                processNewContacts (needAccountConList);

            } catch (Exception e) {
                //no need to fail the whole transaction?
                for (Contact c: contacts) {
                    c.addError (e.getMessage() + ' ' + e.getStackTraceString());
                }
                System.debug(e.getMessage() + ' ' + e.getStackTraceString());
            }
        }
    }

    public static void processExistingContacts (Map <Id, Contact> oldMap, Map <Id, Contact> newMap) {
        List <Contact>changedContacts = new List <Contact> ();
        for (Contact c: newMap.values()) {
            if(c.RecordTypeId != ContactRecordTypeInfoByNameMap.get('Business Contact').getRecordTypeId()){
                if ((oldMap.get(c.Id).Complete_Address__c != c.Complete_Address__c) || c.AccountId == null) {
                    changedContacts.add (c);
                }
            }

        }

        if (!changedContacts.isEmpty()) {
            processNewContacts (changedContacts);
        }
    }

    private static String getContactCreatedDate(Contact c){
        if(c.CreatedDate == null){
            // The contact is being created, and hasnt been saved yet.
            //return Date.today().year() + '-' + Date.today().month() + '-' + Date.today().day();
            return Datetime.now().format('YYYY-MM-dd');
        }else{
            // The contact already has a createdDate
            //return c.CreatedDate.year() + '-' + c.CreatedDate.month() + '-' + c.CreatedDate.day();
            return c.CreatedDate.format('YYYY-MM-dd');
        }
    }
    private static Account createAccountFromContact (Contact c) {
        System.debug('TRIGGER_createAccountFromContact contact.LastName = ' + c.LastName + '; contact.Complete_Address__c = ' + c.Complete_Address__c);
        Account a = new Account ();
        if(String.isEmpty(c.Primary_Address_Line_1__c)){
            a.Name = getContactCreatedDate(c);
        }else{
            a.Name = c.Primary_Address_Line_1__c;
        }
        a.Address_Line_1__c = c.Primary_Address_Line_1__c;
        a.Address_Line_2__c = c.Primary_Address_Line_2__c;
        a.Address_Line_3__c = c.Primary_Address_Line_3__c;
        a.City__c = c.Primary_City__c;
        a.State_Province__c = c.Primary_State_Province__c;
        a.Postal_Code__c = c.Primary_Postal_Code__c;
        a.Country__c = c.Primary_Country__c;
        a.RecordTypeId = AccountRecordTypeInfoByNameMap.get('Household').getRecordTypeId();

        return a;
    }
}