src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Path__c</fullName>
        <description>This is the full path for the product starting at Brand</description>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image_Url_Thumb__c</fullName>
        <description>Front of product thumbnail.</description>
        <inlineHelpText>Front of product thumbnail.</inlineHelpText>
        <label>Image Url Thumb</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Search_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores settings for the Product Search</description>
    <label>Product Search Configuration</label>
</CustomObject>

src/classes/sf_DAMImageProxyCtrlTest.cls
/*
* @author: salesforce.com
* @date: 05/11/2015
* @description:  Test class for sf_DAMImageProxyCtrl
*/

@isTest
private class sf_DAMImageProxyCtrlTest {
	
	@testSetup 
	static void setupData () {

        Global_Product__c gp = new Global_Product__c();
        gp.Path__c = 'TestBrand/TestSegment';
        insert gp;

        Local_Product__c lp = new Local_Product__c ();
        lp.Name = 'Test Path';
        lp.Country__c = 'China';
        lp.Translated_Path__c = 'Test Path/Test/Path';
        lp.Global_Product__c = gp.Id;
        lp.Image_Url_Thumb__c = 'https://test.salesforce.com';
        insert lp;

       	Product_Search_Configuration__c conf = new 	Product_Search_Configuration__c ();
       	insert conf;
	}

	@isTest static void testInit() {
		sf_DAMImageProxyCtrl ctrl = new sf_DAMImageProxyCtrl ();
		sf_DAMImageProxyCtrl ctrl2 = new sf_DAMImageProxyCtrl (new ApexPages.StandardController (new Account()));
	}
	
	@isTest static void testCallouts() {

		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource('sf_MissingProductImage');
		mock.setStatusCode(302);
		mock.setHeader('Content-Type', 'application/json');
		mock.setHeader('Location', 'https//google.com');

		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
		List <Local_Product__c> lpList = sf_DAMImageProxyCtrl.getDamImageThumbnailUrlInBulk(new List <Id> {[SELECT Id, Image_Url_Thumb__c FROM Local_Product__c].Id});
		Test.stopTest();
		System.assertNotEquals(null, lpList[0].Image_Url_Thumb__c);

	}

	@isTest static void testCallouts2() {

		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource('sf_MissingProductImage');
		mock.setStatusCode(302);
		mock.setHeader('Content-Type', 'application/json');
		mock.setHeader('Location', 'https//google.com');
		
		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
		String url = sf_DAMImageProxyCtrl.getDamImageUrl('https://test.salesforce.com');
		Test.stopTest();
		System.assertNotEquals(null, url);

	}

	@isTest static void testCalloutsFail() {

		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource('sf_MissingProductImage');
		mock.setStatusCode(500);
		mock.setHeader('Content-Type', 'application/json');

		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
		List <Local_Product__c> lpList = sf_DAMImageProxyCtrl.getDamImageThumbnailUrlInBulk(new List <Id> {[SELECT Id, Image_Url_Thumb__c FROM Local_Product__c].Id});
		Test.stopTest();
		System.assertNotEquals(null, lpList[0].Image_Url_Thumb__c);

	}

	@isTest static void testCalloutsFail2() {

		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource('sf_MissingProductImage');
		mock.setStatusCode(500);
		mock.setHeader('Content-Type', 'application/json');

		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
		String url = sf_DAMImageProxyCtrl.getDamImageUrl('https://test.salesforce.com');
		Test.stopTest();
		System.assertNotEquals(null, url);

	}


	
}