src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>New_Owner_ID__c</fullName>
        <label>New Owner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Owner_Location__c</fullName>
        <label>New Owner Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Owner__c</fullName>
        <label>New Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Owner_ID__c</fullName>
        <label>Old Owner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Owner_Location__c</fullName>
        <label>Old Owner Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Owner__c</fullName>
        <label>Old Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>118.KZ Almaty Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Accenture Newcastle UK</fullName>
                </value>
                <value>
                    <fullName>Adecco Cincinnati US</fullName>
                </value>
                <value>
                    <fullName>Alta Neenah US</fullName>
                </value>
                <value>
                    <fullName>Alta Neenah US Connect</fullName>
                </value>
                <value>
                    <fullName>Apex Cordoba Argentina</fullName>
                </value>
                <value>
                    <fullName>Apex Cordoba Argentina Connect</fullName>
                </value>
                <value>
                    <fullName>Apex San Pedro Sula Honduras</fullName>
                </value>
                <value>
                    <fullName>Apex San Pedro Sula Honduras Connect</fullName>
                </value>
                <value>
                    <fullName>Apex Sao Paulo Brazil</fullName>
                </value>
                <value>
                    <fullName>Apex Sao Paulo Brazil Connect</fullName>
                </value>
                <value>
                    <fullName>C3i Horsham US</fullName>
                </value>
                <value>
                    <fullName>Connections Consult Bucharest Romania</fullName>
                </value>
                <value>
                    <fullName>ConSol Lagos Nigeria</fullName>
                </value>
                <value>
                    <fullName>Convergys Jacksonville US (Beauty)</fullName>
                </value>
                <value>
                    <fullName>Convergys Jacksonville US (Clairol French)</fullName>
                </value>
                <value>
                    <fullName>DPIC Clifton US</fullName>
                </value>
                <value>
                    <fullName>Ignite Cincinnati US</fullName>
                </value>
                <value>
                    <fullName>Infosys OffShore India</fullName>
                </value>
                <value>
                    <fullName>Ipsos Johannesburg South Africa</fullName>
                </value>
                <value>
                    <fullName>Lingaro Warsaw Poland</fullName>
                </value>
                <value>
                    <fullName>New Moment Belgrade Serbia</fullName>
                </value>
                <value>
                    <fullName>NewPoint Moscow Russia</fullName>
                </value>
                <value>
                    <fullName>Olympic Shavers Nottingham UK</fullName>
                </value>
                <value>
                    <fullName>PFSweb Cincinnati US</fullName>
                </value>
                <value>
                    <fullName>PG Athens Greece</fullName>
                </value>
                <value>
                    <fullName>PG Bangkok Thailand</fullName>
                </value>
                <value>
                    <fullName>PG Boston US</fullName>
                </value>
                <value>
                    <fullName>PG Brussels Belgium</fullName>
                </value>
                <value>
                    <fullName>PG Bucharest Romania</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/sf_CaseHelperWithoutSharingTest.cls
@isTest
private class sf_CaseHelperWithoutSharingTest {

    @isTest //
    public static void testTransferActivityTaskUserToUser() {
        sf_TestDataUtility tdu = new sf_TestDataUtility();
        User olduser = sf_TestDataUtility.createUser('System Administrator', 'alpha');
        User newuser = sf_TestDataUtility.createUser('System Administrator', 'omega');

        olduser.location__c = 'US';
        newuser.location__c = 'CA';

        insert oldUser;
        insert newUser;

        Case c = new Case();
        c.ownerid = oldUser.id;
        insert c;
        c.ownerid = newuser.id;

        test.startTest();
        update c;
        test.stopTest();

        List<Task> taskResults = [SELECT id, subject, status, New_Owner__c, New_Owner_Location__c, New_Owner_Id__c, Old_Owner__c, Old_Owner_Location__c, Old_Owner_Id__c FROM Task WHERE Recordtype.name = 'Transfer Activity'];
        
        system.debug('@@@taskResults: ' + taskResults);
        system.debug('@@@taskResults[0]: ' + taskResults[0]);
        
        system.assertEquals(1, taskResults.size());
        system.assertEquals('CA', taskResults[0].New_Owner_Location__c);
        system.assertEquals('US', taskResults[0].Old_Owner_Location__c);

    }
}