src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Follow_Up_Category__c</fullName>
        <label>Follow Up Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>CCM Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Follow_Up_Reason__c</fullName>
        <label>Follow Up Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Follow_Up_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer requests findings of investigation</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t like response handling</fullName>
                </value>
                <value>
                    <fullName>Did not receive what was promised; item damaged</fullName>
                </value>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Production Code Update</fullName>
                </value>
                <value>
                    <fullName>Product Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Thank you; service testimonial (i.e. agent; reply helpful)</fullName>
                </value>
                <value>
                    <fullName>Welcome Call</fullName>
                </value>
                <value>
                    <fullName>Retention Call</fullName>
                </value>
                <value>
                    <fullName>Service Visit</fullName>
                </value>
                <value>
                    <fullName>Pregnancy Follow Up</fullName>
                </value>
                <value>
                    <fullName>Closeout with Consumer</fullName>
                </value>
                <value>
                    <fullName>Intake Agent Request</fullName>
                </value>
                <value>
                    <fullName>Audio Log Request</fullName>
                </value>
                <value>
                    <fullName>Product Retrieval Request</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Request</fullName>
                </value>
                <value>
                    <fullName>Consumer Recontact Request</fullName>
                </value>
                <value>
                    <fullName>GCR Request on AE</fullName>
                </value>
                <value>
                    <fullName>GCR Request to QA</fullName>
                </value>
                <value>
                    <fullName>Agent Clarification Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originating_System__c</fullName>
        <description>Originating system of the Task</description>
        <inlineHelpText>Originating system of the Task</inlineHelpText>
        <label>Originating System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ARGUS</fullName>
                </value>
                <value>
                    <fullName>CCM</fullName>
                </value>
                <value>
                    <fullName>SFDC</fullName>
                    <default>true</default>
                    <label>SFDC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Child_Last_Modified_Date__c</fullName>
        <description>The datetime a child of the case was updated.</description>
        <inlineHelpText>The datetime a child of the case was updated.</inlineHelpText>
        <label>Child Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Intake_Agent_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ALM 662 - this get&apos;s checked when task subject is Intake Agent Request. This way case product will know when to show CCM Retreival Request flag on products added page</description>
        <label>Intake Agent Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reassign_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reassign Case</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/sf_TaskHelper.cls
/**
* @author: Archana Sethuraman
* @date: 09/8/2014
* @description: 
*   Helper class for Task Trigger
*/

public class sf_TaskHelper {

    /**
    * @author: Archana Sethuraman
    * @date: 09/8/2014
    * @description: 
    *   When a task related to a case with type CCM activity gets Inserted/updated, update the Reassign Case and Status
    *   fields on case 
    */

    public static void updateCaseFields (List <Task> newTasks, Map <Id,Task> oldTasksMap) {

        Map <Id, Case> casesToUpdateMap = new Map <Id, Case> ();
        
		/*April 2016 christopher.macduff@accenture.com
		 *Need to use a try/catch and a string as occasionally this method is called by a time based
		 *Workflow rule running as the "Automated process user"
		 *This user does not have a profile and the below fails silently
		*/
        String profileName = '';
        try{
            profileName = [SELECT Id, Name FROM Profile WHERE Id = :UserInfo.getProfileId()].name;
        }
        catch(queryexception e){
            system.debug('!!! error on querying current user profile: '+e);
        }

        for (Task t: newTasks) {

            Case c = new Case ();

            //ALM 662
            /*christopher.macduff@accenture.com - Mar 2016
             *Ecosystem change - "intake agent request" is being depreciated
             *Added new subject line support. Need to keep "intake agent request" to support crossover period and
			 *if a historical case is updated downstream
			*/

            if((t.Subject == sf_Constants.TASK_SUBJECT_INTAKE || t.Subject == sf_Constants.TASK_SUBJECT_PRODUCT_RETRIEVAL)
               	&& (t.whatId).getSObjectType().getDescribe().getName() == sf_Constants.SOBJECTTYPE_CASE
              	){
            //if (t.Subject == 'Intake Agent Request' && (t.whatId).getSObjectType().getDescribe().getName() == sf_Constants.SOBJECTTYPE_CASE) {
                c.Id = t.WhatId;
                /*ChrisM Comment:
                 *Intake_Agent_Request__c:
                 *ALM 662 - this get's checked when task subject is Intake Agent Request. This way case product will know when to show CCM Retreival Request flag on products added page
				*/
                c.Intake_Agent_Request__c = true;
            } 

            if (t.Follow_up_category__c == sf_Constants.TASK_TYPE_CCM_ACTIVITY 
                && t.WhatId != null
                && (  oldTasksMap == null || oldTasksMap.get(t.Id).Follow_up_category__c != t.Follow_up_category__c)
                && (t.whatId).getSObjectType().getDescribe().getName() == sf_Constants.SOBJECTTYPE_CASE
               	&& t.Originating_System__c != 'SFDC') {
                    
                c.Id = t.WhatId;
                c.Reassign_Case__c = true;
                c.Child_Last_Modified_Date__c = datetime.now(); //ChrisM Ecosystem Spring CR

                system.debug('@@@c.Reassign_Case__c: ' + c.Reassign_Case__c);

                if (t.Follow_Up_Reason__c != sf_Constants.TASK_FOLLOWUP_REASON_AUDIO_LOG_REQUEST) {
                    c.Status = sf_Constants.CASE_STATUS_REOPENED_BY_CCM;
                } else {
                    c.Status = sf_Constants.CASE_STATUS_REOPENED_BY_CCM_SUPERVISOR;
                }   
            }
			
            if (c.Id != null){
                casesToUpdateMap.put(t.WhatId, c);
            }
 
            if(profileName.toLowerCase() != sf_Constants.INTEGRATION_USER_PROFILE_NAME){
                //salesforce.com fix NPE on WhatId 5/18/2015 - add && t.WhatId != null
                if (!checkRecursive.newCase && casesToUpdateMap.get(t.WhatId) == null && t.WhatId != null && (t.whatId).getSObjectType().getDescribe().getName() == sf_Constants.SOBJECTTYPE_CASE) {
                    c.Id = t.WhatId;
                    casesToUpdateMap.put(t.WhatId, c);
                }

                if (casesToUpdateMap.get(t.WhatId) != null){
                    casesToUpdateMap.get(t.WhatId).Child_Last_Modified_Date__c = datetime.now();//ChrisM Test
                }   
            }
        }
        
        if (!casesToUpdateMap.isEmpty()){
            update casesToUpdateMap.values();            
        }
    }

    public static void checkTaskBeforeDelete (List <Task> triggerOld) {
        for (Task t: triggerOld) {
            if (t.whatId.getSObjectType().getDescribe().getName() == sf_Constants.SOBJECTTYPE_CASE) {
                if (!Schema.sObjectType.Case.isDeletable()){
					t.addError ('You are not allowed to delete tasks assigned to the case');                    
                }
            }
        }
    }
}