src/objects/Auto_Communication_Rule__c.object
<CustomObject>
    <description>Proof of Concept - to replace existing MAC rules that:

Describes consumer-facing communications that can be generated automatically, either as an email or a fulfillment order. These include Medical Questionnaire reminders, Product Return reminders, and Fraud Case notifications.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fraud Notice</fullName>
                </value>
                <value>
                    <fullName>Medical Questionnaire</fullName>
                </value>
                <value>
                    <fullName>Product Return</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auto Communication Rule</label>
    <nameField>
        <displayFormat>ACR-{00000}</displayFormat>
        <label>Auto Communication Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Communication Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>WE</fullName>
        <active>true</active>
        <businessProcess>Country Defaults</businessProcess>
        <description>WE Cases</description>
        <label>WE</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Local_Comment_Code__r.GCC_Level_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_available_for_return__c</fullName>
        <label>Product available for return</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes - Product is available</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>No - Product cannot be returned</fullName>
                </value>
                <value>
                    <fullName>Unknown - Written communication</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Production_Code__c</fullName>
        <inlineHelpText>What is the production code?</inlineHelpText>
        <label>Production Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fulfillment_Item__c.object
<CustomObject>
    <description>This object provides a list of all active or inactive fulfillment items available in P&amp;G.  CR Agents will perform a search of this table to select the appropriate fulfillment items to send to Consumers.  Fulfillment item master data will be loaded my P&amp;G regional admins.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>CR</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DD</fullName>
                </value>
                <value>
                    <fullName>EL</fullName>
                </value>
                <value>
                    <fullName>ET</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FU</fullName>
                </value>
                <value>
                    <fullName>GI</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MP</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>RC</fullName>
                </value>
                <value>
                    <fullName>RE</fullName>
                </value>
                <value>
                    <fullName>RL</fullName>
                </value>
                <value>
                    <fullName>RP</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fulfillment Item</label>
    <nameField>
        <label>Fulfillment Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <fields>
        <fullName>Level_2__c</fullName>
        <description>This indicates the next level of detail after the type of comment has been classified</description>
        <label>Level 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Alleged Contamination</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Consumer Preference / Dislikes</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Damage to Property</fullName>
                </value>
                <value>
                    <fullName>Dissatisfied with Product Performance</fullName>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Label, Insert Legibility or Confusing</fullName>
                </value>
                <value>
                    <fullName>Marketing Loyalty</fullName>
                </value>
                <value>
                    <fullName>Marketing Personal Information</fullName>
                </value>
                <value>
                    <fullName>Marketing Pricing</fullName>
                </value>
                <value>
                    <fullName>Marketing Promotion, Advertising</fullName>
                </value>
                <value>
                    <fullName>Marketing Shopping Experience</fullName>
                </value>
                <value>
                    <fullName>Missing Label, Coding, Insert</fullName>
                </value>
                <value>
                    <fullName>Moe</fullName>
                </value>
                <value>
                    <fullName>Packaging or Product Mix Up, Mislabel</fullName>
                </value>
                <value>
                    <fullName>Pet Health Effect</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Product or Packaging Malfunction Hazard</fullName>
                </value>
                <value>
                    <fullName>Product or Packaging Non Functioning or Damaged (Not Hazardous)</fullName>
                </value>
                <value>
                    <fullName>Product Usage</fullName>
                </value>
                <value>
                    <fullName>Safety Closure defect, child resistant closure</fullName>
                </value>
                <value>
                    <fullName>Sensory</fullName>
                </value>
                <value>
                    <fullName>Suspect Counterfeit</fullName>
                </value>
                <value>
                    <fullName>Suspect Tampering</fullName>
                </value>
                <value>
                    <fullName>Testimonial</fullName>
                </value>
                <value>
                    <fullName>Volume/Fill/Count/missing parts</fullName>
                </value>
                <value>
                    <fullName>Unable to Classify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Path__c</fullName>
        <description>This is the full path for the product starting at Brand</description>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Level_2__c</fullName>
        <description>This is the next level up once we know the type of Comment Code</description>
        <externalId>true</externalId>
        <label>Level 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/getProductReturnACR_Test.cls
@isTest
public class getProductReturnACR_Test {
	
    @testSetup
    static void setupData(){
        checkrecursive.toggleAllTriggers(false);
        AutoComRuleHelper_datasetup_Test.dataSetup();
        checkrecursive.toggleAllTriggers(true);
    }
	/****************************************************
     * Covers:											*
     * No Match found									*
	****************************************************/
    @isTest
    static void noACRMatchFoundTest(){
        //Get Case and CP and LC to use
        Case noACRCase = [SELECT Id FROM Case WHERE Subject = 'NoACR' LIMIT 1];
        Case_Product__c noACRCP = [SELECT id, ACR_Info__C FROM Case_Product__c WHERE Case__c = :noACRCase.Id LIMIT 1];
        system.assertEquals(null, noACRCP.ACR_Info__c);
        
        test.startTest();
            Local_Comment_Code__c lcc = [SELECT Id FROM Local_Comment_Code__c WHERE Translated_Path__c = 'AE/AE/AE' LIMIT 1];
            Case_Comment_Code__c testCCC = new Case_Comment_Code__c(
                Case__c = noACRCase.Id,
                Local_Comment_Code__c = lcc.Id,
                Case_Product__c = noACRCP.Id
            );
            insert testCCC;
            
            testCCC = [SELECT Id, ACR_Info__c FROM Case_Comment_Code__c WHERE Id = :testCCC.Id];
            system.assertEquals(getProductReturnACR.NO_MATCH, testCCC.ACR_Info__c);        
        test.stopTest();
    }
    
    /****************************************************
     * Covers:											*
     * Finding a matching ACR on CaseCommentCode insert	*
     * based on a product segment match					*
	****************************************************/
    @isTest
    static void cccTriggerSegmentTest(){
        //Query records we need
        Case testCase = [SELECT Id, ContactId FROM Case LIMIT 1];
        Local_Product__c testLP = [SELECT Id FROM Local_Product__c WHERE Name = 'Bag' LIMIT 1];
        Local_Comment_Code__c testLC = [SELECT Id FROM Local_Comment_Code__c WHERE Level_2__c = 'Foreign Material' LIMIT 1];

        //Create Case Product
        Case_Product__c testCP = new Case_Product__c(
            Case__c = testCase.Id,
            Local_Product__c = testLP.Id,
            Production_Code__c = 'randomvaluehere',
            Product_available_for_return__c = 'Yes - Product is available'     
        );
        system.debug(logginglevel.WARN,'!!! insert Case Product');
        insert testCP;
          
        //ChrisM Aug 2016 boolean deprecated
        checkRecursive.ACRprocessedIds.clear();
        
        Case_Comment_Code__c testCCC = new Case_Comment_Code__c(
            Case__c = testCase.Id,
            Local_Comment_Code__c = testLC.Id,
            Case_Product__c = testCP.Id
        );
        
        test.startTest();
            system.debug(logginglevel.WARN,'!!! insert Case Comment Code');
            insert testCCC;
        
            //Requery new CCC
            Auto_Communication_Rule__c ACR = [SELECT Id, Name FROM Auto_Communication_Rule__c WHERE Type__c = 'Product Return' AND Supported_Return_Type__c = 'Digital' LIMIT 1];
            testCP = [SELECT ACR_Info__c, Digital_Return_Id__c, ACR_Return_Type__c, Status__c FROM Case_Product__c WHERE Id = :testCP.Id];
            system.assertEquals(ACR.Name, testCP.ACR_Info__c);
        	system.assertNotEquals(null, testCP.Digital_Return_Id__c);
        	system.assertEquals('Digital', testCP.ACR_Return_Type__c);
        test.stopTest();
    }
    
    /****************************************************
     * Covers:											*
     * Finding a matching ACR on CaseCommentCode insert	*
     * based on an exact product segment match	        *
	****************************************************/    
	@isTest
    static void cccTriggerPathTest(){
        String productPath = 'Ariel/Laundry segment/Powder/-/-/Original/Compact/63oz/Bag/digi';//manually updated path to get an exact match > segment 
		Fulfillment_Item__c ffItem1 = [SELECT Id FROM Fulfillment_Item__c WHERE Type__c = 'BD' LIMIT 1];
        Global_Comment_Code__c gcc2 = [SELECT Id FROM Global_Comment_Code__c WHERE Level_2__c = 'Foreign Material' LIMIT 1];
        String kavNumber = [SELECT Id, ArticleNumber FROM Return_Instructions__kav
                            WHERE PublishStatus = 'Online' AND Language = 'en_US' AND UrlName = 'Return-Instructions-test-Article-1' LIMIT 1].ArticleNumber;
        
        //Create path ACR
		Auto_Communication_Rule__c pathDigiACR = new Auto_Communication_Rule__c (
            Type__c = 'Product Return',
			Global_Product_Path__c = productPath,
			Supported_Return_Type__c = 'Digital',//CR16
            Global_Comment_Code__c = gcc2.Id,
            Product_Search_Key__c = '', //Should be set by WFR
			X1st_Attempt_Fulfillment_Item__c = ffItem1.Id,
			X2nd_Attempt_Fulfillment_Item__c = ffItem1.Id,
			X3rd_Attempt_Fulfillment_Item__c = ffItem1.Id,
			Generate_PDF_for_Attempt__c = '2;3',
			Template_Unique_Name__c =  'ACR_UnitTest_EmailTemplate',
            Digital_Attempt_1st_Template__c = 'ACR_UnitTest_EmailTemplate',
            Digital_Attempt_2nd_Template__c = 'ACR_UnitTest_EmailTemplate',
            Digital_Attempt_3rd_Template__c = 'ACR_UnitTest_EmailTemplate',
            Digital_Thankyou_Email__c = 'ACR_UnitTest_EmailTemplate',
            Digital_Instructions__c = kavNumber
        );
        insert pathDigiACR;
        
		//Query records we need
		pathDigiACR = [SELECT Id, Name FROM Auto_Communication_Rule__c WHERE Id = :pathDigiACR.Id];
        Case testCase = [SELECT Id, ContactId FROM Case LIMIT 1];
        Local_Product__c testLP = [SELECT Id, Global_Product__c FROM Local_Product__c WHERE Name = 'Bag' LIMIT 1];
        Global_Product__c testGP = [SELECT Id FROM Global_Product__c WHERE Id = :testLP.Global_Product__c LIMIT 1];
        Local_Comment_Code__c testCC = [SELECT Id FROM Local_Comment_Code__c WHERE Level_2__c = 'Foreign Material' LIMIT 1];
        
        testGP.Path__c = productPath;
        update testGP;

        //Create Case Product
        Case_Product__c testCP = new Case_Product__c(
            Case__c = testCase.Id,
            Local_Product__c = testLP.Id,
            Production_Code__c = 'randomvaluehere',
            Product_available_for_return__c = 'Yes - Product is available'     
        );
        system.debug(logginglevel.WARN,'!!! insert Case Product');
        insert testCP;
          
        //ChrisM Aug 2016 boolean deprecated
        checkRecursive.ACRprocessedIds.clear();
        
        Case_Comment_Code__c testCCC = new Case_Comment_Code__c(
            Case__c = testCase.Id,
            Local_Comment_Code__c = testCC.Id,
            Case_Product__c = testCP.Id
        );
        
        test.startTest();
            system.debug(logginglevel.WARN,'!!! insert Case Comment Code');
            insert testCCC;
        
            //Requery new CCC
            testCP = [SELECT ACR_Info__c, Digital_Return_Id__c, ACR_Return_Type__c, Status__c FROM Case_Product__c WHERE Id = :testCP.Id];
            system.assertEquals(pathDigiACR.Name, testCP.ACR_Info__c);
        	system.assertNotEquals(null, testCP.Digital_Return_Id__c);
        	system.assertEquals('Digital', testCP.ACR_Return_Type__c);
        test.stopTest(); 
    }

}