src/objects/Auto_Communication_Rule__c.object
<CustomObject>
    <description>Proof of Concept - to replace existing MAC rules that:

Describes consumer-facing communications that can be generated automatically, either as an email or a fulfillment order. These include Medical Questionnaire reminders, Product Return reminders, and Fraud Case notifications.</description>
    <fields>
        <fullName>Full_Comment_Path__c</fullName>
        <description>Chris - this may be a duplicate/unnecessary now.</description>
        <formula>Global_Comment_Code__r.Full_Comment_Path__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Comment Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GCR_CID__c</fullName>
        <formula>Global_Comment_Code__r.GCR_CID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GCR_CID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used as MAC rules reviewed all used global comment code</description>
        <inlineHelpText>Lookup to Global Comment Code</inlineHelpText>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipName>Auto_Communcation_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Global_Comment_Path__c</fullName>
        <description>External Id set via WFR</description>
        <externalId>true</externalId>
        <inlineHelpText>External Id set via WFR</inlineHelpText>
        <label>Global Comment Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product_Path__c</fullName>
        <description>Global Product Path</description>
        <inlineHelpText>Global Product Path, enter either segment or path</inlineHelpText>
        <label>Global Product Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Auto Communication Rule</label>
    <nameField>
        <displayFormat>ACR-{00000}</displayFormat>
        <label>Auto Communication Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Communication Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>WE</fullName>
        <active>true</active>
        <businessProcess>Country Defaults</businessProcess>
        <description>WE Cases</description>
        <label>WE</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Contact_Id__c</fullName>
        <formula>Case__r.ContactId</formula>
        <label>Case Contact Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Has_Address__c</fullName>
        <description>Formula Field. True if Contact on the parent Case has a Primary Address.</description>
        <formula>/*Pre WR349
AND( 
  IF(Case__r.Contact.Primary_Address_Line_1__c  != null, True, False) , 
  IF(Case__r.Contact.Primary_City__c != null, True, False), 
  IF(Case__r.Contact.Primary_State_Province__c != null, True, False), 
  IF(Case__r.Contact.Primary_Postal_Code__c != null, True, False)
)*/
AND( 
  IF(Case__r.Contact.Primary_Address_Line_1__c  != null, True, False) , 
  IF(Case__r.Contact.Primary_City__c != null, True, False) 
)</formula>
        <inlineHelpText>Formula Field. True if Contact on the parent Case has a Primary Address.</inlineHelpText>
        <label>Contact Has Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GCR_CID__c</fullName>
        <formula>Local_Comment_Code__r.Global_Comment_Code__r.GCR_CID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GCR CID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Comment_Path__c</fullName>
        <formula>Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c</formula>
        <label>Global Comment Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product_Path__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Path__c</formula>
        <label>Global Product Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product_Segment__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Segment__c</formula>
        <label>Global Product Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Brand__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Postal_Restriction__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Postal_Restriction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Postal Restriction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Global_Product_Path__c</fullName>
        <formula>Local_Product__r.Global_Product__r.Path__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Global Product Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_available_for_return__c</fullName>
        <label>Product available for return</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes - Product is available</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>No - Product cannot be returned</fullName>
                </value>
                <value>
                    <fullName>Unknown - Written communication</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <fields>
        <fullName>Full_Comment_Path__c</fullName>
        <formula>text(Level_1__c ) &amp;&apos;/&apos;&amp;  text(Level_2__c)  &amp;&apos;/&apos;&amp; Level_3__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Comment Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GCR_CID__c</fullName>
        <description>This is an ID that will be populated by the C3DB system</description>
        <externalId>true</externalId>
        <label>GCR_CID</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/getProductReturnACR.cls
/*
 * Want to set ACR.Id and ACR.ReturnType on CaseProduct
*/
public class getProductReturnACR {
    public static final String NO_MATCH = 'No Match';
    
    public static void getCCCACRs(map<id, Case_Comment_Code__c>cccMap){
        Set<Id> cccsToQuery = new Set<Id>();//CaseCommentCode Ids to process
        List<Case_Comment_Code__c> cccProcessList = new List<Case_Comment_Code__c>();
        Map<Id, Case_Product__c> cpMap = new Map<Id, Case_Product__c>(); //Want ACR info on the CP - issue with using Set is CCs can hit different ACRs so won't appear identical. 
        List<Case_Product__c> cpsToUpdate = new List<Case_Product__c>();
        
		//Only process thoughs without an ACR already
        for(Case_Comment_Code__c ccc : cccMap.values()){
            if(String.isBlank(ccc.ACR_Info__c)){
                cccsToQuery.add(ccc.Id);
            }
        }  
        
        if(!cccsToQuery.isEmpty()){
            //Will have to query to get Case and Case Product info to use
            cccProcessList = [SELECT Id, ACR_Info__c, Contact_Has_Address__c, Case_Product__r.Product_available_for_return__c, Case_Product__r.Status__c, Case_Product__r.ACR_Info__c,
                                Status__c, GCR_CID__c, Case_Contact_Id__c, Case__c, Case_Product__c, Global_Product_Segment__c, Product_Postal_Restriction__c,
                                Global_Comment_Path__c, Global_Product_Path__c, Product_Brand__c, Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c,
                                Case__r.Country__c, Case__r.Language__c, Name
                                FROM Case_Comment_Code__c
                                WHERE Id In :cccsToQuery];
            
			//Create Search Keys
            Set<String> caseSearchKeys = new Set<String>(); //Stores Case search Keys
            for(Case_Comment_Code__c ccc :cccProcessList){
                String caseSearchPathKey = ccc.Case__r.Country__c+':'+ccc.Case__r.Language__c+':'+ccc.Global_Product_Path__c+':'+ccc.Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c;
                String caseSearchSegmentKey = ccc.Case__r.Country__c+':'+ccc.Case__r.Language__c+':'+ccc.Global_Product_Segment__c+':'+ccc.Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c;
                caseSearchKeys.add(caseSearchPathKey);
                caseSearchKeys.add(caseSearchSegmentKey);
            }

			//Now find ACR
            Map<String, Auto_Communication_Rule__c> ACRMap = new Map<String, Auto_Communication_Rule__c>();
            if(caseSearchKeys.size() > 0 ){
                system.debug(logginglevel.WARN,'>>> Finding ACRs');
                
                //Don't need all the ACR fields here
                for(Auto_Communication_Rule__c acr :  [SELECT Id, Name, Product_Search_Key__c, Supported_Return_Type__c
                                                        FROM Auto_Communication_Rule__c
                                                        WHERE Product_Search_Key__c IN :caseSearchKeys
                                                        AND Type__c = :trg_AutoComRuleHelper.ACR_TYPE_PRODUCT_RETURN]){
                        
                    ACRMap.put(acr.Product_Search_Key__c, acr);
                } 
            }
			    
            //Now match up and updated CC/CP if required
            for(Case_Comment_Code__c ccc :cccProcessList){
                system.debug(logginglevel.WARN,'>>> Matching found ACRs to CCC');
                String caseSearchPathKey = ccc.Case__r.Country__c+':'+ccc.Case__r.Language__c+':'+ccc.Global_Product_Path__c+':'+ccc.Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c; //Country+':'+Language+':'+Global_Product_Path__c+':'+Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c
                String caseSearchSegmentKey = ccc.Case__r.Country__c+':'+ccc.Case__r.Language__c+':'+ccc.Global_Product_Segment__c+':'+ccc.Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c;//Country+':'+Language+':'+Global_Product_Segment__c+':'+Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c
                
                Auto_Communication_Rule__c matchedACR = new Auto_Communication_Rule__c();
                
                //Look for segment match first
                if(ACRMap.containsKey(caseSearchSegmentKey)){
					System.debug(logginglevel.WARN,'>>> Match found on Product Segment');
                    matchedACR = ACRMap.get(caseSearchSegmentKey);
                    ccc.ACR_Info__c = matchedACR.Name;
                    
                }
                else if(ACRMap.containsKey(caseSearchPathKey)){
					System.debug(logginglevel.WARN,'>>> Match found on Product Path');
                    matchedACR = ACRMap.get(caseSearchPathKey);
                    ccc.ACR_Info__c = matchedACR.Name;
                }
                //If no match set ACR_Info__c to no match to prevent searching for a match again in the future. Prevent an old case hitting a new acr
                else{
                    ccc.ACR_Info__c = NO_MATCH;
                }

                //Now check to see if parent CP needs updating
                if(String.isBlank(ccc.Case_Product__r.ACR_Info__c) || ccc.Case_Product__r.ACR_Info__c == NO_MATCH){
                    
                    Case_Product__c cp = new Case_Product__c(id = ccc.Case_Product__c);
					//If Supported_Return_Type__c is null assume physical:
					cp.ACR_Info__c = matchedACR.Name;
					cp.ACR_Return_Type__c = String.isBlank(matchedACR.Supported_Return_Type__c) ? 'Physical' : matchedACR.Supported_Return_Type__c;
                    cp.Digital_Return_Id__c = setDigitalReturnId(cp.Id);
					//Note: Last element added to a map with the same key overrides the previous value. We want to keep the first.
                    if(cpMap.get(cp.Id)==null){
						cpMap.put(cp.Id, cp);
                    }
                    system.debug(logginglevel.WARN,'!!!!!!!!!!!!!!!! Updating CaseProduct: '+cp);
                }
                try{
                    update cccProcessList;
                    cpsToUpdate = new List<Case_Product__c>(cpMap.values());
                    update cpsToUpdate;
                }
                catch(exception e){
                    System.enqueueJob(new exceptionHelperQueable(e,'Error updating CCCs: '+String.ValueOf(cccProcessList)));
                }
            }
        }//isemtpy end
        
    }//method end
    
     /********************************************
     * Sets unique hashed Id that will be used  *
     * In the form url sent to consumer         *
     *******************************************/
    
    public static String setDigitalReturnId(Id cpId) {
        String hashedCPID = '';
        Blob b = Crypto.generateDigest('SHA-256', Blob.valueOf(cpId));
        hashedCPID = EncodingUtil.convertToHex(b);
        return hashedCPID;
    }
}//class end