src/objects/Call_Center_Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Call_Center_Location__c</fullName>
        <label>Call Center Location</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Center_Management__c</fullName>
        <label>Call Center Management</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outsourced (OV)</fullName>
                </value>
                <value>
                    <fullName>Insourced (IV)</fullName>
                </value>
                <value>
                    <fullName>P&amp;G Inhouse (P)</fullName>
                </value>
                <value>
                    <fullName>P&amp;G Inhouse contractors (C)</fullName>
                </value>
                <value>
                    <fullName>Distributor (D)</fullName>
                </value>
                <value>
                    <fullName>ER (E)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>AAI</fullName>
                </value>
                <value>
                    <fullName>WE</fullName>
                </value>
                <value>
                    <fullName>CEEMEA</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>NEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Center Inventory</label>
    <nameField>
        <label>Call Center Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Center Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRCountryIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRLanguageIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Iso Code</label>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Telephony__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pampers</fullName>
                </value>
                <value>
                    <fullName>NULL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AAI</fullName>
                </value>
                <value>
                    <fullName>CEEMEA</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>NEA</fullName>
                </value>
                <value>
                    <fullName>WE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Telephony</label>
    <nameField>
        <displayFormat>Tel-{00000}</displayFormat>
        <label>Telephony Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telephony</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/gcr_callusControllerTest.cls
/*
* @author: 		 Accenture
* @date: 		 30/08/2016
* @description:  Test class for call us Controller
* CHANGE LOG
* DATE			NAME				CHANGE DESCRIPTION
* 30/08/2016	Accenture			Initial Draft
*/
@isTest(SeeAllData = false)
public class gcr_callusControllerTest {
	/*
     * @author: 		Accenture
	 * @date: 		 	30/08/2016
	 * @description:  	TEST SETUP METHOD TO SETUP TEST DATA
     */
    @testSetup
    static void setupTestData() {
        gcr_TestUtility.createCustomSettings();
        String brandConLangId = gcr_TestUtility.createContactUsObjectData();
        sObject careHub = gcr_TestUtility.getCareHubData(brandConLangId);
        Database.insert(careHub, true);
        List<sObject> lCareHubChannels = gcr_TestUtility.getCareHubChannels(careHub.Id);
        Database.insert(lCareHubChannels, true);
    }
    
        /*
     * @author: 		Accenture
	 * @date: 		 	30/08/2016
	 * @description:  	TEST METHOD TO GET ALL SIDEBAR ICONS WITH THEIR FUNCTIONALITIES
     */
    static testmethod void telephonyRecordTest() {
        // CREATE TELEPHONY DATA
        Call_Center_Inventory__c ccInventory = new Call_Center_Inventory__c(Name = 'Call Center 1'
                                                                          , Call_Center_Location__c = 'Newcastle'
                                                                          , Call_Center_Management__c = 'Outsourced (OV)'
                                                                          , Region__c = 'NA');
        Database.insert(ccInventory, true);
        String profileId = [ SELECT Id FROM profile where Name = 'System Administrator' ].get(0).Id;
        User gcrContact = gcr_TestUtility.createUser(profileId);
        // CREATE 10 TELEPHONY RECORDS 5 TOLL FREE AND 2 PAID NUMBER AND 3 SUPER NUMBER
        List<Telephony__c> lTelephony = new List<Telephony__c>();
        lTelephony.add(gcr_TestUtility.getTelephonyData(true, 'Tide', 'Toll Free', ccInventory.Id, gcrContact.Id, '1800 (234) 5678'));
        lTelephony.add(gcr_TestUtility.getTelephonyData(false, 'Tide', 'Toll Free', ccInventory.Id, gcrContact.Id, '1800 (234) 5678'));
        lTelephony.add(gcr_TestUtility.getTelephonyData(false, 'Tide', 'Toll Free', ccInventory.Id, gcrContact.Id, '1800 (234) 5678'));
        lTelephony.add(gcr_TestUtility.getTelephonyData(false, 'Tide', 'Toll Free', ccInventory.Id, gcrContact.Id, '1800 (234) 5678'));
        lTelephony.add(gcr_TestUtility.getTelephonyData(false, 'Tide', 'Toll Free', ccInventory.Id, gcrContact.Id, '1800 (234) 5678'));

        lTelephony.add(gcr_TestUtility.getTelephonyData(true, 'Tide', 'Paid Number', ccInventory.Id, gcrContact.Id, '44 20 12345678'));
        lTelephony.add(gcr_TestUtility.getTelephonyData(false, 'Tide', 'Paid Number', ccInventory.Id, gcrContact.Id, '44 20 12345678'));
        lTelephony.add(gcr_TestUtility.getTelephonyData(false, 'Tide', 'Paid Number', ccInventory.Id, gcrContact.Id, '44 20 12345678'));
        
		lTelephony.add(gcr_TestUtility.getTelephonyData(false, 'Tide', 'Super Number', ccInventory.Id, gcrContact.Id, '1 301 34567890'));
        lTelephony.add(gcr_TestUtility.getTelephonyData(true, 'Tide', 'Super Number', ccInventory.Id, gcrContact.Id, '1 301 09876543'));
        
        Database.insert(lTelephony, true);
        
		Map<String, Schema.RecordTypeInfo> mRecordTypeInfoByName = GCRChannelContent__c.getSObjectType().getDescribe().getRecordTypeInfosByName();
		List<GCRCareHub__c> lCareHub = [ SELECT Id FROM GCRCareHub__c
                                         WHERE Brand__c = :gcr_TestUtility.DEFAULT_BRAND
                                             AND CountryIsoCode__c = :gcr_TestUtility.DEFAULT_COUNTRY_ISO 
                                             AND LanguageIsoCode__c = :gcr_TestUtility.DEFAULT_LANGUAGE_ISO ];

		gcr_callusController cuController = new gcr_callusController();
        cuController.inBrand = gcr_TestUtility.DEFAULT_BRAND;
        cuController.inCountry = gcr_TestUtility.DEFAULT_COUNTRY;
        cuController.inLanguage = gcr_TestUtility.DEFAULT_LANGUAGE;
        cuController.isRightToLeft = false;
        cuController.channelId = [ SELECT Id 
                                   FROM GCRChannelContent__c
                                   WHERE CareHub__c = :lCareHub.get(0).Id
									AND RecordTypeId = :mRecordTypeInfoByName.get('call us').getRecordTypeId() ].get(0).Id;

        Test.startTest();
        Boolean tempBool = cuController.controlInit;
        Test.stopTest();
        SYSTEM.assert(String.isNotEmpty(cuController.strOperationalHours)
                   && cuController.strOperationalHours.equalsIgnoreCase('We are available from 9:00 - 5:00 Monday - Friday'));
        SYSTEM.assert(cuController.mTelephoneNumbers != null && !cuController.mTelephoneNumbers.isEmpty());
    }
}