src/objects/Call_Center_Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Call_Center_Location__c</fullName>
        <label>Call Center Location</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>AAI</fullName>
                </value>
                <value>
                    <fullName>WE</fullName>
                </value>
                <value>
                    <fullName>CEEMEA</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>NEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Center Inventory</label>
    <nameField>
        <label>Call Center Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Center Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Us_Brand__c.object
<CustomObject>
    <description>This object is for configuring the brand options for the contact us page.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>This is the brand that is to be configured.</description>
        <label>Brand</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Contact Us Brand</label>
    <nameField>
        <label>Contact Us Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Telephony__c.object
<CustomObject>
    <fields>
        <fullName>Accept_Calls_from_Landline_Phone__c</fullName>
        <label>Accept Calls from Landline Phone?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Accept_Calls_from_Mobile__c</fullName>
        <label>Accept Calls from Mobile?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Accept_Calls_from_Prepaid_Phone__c</fullName>
        <label>Accept Calls from Prepaid?Phone?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pampers</fullName>
                </value>
                <value>
                    <fullName>NULL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Center</label>
        <referenceTo>Call_Center_Inventory__c</referenceTo>
        <relationshipLabel>Telephony</relationshipLabel>
        <relationshipName>Telephony</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Carrier_Contact_Information__c</fullName>
        <label>Carrier Contact Information</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Us_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Us Brand</label>
        <referenceTo>Contact_Us_Brand__c</referenceTo>
        <relationshipLabel>Telephony</relationshipLabel>
        <relationshipName>Telephony</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Has_1_Phone_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if the country uses the same phone number for all brands. Note, do not check if country uses the same phone number for multiple brands but not all</inlineHelpText>
        <label>Country Has 1 Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GCR_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GCR Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Telephony</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ITFS_Number__c</fullName>
        <label>ITFS Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ITFS_Status__c</fullName>
        <label>ITFS Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Crisis</fullName>
                </value>
                <value>
                    <fullName>Divested</fullName>
                </value>
                <value>
                    <fullName>Spare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albanian</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Armenian</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LocalOperationalHours__c</fullName>
        <label>Local Operational Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AAI</fullName>
                </value>
                <value>
                    <fullName>CEEMEA</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>NEA</fullName>
                </value>
                <value>
                    <fullName>WE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Telephony_Name__c</fullName>
        <label>Telephony Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>localBrand__c</fullName>
        <label>Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Telephony</label>
    <nameField>
        <displayFormat>Tel-{00000}</displayFormat>
        <label>Telephony Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telephony</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TelephonyTrigger_Test.cls
//Test Class for TelephonyTrigger
//Sylvester Agyen (Appirio, Inc)

@isTest(SeeAllData=true)

private class TelephonyTrigger_Test{


 static testMethod void validateTelephony(){
  Test.startTest();
     
  Contact_Us_Brand__c brand = new Contact_Us_Brand__c(name='dfdfg',Brand__c='jibberish');
   insert brand;
  Call_Center_Inventory__c callCenter = new Call_Center_Inventory__c(Name='test', Call_Center_Location__c='test');
     insert callCenter;
  Telephony__c tel1 = new Telephony__c(telephony_name__c='testtel1', 
                                       Language__c='English-US', 
                                       Country__c='Andorra',
                                       GCR_Contact__c =Userinfo.getUserId(),
                                       ITFS_Number__c ='1111111111',
                                       LocalOperationalHours__c= 'test',
                                       ITFS_Status__c ='Active',
                                       Region__c = 'NA',
                                       localBrand__c ='test',
                                       Carrier__c = '1111111111',
                                       Call_Center__c = callCenter.id,
                                       Contact_Us_Brand__c=brand.id,
                                       Accept_Calls_from_Prepaid_Phone__c='Yes',
                                       Accept_Calls_from_Landline_Phone__c = 'Yes',
                                       Accept_Calls_from_Mobile__c = 'Yes',
                                       Country_Has_1_Phone_Number__c=false,
                                       Carrier_Contact_Information__c ='tst'
                                       );
              
  
  
  try{
    insert tel1;
  }catch(DMLException e){
      system.debug(e);
  }
  
  tel1.Country_Has_1_Phone_Number__c = true;
  tel1.Contact_Us_Brand__c = null;
  try{
    update tel1;
  }catch(DMLException e){
      system.debug(e);
  }
  sf_ContactUsHeaderComponentCtrl handr= new sf_ContactUsHeaderComponentCtrl();
  handr.setTelephony();
  Test.stopTest();
 }
}