src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Return_Status__c</fullName>
        <description>Hidden field used by workflows to manage sending of reminders for product returns</description>
        <label>Product Return Reminder Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/d2p_consoleComp_ext_test.cls
@isTest
public class d2p_consoleComp_ext_test {

	@testSetup static void setupData(){
		checkrecursive.toggleAllTriggers(false);
        AutoComRuleHelper_datasetup_Test.dataSetup();
        checkrecursive.toggleAllTriggers(true);
    }
    
	/****************************
     * No valid CPS found		*
     ***************************/
	@isTest
    static void noValidCPTest(){
		Case noCPCase = [SELECT Id FROM Case WHERE Subject = 'CaseOnly' LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(noCPCase);
        
        test.startTest();
            d2p_consoleComp_ext ext = new d2p_consoleComp_ext(sc);
            ext.caseId = noCPCase.Id;
            ext.setCaseId();
            List<d2p_consoleComp_ext.cpWrapper> cps = new List<d2p_consoleComp_ext.cpWrapper>(ext.getACRCaseProducts());
            system.assertEquals(0, cps.size());
        test.stopTest();
    }
    
	/****************************
     * Valid and in progress CP	*
     * found and processed to	*
     * physical					*
     ***************************/
	@isTest
    static void inprogressCPTest(){
        Case validCase = [SELECT Id FROM Case WHERE Subject = 'digital' LIMIT 1];
        Case_Product__c validCP = [SELECT Id, Status__c FROM Case_Product__c WHERE Case__c = :validCase.Id LIMIT 1];
        
        checkrecursive.toggleAllTriggers(false);
        	List<SObject> updateRecords = new List<SObject>();
            validCP.Status__c = 'Photo - Attempt 2';
            validCase.Product_Return_Status__c = 'Photo - Attempt 2';
            updateRecords.add(validCP);
            updateRecords.add(validCase);
            update updateRecords;
        checkrecursive.toggleAllTriggers(true);

        ApexPages.StandardController sc = new ApexPages.StandardController(validCase);
        
		test.startTest();
        	//Open page and confirm 1 CP is displayed
            d2p_consoleComp_ext ext = new d2p_consoleComp_ext(sc);
            ext.caseId = validCase.Id;
            ext.setCaseId();
            List<d2p_consoleComp_ext.cpWrapper> cps = new List<d2p_consoleComp_ext.cpWrapper>(ext.getACRCaseProducts());
            system.assertEquals(1, cps.size());
        
			//Now select and process
        	//Already selected as in progress
        	ext.processSelected();

            validCP = [SELECT Id, Status__c FROM Case_Product__c WHERE Case__c = :validCase.Id LIMIT 1];
        	system.assertEquals('Product Requested - Attempt 1', validCP.Status__c);
        test.stopTest();
    }
    
	/****************************
     * Valid and NOT in progress*
     * CP found and processed 	*
     * to physical				*
     ***************************/
	@isTest
    static void validCPTest(){
		Case validCase = [SELECT Id FROM Case WHERE Subject = 'digital' LIMIT 1];
        Case_Product__c validCP = [SELECT Id, Status__c FROM Case_Product__c WHERE Case__c = :validCase.Id LIMIT 1];
        
		ApexPages.StandardController sc = new ApexPages.StandardController(validCase);
        
		test.startTest();
        	//Open page and confirm 1 CP is displayed
            d2p_consoleComp_ext ext = new d2p_consoleComp_ext(sc);
            ext.caseId = validCase.Id;
            ext.setCaseId();
            List<d2p_consoleComp_ext.cpWrapper> cps = new List<d2p_consoleComp_ext.cpWrapper>(ext.getACRCaseProducts());
            system.assertEquals(1, cps.size());

			//Try to process without selecting a CP
			ext.processSelected();
			List<ApexPages.Message> msgs = new List<ApexPages.Message>(ApexPages.getMessages());
			system.assertEquals(1, msgs.size());    
        
        test.stopTest();
    }
}