src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>7th Stage</fullName>
                </value>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>Align</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Always Discreet</fullName>
                </value>
                <value>
                    <fullName>Anna Sui</fullName>
                </value>
                <value>
                    <fullName>Ariel</fullName>
                </value>
                <value>
                    <fullName>Atra</fullName>
                </value>
                <value>
                    <fullName>Aussie</fullName>
                </value>
                <value>
                    <fullName>Avril Lavigne</fullName>
                </value>
                <value>
                    <fullName>Baldessarini</fullName>
                </value>
                <value>
                    <fullName>Balsam Color</fullName>
                </value>
                <value>
                    <fullName>Basic White</fullName>
                </value>
                <value>
                    <fullName>Beautiful Collection</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>Born Blonde</fullName>
                </value>
                <value>
                    <fullName>Boss Skin</fullName>
                </value>
                <value>
                    <fullName>Bounce</fullName>
                </value>
                <value>
                    <fullName>Bounty</fullName>
                </value>
                <value>
                    <fullName>Braun</fullName>
                </value>
                <value>
                    <fullName>BW2</fullName>
                </value>
                <value>
                    <fullName>Camay</fullName>
                </value>
                <value>
                    <fullName>Cascade</fullName>
                </value>
                <value>
                    <fullName>Charmin</fullName>
                </value>
                <value>
                    <fullName>Cheer</fullName>
                </value>
                <value>
                    <fullName>Christina Aguilera</fullName>
                </value>
                <value>
                    <fullName>Clairol</fullName>
                </value>
                <value>
                    <fullName>Clairol Pro Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional liquicolor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Received Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Level_3__c</fullName>
        <label>Level 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <externalId>true</externalId>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_CaseHighlightsPanelExt.cls
/*
* @author: Oleg Rikkers
* @date: 07/10/2014
* @description:  Extension class for Case highlight panel page
*/

public with sharing class sf_CaseHighlightsPanelExt {

	public String timeOpened {get; private set;}
	public String brands;
	public String products;
	public String comments;
	public Boolean showMakeMeCaseOwner {get; set;}

	private Case c;
	private List <Case_Product__c> caseProducts;

	public sf_CaseHighlightsPanelExt(ApexPages.StandardController sc) {
		c = (Case) sc.getRecord();
		showMakeMeCaseOwner = c.OwnerId == null ? false : String.valueOf(c.OwnerId.getSobjectType()) != 'User';

		if (c.Received_Date__c != null) 
			timeOpened = c.Received_Date__c.format('hh:mm a', String.valueOf(UserInfo.getTimeZone()));
		
		caseProducts = new List <Case_Product__c> ([SELECT Id
										,Local_Product__r.Global_Product__r.Brand__c
										,Local_Product__r.Name
									FROM Case_Product__c 
									WHERE Case__c = :c.Id]);


	}

	public String getBrands () {
		brands = '';
		Set <String> bSet = new Set <String> ();
		

		for (Case_Product__c cp: caseProducts) {
			if (cp.Local_Product__r.Global_Product__r.Brand__c != null)
				bSet.add (cp.Local_Product__r.Global_Product__r.Brand__c);
		}

		for (String s: bSet) {
			brands += ' ' + s + ',';
		}

		return brands.removeEnd(',');
	}


	//ALM276 - remove products

	//public String getProducts () {
	//	products = '';
	//	Set <String> pSet = new Set <String> ();
		

	//	for (Case_Product__c cp: caseProducts) {
	//		pSet.add (cp.Local_Product__r.Name);
	//	}

	//	List <String> pList = new List <String> ();

	//	pList.addAll(pSet);

	//	String s = '';

	//	for (Integer i=0; i<pList.size(); i++) {
	//		if (i==2) {
	//			s += ' +' + String.valueOf(pList.size()-2) + ' more...';
	//			break;
	//		} else {
	//			s += ' ' + pList[i] + ',';
	//		}
	//	}

	//	products = s.removeEnd(',');

	//	return products;
	//}

	public String getComments () {
		Set <String> cSet = new Set <String> ();

		for (Case_Comment_Code__c ccc: [SELECT Id
											,Local_Comment_Code__r.Level_3__c 
										FROM Case_Comment_Code__c 
										WHERE Case__c = :c.Id]) {
			cSet.add (ccc.Local_Comment_Code__r.Level_3__c);
		}

		List <String> cccList = new List <String> ();

		cccList.addAll(cSet);
		String s = '';

		for (Integer i=0; i<cccList.size(); i++) {
			if (i==2) {
				s += ' +' + String.valueOf(cccList.size()-2) + ' more...';
				break;
			} else {
				s += ' ' + cccList[i] + ',';
			}
		}

		comments = s.removeEnd(',');
		return comments;
	}
}