src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_ProductSearchCompTest.cls
/*

Test class for sf_ProductSearchConsoleComponentCtrl

@author 	Oleg Rikkers
@date 		05/09/2014


*/


@isTest

public with sharing class   sf_ProductSearchCompTest {

    public static testMethod void testAddProductComment () {

    	Case c = new Case ();
    	c.Country__c = 'China';
    	insert c;

        Global_Product__c gp = new Global_Product__c();
        //gp.Name = 'test product';
        insert gp;

    	List <Local_Product__c> lpl = new List <Local_Product__c> ();

    	for (Integer i=0; i<200; i++) {
    		Local_Product__c lp = new Local_Product__c ();
	    	lp.Name = 'tester' + i;
	    	lp.Country__c = 'China';
	    	lp.Translated_Path__c = 'tester path ' + i;
            lp.Global_Product__c = gp.Id;

	    	lpl.add(lp);
    	}

    	insert lpl;



    	Global_Comment_Code__c gcc = new Global_Comment_Code__c ();
    	insert gcc;

    	Local_Comment_Code__c cc = new Local_Comment_Code__c ();
    	//cc.Name = 'test';
    	cc.Global_Comment_Code__c = gcc.Id;

    	insert cc;

    	System.assertEquals(200, [SELECT Id FROM Local_Product__c].size(), 'Product was not created.');

    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_ProductSearchConsoleComponentCtrl ctrl = new sf_ProductSearchConsoleComponentCtrl (sc);

    	Test.startTest();
    	
    	List <sObject> lpList = sf_ProductSearchConsoleComponentCtrl.doSoslSearch('test', 'China');
    	List <sObject> ccList = sf_ProductSearchConsoleComponentCtrl.doCaseCommentSoslSearch('test', 'China', null);

    	//System.assertEquals(1, lpList.size(), 'Search did not return expected results');
    	sf_ProductSearchConsoleComponentCtrl.addProduct([SELECT Id FROM Local_Product__c LIMIT 1].Id, c.Id);

    	System.assertEquals(1, [SELECT Id FROM Case_Product__c].size(), 'Product was not added.');

    	ctrl.refreshCaseProducts();
    	ctrl.localProductId = [SELECT Id FROM Case_Product__c LIMIT 1].Id;
    	
    	sf_ProductSearchConsoleComponentCtrl.addCaseCommentCode(c.Id, cc.Id, ctrl.localProductId);
    	
    	System.assertEquals(1, [SELECT Id FROM Case_Comment_Code__c].size(), 'Case Comment was not added.');
    	
    	ctrl.refreshCaseProducts();
    	ctrl.commentCodeId = [SELECT Id FROM Case_Comment_Code__c LIMIT 1].Id;
    	
    	ctrl.removeCommentCode();
    	System.assertEquals(0, [SELECT Id FROM Case_Comment_Code__c].size(), 'Case Comment was not removed.');

    	
    	ctrl.removeCaseProduct();

    	Test.stopTest();
    }


    public static testMethod void testExceptions () {

    	Case c = new Case ();
    	c.Country__c = 'China';
    	insert c;

    

    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_ProductSearchConsoleComponentCtrl ctrl = new sf_ProductSearchConsoleComponentCtrl (sc);

    	Test.startTest();
    	
    	

    	ctrl.removeCommentCode();
    	ctrl.removeCaseProduct();
    
    	ctrl.localProductId = 'sdas';
    	ctrl.commentCodeId = 'sdasd';
    	
    	ctrl.removeCommentCode();
    	ctrl.removeCaseProduct();


    	Test.stopTest();
    }
}