src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>7th Stage</fullName>
                </value>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>Align</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Always Discreet</fullName>
                </value>
                <value>
                    <fullName>Anna Sui</fullName>
                </value>
                <value>
                    <fullName>Ariel</fullName>
                </value>
                <value>
                    <fullName>Atra</fullName>
                </value>
                <value>
                    <fullName>Aussie</fullName>
                </value>
                <value>
                    <fullName>Avril Lavigne</fullName>
                </value>
                <value>
                    <fullName>Baldessarini</fullName>
                </value>
                <value>
                    <fullName>Balsam Color</fullName>
                </value>
                <value>
                    <fullName>Basic White</fullName>
                </value>
                <value>
                    <fullName>Beautiful Collection</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>Born Blonde</fullName>
                </value>
                <value>
                    <fullName>Boss Skin</fullName>
                </value>
                <value>
                    <fullName>Bounce</fullName>
                </value>
                <value>
                    <fullName>Bounty</fullName>
                </value>
                <value>
                    <fullName>Braun</fullName>
                </value>
                <value>
                    <fullName>BW2</fullName>
                </value>
                <value>
                    <fullName>Camay</fullName>
                </value>
                <value>
                    <fullName>Cascade</fullName>
                </value>
                <value>
                    <fullName>Charmin</fullName>
                </value>
                <value>
                    <fullName>Cheer</fullName>
                </value>
                <value>
                    <fullName>Christina Aguilera</fullName>
                </value>
                <value>
                    <fullName>Clairol</fullName>
                </value>
                <value>
                    <fullName>Clairol Pro Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional liquicolor</fullName>
                </value>
                <value>
                    <fullName>Tide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <formula>CASE(Language__c,&quot;Arabic&quot;,&quot;ar&quot;,&quot;Chinese&quot;,&quot;zh&quot;,&quot;Chinese-T&quot;,&quot;bo&quot;,&quot;Croatian&quot;,&quot;hr&quot;,&quot;Czech&quot;,&quot;cs&quot;,&quot;Danish&quot;,&quot;da&quot;,&quot;Dutch&quot;,&quot;nl&quot;,&quot;Finnish&quot;,&quot;fi&quot;,&quot;Flemish&quot;,&quot;nl&quot;,&quot;French&quot;,&quot;fr&quot;,&quot;German&quot;,&quot;de&quot;,&quot;Greek&quot;,&quot;el&quot;,&quot;Hindi&quot;,&quot;hi&quot;,&quot;Hungarian&quot;,&quot;hu&quot;,&quot;Indonesian&quot;,&quot;in&quot;,&quot;Italian&quot;,&quot;it&quot;,&quot;Japanese&quot;,&quot;ja&quot;,&quot;Korean&quot;,&quot;ko&quot;,&quot;Malay&quot;,&quot;ms&quot;,&quot;Norwegian&quot;,&quot;no&quot;,&quot;Polish&quot;,&quot;pl&quot;,&quot;Portuguese&quot;,&quot;pt&quot;,&quot;Russian&quot;,&quot;ru&quot;,&quot;Slovakian&quot;,&quot;sk&quot;,&quot;Slovenian&quot;,&quot;sl&quot;,&quot;Spanish&quot;,&quot;es&quot;,&quot;Swedish&quot;,&quot;sv&quot;,&quot;Tagalog&quot;,&quot;tl&quot;,&quot;Thai&quot;,&quot;th&quot;,&quot;Turkish&quot;,&quot;tr&quot;,&quot;Ukrainian&quot;,&quot;uk&quot;,&quot;Vietnamese&quot;,&quot;vi&quot;,&quot;Hebrew&quot;,&quot;iw&quot;,&quot;en&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>WE</fullName>
        <active>true</active>
        <businessProcess>Country Defaults</businessProcess>
        <description>WE Cases</description>
        <label>WE</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QueueRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the Relation between Queues and Recordtypes. Replica of Email Service Configuration</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>QueueRecordType</label>
</CustomObject>

src/objects/SocialMediaEmailAddresses__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It stores email addresses which being used for sending error emails in Sprinklr integration.</description>
    <fields>
        <fullName>isExternal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this option if this email address is external. We do not send few kinds of emails outside</description>
        <inlineHelpText>Check this option if this email address is external. We do not send few kinds of emails outside</inlineHelpText>
        <label>isExternal</label>
        <type>Checkbox</type>
    </fields>
    <label>SocialMediaEmailAddresses</label>
</CustomObject>

src/objects/SocialMediaSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It stores all settings for Sprinklr integration</description>
    <fields>
        <fullName>Brand__c</fullName>
        <inlineHelpText>Leave empty if Unknown</inlineHelpText>
        <label>Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Leave empty if unknown</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Id__c</fullName>
        <label>Queue Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SN_Type__c</fullName>
        <description>Social network Name</description>
        <inlineHelpText>Name of the Social Network. Ex: Facebook, Twitter,...</inlineHelpText>
        <label>SN Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SN_Unique_Id__c</fullName>
        <inlineHelpText>Unique identifier of the Social Network</inlineHelpText>
        <label>SN Unique Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SocialMediaSettings</label>
</CustomObject>

src/classes/sf_SocialMediaServiceTest.cls
/**
* @author: Salesforce.com
* @date: 08/18/2014
* @description:  test class
*/

@isTest
private class sf_SocialMediaServiceTest{
	
	public static Id queueId { get; set; }
	public static Id getQueue() {
		 if (queueId == null) {
			Group grp = new Group(
			  Name = 'Default_Queue',
			  Type = 'Queue'
			);
			insert grp;
			System.runAs(new User(Id=UserInfo.getUserId()))
			{
				QueuesObject testQueue = new QueueSObject(QueueID = grp.id, SobjectType = 'Case');
				insert testQueue;
			}
			queueId = grp.Id;
		 }
		return queueId;
	}

    public static void insertEmailAddresses(){
        SocialMediaEmailAddresses__c metadata=new SocialMediaEmailAddresses__c();
        metadata.isExternal__c=false;
        metadata.name='bommali.a@pg.com';     
        insert metadata;
    }
    
    public static void insertSMSetting(string brand, string languagecode, string sntype, string snuid){
        SocialMediaSettings__c smset=new SocialMediaSettings__c();
        smset.name='Test';
        if(string.isNotBlank(brand))smset.Brand__c=brand;
        smset.Country__c='United States of America';
        smset.Language__c='English-US';
        smset.Language_Code__c=languagecode;
        smset.Queue_Id__c = getQueue();
        smset.SN_Type__c=sntype;
        smset.SN_Unique_Id__c=snuid;
        insert smset;
    }
    
    public static void insertQRRecord(){
    	
        QueueRecordType__c qrset = new QueueRecordType__c();
        qrset.name = getQueue();
        qrset.Country__c='United States of America';
        qrset.Language__c='English-US';
        qrset.MDO__c='AAI';
        qrset.Region__c='ASIA';
        RecordType rt = new RecordType();
        rt = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'case' LIMIT 1];
        qrset.Case_Record_Type_Id__c = rt.Id;
        qrset.Case_Record_Type_Name__c = rt.Name;
        insert qrset;
    }
    
    public static testmethod void testSocialMediaService(){
        insertEmailAddresses();
        insertSMSetting('Tide', 'en', 'Facebook', '123456789');
        insertQRRecord();      
      
        String snconsumerid='987654321';
        String snuniqueid='123456789';
        String sntype='Facebook';
        String lastname = 'Bommali';
        String firstname='Ashok';
        String summary='How are you?';
        String website = 'https://www.facebook.com/pgtest1';
        String languagecode = 'en';
        String snmessageid = '123123123';
      
        SocialMediaService.CaseAccountFields  inputobj = new SocialMediaService.CaseAccountFields();
        inputobj.SNConsumerID = snconsumerid;
        inputobj.SNUniqueID = snuniqueid;
        inputobj.SNTYPE = sntype;
        inputobj.lastname = lastname;
        inputobj.firstname = firstname;
        inputobj.summary = summary;
        inputobj.contactWebsite = website;
        inputobj.language= languagecode;
        inputobj.SNMessageID = snmessageid;
        inputobj.receivedDate = system.today();
        inputobj = SocialMediaService.createCaseServiceMethod(inputobj);
         
         
        System.assertNotEquals(inputobj.SFCaseID,null);
        //Activity call
        String sfdccaseidactivity=inputobj.SFCaseID;
        String activitydescription='Consumer comments come here...';
      
        SocialMediaService.ActivityFields inputobj2 = new SocialMediaService.ActivityFields();
        inputobj2.SFCaseID = sfdccaseidactivity;
        inputobj2.description = activitydescription;
        inputobj2.SNMessageID = snmessageid;
        inputobj2.receivedDate = system.today();
        inputobj2.isConsumerComment = true;
        inputobj2 = SocialMediaService.createActivityMethod(inputobj2);
        System.assertNotEquals(inputobj2.SFActivityID,null);
        
    }
    
    public static testmethod void testSocialMediaService2(){
        insertEmailAddresses();
        insertSMSetting('Tide', 'all', 'Facebook', '123456789');
        insertQRRecord(); 
      
        String snconsumerid='987654321';
        String snuniqueid='123456789';
        String sntype='Facebook';
        String lastname = 'Bommali';
        String firstname='Ashok';
        String summary='How are you?';
        String website = 'https://www.facebook.com/pgtest1';
        String languagecode = 'en';
        String snmessageid = '123123123';
      
        SocialMediaService.CaseAccountFields  inputobj = new SocialMediaService.CaseAccountFields();
        inputobj.SNConsumerID = snconsumerid;
        inputobj.SNUniqueID = snuniqueid;
        inputobj.SNTYPE = sntype;
        inputobj.lastname = lastname;
        inputobj.firstname = firstname;
        inputobj.summary = summary;
        inputobj.contactWebsite = website;
        inputobj.language= languagecode;
        inputobj.SNMessageID = snmessageid;
        inputobj.receivedDate = system.today();
        inputobj = SocialMediaService.createCaseServiceMethod(inputobj);
    }
    
    public static testmethod void testSocialMediaService3(){
    	  Boolean isException = false;
        try{  
            insertEmailAddresses();
            insertSMSetting('', 'all', 'Twitter', '12345678912345555');
            insertQRRecord(); 
          
            String snconsumerid='987654321';
            String snuniqueid='123456789';
            String sntype='Facebook';
            String lastname = 'Bommali';
            String firstname='Ashok';
            String summary='How are you?';
            String website = 'https://www.facebook.com/pgtest1';
            String languagecode = 'en';
            String snmessageid = '123123123';
          
            SocialMediaService.CaseAccountFields  inputobj = new SocialMediaService.CaseAccountFields();
            inputobj.SNConsumerID = snconsumerid;
            inputobj.SNUniqueID = snuniqueid;
            inputobj.SNTYPE = sntype;
            inputobj.lastname = lastname;
            inputobj.firstname = firstname;
            inputobj.summary = summary;
            inputobj.contactWebsite = website;
            inputobj.language= languagecode;
            inputobj.SNMessageID = snmessageid;
            inputobj.receivedDate = system.today();
            inputobj = SocialMediaService.createCaseServiceMethod(inputobj);
        } catch(Exception ex){
                System.debug(ex);
                System.assert(true); //we wanted exception ? 
                isException = true;
        }
        System.assert(isException);
    }
    
    public static testmethod void testSocialMediaService4(){
    	 Boolean isException = false;
        try{  
            insertEmailAddresses();
            insertSMSetting('', 'all', 'Twitter', '12345678912345555');
            insertQRRecord();
      
            String snconsumerid='987654321';
            String snuniqueid='123456789';
            String sntype='Facebook';
            String lastname = 'Bommali';
            String firstname='Ashok';
            String summary='How are you?';
            String website = 'https://www.facebook.com/pgtest1';
            String languagecode = 'en';
            String snmessageid = '123123123';
      
            SocialMediaService.CaseAccountFields  inputobj = new SocialMediaService.CaseAccountFields();
            inputobj.SNConsumerID = snconsumerid;
            inputobj.SNUniqueID = snuniqueid;
            inputobj.SNTYPE = sntype;
            //inputobj.lastname = lastname;
            //inputobj.firstname = firstname;
            inputobj.summary = summary;
            //inputobj.contactWebsite = website;
            inputobj.language= languagecode;
            inputobj.SNMessageID = snmessageid;
            inputobj.receivedDate = system.today();
            inputobj = SocialMediaService.createCaseServiceMethod(inputobj);
        } catch(Exception ex){
            System.debug(ex);
            System.assert(true); //we wanted exception ? 
            isException = true;
        }
        System.assert(isException);
    }
    
    public static testmethod void testSocialMediaService5(){
        try {
            insertEmailAddresses();
            insertSMSetting('Tide', 'en', 'Facebook', '123456789');
            insertQRRecord();  
      
            String snconsumerid='987654321';
            String snuniqueid='123456789';
            String sntype='Facebook';
            String lastname = 'Bommali';
            String firstname='Ashok';
            String summary='How are you?';
            String website = 'https://www.facebook.com/pgtest1';
            String languagecode = 'en';
            String snmessageid = '123123123';
          
            SocialMediaService.CaseAccountFields  inputobj = new SocialMediaService.CaseAccountFields();
            inputobj.SNConsumerID = snconsumerid;
            inputobj.SNUniqueID = snuniqueid;
            inputobj.SNTYPE = sntype;
            inputobj.lastname = lastname;
            inputobj.firstname = firstname;
            inputobj.summary = summary;
            inputobj.contactWebsite = website;
            inputobj.language= languagecode;
            inputobj.SNMessageID = snmessageid;
            inputobj.receivedDate = system.today();
            inputobj = SocialMediaService.createCaseServiceMethod(inputobj);
          
            //Activity call
            String sfdccaseidactivity=inputobj.SFCaseID;
            String activitydescription='internal comments come here...';
          
            SocialMediaService.ActivityFields inputobj2 = new SocialMediaService.ActivityFields();
            inputobj2.SFCaseID = sfdccaseidactivity;
            inputobj2.description = activitydescription;
            inputobj2.SNMessageID = snmessageid;
            inputobj2.receivedDate = system.today();
            inputobj2.isConsumerComment = false;
            inputobj2 = SocialMediaService.createActivityMethod(inputobj2);
            System.assertNotEquals(inputobj2.SFActivityID,null);
        } catch(Exception ex){
            System.debug(ex);
            System.assert(true); //we wanted exception ? 
        }
    } 
}