src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the caller/contact</description>
        <inlineHelpText>Please select the language of the contact</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Language__c.object
<CustomObject>
    <description>This object is for configuring the language/countries for the contact us page</description>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Us Language</label>
    <nameField>
        <label>Contact Us Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSAT_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CSAT Surveys</relationshipLabel>
        <relationshipName>CSAT_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Id__c</fullName>
        <externalId>true</externalId>
        <label>Survey Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CSAT Survey</label>
    <nameField>
        <displayFormat>CSAT-{00000000}</displayFormat>
        <label>CSAT Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSAT Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_CSATSurveyExtTest.cls
/**
* @author: salesforce.com
* @date: 02/10/2015
*
* @description: test class for sf_CSATSurveyExt
* Updated to include coverage for WR212 work
* 
*/

@isTest
private class sf_CSATSurveyExtTest {
	/*Rewriting as part of WR212*/
    /*
	@isTest static void testNewSurvey() {
		//create a contact 
    	Contact c = new Contact ();
    	c.LastName = 'test';
        c.Email = 'test@qeqwetestc.com';
    	insert c;

		Case ca = new Case ();
    	ca.Status = 'New';
    	ca.ContactId = c.Id;
    	insert ca;

    	ca.Status = 'Closed';
    	update ca;

    	CSAT_Survey__c csat = [SELECT Id, Survey_Id__c FROM CSAT_Survey__c WHERE Case__c = :ca.Id LIMIT 1];

    	PageReference p = Page.sf_CSATSurvey;
    	p.getParameters().put ('surveyid', csat.Survey_Id__c);

    	Test.setCurrentPage(p);

    	Test.startTest();

    	sf_CSATSurveyExt ext = new sf_CSATSurveyExt (new sf_ContactUsTemplateController ());
    	ext.getBrandYouCanTrustOptions();
    	ext.getRadioButtonOptions();
    	ext.getRadioButtonTenOptions();
    	ext.getBrandYouWillBuyOptions();
    	ext.saveSurvey();

    	Test.stopTest();

    	System.assert(ext.showThankYou);
    	System.assertEquals(false, ext.hasErrors);

	}*/

    @testSetup
    static void setupData(){
    	Contact c = new Contact ();
    	c.LastName = 'test';
        c.Email = 'test@qeqwetestc.com';
    	insert c;

		Case ca = new Case ();
    	ca.Status = 'New';
    	ca.ContactId = c.Id;
    	insert ca;
        
		EmailMessage lastResponseEm = new EmailMessage();
        lastResponseEm.ParentId = ca.Id;
        lastResponseEm.Subject = 'Agent last response';
        lastResponseEm.TextBody = 'Last response content goes here';
        lastResponseEm.Status = '3';
        lastResponseEm.Incoming = False;
        insert lastResponseEm;

    	ca.Status = 'Closed';
    	update ca;

        Contact_Us_Language__c langConfig = new Contact_Us_Language__c();
        langConfig.Country__c = 'United States of America';
        langConfig.Language__c = 'English-US';
        langConfig.Brand_Please_Select__c = 'Please select';
        langConfig.Helpful_Yes__c = 'Yes';
        langConfig.Helpful_No__c = 'No';
        insert langConfig;
    }
    @isTest
    static void noCSATTest(){
        
		PageReference p = Page.sf_CSATSurvey;
        
        Test.setCurrentPage(p);
        
		test.startTest();
            sf_CSATSurveyExt ext = new sf_CSATSurveyExt (new sf_ContactUsTemplateController ());
			List<ApexPages.Message> msgs = new List<ApexPages.Message>(ApexPages.getMessages());

        	system.assertEquals(1, msgs.size());
        	msgs.clear();
        
        	p.getParameters().put ('surveyid', 'stuff here');
            try{
                ext = new sf_CSATSurveyExt (new sf_ContactUsTemplateController ());
            }
            catch(exception e){
                msgs = new List<ApexPages.Message>(ApexPages.getMessages());
            }
        	system.assertEquals(1, msgs.size());        
    	Test.stopTest();
        
    }
    @isTest
    static void noEmailFoundTest(){
        Case ca = [SELECT Id FROM Case LIMIT 1];
        CSAT_Survey__c csat = [SELECT Id, Survey_Id__c FROM CSAT_Survey__c WHERE Case__c = :ca.Id LIMIT 1];
		EmailMessage deleteMe = [SELECT Id FROM EmailMessage WHERE ParentID = :ca.Id];
        delete deleteMe; //So no email message is found
        
		PageReference p = Page.sf_CSATSurvey;
    	p.getParameters().put ('surveyid', csat.Survey_Id__c);
        
        Test.setCurrentPage(p);
        
        test.startTest();
        	sf_CSATSurveyExt ext = new sf_CSATSurveyExt (new sf_ContactUsTemplateController ());
        	ext.replyReceived = 'No';
        	system.assertEquals('Sorry something went wrong, no message was found', ext.lastResponse);
        test.stopTest();
        
    }
    
	@isTest
    static void sf_CSATSurveyExtTest(){
        Case ca = [SELECT Id FROM Case LIMIT 1];
        CSAT_Survey__c csat = [SELECT Id, Survey_Id__c FROM CSAT_Survey__c WHERE Case__c = :ca.Id LIMIT 1];
        
		PageReference p = Page.sf_CSATSurvey;
    	p.getParameters().put ('surveyid', csat.Survey_Id__c);
        
        Test.setCurrentPage(p);
        
        test.startTest();
            sf_CSATSurveyExt ext = new sf_CSATSurveyExt (new sf_ContactUsTemplateController ());
        	String testString = ext.taskDescription;
            ext.getBrandYouCanTrustOptions();
            ext.getRadioButtonOptions();
            ext.getRadioButtonTenOptions();
            ext.getBrandYouWillBuyOptions();
        	
            ext.saveSurvey();
    	Test.stopTest();

    	System.assert(ext.showThankYou);
    	System.assertEquals(false, ext.hasErrors);
    }
    
    @isTest
    static void CSATResponseTest(){
		Case ca = [SELECT Id FROM Case LIMIT 1];
        CSAT_Survey__c csat = [SELECT Id, Survey_Id__c FROM CSAT_Survey__c WHERE Case__c = :ca.Id LIMIT 1];
		Contact_Us_Language__c langConfig = [SELECT Country__c, Language__c, Brand_Please_Select__c, Helpful_Yes__c, Helpful_No__c FROM Contact_Us_Language__c LIMIT 1];
        
    	PageReference p = Page.sf_CSATSurvey;
    	p.getParameters().put ('surveyid', csat.Survey_Id__c);
        p.getParameters().put ('country', langConfig.Country__c);
        p.getParameters().put ('language', langConfig.Language__c);

		Test.setCurrentPage(p);
        
        test.startTest();
        	sf_CSATSurveyExt ext = new sf_CSATSurveyExt (new sf_ContactUsTemplateController ());
        
			Integer taskCount = [SELECT Count() FROM Task WHERE WhatId = :ca.Id];
        	List <SelectOption> replyOption = ext.ReplyOptions;
        
        	ext.replyReceived = 'No';
        	String lastResponse = ext.lastResponse;
        	ext.needMoreHelp = 'No';
        	ext.taskDescription = 'Consumer response here. Please contact me on...';
        	ext.saveTask();

        	//Confirm Case has been reopened and flagged as Did not receive response
        	ca = [SELECT Id, Status, CX_Did_not_receive_response__c FROM Case WHERE Id = :ca.Id];
        	system.assertEquals(True, ca.CX_Did_not_receive_response__c);
        	system.assertEquals('Reopened by Consumer', ca.Status);
        
        	//Confirm that recontact task has been created:
			Integer postTaskCount = [SELECT Count() FROM Task WHERE WhatId = :ca.Id];
        	system.assertEquals(taskCount+1, postTaskCount);
        
        	//Confirm that CSAT record has been deleted
        	List<CSAT_Survey__c> csatList = new List<CSAT_Survey__c>([SELECT Id FROM CSAT_Survey__c WHERE Case__c = :ca.Id]);
        	system.assertEquals(0, csatList.size());
        test.stopTest();
    }
}