src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Consumer_Facing_Brand__c</fullName>
        <formula>Local_Product__r.Consumer_Facing_Brand__c</formula>
        <label>Consumer Facing Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Consumer_Facing_Brand__c</fullName>
        <label>Consumer Facing Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GTIN__c.object
<CustomObject>
    <description>Contains the GTINs related to Local Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Austria-PGP</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belgium-PGP</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>France-PGP</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Germany-PGP</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>GTIN</relationshipLabel>
        <relationshipName>GTINProducts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GTIN</label>
    <nameField>
        <label>GTIN Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GTIN</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPMS__c.object
<CustomObject>
    <description>This object holds the IPMS information</description>
    <fields>
        <fullName>Local_Product__c</fullName>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>IPMS</relationshipLabel>
        <relationshipName>IPMS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPMS</label>
    <nameField>
        <label>IPMS Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Search_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores settings for the Product Search</description>
    <fields>
        <fullName>Max_Search_Results_Returned__c</fullName>
        <label>Max Search Results Returned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Search Configuration</label>
</CustomObject>

src/classes/sf_ProductSearchSubtabControllerTest.cls
@isTest
private class sf_ProductSearchSubtabControllerTest {

    static testMethod void searchProductAndAddProductTest() {
    	Product_Search_Configuration__c psc = new Product_Search_Configuration__c();
    	psc.Max_Search_Results_Returned__c = 100;
    	insert psc;
    	
    	Case c = new Case ();
    	c.Country__c = 'United States of America';
    	c.Language__c = 'English-US';
    	insert c;

        Global_Product__c gp = new Global_Product__c();
        //gp.Name = 'test product';
        insert gp;

    	List <Local_Product__c> lpl = new List <Local_Product__c> ();

    	for (Integer i=0; i<200; i++) {
    		Local_Product__c lp = new Local_Product__c ();
	    	lp.Name = 'tester' + i;
	    	lp.Country__c = 'United States of America';
	    	lp.Translated_Path__c = 'tester path ' + i;
            lp.Global_Product__c = gp.Id;
            lp.Consumer_Facing_Brand__c = 'test';

	    	lpl.add(lp);
    	}

    	insert lpl;

		//Verify Products inserted
    	System.assertEquals(200, [SELECT Id FROM Local_Product__c].size(), 'Product was not created.');

    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_ProductSearchSubtabController ctrl = new sf_ProductSearchSubtabController (sc);

	    Test.startTest();
	    	
	    	//verify case query by caseId
	    	System.assertEquals(c.Id, ctrl.caseRecord.Id, 'Case Id not set');
	    	System.assertEquals('United States of America', ctrl.caseRecord.Country__c, 'Case Country not set');
	    	System.assertEquals('English-US', ctrl.caseRecord.Language__c, 'Case Language not set');
        
        	List<SelectOption> countries = ctrl.getCountries();
        	System.assert(countries.size() > 0);

	    	//Verify product search results
			Id [] productResults = new Id[1];
	   		productResults[0] = lpl[0].Id;
			Test.setFixedSearchResults(productResults);
	    	List <sf_ProductSearchSubtabController.SearchResult> lpList = sf_ProductSearchSubtabController.doSoslSearch('test', 'United States of America', 'freeText');
	    	System.assertNotEquals(1, lpList.size(), 'Search did not return expected results');
	
	    	//Verify product search results with IPMS

			//verify adding product
	    	Integer successCount = sf_ProductSearchSubtabController.addProduct([SELECT Id FROM Local_Product__c LIMIT 1].Id, 'test', c.Id, 'test', '', '');
	    	System.assertEquals(1, [SELECT Id FROM Case_Product__c].size(), 'Product was not added.');
	    	System.assertEquals(1, successCount, 'Test Error: Expecting 1 Product to be added.');
	    	
	    	//verify add product error for blank Local_Product__c.Id
	    	Integer failCount = sf_ProductSearchSubtabController.addProduct('', 'test', c.Id, 'test', '', '');
	    	System.assertEquals(-1, failCount, 'Test Error: Expecting Add Product Failure (-1)');

    	Test.stopTest();
    }
    
	public static testMethod void gtinAndIpmsSearchTest(){
		Product_Search_Configuration__c psc = new Product_Search_Configuration__c();
    	psc.Max_Search_Results_Returned__c = 100;
    	insert psc;
    	
    	Case c = new Case ();
    	c.Country__c = 'China';
    	c.Language__c = 'Chinese';
    	insert c;

        Global_Product__c gp = new Global_Product__c();
        insert gp;

    	Local_Product__c lp = new Local_Product__c ();
	    lp.Name = 'tester';
	    lp.Country__c = 'China';
	    lp.Translated_Path__c = 'tester path 1';
        lp.Global_Product__c = gp.Id;
        lp.GTIN_Number__c = '0000012345';
    	insert lp;
    	
    	Local_Product__c lp2 = new Local_Product__c ();
	    lp2.Name = '12345';
	    lp2.Country__c = 'China';
	    lp2.Translated_Path__c = 'tester path 1';
        lp2.Global_Product__c = gp.Id;
        lp2.GTIN_Number__c = '0000012345';
    	insert lp2;
    	
    	IPMS__c ipms = new IPMS__c();
    	ipms.Name = '0012345';
    	ipms.Local_Product__c = lp.Id;
    	insert ipms;

    	IPMS__c ipms2 = new IPMS__c();
    	ipms2.Name = '0012345678';
    	ipms2.Local_Product__c = lp.Id;
    	insert ipms2;
    	
        GTIN__c gtin = new GTIN__c();
    	gtin.Name = '0012345';
    	gtin.Local_Product__c = lp.Id;
    	insert gtin;
    	
    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_ProductSearchSubtabController ctrl = new sf_ProductSearchSubtabController (sc);
    
    	test.startTest();
    		
    		//coverage for GTIN search
    		Id [] gtinResults = new Id[2];
       		gtinResults[0] = lp.Id;
       		gtinResults[1] = gtin.Id;
    		Test.setFixedSearchResults(gtinResults);
    		List<sf_ProductSearchSubtabController.SearchResult> gtinProdList = sf_ProductSearchSubtabController.doSoslSearch('12345', 'China', 'barCode');
    		System.assertEquals(1, gtinProdList.size(), 'Invalid results returned for GTIN search.');

			//Test IPMS search
			Id [] ipmsResults = new Id[4];
			ipmsResults[0] = lp.Id;
       		ipmsResults[1] = lp2.Id;
       		ipmsResults[2] = ipms.Id;
       		ipmsResults[3] = ipms2.Id;
    		Test.setFixedSearchResults(ipmsResults);			
			List<sf_ProductSearchSubtabController.SearchResult> ipmsProdList = sf_ProductSearchSubtabController.doSoslSearch('12345', 'China', 'ipmsSearch');
    		System.assertEquals(2, ipmsProdList.size(), 'Invalid results returned for IPMS search.');

    	test.stopTest();	
    }
}