src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                    <default>true</default>
                    <label>United States of America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is going to be the First Level Identifying the Type of Comment</description>
        <label>Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Complaints Other</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Product Quality Complaint</fullName>
                </value>
                <value>
                    <fullName>Testimonial</fullName>
                </value>
                <value>
                    <fullName>Unable to Classify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Consumer_Facing_Name__c</fullName>
        <label>Consumer Facing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <description>This is the full path for the product starting at Brand</description>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is the first level indicating the type of the comment code</description>
        <externalId>true</externalId>
        <label>Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Consumer_Facing_Name__c</fullName>
        <description>Used for ContactUs page.</description>
        <label>Consumer Facing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Facing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for ContactUs page.</description>
        <label>Consumer Facing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_TestDataUtility.cls
/**
* @author: Oleg Rikkers
* @date: 06/02/2014
*
* @description: creates test data for test classes
*
*/

public with sharing class sf_TestDataUtility {
	
	//create global and local products
	public static void setupProducts (Integer size) {
		List <Global_Product__c> gpList = new List <Global_Product__c> ();
		List <Local_Product__c> lpList = new List <Local_Product__c> ();

		for (Integer i = 0; i<size; i++) {
			Global_Product__c gp = new Global_Product__c ();
			gp.Path__c = 'Gp/test/test/test';

			gpList.add (gp);
		}

		if (Test.isRunningTest())
			insert gpList;

		for (Global_Product__c gp: gpList) {
			for (Integer i=0; i<5; i++) {
				Local_Product__c lp = new Local_Product__c ();
				lp.Global_Product__c = gp.Id;
				lp.Country__c = 'United States of America';
				lp.Translated_Path__c = 'Test/Test/Test/Test/' + gp.Id;
				lp.Consumer_Facing__c = true;
				lp.Consumer_Facing_Name__c = 'Test consumer name ' + gp.Id;


				lpList.add(lp);	
			}
		}

		insert lpList;
	}

	public static void setupComments (Integer size) {
		List <Global_Comment_Code__c> gccList = new List <Global_Comment_Code__c> ();
		List <Local_Comment_Code__c> lccList = new List <Local_Comment_Code__c> ();

		for (Integer i = 0; i<size; i++) {
			Global_Comment_Code__c gcc = new Global_Comment_Code__c ();
			gcc.Level_1__c = 'test';
			gcc.Level_2__c = 'test';
			gcc.Level_3__c = 'test';
			
			gccList.add (gcc);
		}

		if (Test.isRunningTest())
			insert gccList;

		for (Global_Comment_Code__c gcc: gccList) {
			for (Integer i=0; i<5; i++) {
				Local_Comment_Code__c lcc = new Local_Comment_Code__c ();
				//lcc.Country__c = 'United States of America';
				lcc.Global_Comment_Code__c = gcc.Id;
				lcc.Translated_Language__c = 'English-US';
				lcc.Criticality__c = 'Super';


				lccList.add(lcc);	
			}
		}

		insert lccList;

	}

	//create user
	public static User createUser (String profileName, String lastName) {
		User user = new User ();
		user.Username = lastName + 'newuser@example.com';
		User.ProfileId = [SELECT ID FROM Profile WHERE Name = :profileName].ID;
		user.LastName = LastName;
		user.Alias = 'nus010';
		user.Email = lastName + '@example.com';
		user.CompanyName = 'TestCompany001001';
		user.EmailEncodingKey = 'ISO-8859-1';
		user.LanguageLocaleKey = 'en_US';
		user.TimeZoneSidKey = 'America/Indiana/Indianapolis';
		user.LocaleSidKey = 'en_US';
		user.Country = 'United States';
		user.IsActive = true;
		return user;

	}

	//create case
	public static Case createCase () {
		Case c = new Case ();
		c.Subject = 'Test subject';
		insert c;
		return c;
	}
   
   public static Contact createContact () {
		Contact con = new Contact();
		con.LastName = 'TestLastName';
		con.FirstName = 'TestFirstName';
		return con;
	}
	
	 public static Attachment createAttachment (Id parentId) {
		Attachment att = new Attachment ();
		att.ParentId = parentId; 
		att.Name = 'skjenkjfnejnfsjkennskjeskjenkjfnejnfsjkennskjeskjenkjfnejnfsjkennskjenkjfnejnfsjkenfjkekjenkjfnejnfsjknfjksenfkjsenfjksenf.pdf';
		att.Body = Blob.valueOf(att.Name);
		return att;
	}
	
	public static Task createTask (Id parentId,Id recTypeId) {
		Task tsk = new Task ();
		tsk.WhatId = parentId; 
		tsk.RecordTypeId = recTypeId;
		tsk.Priority = sf_Constants.PRIORITY_LOW;
		tsk.Subject = 'Test';
		tsk.Status = 'In Progress';
		return tsk;
	}
	
	public static Fulfillment_Order__c createFFOrder(Id caseId){
      Fulfillment_Order__c ffoObj = new Fulfillment_Order__c();
      ffoObj.Case__c = caseId;
      return ffoObj;
   }
   
   public static Fulfillment_Order_Line_Item__c createFFOrderLineItem(Id ffoObjId){
      Fulfillment_Order_Line_Item__c fforderlineItem = new Fulfillment_Order_Line_Item__c();
      fforderlineItem.fulfillment_Order__c = ffoObjId;
      return fforderlineItem;
   }
}