src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Return_Status__c</fullName>
        <description>Hidden field used by workflows to manage sending of reminders for product returns</description>
        <label>Product Return Reminder Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_Return_Type__c</fullName>
        <description>Return type for Case - cannot be a mixture of physical/digital</description>
        <inlineHelpText>Return type for Case - cannot be a mixture of physical/digital</inlineHelpText>
        <label>Selected Return Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACR_Return_Type__c</fullName>
        <description>Return types supported by matching ACR:
Digital = Digital + Physical 
Physical = Physical only</description>
        <inlineHelpText>Return types supported by matching ACR:
•Digital = Digital + Physical 
•Physical = Physical only</inlineHelpText>
        <label>ACR Return Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACR_Return_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Digital_Return_Id__c</fullName>
        <description>Unique Id generated for digital return form, set by code</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Id generated for digital return form, set by code</inlineHelpText>
        <label>Digital Return Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Exception__c.object
<CustomObject>
    <description>Custom exception object to store exceptions/errprs</description>
    <fields>
        <fullName>Further_Details__c</fullName>
        <description>Optional/extra details that can be sent via specific code calling exception handler</description>
        <label>Further Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <displayFormat>Ex-{000000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ctr_DPRUploadForm_test.cls
@isTest
public class ctr_DPRUploadForm_test {
    
	private static String attachmentBody ='Unit Test Attachment Body';
	private static String attachmentName = 'IamanAttachment';
	private static String attachmentType = '.png';
	private static String attachmentId = null;

    @testSetup static void setupData(){
		checkrecursive.toggleAllTriggers(false);
        AutoComRuleHelper_datasetup_Test.dataSetup();
        checkrecursive.toggleAllTriggers(true);
    }

	/****************************
     * Invalid/No UID given		*
     ***************************/
	@isTest
    static void noUIDTest(){
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);   
        
		test.startTest();
        	ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.pii = false;
        	ctr.uid = 'cheese';
        	String pageError = ctr.errorMessage;
        	system.assertEquals(System.label.Invalid_URL,pageError);
        test.stopTest();
    }
    
	/****************************
     * Photos already received	*
     ***************************/
	@isTest
    static void photosAlreadyReceivedTest(){
        Case_Product__C cp = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, Digital_Return_Id__c FROM Case_Product__c WHERE ACR_Return_Type__c = 'Digital' AND Digital_Return_Id__c != null];
        cp.Status__c = 'Photo Received';
        update cp;
        
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('uid', cp.Digital_Return_Id__c);   
        
        test.startTest();
			ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.init();
			String pageError = ctr.errorMessage;
        	system.assertEquals(System.label.Photos_Already_Received,pageError);
        test.stopTest();
    }
    
	/****************************
     * Succesfully upload and	*
     * remove attachment		*
     ***************************/    
    @isTest
    static void successfulUploadandRemoveTest(){
        Case testCase =[SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__C cp = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, Digital_Return_Id__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        system.assertNotEquals(null, cp.Digital_Return_Id__c);
        
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('uid', cp.Digital_Return_Id__c);
        
        test.startTest();
        	ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.init();

        	ctr_DPRUploadForm.doUploadAttachment(attachmentBody, attachmentName, attachmentType, attachmentId, cp.Digital_Return_Id__c);
        	ctr.attachmentName = attachmentName;
        	ctr.saveAttachment();
        
        	List<Attachment> caseAtts = new List<Attachment>([SELECT Id FROM Attachment WHERE ParentId = :testCase.Id]);
        	system.assertEquals(1, caseAtts.size());
        
        	//Remove attachment test
        	ctr.remAttachmentIndex = '0';
        	ctr.srtAttachmentId = caseAtts[0].Id;
        	ctr.removeAttachment();
        	caseAtts = new List<Attachment>([SELECT Id FROM Attachment WHERE ParentId = :testCase.Id]);
        
        	system.assertEquals(0, caseAtts.size());
        
        test.stopTest();
    }
    
	/****************************
     * Succesfully upload and	*
     * submit form				*
     ***************************/ 
	@isTest
    static void uploadandSubmitTest(){
        Case testCase = [SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__C cp = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, Digital_Return_Id__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        system.assertNotEquals(null, cp.Digital_Return_Id__c);
        
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('uid', cp.Digital_Return_Id__c);
        
        test.startTest();
        	ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.init();

        	ctr_DPRUploadForm.doUploadAttachment(attachmentBody, attachmentName, attachmentType, attachmentId, cp.Digital_Return_Id__c);
        	ctr.attachmentName = attachmentName;
        	ctr.saveAttachment();
        
        	List<Attachment> caseAtts = new List<Attachment>([SELECT Id FROM Attachment WHERE ParentId = :testCase.Id]);
        	system.assertEquals(1, caseAtts.size());

        	ctr.submit();
        	testCase = [SELECT Id, Product_Return_Status__c, Status FROM Case WHERE Id = :testCase.Id];
        	List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        	system.assertEquals('Photo Received', testCase.Product_Return_Status__c);
        	system.assertEquals(1, caseEmails.size());
        
        test.stopTest();
    }
    
	/****************************
     * confirmation email		*
     * error tests				*
     ***************************/
 	@isTest
    static void noEmailThankyouTemplateTest(){
        Case testCase = [SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__C cp = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, Digital_Return_Id__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        system.assertNotEquals(null, cp.Digital_Return_Id__c);
        
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('uid', cp.Digital_Return_Id__c);
        
		test.startTest();
        	ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.init();
        	//Null thank you email so no email template is found
        	ctr.acr.Digital_Thankyou_Email__c = '';
        	ctr.submit();
		test.stopTest(); 
        
        List<Exception__c> exceptions = new List<Exception__c>([SELECT Id, Further_Details__c FROM Exception__c]);
        system.assertEquals(1, exceptions.size());
        system.assert(exceptions[0].Further_Details__c.startsWith('DPR Upload Form - Failure on confirmation email.'));
    }
    
	@isTest
    static void confirmationEmailErrorTest(){
        Case testCase = [SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__C cp = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, Digital_Return_Id__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        system.assertNotEquals(null, cp.Digital_Return_Id__c);
        
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('uid', cp.Digital_Return_Id__c);
        
		test.startTest();
        	ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.init();
        	Case_Product__c nullCP = new Case_Product__c();
        	ctr.caseCP = nullCP;

        	ctr.sendConfirmationEmail();
		test.stopTest(); 
        
        List<Exception__c> exceptions = new List<Exception__c>([SELECT Id, Further_Details__c FROM Exception__c]);
        system.assertEquals(1, exceptions.size());
        system.assert(exceptions[0].Further_Details__c.startsWith('DPR Upload Form - Failure on confirmation email.'));
    }
    
	/****************************
     * Submit error tests		*
     ***************************/ 
	@isTest
    static void submitErrorTest(){
        Case testCase = [SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__C cp = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, Digital_Return_Id__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        system.assertNotEquals(null, cp.Digital_Return_Id__c);
        
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('uid', cp.Digital_Return_Id__c);
        
		test.startTest();
        	ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.init();
        	Case_Product__c nullCP = new Case_Product__c();
        	
        	ctr.caseCP = nullCP;
        	ctr.submit();
        
        	system.assertEquals(system.label.DPR_Submit_Error, ctr.submitErrorMsg);
        test.stopTest();
    }
   
	/****************************
     * Attachment method tests	*
     ***************************/    
    @isTest
    static void attachmentTests(){
        Case testCase =[SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__C cp = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, Digital_Return_Id__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        system.assertNotEquals(null, cp.Digital_Return_Id__c);
        
		PageReference pageRef = Page.siteDPRUploadForm;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('uid', cp.Digital_Return_Id__c);
        
		test.startTest();
        	ctr_DPRUploadForm ctr = new ctr_DPRUploadForm();
        	ctr.init();
        
			//coverage of null
			ctr.srtAttachmentErr = '';
			ctr_DPRUploadForm.doUploadAttachment(null, null, null, null, null);
        
        	//Coverage of getAttachment
			attachmentId = ctr_DPRUploadForm.doUploadAttachment(attachmentBody, attachmentName, attachmentType, attachmentId, cp.Digital_Return_Id__c);
        	ctr_DPRUploadForm.doUploadAttachment(attachmentBody, attachmentName, attachmentType, attachmentId, cp.Digital_Return_Id__c);
        
        	//Remove attachment error
        	ctr.removeAttachment();
        
        test.stopTest();
        
		List<Exception__c> exceptions = new List<Exception__c>([SELECT Id, Further_Details__c FROM Exception__c]);
        system.assertEquals(1, exceptions.size());
        system.assert(exceptions[0].Further_Details__c.startsWith('DPR Upload Form - Error removing attachment.'));
    }    
}