src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Search_Term__c</fullName>
        <description>Search term used on email us page to find product</description>
        <label>Search Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Country_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings controlling if the State/County AND ZIP/Postal code are mandatory fields in the console and contact us pages</description>
    <fields>
        <fullName>Uses_Postal_Codes__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Uses Postal Codes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uses_States__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Uses States</label>
        <type>Checkbox</type>
    </fields>
    <label>Country Status</label>
</CustomObject>

src/objects/DAM_Brandstore_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Brandstore_Image_Token__c</fullName>
        <defaultValue>&apos;Qbzrr3Nue4wvx4ysjrvfKGVPvC6KpHCh&apos;</defaultValue>
        <label>Brandstore Image Token</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brandstore_Url__c</fullName>
        <defaultValue>&quot;https://download.pgbrandstoreqa2.com&quot;</defaultValue>
        <label>Brandstore Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>DAM Brandstore Settings</label>
</CustomObject>

src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>AddProductLimit__c</fullName>
        <description>Count of product search results shown in the page</description>
        <label>Add Product Limit</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country picklist from Global Picklist to fetch global picklist values</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmailProdUsedLabel__c</fullName>
        <label>Email Product Used Before Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailStillProdLabel__c</fullName>
        <label>Email Still Have Prod Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageField__c</fullName>
        <defaultValue>&apos;Image_Url_Thumb__c&apos;</defaultValue>
        <description>Field name of product image in Local Product object - Only for System Admins</description>
        <label>Product Search Image Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfProdLabel__c</fullName>
        <label>Number of Product Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberProdCount__c</fullName>
        <label>Number of Product Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PiTranslationNo__c</fullName>
        <label>Picklist Translation No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlTranslationYes__c</fullName>
        <label>Picklist Translation Yes</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GCRGenericProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains Generic Properties for GCR widget.</description>
    <fields>
        <fullName>value__c</fullName>
        <description>Field contains values for GCR widget Generic properties</description>
        <label>value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Care Hub Generic Properties</label>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF (
FIND (&quot;/&quot;, Path__c) == 0, Path__c, 

LEFT(Path__c, FIND ( &quot;/&quot;, Path__c)-1)

)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Facing_Name__c</fullName>
        <label>Consumer Facing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>IF (FIND(&quot;/&quot;, Path__c) == 0, &quot;&quot;, 

IF (FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1) == 0, 


RIGHT(Path__c, 
LEN (Path__c)
-
FIND(&quot;/&quot;, Path__c)

)

,


RIGHT(LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1), 
LEN (LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))
-
FIND(&quot;/&quot;, LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))

)



)

)</formula>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <externalId>true</externalId>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Facing_Name__c</fullName>
        <description>Used for ContactUs page.</description>
        <label>Consumer Facing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image_Url_Thumb__c</fullName>
        <description>Front of product thumbnail.</description>
        <inlineHelpText>Front of product thumbnail.</inlineHelpText>
        <label>Image Url Thumb</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Image_Url__c</fullName>
        <label>Image Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/gcr_emailUsPrbController.cls
/*
* @author:       Accenture
* @date:         27/06/2016
* @description:  Controller class for email us report a problem component of gcr widget
* DATE              NAME                CHANGE DESCRIPTION
* 14/12/2016		Accenture			Fetch images for each displayed page in the product list added "gcr_helperClass.getImageUrl()" method call to
* 										searchProducts(), displaySelectedPage(), previous(), next(), firstPage(), lastPage().
* 24/02/2017		Accenture			WR467 - Add field set for dynamic sequence for address fields
*/
public class gcr_emailUsPrbController {
    public GCRChannelContent__c chlContentRec { get; set; }
    public gcr_WidgetHandshake iHandshake { get; set; }
    public Boolean isRightToLeft { get; set; }
    // WR467 FIELD SET LIST TO BE USED
    //public String fieldSetName { public get; private set; }
    
    // PUBLIC VARIABLES FOR THE COMPONENTS
    // VARIABLES FOR gcr_cmpEmailUsProblem COMPONENT
    public String selectedProduct { get; set; }
    public List<SelectOption> lCountry { public get {
        Map<String, String> mCountryPlVal = gcr_helperClass.getAllPicklistValues('GCRChannelContent__c', 'Country__c');
        lCountry = new List<SelectOption>();
		for (String eachVal :mCountryPlVal.keySet()) {
            lCountry.add(new SelectOption(eachVal, mCountryPlVal.get(eachVal)));
        } return lCountry;
    } private set; }

	// SEARCHED PRODUCTS PAGINATION RELATED VARIABLES
    public List<sObject> lProduct { get; set; }
    public String strProdSearch { get; set; }
    public Boolean isMinCharError { get; set; }
    
    private Integer intOffsetVal { get; set; }
    public Integer intCurrentPage { get; set; }
    public Integer intTotalPages { get; private set; }
    public Integer intTotalRecords { get; private set; }
    public List<Integer> lPageNumbers { get; private set; }
    public Boolean isProdLimit { get; private set; }

    public Boolean isSearch { get; set; }
    public Integer selectedProdId  { get; set; }
    public Integer fieldSetCount { get; set; }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	27/06/2016
	 * @description:  	CONSTRUCTOR FOR EMAIL US PROBLEM CONTROLLER
     */
    public gcr_emailUsPrbController() {
        // INITIALIZE VARIABLES ON PAGE LOAD
        intCurrentPage = 1;
        intOffsetVal = 0;
        intTotalPages = 0;
        intTotalRecords = 0;
        isSearch = true;
        isMinCharError = false;
        selectedProdId = 0;
        isProdLimit = false;
        if (lProduct != null && !lProduct.isEmpty()) {
			lProduct.clear();
		}

        fieldSetCount = 0;
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	27/06/2016
	 * @description:  	METHOD TO RETRIEVE SELECT OPTIONS FOR REASON FOR WRITING DROPDOWN
     * @param:			none 
     * @return:			List<SelectOption>
     */
    public void actionSelectProduct() {
        if (iHandshake.lCaseProduct.size() < chlContentRec.AddProductLimit__c) {
            Local_Product__c selectedProd = [ SELECT Id
                                                   , Image_Url_Thumb__c
                                             	   , Image_Url__c
                                                   , Consumer_Facing_Name__c 
                                             	   , Global_Product__r.Segment__c
                                              FROM Local_Product__c 
                                              WHERE Id = :selectedProduct ];
            Case_Product__c newCaseProd = new Case_Product__c();
            newCaseProd.Local_Product__c = selectedProd.Id;
            newCaseProd.Search_Term__c = strProdSearch;
            selectedProd.Image_Url__c = gcr_helperClass.getImageUrl((String) selectedProd.get(chlContentRec.ImageField__c)
                                      							  , DAM_Brandstore_Settings__c.getInstance().Brandstore_Image_Token__c
                                      							  , DAM_Brandstore_Settings__c.getInstance().Brandstore_Url__c);
            CaseProductWrapper newSelectedProd 
                = new CaseProductWrapper(selectedProdId, selectedProd.Consumer_Facing_Name__c, selectedProd.Image_Url__c, newCaseProd);
            newSelectedProd.numberProd = '0';
            newSelectedProd.stillHaveProd = '0';
            newSelectedProd.usedBefore = '0';
            iHandshake.mValidationMap.put('stillHave' + String.valueOf(selectedProdId), false);
            iHandshake.mValidationMap.put('prodUse' + String.valueOf(selectedProdId), false);
            iHandshake.mValidationMap.put('expiryDate' + String.valueOf(selectedProdId), false);
            selectedProdId++;
            iHandshake.lCaseProduct.add(newSelectedProd);
            if (String.isEmpty(iHandshake.newCase.Segment__c)) {
            	iHandshake.newCase.Segment__c = selectedProd.Global_Product__r.Segment__c;
            }
            this.clearSearchResults();
            isProdLimit = false;
        } else {
            this.clearSearchResults();
            isProdLimit = true;
        }
    }
    
    public void actionRemoveProduct() {
        for (Integer itr = 0; itr < iHandshake.lCaseProduct.size(); itr++) {
            CaseProductWrapper eachProdWrapper = iHandshake.lCaseProduct.get(itr);
            if(eachProdWrapper.uniqueId == Integer.valueOf(selectedProduct)) {
                iHandshake.lCaseProduct.remove(itr);
				iHandshake.mValidationMap.remove('stillHave' + String.valueOf(eachProdWrapper.uniqueId));
            	iHandshake.mValidationMap.remove('prodUse' + String.valueOf(eachProdWrapper.uniqueId));
                isProdLimit = isProdLimit ? false : isProdLimit;
                break;
            }
        }
    }
    
    // METHOD TO GET DROPDOWN VALUES FOR NUMBER OF PRODUCTS
    public List<SelectOption> getLNumProdOption() {
        List<SelectOption> retVal = new List<SelectOption>();
        if (String.isNotEmpty(chlContentRec.NumberOfProdLabel__c)) {
        	retVal.add(new SelectOption('0', chlContentRec.NumberOfProdLabel__c, true));
        }
        if (chlContentRec.NumberProdCount__c != null) {
        	Integer intIterator = 1;
            while (intIterator < chlContentRec.NumberProdCount__c) {
                retVal.add(new SelectOption(String.valueOf(intIterator), String.valueOf(intIterator)));
                intIterator++;
            }
        }
        return retVal;
    }
    
    // METHOD TO GET DROPDOWN VALUES FOR NUMBER OF PRODUCTS
    public List<SelectOption> getLStillHaveProd() {
        List<SelectOption> retVal = new List<SelectOption>();
        retVal.add(new SelectOption('0', chlContentRec.EmailStillProdLabel__c, true));
        retVal.add(new SelectOption(chlContentRec.PlTranslationYes__c, chlContentRec.PlTranslationYes__c));
        retVal.add(new SelectOption(chlContentRec.PiTranslationNo__c, chlContentRec.PiTranslationNo__c));
        return retVal;
    }
    
    // METHOD TO GET DROPDOWN VALUES FOR NUMBER OF PRODUCTS
    public List<SelectOption> getLProdUsed() {
        List<SelectOption> retVal = new List<SelectOption>();
        retVal.add(new SelectOption('0', chlContentRec.EmailProdUsedLabel__c, true));
        retVal.add(new SelectOption(chlContentRec.PlTranslationYes__c, chlContentRec.PlTranslationYes__c));
        retVal.add(new SelectOption(chlContentRec.PiTranslationNo__c, chlContentRec.PiTranslationNo__c));
        return retVal;
    }

    // TODO: GENERATE (DYNAMIC) QUERY FROM HELPER CLASS
    public void searchProducts() {
        //CDOY WR467 - search langth changed to greater than 1
        if (String.isNotEmpty(strProdSearch) && strProdSearch.length() > 1) {
            isMinCharError = false;
            // RESET CURRENT PAGE AND OFFSET VALUE ON SEARCH
            intCurrentPage = 1;
            intOffsetVal = 0;
            intTotalRecords = 0;
            isSearch = true;
            // GET PAGE SIZE OF PRODUCT SEARCH FROM CONFIGURATION
            Integer intPageSize = GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE') != null ?
                Integer.valueOf(GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE').value__c) : 5;
            // GET TOTAL RECORDS RETURNED ON SEARCH
            // IF SEARCH STRING IS TEXT SEARCH ALL PRODUCTS ELSE SEARCH PRODUCT GTIN
            List<sObject> lTotalProduct = new List<sObject>();
            try {
                lTotalProduct = gcr_helperClass.getProducts(strProdSearch, chlContentRec.CareHub__r.Country__c, chlContentRec.CareHub__r.Brand__c, chlContentRec.ImageField__c, null, null);
            } catch (Exception caughtException) {
                SYSTEM.DEBUG('CAUGHT EXCEPTION: ' + caughtException.getMessage());
            }
        
            // GET COUNT OF TOTAL RETURNED RECORDS MAXIMIZED TO 2000
            intTotalRecords = lTotalProduct.size();
            lTotalProduct.clear();
            intTotalPages = Math.mod(intTotalRecords, intPageSize) > 0 ? (intTotalRecords/intPageSize) + 1 : intTotalRecords/intPageSize;
            
            try {
            	lProduct = gcr_helperClass.getProducts(strProdSearch, chlContentRec.CareHub__r.Country__c, chlContentRec.CareHub__r.Brand__c, chlContentRec.ImageField__c, intPageSize, intOffsetVal);
                // RETRIEVE IMAGE URLS
                gcr_helperClass.getImageUrl(lProduct, chlContentRec.ImageField__c);
            } catch (Exception caughtException) {
                SYSTEM.DEBUG('CAUGHT EXCEPTION: ' + caughtException.getMessage());
            }
            lPageNumbers = new List<Integer>();
            Integer itr = 1;
            Integer lastPage = intTotalPages < 3 ? intTotalPages : 3;
            // TODO: REMOVE HARDCODING GET THIS SIZE FROM CUSTOM SETTINGS
            while (itr <= lastPage) {
                lPageNumbers.add(itr);
                itr++;
            }
            iHandshake.newCase.Unable_To_Find_Product__c = strProdSearch;
        } else {
            isMinCharError = true;
        }
    }
    
    public void displaySelectedPage() {
		Integer intPageSize = GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE') != null ?
            Integer.valueOf(GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE').value__c) : 5;
        intOffsetVal = (intPageSize * intCurrentPage) - intPageSize;
        lProduct = gcr_helperClass.getProducts(strProdSearch, chlContentRec.CareHub__r.Country__c, chlContentRec.CareHub__r.Brand__c, chlContentRec.ImageField__c, intPageSize, intOffsetVal);
        // RETRIEVE IMAGE URLS
        gcr_helperClass.getImageUrl(lProduct, chlContentRec.ImageField__c);
        lPageNumbers.clear();
		// TODO: HERE "3" SHOULD REPLACE WITH TOTAL VISIBLE PAGES FROM CONFIGURATION
        Integer itr;
        Integer lastPage;
        if (intTotalPages > 3) {
            if (intCurrentPage + 1 > intTotalPages) {
                itr = intTotalPages - 2;
                lastPage = intTotalPages;
            } else {
                if (intCurrentPage - 1 > 0) {
                	itr = intCurrentPage - 1;
                    lastPage = intCurrentPage + 1;
                } else {
                    itr = 1;
                    lastPage = 3;
                }
            }
        } else {
            itr = 1;
            lastPage = intTotalPages;
        }
        while (itr <= lastPage) {
            lPageNumbers.add(itr);
            itr++;
        }
    }
    
    public void previous() {
        Integer intPageSize = GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE') != null ?
            Integer.valueOf(GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE').value__c) : 5;
        intOffsetVal = intOffsetVal - intPageSize;
		intCurrentPage--;
        lProduct = gcr_helperClass.getProducts(strProdSearch, chlContentRec.CareHub__r.Country__c, chlContentRec.CareHub__r.Brand__c, chlContentRec.ImageField__c, intPageSize, intOffsetVal);
        // RETRIEVE IMAGE URLS
        gcr_helperClass.getImageUrl(lProduct, chlContentRec.ImageField__c);
        if (intTotalPages > 3) {
        	Integer intFirstPage = lPageNumbers.get(0);
            if (intCurrentPage - intFirstPage < 1 && intFirstPage > 1) {
                lPageNumbers.add(0, intFirstPage - 1);
                lPageNumbers.remove(lPageNumbers.size() - 1);
            }
        }
    }
    
    public void next() {
        Integer intPageSize = GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE') != null ?
            Integer.valueOf(GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE').value__c) : 5;
        intOffsetVal = intOffsetVal + intPageSize;
        intCurrentPage++;
        lProduct = gcr_helperClass.getProducts(strProdSearch, chlContentRec.CareHub__r.Country__c, chlContentRec.CareHub__r.Brand__c, chlContentRec.ImageField__c, intPageSize, intOffsetVal);
        // RETRIEVE IMAGE URLS
        gcr_helperClass.getImageUrl(lProduct, chlContentRec.ImageField__c);
        if (intTotalPages > 3) {
        	Integer intLastPage = lPageNumbers.get(lPageNumbers.size() - 1);
            if (intLastPage - intCurrentPage < 1 && intLastPage < intTotalPages) {
                lPageNumbers.add(intLastPage + 1);
                lPageNumbers.remove(0);
            }
        }
    }
    
    public void firstPage() {
        Integer intPageSize = GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE') != null ?
            Integer.valueOf(GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE').value__c) : 5;
        intOffsetVal = 0;
        intCurrentPage = 1;
		lProduct = gcr_helperClass.getProducts(strProdSearch, chlContentRec.CareHub__r.Country__c, chlContentRec.CareHub__r.Brand__c, chlContentRec.ImageField__c, intPageSize, intOffsetVal);
        // RETRIEVE IMAGE URLS
        gcr_helperClass.getImageUrl(lProduct, chlContentRec.ImageField__c);
        lPageNumbers.clear();
		Integer itr = 1;
        Integer lastPage = intTotalPages < 3 ? intTotalPages : 3;
		while (itr <= lastPage) {
			lPageNumbers.add(itr);
			itr++;
		}
    }
    
    public void lastPage() {
        Integer intPageSize = GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE') != null ?
            Integer.valueOf(GCRGenericProperties__c.getInstance('EMAILUS_PRODUCT_SEARCH_PAGESIZE').value__c) : 5;
        intOffsetVal = (intTotalPages - 1) * intPageSize;
        intCurrentPage = intTotalPages;
		lProduct = gcr_helperClass.getProducts(strProdSearch, chlContentRec.CareHub__r.Country__c, chlContentRec.CareHub__r.Brand__c, chlContentRec.ImageField__c, intPageSize, intOffsetVal);
        // RETRIEVE IMAGE URLS
        gcr_helperClass.getImageUrl(lProduct, chlContentRec.ImageField__c);
        lPageNumbers.clear();
		Integer itr = intTotalPages > 3 ? intTotalPages - 2 : 1;
		while (itr <= intTotalPages) {
			lPageNumbers.add(itr);
			itr++;
		}
    }
    
    private void clearSearchResults() {
        isSearch = false;
		lProduct.clear();
        intCurrentPage = 1;
        intOffsetVal = 0;
        intTotalPages = 0;
    }

    public void isActionMethod() {
        isSearch = false;
        if (lProduct != null && !lProduct.isEmpty()) lProduct.clear();
        intCurrentPage = 1;
        intOffsetVal = 0;
        intTotalPages = 0;
        if (iHandshake.lCaseProduct != null && !iHandshake.lCaseProduct.isEmpty()) iHandshake.lCaseProduct.clear();
    }
    
    public void changeCountry() {
        Country_Status__c countryStatus = Country_Status__c.getInstance(chlContentRec.Country__c);
        if (countryStatus != null) {
        	iHandshake.isStateMandatory = countryStatus.Uses_States__c ? true : false;
            iHandshake.isZipMandatory = countryStatus.Uses_Postal_Codes__c ? true : false;
        } else {
            iHandshake.isStateMandatory = true;
            iHandshake.isZipMandatory = true;
        }
    }

    public class CaseProductWrapper {
        public Integer uniqueId { public get; private set; }
        public String productName { public get; private set; }
        public String imageUrl { public get; private set; }
        public Case_Product__c caseProduct { public get; private set; }
        
        public String numberProd { public get; public set; }
        public String stillHaveProd { public get; public set; }
        public String usedBefore { public get; public set; }
        public String expiryDate { public get; public set; }
        public String productionCode { public get; public set; }
        
        public caseProductWrapper(Integer uniqueId, String productName, String imageUrl, Case_Product__c caseProduct) {
            this.uniqueId = uniqueId;
            this.productName = productName;
            if (String.isNotEmpty(imageUrl)) {
            	this.imageUrl = imageUrl;
            }
            this.caseProduct = caseProduct;
        }
    }
}