src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Return_Status__c</fullName>
        <description>Hidden field used by workflows to manage sending of reminders for product returns</description>
        <label>Product Return Reminder Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACR_Return_Type__c</fullName>
        <description>Return types supported by matching ACR:
Digital = Digital + Physical 
Physical = Physical only</description>
        <inlineHelpText>Return types supported by matching ACR:
•Digital = Digital + Physical 
•Physical = Physical only</inlineHelpText>
        <label>ACR Return Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACR_Return_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Digital_Return_Id__c</fullName>
        <description>Unique Id generated for digital return form, set by code</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Id generated for digital return form, set by code</inlineHelpText>
        <label>Digital Return Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Digital_Returns_Link__c</fullName>
        <formula>$Setup.Global_Org_Settings__c.Base_Site_URL__c+&quot;ContactUs/siteDPRUploadForm?uid=&quot;+ Digital_Return_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Digital Returns Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Consumer_Facing_Name__c</fullName>
        <description>Used for ContactUs page.</description>
        <label>Consumer Facing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/dprLinks_ext.cls
public class dprLinks_ext {
    private Set <String> validCaseOrigins = new Set<String>{'Chat','Social Media'};
	public case currentCase {get;set;}//The Current Case
    public list<Case_Product__c> cps {
        get{
            if(cps==null){
                cps = new List<Case_Product__c>();
                cps = [SELECT Id, ACR_Info__c, ACR_Return_Type__c, 	Digital_Return_Id__c, Digital_Returns_Link__c, Case__r.Product_Return_Status__c, Local_Product__r.Consumer_Facing_Name__c
                       	FROM Case_Product__c
                      	WHERE Case__c = :currentCase.Id AND Digital_Return_Id__c != null AND Case__r.Origin IN :validCaseOrigins];
                        //WHERE Case__c = :currentCase.Id AND Digital_Return_Id__c != null AND Case__r.Origin != 'Phone'];
            }
            return cps;
        }
		set;
	}

    public dprLinks_ext(ApexPages.StandardController stdctr){
        currentCase = (case)stdctr.getRecord(); 
        currentCase = [SELECT Id, Origin, CaseNumber FROM Case WHERE Id = :currentCase.Id];
    }
}