src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CCM_Initial_Pull__c</fullName>
        <label>CCM Initial Pull</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Case_Products__c</fullName>
        <label>Case Products</label>
        <summaryForeignKey>Case_Product__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Deletable__c</fullName>
        <formula>OR( 
   ISBLANK(Case__r.CCM_Initial_Pull__c), 
   AND(
      NOT(ISBLANK(Case__r.CCM_Initial_Pull__c)),
      NOT(Local_Comment_Code__r.GCC_Level_1__c = &apos;Product Quality Complaint&apos;), 
      NOT(Local_Comment_Code__r.GCC_Level_1__c = &apos;Adverse Event&apos;)
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Deletable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_CaseProductHelper.cls
public with sharing class sf_CaseProductHelper {
    
    /**
    * @author: Chris Southworth
    * @date: 05/08/2014
    * @param: oldProductMap: Map of Case_Products__c before update or delete
    * @param: newProductMap: Map of updated Case_Products after update, NULL if part of delete trigger
    * @description: Prevent all users except System Admin from modifying/deleting Case_Products__c once 
    *   the Status__c has been changed to 'Received'
    */
	public static void preventModifyAndDeleteCaseProduct(Map<Id, Case_Product__c> oldProductMap, Map<Id, Case_Product__c> newProductMap){
	/* Note the below can be called by the Automated Process user via MAC/ACR, which has no profile
	 * This is why the boolean/try-catch is used */
		boolean canEdit = true;
		try{
			String profileName = [SELECT Id, Name FROM Profile WHERE Id =:UserInfo.getProfileId()].Name;
			if(profileName != 'System Administor'){
				canEdit = false;
			}            
		}
		catch(queryException e){
			system.debug('>>> error on querying current user profile: '+e);
		}
        
        if(!canEdit){
            String error = Label.CaseProduct_PreventModifyOrDelete;
            for(Case_Product__c cp : oldProductMap.values()){
                if(cp.Status__c == 'Received'){
                    if(newProductMap != NULL){
                        newProductMap.get(cp.Id).addError(error);
                    }
                    else{
                        cp.addError(error);
                    }                   
                }
            }
        }
	}
    
   /**
    * @author: Chris Southworth
    * @date: 09/23/2014
    * @param: cpMap: Map of updated Case_Products before delete
    * @description: prevent all users from deleting Case Products after the case has been submitted when the
    *   case comment code is of type AE or PQC.
    *   Users can use the Product/Comment tab in the console to 'soft' delete the case products.
    */
    public static void preventDeleteSubmittedCaseProducts(Map<Id, Case_Product__c> cpMap){
        Set<Id> submittedCpSet = new Set<Id>();
        Set<Id> caseIds = new Set<Id>();
        for(Case_Product__c cp : cpMap.values()){
            caseIds.add(cp.Case__c);
        }
        
        Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id, CCM_Initial_Pull__c FROM Case WHERE Id IN :caseIds AND CCM_Initial_Pull__c != null]);
        if(caseMap.size() > 0){
            for(Case_Product__c cp : cpMap.values()){
                if(caseMap.containsKey(cp.Case__c)){
                    submittedCpSet.add(cp.Id);
                }
            }
            //System.debug('**Case Product Ids: ' + submittedCpSet);
            if(submittedCpSet.size() > 0){
                List<Case_Comment_Code__c> cccList = [SELECT Id, Case_Product__c, Is_Deletable__c FROM Case_Comment_Code__c 
                                                    WHERE Case_Product__c IN :submittedCpSet AND Is_Deletable__c = false];
                                                    
                if(cccList.size() > 0){
                    Set<Id> cpIds = new Set<Id>();
                    for(Case_Comment_Code__c ccc : cccList){
                        cpIds.add(ccc.Case_Product__c);
                    }
                    if(cpIds.size() > 0){
                        for(Case_Product__c cp : cpMap.values()){
                            if(cpIds.contains(cp.Id)){
                                 cpMap.get(cp.Id).addError(Label.CaseProduct_PreventDeleteForCCCAEorPQC);
                            }
                        }
                    }
                }
            }
        }
    }
}