src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Medical_QR_Status__c</fullName>
        <description>The status the Medical Questionnaire Request is in.</description>
        <inlineHelpText>The status the Medical Questionnaire Request is in.</inlineHelpText>
        <label>Medical QR Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Received</fullName>
                </value>
                <value>
                    <fullName>Unwilling to Complete</fullName>
                </value>
                <value>
                    <fullName>Sent by consumer but not received</fullName>
                </value>
                <value>
                    <fullName>Unable to Re-contact Consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Safety_Assessment_Survey__c.object
<CustomObject>
    <description>Holds the questions(fields) and responses(field values) for all Adverse Event surveys.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>This is the Case that generated this AE Survey</description>
        <inlineHelpText>Please pick the case to which this survey relates to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>AE_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Medical_QR_Status__c</fullName>
        <description>The status the Medical Questionnaire Request is in.</description>
        <inlineHelpText>The status the Medical Questionnaire Request is in.</inlineHelpText>
        <label>Medical QR Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Questionnaire Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Questionnaire Received</fullName>
                </value>
                <value>
                    <fullName>Unwilling to Complete</fullName>
                </value>
                <value>
                    <fullName>Sent by consumer but not received</fullName>
                </value>
                <value>
                    <fullName>Unable to Re-contact Consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Owned by GSSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Safety Assessment Survey</label>
    <nameField>
        <displayFormat>SAS-{0000000}</displayFormat>
        <label>Safety Assessment Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Safety Assessment Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SafetyAssessmentSurveyHelperTest.cls
/**

Test class for SafetyAssessmentSurveyHelper.cls
@author     Ian Barker
@date       11/10/2015

*/
@isTest
private class SafetyAssessmentSurveyHelperTest {

    @isTest
    public static void updateCasefromSAS(){
    	Case c = new Case();
    	c.Subject = 'updateCasefromSAS';
    	c.status = 'open';
    	//c.Medical_QR_Status__c = 'Questionnaire Requested - Attempt 1';
    	insert c;
    	system.assertEquals('open', c.status);
    	//system.assertEquals('Questionnaire Requested - Attempt 1', c.Medical_QR_Status__c);

    	Safety_Assessment_Survey__c sas = new Safety_Assessment_Survey__c();
    	sas.Case__r = c;
    	sas.Case__c = c.id;
    	sas.Status__c = 'Active';

    	//Safety_Assessment_Survey__c sas = [select Status__c, Medical_QR_Status__c, Case__r.Medical_QR_Status__c from Safety_Assessment_Survey__c where Id = :presas.Id];
    	insert sas;

    	//system.assertEquals(null, sas.Medical_QR_Status__c);

    	sas.Medical_QR_Status__c = 'Questionnaire Requested - Attempt 2';

    	system.assertEquals('Questionnaire Requested - Attempt 2', sas.Medical_QR_Status__c);

    	Test.startTest();
    	update sas;
    	system.debug('@@@Case Status ' + sas.case__r.status);
    	Test.stopTest();

    	system.assertEquals('Questionnaire Requested - Attempt 2', sas.Medical_QR_Status__c);

    	List <Case> caseResults = [SELECT Id, Medical_QR_Status__c, Subject FROM Case WHERE Subject = 'updateCasefromSAS'];

    	system.assertEquals('updateCasefromSAS', caseResults[0].Subject);
    	system.assertEquals(1, caseResults.size());
    	system.assertEquals('Questionnaire Requested - Attempt 2', caseResults[0].Medical_QR_Status__c);
    }

        @isTest
    public static void notupdateCasefromSAS(){
        Case c = new Case();
        c.Subject = 'notupdateCasefromSAS';
        c.status = 'open';
        c.Medical_QR_Status__c = 'Questionnaire Requested - Attempt 2';
        insert c;
        system.assertEquals('open', c.status);
        system.assertEquals('Questionnaire Requested - Attempt 2', c.Medical_QR_Status__c);

        Safety_Assessment_Survey__c sas = new Safety_Assessment_Survey__c();
        sas.Case__c = c.id;
        sas.Status__c = 'Active';
        insert sas;

        //check 

        sas.Medical_QR_Status__c = 'Questionnaire Requested - Attempt 1';

        Test.startTest();
        update sas;
        Test.stopTest();

        List <Case> caseResults = [SELECT Id, Medical_QR_Status__c, Subject FROM Case WHERE Subject = 'notupdateCasefromSAS'];

        system.assertEquals('notupdateCasefromSAS', caseResults[0].Subject);
        system.assertEquals(1, caseResults.size());
        system.assertEquals('Questionnaire Requested - Attempt 2', caseResults[0].Medical_QR_Status__c);
    }

}