src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is going to be the First Level Identifying the Type of Comment</description>
        <label>Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Complaints Other</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Product Quality Complaint</fullName>
                </value>
                <value>
                    <fullName>Testimonial</fullName>
                </value>
                <value>
                    <fullName>Unable to Classify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is the first level indicating the type of the comment code</description>
        <externalId>true</externalId>
        <label>Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QueueRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the Relation between Queues and Recordtypes. Replica of Email Service Configuration</description>
    <fields>
        <fullName>Case_Record_Type_Id__c</fullName>
        <label>Case Record Type Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>QueueRecordType</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_Monetary_Threshold__c</fullName>
        <label>EUR Monetary Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP_Monetary_Threshold__c</fullName>
        <label>GBP Monetary Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>USD_Monetary_Threshold__c</fullName>
        <label>USD Monetary Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/sf_CaseHelperTest_Part2.cls
@isTest
private class sf_CaseHelperTest_Part2 {
    Static Final String COUNTRY = 'New Zealand';
    
    @testSetup static void setupData(){
        //Create User to avoid mixed DML
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User adminTestUser = new User(
            Lastname = 'Admin',
            Alias = 'UTAdmin',
            Email = 'UTAdmin@pgTEST.com',
            Username = String.valueOF(math.random())+'@pgTEST.com',
            CommunityNickname = 'atu',
            ProfileId=p.Id,
            TimeZoneSidKey='America/New_York',
            LocaleSidKey='en_US',
            EmailEncodingKey='ISO-8859-1',
            LanguageLocaleKey='en_US',
            USD_Monetary_Threshold__c = 50,
            GBP_Monetary_Threshold__c = 50,
            EUR_Monetary_Threshold__c = 50,
            IsActive = True
        );
        Insert adminTestUser;
        
        system.runAs(adminTestUser){
            //Get Case RTs
            List<RecordType> caseRTs = [SELECT Id FROM RecordType WHERE SObjectType = 'Case'];
    
            //Create Group
            List<Group> groupsToInsert = new List<Group>();
            Group qGroup1 = new Group();
            qGroup1.Name = 'HasCountryValue';
            qGroup1.Type = 'Queue';
            groupsToInsert.add(qGroup1);
            
            Group qGroup2 = new Group();
            qGroup2.Name = 'CountryValueIsAll';
            qGroup2.Type = 'Queue';
            groupsToInsert.add(qGroup2);            

            Insert groupsToInsert;
            
            //Create Queue
            List<QueueSObject> qs = new List<QueueSObject>();
            QueueSObject q1 = New QueueSobject(
                sObjectType = 'Case',
                QueueId = qGroup1.Id
            );
            qs.add(q1);
            
			QueueSObject q2 = New QueueSobject(
                sObjectType = 'Case',
                QueueId = qGroup2.Id
            );
            qs.add(q2);
            
            insert qs;
            
            //Create QueueRecordType__c
            List<QueueRecordType__c> qrts = new List<QueueRecordType__c>();
            QueueRecordType__c qrt = new QueueRecordType__c(
                Name = qGroup1.Id,
                Country__c = COUNTRY,
                Case_Record_Type_Id__c = caseRTs[0].Id
            );
            qrts.add(qrt);
            
			QueueRecordType__c qrtAll = new QueueRecordType__c(
                Name = qGroup2.Id,
                Country__c = 'All',
                Case_Record_Type_Id__c = caseRTs[3].Id
            );
            qrts.add(qrtAll);

            insert qrts;
            
            Case testCase = new Case(
                Status = 'Open',
                Country__c = 'United States of America',
                RecordTypeId = caseRTs[1].Id
        	);
        	insert testCase;
        }
    }
    
    @isTest static void setCaseRecordTypeTest(){

        Case testCase = [SELECT Country__c, RecordTypeId FROM Case ORDER BY CaseNumber DESC LIMIT 1];

        system.assertNotEquals(COUNTRY, testCase.Country__c);
        
        Id oldRecordTypeId = [SELECT RecordTypeId FROM Case WHERE Id = :testCase.Id].RecordTypeId;
        
        Id assignToAllQueueId = [SELECT QueueId FROM QueueSObject WHERE queue.Name = 'CountryValueIsAll' LIMIT 1].QueueId;
        Id assignToCountryQueueId = [SELECT QueueId FROM QueueSObject WHERE queue.Name = 'HasCountryValue' LIMIT 1].QueueId;

        test.startTest();
        //Country = 'All' test. Country and Language should not be updated
        testCase.OwnerId = assignToAllQueueId;
        update testCase;
        
        testCase = [SELECT Country__c, RecordTypeId FROM Case WHERE Id = :testCase.Id];
        
       	system.assertNotEquals(testCase.RecordTypeId, oldRecordTypeId);//RecordTypeId should have been changed
        system.assertEquals(null, testCase.Country__c);//Country value should have been cleared
        
        
        //Country has specific value, Country should be updated
        testCase.OwnerId = assignToCountryQueueId;
        update testCase;
        
        testCase = [SELECT Country__c, RecordTypeId FROM Case WHERE Id = :testCase.Id];
        
        system.assertNotEquals(testCase.RecordTypeId, oldRecordTypeId);//RecordTypeId should have been changed
        system.assertEquals(COUNTRY, testCase.Country__c);//Country should be set to match the QueueRecordType__c
        
        test.stopTest();
    }
    
    @isTest static void updateCPBasedonCaseTest(){
        //Setup data
		Case c = [SELECT Id FROM Case LIMIT 1];
    
		Global_Product__c gp = new Global_Product__c();
		insert gp;
		
        Local_Product__c lp = new Local_Product__c();
		lp.Name = 'Test Product';
		lp.Country__c = 'United States of America';
		lp.Translated_Path__c = 'Test Path';
		lp.Global_Product__c = gp.Id;
		insert lp;
    
		Global_Comment_Code__c gcc = new Global_Comment_Code__c ();
		gcc.Level_1__c = 'Adverse Event';
		insert gcc;
    
		Local_Comment_Code__c lcc = new Local_Comment_Code__c ();
		lcc.Global_Comment_Code__c = gcc.Id;
		insert lcc;
    
		Case_Product__c cp = new Case_Product__c();
		cp.Local_Product__c = lp.Id;
		cp.Case__c = c.Id;
        cp.Status__c = 'Product Requested - Attempt 1';
		insert cp;
    
		Case_Comment_Code__c ccc = new Case_Comment_Code__c();
		ccc.Local_Comment_Code__c = lcc.Id;
		ccc.Case__c = c.Id;
		ccc.Case_Product__c = cp.Id;
		insert ccc;
        
        //Confirm both fields are setup as expected
        cp = [SELECT Id, Status__c, Case__r.Product_Return_Status__c FROM Case_Product__c WHERE Id = :cp.Id];
        system.assertEquals('Product Requested - Attempt 1', cp.Case__r.Product_Return_Status__c);
        system.assertEquals('Product Requested - Attempt 1', cp.Status__c);
        
        test.startTest();
        	//Change case status to a non cp update value
        	c.Product_Return_Status__c = 'Product Requested - Attempt 2';
        	update c;
        
			cp = [SELECT Id, Status__c, Case__r.Product_Return_Status__c FROM Case_Product__c WHERE Id = :cp.Id];
        	system.assertEquals('Product Requested - Attempt 2', cp.Case__r.Product_Return_Status__c);
       	 	system.assertEquals('Product Requested - Attempt 1', cp.Status__c); //CP is not updated
        
        	//Change case status to a cp update value
            c.Product_Return_Status__c = 'Product Received';
        	update c;
        
        	cp = [SELECT Id, Status__c, Case__r.Product_Return_Status__c FROM Case_Product__c WHERE Id = :cp.Id];
        	system.assertEquals('Product Received', cp.Case__r.Product_Return_Status__c);
       	 	system.assertEquals('Product Received', cp.Status__c); //CP is updated

        test.stopTest();
    }

}