src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Product_Return_Status__c</fullName>
        <description>Hidden field used by workflows to manage sending of reminders for product returns</description>
        <label>Product Return Reminder Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_Return_Type__c</fullName>
        <description>Return type for Case - cannot be a mixture of physical/digital</description>
        <inlineHelpText>Return type for Case - cannot be a mixture of physical/digital</inlineHelpText>
        <label>Selected Return Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Contact_Id__c</fullName>
        <formula>Case__r.ContactId</formula>
        <label>Case Contact Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GCR_CID__c</fullName>
        <formula>Local_Comment_Code__r.Global_Comment_Code__r.GCR_CID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GCR CID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Comment_Path__c</fullName>
        <formula>Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c</formula>
        <label>Global Comment Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product_Path__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Path__c</formula>
        <label>Global Product Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product_Segment__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Segment__c</formula>
        <label>Global Product Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Brand__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Postal_Restriction__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Global_Product__r.Postal_Restriction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Postal Restriction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Global_Product_Path__c</fullName>
        <formula>Local_Product__r.Global_Product__r.Path__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Global Product Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Path__c</fullName>
        <formula>Local_Product__r.Translated_Path__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_available_for_return__c</fullName>
        <label>Product available for return</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes - Product is available</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>No - Product cannot be returned</fullName>
                </value>
                <value>
                    <fullName>Unknown - Written communication</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Repeater_Status__c</fullName>
        <label>Repeater Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Suspected Repeater</fullName>
                </value>
                <value>
                    <fullName>Known Repeater</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/d2p_consoleComp_ext.cls
public class d2p_consoleComp_ext {

    public case currentCase {get;set;}//The Current Case
    public List<cpWrapper> cpList {get;set;}//The ACR matching CPs to display
    public String caseId {get; set;}

    public d2p_consoleComp_ext(ApexPages.StandardController stdctr){
        currentCase = (case)stdctr.getRecord(); //for use with button on Case layout 
    }
    
	/*
	* @description: A method that grabs the case fields based on the caseId sent from the VF page as part of an action function
	* @return: PageReference is returned NULL to stay on page
	*/
    public PageReference setCaseId(){
        system.debug('>>> setCaseId : '+caseId);
    	if(caseId != null && !String.isBlank(caseId)){
    		currentCase = [SELECT Id, CaseNumber, Product_Return_Status__c, ContactId FROM Case WHERE Id =:caseId];
    	}
    	return null;
    }
    
    //Method to find/build ACR matching Case Products to display
    public List<cpWrapper> getACRCaseProducts(){
		cpList = new List<cpWrapper>();
        system.debug('>>> in getACRCaseProducts : '+currentCase);
		for(Case_Product__c cp : [SELECT Id, Name, ACR_Info__c, Status__c, Product_Path__c FROM Case_Product__c WHERE Case__c = :currentCase.Id AND ACR_Info__c != null]){
			if(trg_AutoComRuleHelper.digitalProductReturnStatuses.contains(cp.Status__c) || trg_AutoComRuleHelper.physicalProductReturnStatuses.contains(cp.Status__c)){
				cpWrapper cpw = new cpWrapper(cp, True, True);
				cpList.add(cpw);
			}
			else{
				cpWrapper cpw = new cpWrapper(cp, false, false);
				cpList.add(cpw);
			}
		}

        return cpList;
    }
    
    //Swap selected from Digital to Physical OR start Physical
    public void processSelected(){
        //send to ACR to action
        //Should only send Case Comment Codes associatated to selected CPs
        Set<Id> cpIds = new Set<Id>();
        for(cpWrapper cpw : cpList){
            if(cpw.selected){
                system.debug('!!! selected CP: '+cpw);
                cpIds.add(cpw.caseProduct.Id);
                //Clear current status
                cpw.caseProduct.status__c = '';
                
            }
        }
        if(cpIds.isEmpty()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, System.Label.No_Product_s_Selected));
        }
        else{
            Map<Id, Case_Comment_Code__c> cccMap = new Map<Id,Case_Comment_Code__c>([SELECT Status__c, GCR_CID__c, Case_Contact_Id__c, Case__c, Case_Product__r.Product_available_for_return__c,
                                                                                     Case_Product__c, Global_Product_Segment__c, Product_Postal_Restriction__c, Global_Comment_Path__c, Global_Product_Path__c,
                                                                                     Product_Brand__c, Local_Comment_Code__r.Global_Comment_Code__r.Full_Comment_Path__c, Case_Product__r.ACR_Info__c
                                                                                     FROM Case_Comment_Code__C
                                                                                     WHERE Case__c = :currentCase.Id AND Case_Product__c IN :cpIds]);
            Map<Id, Case> caseMap = new Map<Id, Case>();
            
            currentCase.Product_Return_Status__c = '';
            currentCase.Selected_Return_Type__c = 'Physical';
            caseMap.put(currentCase.Id, currentCase);
            Map<Id, Contact> conMap = new Map<Id,Contact>([SELECT Id, Email, FirstName, LastName, Salutation, Repeater_Status__c FROM Contact WHERE Id = :currentCase.ContactId]);

            
            try{
                checkRecursive.ACREnabled = false;//prevent ACR firing on Case edit
                trg_AutoComRuleHelper.dprToPhysical(cccMap, caseMap, conMap);
                checkRecursive.ACREnabled = true;
            }
            catch(exception e){
                System.enqueueJob(new exceptionHelperQueable(e,'Error on converting Digital to Physical. CCCMap: '+String.ValueOf(cccMap)+' *CaseMap: '+String.ValueOf(caseMap)+' *ConMap: '+String.valueOf(conMap)));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Something went wrong - details: '+e.getMessage()+' : '+e.getStackTraceString()));
            }            
        }
    }
    
    //Wrapper for Case checklist and to provide selected CPs to process
    public class cpWrapper{
        public Case_Product__c caseProduct {get;set;}
        public Boolean selected {get;set;}//Selected by advisor
        public Boolean inprogress {get;set;}//Is in an in progress return process
        
        public cpWrapper(Case_Product__c cp, Boolean selectedCP, Boolean cpInProgress){
            caseProduct = cp;
            selected = selectedCP;
            inprogress = cpInProgress;
        }
    }
}