src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Metadata_Priority__c.object
<CustomObject>
    <description>US669
Admin can set up keywords to look for and the priority to set on the case with those keywords
When case is created with a keyword the priority is set appropriately
Cases without the keywords are set to Priority 5</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keywords__c</fullName>
        <label>Keywords</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Metadata Priority</label>
    <nameField>
        <displayFormat>MP-{0000}</displayFormat>
        <label>Metadata Priority Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Priority</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseUtilityTest.cls
/**
* @author: Salesforce.com
* @date: 10/21/2014
* @description: 
*	Test class for CaseUtility
* @changes:
* 21-10-2015
* Removing meta site/auto response functionality
* as converting to standard auto response rules
* christopher.macduff@accenture.com
*/

@isTest
private class CaseUtilityTest {
    
	static testMethod void makeMeCaseOwnerTest(){
		Case ca = new Case (
            Status = 'New',
            Origin = 'Email'
        );
    	insert ca;
        test.startTest();
        CaseUtility.makeMeCaseOwner(ca.Id);        
        test.stopTest();
    }
    
    static testmethod void getAttachmentTest(){
		Case ca = new Case ();
    	ca.Status = 'New';
    	insert ca;
        
        test.startTest();
        CaseUtility util = new CaseUtility ();
        Blob b = Blob.valueOf('some content here for attachment');
		Attachment att = new Attachment(
		ParentId = ca.Id,
		Body = b,
        Name = 'Attachment name',
        Description = 'Attachment description'
        );
        
        util.insertAttachment(att);
        
        test.stopTest();
    }

	static testmethod void getPriorityTest() {

		Test.startTest();
		CaseUtility util = new CaseUtility ();
		System.assertEquals ( '5', util.getPriority('test', 'us'));

		Metadata_priority__c mp = new Metadata_priority__c ();
		mp.Country__c = 'US';
		mp.Keywords__c = 'test';
		mp.Priority__c = '1';

		insert mp;

		System.assertEquals ( '1', util.getPriority('test', 'us'));
		Test.stopTest();
	}

	static testmethod void getContactByLastNameTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();
    	util.getContactByFNameLNameEmail('test', 'test', 'test');

		Test.stopTest();
	}

	static testmethod void updateContactTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();
    	
    	//should throw exception
    	try {
    		util.updateContact(null, null, null, null,null,null, null,null,null, null,null,null);
    	} catch (Exception e){
    		System.assert(true);
    	}

    	//create a contact 
    	Contact c = new Contact ();
    	c.LastName = 'test';

    	insert c;

    	util.updateContact(c.Id, 'test', null, null,'test','test', 'test','test',null, null,false,null);
    	util.updateContact(c);
		Test.stopTest();
	}

	static testmethod void attachFileToCaseTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();
    	
    	//should throw exception
    	try {
    		util.attachFileToCase(null);
    	} catch (Exception e){
    		System.assert(true);
    	}

		Test.stopTest();
	}

	static testmethod void isContactNeededTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();
    	
    	util.isContactNeeded('test');
		Test.stopTest();
	}

    /*christopher.macduff@accenture.com - no longer required
	static testmethod void sendEmailToCustomerTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();

    	Case ca = new Case ();
    	ca.Status = 'New';
    	insert ca;

    	//create a contact 
    	Contact c = new Contact ();
    	c.LastName = 'test';

    	insert c;

    	try {
    		util.sendEmailToCustomer(c.Id, ca.Id, null, 'test@test.com', 'test@test.com', 'test@test.com', 'test@test.com');
    	} catch (Exception e){
    		System.assert(true);
    	}
    
		Test.stopTest();
	}

	static testmethod void sendEmailToThirdPartyTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();

    	try {
    		util.sendEmailToThirdParty(null, null, 'test@test.com', null, null, null, null);
    	} catch (Exception e){
    		System.assert(true);
    	}

    	Case ca = new Case ();
    	ca.Status = 'New';
    	insert ca;

    	//create a contact 
    	Contact c = new Contact ();
    	c.LastName = 'test';

    	insert c;

    	try {
    		util.sendEmailToThirdParty(c.Id, ca, 'test@test.com', 'test@test.com', 'test@test.com', 'test@test.com', 'test@test.com');
    	} catch (Exception e){
    		System.assert(true);
    	}

		Test.stopTest();
	}*/

	static testmethod void createTaskTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();

    	Case ca = new Case ();
    	ca.Status = 'New';
    	insert ca;

    	//create a contact 
    	Contact c = new Contact ();
    	c.LastName = 'test';

    	insert c;

    	try {
    		util.createTask(c.Id, ca.Id, 'test', 'test', 'test', 'test', 'test', 'test', 'test');
    	} catch (Exception e){
    		System.assert(true);
    	}

		Test.stopTest();
	}

	static testmethod void createEmailMessageTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();

    	try {
    		util.createEmailMessage(null, null, 'test', 'test@test.com', 'test');
    	} catch (Exception e){
    		System.assert(true);
    	}

		Test.stopTest();
	}

	static testmethod void createCreateContactTest() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();

    	try {
    		util.createContact(null, null,null,null,null,null,null,null,null,null,null,null,null,null,null,null );
    	} catch (Exception e){
    		System.assert(true);
    	}

		Test.stopTest();
	}

	static testmethod void createInsertNewCase() {
		Test.startTest();
    	
    	CaseUtility util = new CaseUtility ();
    	util.insertNewCase(new Case());

		Test.stopTest();
	}

	static testmethod void getQueueRTTest() {
		Test.startTest();
    	CaseUtility util = new CaseUtility ();
    	util.getQueueRecordType('default');

		Test.stopTest();
	}
	
}