src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>7th Stage</fullName>
                </value>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>Align</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Always Discreet</fullName>
                </value>
                <value>
                    <fullName>Anna Sui</fullName>
                </value>
                <value>
                    <fullName>Ariel</fullName>
                </value>
                <value>
                    <fullName>Atra</fullName>
                </value>
                <value>
                    <fullName>Aussie</fullName>
                </value>
                <value>
                    <fullName>Avril Lavigne</fullName>
                </value>
                <value>
                    <fullName>Baldessarini</fullName>
                </value>
                <value>
                    <fullName>Balsam Color</fullName>
                </value>
                <value>
                    <fullName>Basic White</fullName>
                </value>
                <value>
                    <fullName>Beautiful Collection</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>Born Blonde</fullName>
                </value>
                <value>
                    <fullName>Boss Skin</fullName>
                </value>
                <value>
                    <fullName>Bounce</fullName>
                </value>
                <value>
                    <fullName>Bounty</fullName>
                </value>
                <value>
                    <fullName>Braun</fullName>
                </value>
                <value>
                    <fullName>BW2</fullName>
                </value>
                <value>
                    <fullName>Camay</fullName>
                </value>
                <value>
                    <fullName>Cascade</fullName>
                </value>
                <value>
                    <fullName>Charmin</fullName>
                </value>
                <value>
                    <fullName>Cheer</fullName>
                </value>
                <value>
                    <fullName>Christina Aguilera</fullName>
                </value>
                <value>
                    <fullName>Clairol</fullName>
                </value>
                <value>
                    <fullName>Clairol Pro Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional liquicolor</fullName>
                </value>
                <value>
                    <fullName>Tide</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>[Sample Value]</fullName>
                </value>
                <value>
                    <fullName>Promotion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_Return_Type__c</fullName>
        <description>Return type for Case - cannot be a mixture of physical/digital</description>
        <inlineHelpText>Return type for Case - cannot be a mixture of physical/digital</inlineHelpText>
        <label>Selected Return Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <externalId>true</externalId>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIISitespageSettings__c.object
<CustomObject>
    <description>This object stores the selection made by the agent. It auto-generates a URL.</description>
    <fields>
        <fullName>Case_Id__c</fullName>
        <label>Case Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <inlineHelpText>Selected fields will be visible to consumer</inlineHelpText>
        <label>Fields</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FirstName</fullName>
                </value>
                <value>
                    <fullName>LastName</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>AddressLine1</fullName>
                </value>
                <value>
                    <fullName>AddressLine2</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Postal/ZipCode</fullName>
                </value>
                <value>
                    <fullName>Telephone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_DPR_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked will include any digital photo request forms in the PII form</description>
        <inlineHelpText>If checked will include any digital photo request forms in the PII form</inlineHelpText>
        <label>Include DPR Form?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PII_URL__c</fullName>
        <formula>$Setup.Global_Org_Settings__c.Base_Site_URL__c +&apos;PII?sid=&apos;+ Site_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PII URL</label>
        <type>Text</type>
    </fields>
    <label>PIISitespageSettings</label>
    <nameField>
        <displayFormat>PII-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIISitespageSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_PIIPopUpConTest.cls
/*
* @author: original PG class
* @date: 08/19/2014
* @description: Test class for sf_PIIPopUpCon. 
  Class migrated from Prod org
*/
@isTest
private class sf_PIIPopUpConTest{
    
    public static testmethod void testPIIPopupCon(){
        List<PIISitespageSettings__c> piiList = new List<PIISitespageSettings__c>();
        List<Task> piiTaskList = new List<Task>();
        
		Case caseobj = new Case();
      	caseobj.Country__c='United States of America';
      	caseObj.Language__c='English-US';
      	caseObj.Brand__c='Tide';
      	caseObj.Segment__c='Unknown';
      	insert caseObj;
      
		ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
      
		sf_PIIPopupCon con = new sf_PIIPopupCon(sc);
        
         //Assert no pii or task record already exists
        piiList = [SELECT Id, Fields__c, Case_Id__c, PII_URL__c, Include_DPR_Form__c FROM PIISitespageSettings__c WHERE Case_Id__c = :caseObj.Id];
        System.assertEquals(0, piiList.size());
        piiTaskList = [SELECT Id FROM Task WHERE WhatId = :caseObj.Id];
        System.assertEquals(1, piiTaskList.size());//Task gets auto created on Case open

		test.startTest();
            con.save();
            piiList = [SELECT Id, Fields__c, Case_Id__c, PII_URL__c, Include_DPR_Form__c FROM PIISitespageSettings__c];
            System.assertEquals(1, piiList.size());
        	piiTaskList = [SELECT Id FROM Task WHERE WhatId = :caseObj.Id];
        	System.assertEquals(2, piiTaskList.size());
        	con.toggleDisplayInsert();
            System.assert(!con.displayInsert);
        test.stopTest();
    }
    
    public static testmethod void dprEmailMandatoryTest(){
        //Create Case/Product data
		checkrecursive.toggleAllTriggers(false);
			AutoComRuleHelper_datasetup_Test.dataSetup();
	    checkrecursive.toggleAllTriggers(true); 
        
        Case testCase = [SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
		ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
		sf_PIIPopupCon con = new sf_PIIPopupCon(sc);
            
        test.startTest();
        	system.assertEquals(True, con.dprAvailable);
        
        	//Now includeDPR
        	con.piiobject.Include_DPR_Form__c = True;
        	con.save();
        
        	//Test email is mandatory message
			List<ApexPages.Message> msgs = new List<ApexPages.Message>(ApexPages.getMessages());
        	system.assertEquals(1, msgs.size());
  			msgs.clear();      	

        test.stopTest();
    }
    
	/****************************************************************
     * Where CPs return types all = Digital							*
     * Expected: Include_DPR_Form__c = true							*
	****************************************************************/ 
	public static testmethod void includeDPRTest(){
        //Create Case/Product data
		checkrecursive.toggleAllTriggers(false);
      		AutoComRuleHelper_datasetup_Test.dataSetup();
        checkrecursive.toggleAllTriggers(true); 
        
        Case testCase = [SELECT Id, Selected_Return_Type__c, Status FROM Case WHERE Subject = 'Digital' LIMIT 1];
		ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
		sf_PIIPopupCon con = new sf_PIIPopupCon(sc);
            
        test.startTest();
        	system.assertEquals(True, con.dprAvailable);
        
        	//Now includeDPR
        	con.piiobject.Include_DPR_Form__c = True;
			con.isEmail = True;
			
        	con.save();

        	PIISitespageSettings__c pii = [SELECT Id, Fields__c, Case_Id__c, PII_URL__c, Include_DPR_Form__c FROM PIISitespageSettings__c LIMIT 1];
        	system.assertEquals(true, pii.Include_DPR_Form__c);
        
        test.stopTest();
    }

	/****************************************************************
     * Where CPs return types are mixed, if one physical all		*
     * Become physical												*
     * Expected: Include_DPR_Form__c = false						*
	****************************************************************/
	public static testmethod void mixedReturnTypeDPRTest(){
        //Create Case/Product data
		checkrecursive.toggleAllTriggers(false);
      		AutoComRuleHelper_datasetup_Test.dataSetup();
        checkrecursive.toggleAllTriggers(true); 

        Case testCase = [SELECT Id, ContactId, Selected_Return_Type__c FROM Case WHERE Subject = 'digital' LIMIT 1];
        testCase.Selected_Return_Type__c = '';
        update testCase;

        test.startTest();
            //Create second physical only case product - here as getting too many soql if before test.startTest
            Case_Product__c digiCP = [SELECT Id, Case__c, ACR_Info__c, ACR_Return_Type__c, Product_available_for_return__c, Local_Product__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
            Case_Product__c phyCP = digiCP.clone(false,false,false,false);
            phyCP.ACR_Return_Type__c = 'Physical';
            insert phyCP;
        
        	Integer cpCount = [SELECT Count() FROM Case_Product__c WHERE Case__C = :testCase.Id];
        	system.assertEquals(2, cpCount);

			ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
			sf_PIIPopupCon con = new sf_PIIPopupCon(sc);

			system.assertEquals(False, con.dprAvailable);

        test.stopTest();
	}
}