src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chat_Key__c</fullName>
        <description>Field used to store the chat key during the chat cases, this would be used as the identifier to send the PII request if we lose the transcript and case context as enclosed tabs</description>
        <label>Chat Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Return_Type__c</fullName>
        <description>Return types supported by matching ACR:
Digital = Digital + Physical 
Physical = Physical only</description>
        <inlineHelpText>Return types supported by matching ACR:
•Digital = Digital + Physical 
•Physical = Physical only</inlineHelpText>
        <label>ACR Return Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACR_Return_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Digital_Return_Id__c</fullName>
        <description>Unique Id generated for digital return form, set by code</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Id generated for digital return form, set by code</inlineHelpText>
        <label>Digital Return Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_available_for_return__c</fullName>
        <label>Product available for return</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes - Product is available</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>No - Product cannot be returned</fullName>
                </value>
                <value>
                    <fullName>Unknown - Written communication</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>productstatus__c</fullName>
        <description>This field indicates the status of the case product record</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Added</fullName>
                    <default>true</default>
                    <label>Added</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PIISitespageSettings__c.object
<CustomObject>
    <description>This object stores the selection made by the agent. It auto-generates a URL.</description>
    <fields>
        <fullName>Case_Id__c</fullName>
        <label>Case Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DPR_UID__c</fullName>
        <description>Unique ID for the Case Product supporting DPR</description>
        <inlineHelpText>Unique ID for the Case Product supporting DPR</inlineHelpText>
        <label>DPR UID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <inlineHelpText>Selected fields will be visible to consumer</inlineHelpText>
        <label>Fields</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FirstName</fullName>
                </value>
                <value>
                    <fullName>LastName</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>AddressLine1</fullName>
                </value>
                <value>
                    <fullName>AddressLine2</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Postal/ZipCode</fullName>
                </value>
                <value>
                    <fullName>Telephone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_DPR_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked will include any digital photo request forms in the PII form</description>
        <inlineHelpText>If checked will include any digital photo request forms in the PII form</inlineHelpText>
        <label>Include DPR Form?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PII_URL__c</fullName>
        <formula>$Setup.Global_Org_Settings__c.Base_Site_URL__c +&apos;PII?sid=&apos;+ Site_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PII URL</label>
        <type>Text</type>
    </fields>
    <label>PIISitespageSettings</label>
    <nameField>
        <displayFormat>PII-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIISitespageSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_PIIPopupCon.cls
/*
* @author: original PG class
* @date: 08/19/2014
* @description: Test class for sf_PIIPopUpCon. Class migrated from Prod org
* DATE              NAME                CHANGE DESCRIPTION
* ...
* 19/06/2017    Acceture      WR508 - Chat Redsign: New attributes to the class to hold selected pii details
*/
global class sf_PIIPopupCon{
	public PIISitespageSettings__c piiobject { get;set; }
	public boolean displayInsert { get;set; }
	public case caseobj { get;set; }
    
	// WR508 - Chat/Pii Revamp : ADDITIONAL ATTRIBUTES
    public Boolean isName { get; set; }
    public Boolean isEmail { get; set; }
	public Boolean isPhone { get; set; }
    public Boolean isAddress { get; set; }
    public Boolean isValid { get; set; }
    
	public sf_PIIPopupCon(ApexPages.StandardController standcon) {
    	piiobject = new PIISitespageSettings__c();
    	displayInsert = true;
		// WR508 - Chat/Pii Revamp : DEFAULT TO NAME AND INITIALIZE MULTIPICKLIST
        isValid = false;
        isName = true;
      	isAddress = false;
        isPhone = false;
        isEmail = false;
          
        piiobject.Fields__c = 'FirstName; LastName;';
    	caseobj = (case) standcon.getRecord();
        // WR508 - Chat/Pii Revamp : ADDITIONAL FIELD 'Origin' QUERIED
        // WR574 - ADDITIONAL FIELD 'chat_key__c' QUERIED
    	caseobj = [ SELECT Id, ContactId,chat_key__c, AccountId, Origin FROM Case WHERE Id = :caseobj.Id ];
        if (caseobj.Origin == 'Chat' && String.isNotEmpty(caseObj.ContactId) ) {
      		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, System.Label.msgPrechatExist));
            isName = false;
        }
        // WR508 - Chat/Pii Revamp : CHANGED DEFAULT TO NAME ONLY
		//initiate with few default fields
		//piiobject.Fields__c = 'FirstName; LastName;';// AddressLine1; AddressLine2; City; State; Country; Postal/ZipCode
  }
    
  //CR16 Do any products require a digital or physical return?
  //only ONE CP supporting digi
  public boolean dprAvailable{
    get{
      dprAvailable = false;
      Set<String> returnTypes = new Set<String>();
      AggregateResult[] results = [ SELECT ACR_Return_Type__c FROM Case_Product__c 
                                          WHERE Case__c = :caseobj.Id GROUP BY ACR_Return_Type__c];
      for (AggregateResult ar : results){
        returnTypes.add(String.valueOf(ar.get('ACR_Return_Type__c')));
      }
      if(returnTypes.contains('Physical')){
        dprAvailable = false;//If one CP is physical the whole Case becomes physical
      }
      else if(returnTypes.contains('Digital')){
                //How many CPs support digi and are available for return?
                Integer digiCPCount = [SELECT Count()
                                       FROM Case_Product__c
                                       WHERE Case__c = :caseobj.Id
                                       AND Product_available_for_return__c = 'Yes - Product is available'
                                       AND Productstatus__c = 'Added'
                                       AND ACR_Return_Type__c = 'Digital'
                                       AND Status__c = '' ];
                                        
                if(digiCPCount == 1){
                    dprAvailable = true;
                }
        
      }
      return dprAvailable;
    }
    private set;
  }
  // WR508 - Chat/Pii Revamp
    private void mapFieldData () {
        piiobject.Fields__c = '';
        piiobject.Fields__c += isName ? (String.isNotEmpty(piiobject.Fields__c) ? ';' : '') + 'FirstName;LastName' : '';
        piiobject.Fields__c += isAddress ? (String.isNotEmpty(piiobject.Fields__c) ? ';' : '') + 'AddressLine1; AddressLine2; City; State; Country; Postal/ZipCode' : '' ;
        piiobject.Fields__c += isEmail ? (String.isNotEmpty(piiobject.Fields__c) ? ';' : '') + 'Email' : '';
        piiobject.Fields__c += isPhone ? (String.isNotEmpty(piiobject.Fields__c) ? ';' : '') + 'Phone' : '';
    }
    
	public void save() {
        sf_SocialMediaUtility smUtil = new sf_SocialMediaUtility();
        // WR508 - Chat/Pii Revamp : MAP DATA TO MULTI SELECT FIELD
        mapFieldData();
        system.debug('0000 : ' +  piiobject.Fields__c);
        // WR508 - Chat/Pii Revamp : USE RETURN VALUE FROM VALIDATE METHOD
        //Validate input fields
        isValid = validateFields(caseobj.Id, piiobject.Include_DPR_Form__c, piiobject.Fields__c);
        if(!isValid) {
            // WR508 - Chat/Pii Revamp : THIS CONDITION TO CHECK IF PII IS SUBMITTED AGAIN FOR THS SAME OBJECT
            if (String.isEmpty(piiobject.Id)) {
        
                if(piiobject.Include_DPR_Form__c){
                    Case_Product__c dprCP = [ SELECT Id
                                                   , Digital_Return_Id__c
                                              FROM Case_Product__c
                                              WHERE Case__c = :caseobj.Id
                                                AND Product_available_for_return__c = 'Yes - Product is available'
                                                AND Productstatus__c = 'Added'
                                                AND ACR_Return_Type__c = 'Digital'
                                                AND Status__c = '' LIMIT 1 ];
                    
                    piiobject.DPR_UID__c = dprCP.Digital_Return_Id__c;
                }
                    
                system.debug('###### in SAVE ######');
                piiobject.IsActive__c = true;
                piiobject.Case_Id__c = caseobj.Id;
                insert piiobject;
                system.debug(piiobject);
    
                //create a closed activity in the case object
                smUtil.createTask('Consumer PII Request', 'Consumer PII Request', 'Social Media', 'Completed', 'Low', caseobj.Id
                                , sf_GlobalUtilityClass.TASK_INTERNAL_ACTIVITY_RT_ID, caseobj.contactId, null);
            } else {
                update piiobject;
            }
            //make it invisible
            displayInsert = caseobj.Origin != 'Chat' ? false : true;
            
            //retrieve full fields from the same object
            piiobject = [SELECT Id, Fields__c, Case_Id__c, PII_URL__c, Include_DPR_Form__c 
                         FROM PIISitespageSettings__c WHERE Id=:piiobject.Id];
		}
	}
    
    	/*
       * @author:         Accenture
       * @date:           03/10/2017
       * @description:    ADDED TO TOGGLE THE DISPLAYINSERT WHEN THERE IS NO CUSTOM EVENT HAPPENED TO THE CHAT CASES
       * @input:          NONE
       * @return:         NONE
       */
      public void toggleDisplayInsert(){
         displayInsert = false;
      }
  
	// WR508 - Chat/Pii Revamp : ADDED RETURN VALUE
	@RemoteAction
	global static Boolean validateFields(String caseId, Boolean includeDpr, String selectedFields) {
		Boolean retVal = false;
		//if the case is not associated with an account, then firstname, lastname and email are mandatory
		Case currentcase = [ SELECT AccountId FROM Case WHERE Id = :caseId ];
		if (currentcase.AccountId == NULL) {
			if (!selectedFields.contains('FirstName')) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.ContactUs_EM_Firstname));
				retVal = true;
      		}
			if (!selectedFields.contains('LastName')) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.ContactUs_EM_Lastname));
			retVal = true;
      		}
    	}
        
		// CR16 - If DPR selected email is mandatory
		// WR508 - Chat/Pii Revamp : REMOVED EMAIL CONDITION AS EMAIL IS ALWAYS MANDATORY NOW
		if (includeDpr && !selectedFields.contains('Email')) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.DPR_Email_Mandatory));
            retVal = true;
		}
        
        return retVal;
	}
}