src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CCM_Initial_Pull__c</fullName>
        <label>CCM Initial Pull</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Deletable__c</fullName>
        <formula>OR( 
   ISBLANK(Case__r.CCM_Initial_Pull__c), 
   AND(
      NOT(ISBLANK(Case__r.CCM_Initial_Pull__c)),
      NOT(Local_Comment_Code__r.GCC_Level_1__c = &apos;Product Quality Complaint&apos;), 
      NOT(Local_Comment_Code__r.GCC_Level_1__c = &apos;Adverse Event&apos;)
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Deletable</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fulfillment_Order__c.object
<CustomObject>
    <description>The Fulfillment Order object houses order details for Cases requiring a fulfillment order.  The Fulfillment Order represents the ‘Shopping Cart’ of items that complete a single order related to a Case.  The design supports the ability for a case to contain multiple Fulfillment Orders.  Fulfillment Orders can be both manually fulfilled or sent via integration to the P&amp;G Hermes application.  Fulfillment Orders contain a status field to indicate status of the current order.</description>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Comment Code</label>
        <referenceTo>Case_Comment_Code__c</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fulfillment Order</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Fulfillment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Comment_Product__c.object
<CustomObject>
    <description>A many to many relationship object between Safety Assessment Survey and Case Product.</description>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Comment Code</label>
        <referenceTo>Case_Comment_Code__c</referenceTo>
        <relationshipLabel>Survey Comment Products</relationshipLabel>
        <relationshipName>Survey_Comment_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Survey Comment Products</relationshipLabel>
        <relationshipName>Survey_Comment_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <formula>CASESAFEID(Safety_Assessment_Survey__r.Case__c)</formula>
        <label>Case</label>
        <type>Text</type>
    </fields>
    <label>Survey Comment Product</label>
    <nameField>
        <displayFormat>SCP-{0000}</displayFormat>
        <label>Survey Comment Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Comment Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_CaseCommentCodeTriggerHelper.cls
/*
* @author: Oleg Rikkers
* @date: 06/02/2014

* @description: 
* DE412
* Name:Removing the Comment Code association does not disassociate the product

* Description:
	Create a case
	Add a product and comment code which triggers an SAS
	Add another of the same product and same comment code
	Click Associate on the popup
	See that the product is associated on the Required Info page
	Now go back and remove the Comment Code from one of the products
	Notice 2 products are still associated on the Required Info page
 	
 	Cas: Spoke with P&G, they would like to prevent the deletion of products/comment codes associated to the a survey with the error message, "The Comment Code has linked surveys and cannot be deleted."

	Chris:
	Also prevent delete of Case Comment Codes when there are associated Fulfillment Orders
*/ 


public with sharing class sf_CaseCommentCodeTriggerHelper {
	/**
	* @description prevents the delete of comment codes if they are related to a Survey or Fulfillment Order.
	*/
	public static void checkCommentCodesBeforeDelete (Map <Id, Case_Comment_Code__c> triggerOldMap) {
		
		//Map <Id, List <Id>> cpToCccMap = new Map <Id, List <Id>> ();

		//for (Case_Comment_Code__c ccc: triggerOldMap.values()) {
		//	if (cpToCccMap.get(ccc.Case_Product__c) == null) {
		//		cpToCccMap.put (ccc.Case_Product__c, new List <Id> {ccc.Id});
		//	} else {
		//		cpToCccMap.get(ccc.Case_Product__c).add (ccc.Id);
		//	}
		//}

		Set <Id> cccSet = new Set <Id> ();

		for (Survey_Comment_Product__c scp: [SELECT Id, Case_Product__c, Case_Comment_Code__c 
											FROM Survey_Comment_Product__c 
											WHERE Case_Comment_Code__c IN :triggerOldMap.keySet()]) {
			//if (cpToCccMap.get(scp.Case_Product__c) != null) {
			//	for (Id cccId: cpToCccMap.get(scp.Case_Product__c)) {
			//		triggerOldMap.get(cccId).addError(Label.CommentCodeCannotBeDeleted);
			//	}
			//}


			//orikkers 10-13-14 only disallow deletion of comment codes associated to scp
			if (triggerOldMap.get(scp.Case_Comment_Code__c) != null)
				triggerOldMap.get(scp.Case_Comment_Code__c).addError(Label.CommentCodeCannotBeDeleted);
		}
		
		//Prevent delete of Case Comment Codes when there are associated Fulfillment Orders
		for(Fulfillment_Order__c ffo : [SELECT Id, Case_Comment_Code__c FROM Fulfillment_Order__c WHERE Case_Comment_Code__c IN :triggerOldMap.keySet()]){
			triggerOldMap.get(ffo.Case_Comment_Code__c).addError(Label.CommentCodeCannotBeDeletedFulfillmentOrders);
		}
	}
	
   /**
	* @author: Chris Southworth
	* @date: 09/23/2014
	* @param: oldMap: Map of Case Comment Codes before delete
	* @description: prevent all users from deleting Case Comment Codes after the case has been submitted and the
	*	comment code is of type AE or PQC.
	*	Users can use the Product/Comment tab in the console to 'soft' delete the case comment codes.
	*/
	public static void preventDeleteSubmittedCaseComments(Map<Id, Case_Comment_Code__c> oldMap){
		Set<Id> caseIds = new Set<Id>();
		for(Case_Comment_Code__c ccc : oldMap.values()){
			if(ccc.Is_Deletable__c == false){
				caseIds.add(ccc.Case__c);
			}
		}
		if(caseIds.size() > 0){
			Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id FROM Case WHERE Id IN :caseIds AND CCM_Initial_Pull__c != null]);
			for(Case_Comment_Code__c ccc : oldMap.values()){
				if(caseMap.containsKey(ccc.Case__c)){
					oldMap.get(ccc.Id).addError(Label.CaseCommentCode_PreventDeleteForAEorPQC);
				}
			}
		}
	}
}