src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the caller/contact</description>
        <inlineHelpText>Please select the language of the contact</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Brand_Language__c.object
<CustomObject>
    <description>Junction object storing brand- and language-specific settings and translations</description>
    <fields>
        <fullName>Contact_Us_Language__c</fullName>
        <label>Contact Us Language</label>
        <referenceTo>Contact_Us_Language__c</referenceTo>
        <relationshipLabel>Contact Us Brands Languages</relationshipLabel>
        <relationshipName>Contact_Us_Brands_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Us Brand Language</label>
    <nameField>
        <displayFormat>CBL-{0000}</displayFormat>
        <label>Contact Us Brand Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Us Brands Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Language__c.object
<CustomObject>
    <description>This object is for configuring the language/countries for the contact us page</description>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Privacy__c</fullName>
        <label>Privacy</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <label>Terms and Conditions</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Privacy_Policy__c</fullName>
        <description>Link to privacy policy in this language</description>
        <label>URL Privacy Policy</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>URL_Terms_and_Conditions__c</fullName>
        <description>Link to terms and conditions in this language</description>
        <label>URL Terms and Conditions</label>
        <type>Url</type>
    </fields>
    <label>Contact Us Language</label>
    <nameField>
        <label>Contact Us Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_ContactUsFooterComponentCtrl.cls
/*
* @author: Lauren OMeara
* @date: 07/31/2014

* @description: 
* US668 - re-architect contact us page
*/
public with sharing class sf_ContactUsFooterComponentCtrl {
	// footer language config values
	public String termsAndConditions {get; set;}
	public String privacy {get; set;}	
	public String termsAndConditionsURL {get; set;}
	public String privacyURL {get; set;}
    //WR225 CRM banner
    public Contact_Us_Brand_Language__c brand_lang_config {get;set;}
    public boolean showBanner {get;set;}
		
	public sf_ContactUsFooterComponentCtrl() {
		string language = sf_ContactUsHelperCtrl.getLanguage();
		string country = sf_ContactUsHelperCtrl.getCountry();
        string brand = sf_ContactUsHelperCtrl.getBrand(); //WR225
        showBanner = String.isBlank(ApexPages.currentPage().getParameters().get('surveyid')); //WR225 do not display if on CSAT page

		/* get language config for footer */
		List<Contact_Us_Language__c> language_config = [SELECT 
			Terms_and_Conditions__c, Privacy__c, URL_Terms_and_Conditions__c, URL_Privacy_Policy__c 
			FROM Contact_Us_Language__c 
			WHERE Country__c=:country AND Language__c=:language ];
			
		system.debug('***** language config '+language_config);
		// country & language config not found, fall back to default
		if (language_config.size() == 0) {
			language_config = [SELECT 
				Terms_and_Conditions__c, Privacy__c, URL_Terms_and_Conditions__c, URL_Privacy_Policy__c 
				FROM Contact_Us_Language__c 
				WHERE Country__c='United States of America' AND Language__c='English-US' ];
		}
		system.debug('***** language config '+language_config);
		
		termsAndConditions = language_config[0].Terms_and_Conditions__c;
		privacy = language_config[0].Privacy__c;
		termsAndConditionsURL = language_config[0].URL_Terms_and_Conditions__c;
		privacyURL = language_config[0].URL_Privacy_Policy__c;
        
        //WR225 Start
        //Language/Brand/Country should be a unique combination
        List<Contact_Us_Brand_Language__c> blcList = new List<Contact_Us_Brand_Language__c>([SELECT Id, Signup_Blurb__c, Signup_Button_Label__c, Signup_Image__c, signup_URL__c
                             FROM Contact_Us_Brand_Language__c
                             WHERE Contact_Us_Language__r.Language__c = :language
                             AND Contact_Us_Language__r.Country__c = :country
                             AND Contact_Us_Brand__r.Brand__c = :brand
                            ]);
        //If none found find the "default" record
        if(blcList.size()==0){
            brand_lang_config = [SELECT Id, Signup_Blurb__c, Signup_Button_Label__c, Signup_Image__c, signup_URL__c
                                 FROM Contact_Us_Brand_Language__c
                                 WHERE Contact_Us_Language__r.Name = 'Default'
                                 AND Contact_Us_Brand__r.Name = 'P&G'
                                 LIMIT 1 //Just in case...
                                ];
        }
        else{
            brand_lang_config = blcList[0];
        }
        system.debug('>>> brand_lang_config: '+brand_lang_config);
        if(String.isBlank(brand_lang_config.Signup_Image__c)){
            showBanner = false;
        }
        //WR225 Fin

	}
    
}