src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>7th Stage</fullName>
                </value>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>Align</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Always Discreet</fullName>
                </value>
                <value>
                    <fullName>Anna Sui</fullName>
                </value>
                <value>
                    <fullName>Ariel</fullName>
                </value>
                <value>
                    <fullName>Atra</fullName>
                </value>
                <value>
                    <fullName>Aussie</fullName>
                </value>
                <value>
                    <fullName>Avril Lavigne</fullName>
                </value>
                <value>
                    <fullName>Baldessarini</fullName>
                </value>
                <value>
                    <fullName>Balsam Color</fullName>
                </value>
                <value>
                    <fullName>Basic White</fullName>
                </value>
                <value>
                    <fullName>Beautiful Collection</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>Born Blonde</fullName>
                </value>
                <value>
                    <fullName>Boss Skin</fullName>
                </value>
                <value>
                    <fullName>Bounce</fullName>
                </value>
                <value>
                    <fullName>Bounty</fullName>
                </value>
                <value>
                    <fullName>Braun</fullName>
                </value>
                <value>
                    <fullName>BW2</fullName>
                </value>
                <value>
                    <fullName>Camay</fullName>
                </value>
                <value>
                    <fullName>Cascade</fullName>
                </value>
                <value>
                    <fullName>Charmin</fullName>
                </value>
                <value>
                    <fullName>Cheer</fullName>
                </value>
                <value>
                    <fullName>Christina Aguilera</fullName>
                </value>
                <value>
                    <fullName>Clairol</fullName>
                </value>
                <value>
                    <fullName>Clairol Pro Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional liquicolor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Metadata_Case_Assignment_Rule__c.object
<CustomObject>
    <description>This is a new version metadata table for sites page for case queue assignments.</description>
    <fields>
        <fullName>Account_Record_Type_Name__c</fullName>
        <label>Account Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Record_Type_Name__c</fullName>
        <label>Activity Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <inlineHelpText>Leave field empty to work with ALL brands</inlineHelpText>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>353</fullName>
                </value>
                <value>
                    <fullName>365</fullName>
                </value>
                <value>
                    <fullName>7 OClock</fullName>
                </value>
                <value>
                    <fullName>7th Stage</fullName>
                </value>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>Agilite3</fullName>
                </value>
                <value>
                    <fullName>Agility</fullName>
                </value>
                <value>
                    <fullName>Ajax</fullName>
                </value>
                <value>
                    <fullName>Align</fullName>
                </value>
                <value>
                    <fullName>Alldays</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Always Discreet</fullName>
                </value>
                <value>
                    <fullName>Ambi Pur</fullName>
                </value>
                <value>
                    <fullName>Anna Sui</fullName>
                </value>
                <value>
                    <fullName>Antikal</fullName>
                </value>
                <value>
                    <fullName>Ariel</fullName>
                </value>
                <value>
                    <fullName>Atra</fullName>
                </value>
                <value>
                    <fullName>Aussie</fullName>
                </value>
                <value>
                    <fullName>Avril Lavigne</fullName>
                </value>
                <value>
                    <fullName>Baldessarini</fullName>
                </value>
                <value>
                    <fullName>Basic White</fullName>
                </value>
                <value>
                    <fullName>Beautiful Collection</fullName>
                </value>
                <value>
                    <fullName>Bellady</fullName>
                </value>
                <value>
                    <fullName>Blend-A-Dent</fullName>
                </value>
                <value>
                    <fullName>Blend-A-Med</fullName>
                </value>
                <value>
                    <fullName>Blend-A-Med Oral-B</fullName>
                </value>
                <value>
                    <fullName>Blendax</fullName>
                </value>
                <value>
                    <fullName>Blue 3</fullName>
                </value>
                <value>
                    <fullName>Blue II</fullName>
                </value>
                <value>
                    <fullName>Bogner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Record_Type_Name__c</fullName>
        <label>Case Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>If you have this field populated, then no other fields should be populated. The rule looks at email OR country/language/priority/reason for writing/brand/case status.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <inlineHelpText>Queue name. Not label. The one that has underscores.</inlineHelpText>
        <label>Queue Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Metadata Case Assignment Rule</label>
    <nameField>
        <displayFormat>MCAR-{00000}</displayFormat>
        <label>Metadata Case Assignment Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Case Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_CaseAssignmentRuleUtility.cls
/**
* @author: salesforce.com
* @date: 09/04/2014
* @description:  US768 Utility class for Metadata Case Assignment Rule object
*/

//need without sharing because site user needs to be able to get values
public without sharing class sf_CaseAssignmentRuleUtility {
	
	private static Map<String, Schema.SObjectType> globalDescribeMap; 
	private static Map <String, Group> queueNameMap;

	static {
		globalDescribeMap = Schema.getGlobalDescribe(); 
		queueNameMap = new Map <String, Group> ();
		for (Group gr: [SELECT DeveloperName
								,Email
								,Id
								,Name 
						FROM Group 
						WHERE Type = 'Queue']) {
			queueNameMap.put (gr.DeveloperName.toLowerCase(), gr);
		}
	}

	public static String getRecordTypeIdByName (String sObjectApiName, String rtName) {
		Id rtId;
		Map <String, Schema.RecordTypeInfo> rtMap = globalDescribeMap.get(sObjectApiName).getDescribe().getRecordTypeInfosByName();

		if (rtMap.get(rtName) != null)
			rtId = rtMap.get(rtName).getRecordTypeId();

		return rtId;
	}

	public static String getQueueIdByName (String qName) {
		qName = qName != null ? qName.toLowerCase() : '';
		return queueNameMap.get(qName) != null ? queueNameMap.get(qName).Id : null;
	}

	/**
	 * Returns Metadata_Case_Assignment_Rule__c record. If none found, 
	 * it populates an empty one with default queue.
	 *
	 * @param  brand
	 * @param  language
	 * @param  country
	 * @param  priority
	 * @param  caseStatus
	 * @param  reasonForWriting as a order number
	 * @return   Metadata_Case_Assignment_Rule__c record
	 * @see      CaseUtility
	 */
	 
	public static Metadata_Case_Assignment_Rule__c getMCARRecord (String brand
																	,String language
																	,String country
																	,String priority
																	,String caseStatus
                                                                    ,String conEmail
                                                                    ,string caseOrigin //CDOY WR114 - Add case origin to MCAR Rules
																	,String reasonForWriting) { 
		System.debug(LoggingLevel.INFO, 'Searching for MCAR : ' + brand + ', ' + language + ', ' + country + ', ' + priority + ', ' + caseStatus + ', ' + conEmail + ', ' + caseOrigin + ', ' + reasonForWriting);
		Metadata_Case_Assignment_Rule__c mcar;  
		
		//This has been added to stop the Metadata_Case_Assignment_Rule__c object finding a match between 
		//contacts with an blank/empty email address and MCAR rules that have an empty email field. By
		//setting the conEmail to 'thisRandomText' it will never find a match to an MCAR email address.
		conEmail = String.isBlank(conEmail) ? 'thisRandomText' : conEmail; //CDOY WR275 Fix
		system.debug('*** CDOY conEmail ='+conEmail); //CDOY WR275 Fix

		List <Metadata_Case_Assignment_Rule__c> mcarList = new List <Metadata_Case_Assignment_Rule__c> ();
		mcarList = [SELECT Id
							,Brand__c
							,Language__c
							,Account_Record_Type_Name__c
							,Activity_Record_Type_Name__c
							,Queue_Name__c
							,Case_Record_Type_Name__c
                    		,Email__c
                    		,Case_Origin__c //CDOY WR114 - Add case origin to MCAR Rules
					FROM Metadata_Case_Assignment_Rule__c
					WHERE (
					(Brand__c INCLUDES (:brand) OR Brand__c = null)
					AND (Case_Origin__c INCLUDES (:caseOrigin) OR Case_Origin__c = null) //CDOY WR114 - Add case origin to MCAR Rules
					AND Language__c = :language
					AND Country__c INCLUDES (:country)
					AND Case_Status__c INCLUDES (:caseStatus)
					AND Priority__c INCLUDES (:priority)
					AND Reason_For_Writing__c INCLUDES (:reasonForWriting))
					OR Email__c =: conEmail //CDOY - 275 Email Blacklisting
					ORDER BY Rank__c ASC
					NULLS LAST
					LIMIT 1];

		system.debug('caseOrigin = '+caseOrigin);
		system.debug('language = '+language);
		system.debug('country = '+country);
		system.debug('caseStatus = '+caseStatus);
		system.debug('priority = '+priority);
		system.debug('reasonForWriting = '+reasonForWriting);

		system.debug('MCARList Equals = ' + mcarList);

		if (!mcarList.isEmpty()) {
			mcar = mcarList[0];
			system.debug('mcarList is Not Empty');
		} else { //create defaults
		    system.debug('mcarList is Empty');
			mcar = new Metadata_Case_Assignment_Rule__c ();
			mcar.Queue_Name__c = sf_Constants.DEFAULT_QUEUE_NAME;
		}


		System.debug(LoggingLevel.INFO, 'mcar found:  ' + mcar);
		return mcar;
	}
}