src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Return_Status__c</fullName>
        <description>Hidden field used by workflows to manage sending of reminders for product returns</description>
        <label>Product Return Reminder Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACR_Return_Type__c</fullName>
        <description>Return types supported by matching ACR:
Digital = Digital + Physical 
Physical = Physical only</description>
        <inlineHelpText>Return types supported by matching ACR:
•Digital = Digital + Physical 
•Physical = Physical only</inlineHelpText>
        <label>ACR Return Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACR_Return_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_available_for_return__c</fullName>
        <label>Product available for return</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes - Product is available</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>No - Product cannot be returned</fullName>
                </value>
                <value>
                    <fullName>Unknown - Written communication</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Production_Code__c</fullName>
        <inlineHelpText>What is the production code?</inlineHelpText>
        <label>Production Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>productstatus__c</fullName>
        <description>This field indicates the status of the case product record</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Added</fullName>
                    <default>true</default>
                    <label>Added</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Level_2__c</fullName>
        <description>This is the next level up once we know the type of Comment Code</description>
        <externalId>true</externalId>
        <label>Level 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/digiReturnsHelper_test.cls
@isTest
public class digiReturnsHelper_test {
    
    @testSetup static void setupData(){
		checkrecursive.toggleAllTriggers(false);
        AutoComRuleHelper_datasetup_Test.dataSetup();
        checkrecursive.toggleAllTriggers(true);
    }
    
	/************************************
     * Digital return first attempt		*
     ***********************************/
	@isTest
    static void dprFirstAttemptTest(){
		Case testCase = [SELECT Id FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Set<Id> caseIds = new Set<Id>{testCase.Id};
        List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        system.assertEquals(0, caseEmails.size());
        
       	test.startTest();
        	digiReturnsHelper.digiReturnFirstAttempt(caseIds);
        test.stopTest();
        
		caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
		system.assertEquals(1,caseEmails.size());
    }
    /************************************
     * Digital return first attempt     *
     * with cancelled product           *
     ***********************************/    
     @isTest
     static void dprCancelledProduct(){
        Case testCase = [SELECT Id FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Set<Id> caseIds = new Set<Id>{testCase.Id};
        List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        system.assertEquals(0, caseEmails.size());

        Case_Product__c orgCP = new Case_Product__c();
        orgCP = [SELECT Id, Local_Product__c,ACR_Info__c FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        orgCP.Status__c = digiReturnsHelper.DIGI_RETURN_FIRST_ATTEMPT;
        //testCase.Product_Return_Status__c = digiReturnsHelper.DIGI_RETURN_FIRST_ATTEMPT;//WFR?
        update orgCP;

        test.startTest();

            //Now cancel CP
            orgCP.productstatus__c = 'cancelled';
            update orgCP;
            //Now add new CP/CC
            Case_Product__c newCP = new Case_Product__c(
                Case__c = testCase.Id,
                Local_Product__c = orgCP.Local_Product__c,
                Production_Code__c = 'new CP!',
                ACR_Info__c = orgCP.ACR_Info__c,
                ACR_Return_Type__c = 'Digital',
                Product_available_for_return__c = 'Yes - Product is available'     
            );
            insert newCP;
                
            Case_Comment_Code__c newCCC = new Case_Comment_Code__c(
                Case__c = testCase.Id,
                Local_Comment_Code__c = [SELECT Id FROM Local_Comment_Code__c WHERE Level_2__c = 'Foreign Material' LIMIT 1].Id,
                Case_Product__c = orgCP.Id
            );
            insert newCCC;
            //Now resubmit
            digiReturnsHelper.digiReturnFirstAttempt(caseIds);

        test.stopTest();    

        testCase = [SELECT Id, Product_Return_Status__c, CaseNumber FROM Case WHERE Id = :testCase.Id];
        //system.assertEquals(digiReturnsHelper.DIGI_RETURN_FIRST_ATTEMPT,testCase.Product_Return_Status__c);
        system.debug(logginglevel.WARN, '!!!!!!! Post testCase: '+testCase);
        newCP = [SELECT Id, Status__c, Name FROM Case_Product__c WHERE Id = :newCP.Id];
        system.debug(logginglevel.WARN, '!!!!!!! Post newCP: '+newCP);
        //system.assertEquals(digiReturnsHelper.DIGI_RETURN_FIRST_ATTEMPT,newCP.Status__c);*/
        caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        system.assertEquals(1,caseEmails.size());

     }
    
	/************************************
     * Digital return second attempt	*
     ***********************************/
	@isTest
    static void dprSecondAttemptTest(){
        //Get Case/CP and update to attempt 2
        Case testCase = [SELECT Id, ContactId, Country__c, Selected_Return_Type__c, Product_Return_Status__c FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__c cp = [SELECT Id FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        List<SObject> updateRecords = new List<SObject>();
        cp.Status__c = 'Photo - Attempt 2';
        updateRecords.add(cp);
        testCase.Product_Return_Status__c = 'Photo - Attempt 2';
        updateRecords.add(testCase);
        update updateRecords;

        Map<Id, Case> caseMap = new Map<Id, Case>();
        caseMap.put(testCase.Id, testCase);
        
        //Assert no email records before 2nd attempt
		List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        system.assertEquals(0, caseEmails.size());

		test.startTest();
        	digiReturnsHelper.digiReturnFirstAttempt(caseMap);
        test.stopTest();
        
		caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        system.assertEquals(1,caseEmails.size());
    }
    
	/************************************
     * Digital return third attempt		*
     ***********************************/
	@isTest
    static void dprThirdAttemptTest(){
        //Get Case/CP and update to attempt 3
        Case testCase = [SELECT Id, ContactId, Country__c, Selected_Return_Type__c, Product_Return_Status__c FROM Case WHERE Subject = 'Digital' LIMIT 1];
        Case_Product__c cp = [SELECT Id FROM Case_Product__c WHERE Case__c = :testCase.Id LIMIT 1];
        List<SObject> updateRecords = new List<SObject>();
        cp.Status__c = 'Photo - Attempt 3';
        updateRecords.add(cp);
        testCase.Product_Return_Status__c = 'Photo - Attempt 3';
        updateRecords.add(testCase);
        update updateRecords;

        Map<Id, Case> caseMap = new Map<Id, Case>();
        caseMap.put(testCase.Id, testCase);
        
        //Assert no email records before 3rd attempt
		List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        system.assertEquals(0, caseEmails.size());

		test.startTest();
        	digiReturnsHelper.digiReturnFirstAttempt(caseMap);
        test.stopTest();
        
		caseEmails = new List<EmailMessage>([SELECT Id FROM EmailMessage WHERE ParentId = :testCase.Id]);
        system.assertEquals(1,caseEmails.size());
    }
}