src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>7th Stage</fullName>
                </value>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>Align</fullName>
                </value>
                <value>
                    <fullName>Always</fullName>
                </value>
                <value>
                    <fullName>Always Discreet</fullName>
                </value>
                <value>
                    <fullName>Anna Sui</fullName>
                </value>
                <value>
                    <fullName>Ariel</fullName>
                </value>
                <value>
                    <fullName>Atra</fullName>
                </value>
                <value>
                    <fullName>Aussie</fullName>
                </value>
                <value>
                    <fullName>Avril Lavigne</fullName>
                </value>
                <value>
                    <fullName>Baldessarini</fullName>
                </value>
                <value>
                    <fullName>Balsam Color</fullName>
                </value>
                <value>
                    <fullName>Basic White</fullName>
                </value>
                <value>
                    <fullName>Beautiful Collection</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>Born Blonde</fullName>
                </value>
                <value>
                    <fullName>Boss Skin</fullName>
                </value>
                <value>
                    <fullName>Bounce</fullName>
                </value>
                <value>
                    <fullName>Bounty</fullName>
                </value>
                <value>
                    <fullName>Braun</fullName>
                </value>
                <value>
                    <fullName>BW2</fullName>
                </value>
                <value>
                    <fullName>Camay</fullName>
                </value>
                <value>
                    <fullName>Cascade</fullName>
                </value>
                <value>
                    <fullName>Charmin</fullName>
                </value>
                <value>
                    <fullName>Cheer</fullName>
                </value>
                <value>
                    <fullName>Christina Aguilera</fullName>
                </value>
                <value>
                    <fullName>Clairol</fullName>
                </value>
                <value>
                    <fullName>Clairol Pro Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional Crème</fullName>
                </value>
                <value>
                    <fullName>Clairol Professional liquicolor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>BackgroundImgLanding__c</fullName>
        <description>Background image for landing page</description>
        <label>Landing Page Background Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRCountryIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRLanguageIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageLocaleKey__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.Language_Locale_Key__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Locale Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <formula>TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Language__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrivacyPolicyLabel__c</fullName>
        <label>Privacy Policy Label</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrivacyPolicyLink__c</fullName>
        <description>Contains link to privacy policy</description>
        <label>Privacy Policy Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Privacy_Policy_Label_2__c</fullName>
        <label>Privacy Policy Label 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationErrorMessage__c</fullName>
        <label>Validation Error Message</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isLastNameFirst__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to determine if last name should be rendered first</description>
        <label>isLastNameFirst</label>
        <type>Checkbox</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country picklist from Global Picklist to fetch global picklist values</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LiveAgentBusinessHour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live Agent Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>GCRChannelContents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>noPrechat__c</fullName>
        <defaultValue>false</defaultValue>
        <label>noPrechat</label>
        <type>Checkbox</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <recordTypes>
        <fullName>chat</fullName>
        <active>true</active>
        <description>Select this record type for chat channel</description>
        <label>chat</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/gcr_chatController.cls
/*
* @author:       Accenture
* @date:         02/06/2016
* @description:  Controller class for chat component of GCR widget
* DATE              NAME                CHANGE DESCRIPTION
* 02/06/2016        Accenture           Initial Draft
* 09/01/2017        Accenture           Added "retrieveChatPageUrl()" method call in tempBoolean getter method which 
*										retrieves chat url for no prechat form. Added additional condition to 
*										"retrieveChatPageUrl()"" method for no prechat form 
*/
global class gcr_chatController {
    // INCOMING DATA COMING TO CONTROLLER
    public String chlContentId { get; set; }
    public Boolean isButtonAvailable { get; set; }
    public Boolean isRightToLeft { get; set; }
    
    // COMPONENT PUBLIC VARIABLES
	public GCRChannelContent__c chatChannelContent { get; set; }
    public Boolean isBusinessHrsActive { get; set; }
    public Boolean isTNCAgreed { get; set; }
    public String strFirstName { get; set; }
    public String strLastName { get; set; }
    public String strEmail { get; set; }
    public String chatPageUrl { get; set; }
    public Boolean isSubmitDisable { get; private set; }

    public String privacyPolicyFull {get;set;}
    public String privacyPolicy2 {get;set;}

    /*
     * @author:         Accenture
     * @date:           25/08/2016
     * @description:    constructor method for chat controller
     * @input:			None
     */
    public gcr_chatController() {
        isSubmitDisable = true;

    }
    
    /*
     * @author:         Accenture
     * @date:           25/08/2016
     * @description:    getter method for temporary variable to get channel content, this variable is created 
     * 					to overcome salesforce component limitation of execution sequence.
     * @input:			None
     */
    // VARIABLE TO OVERCOME SALESFORCE COMPONENT LIMITATION
    public Boolean tempBoolean { get {
        if (chatChannelContent == null) {
			String queryString = gcr_helperClass.createQueryString('SELECT'
				, gcr_helperClass.getAllFieldsForQuery('GCRChannelContent__c')
                	+ ',CareHub__r.isLastNameFirst__c,CareHub__r.Country__c,CareHub__r.PrivacyPolicyLabel__c,CareHub__r.Privacy_Policy_Label_2__c'
					+ ',RecordType.Name,CareHub__r.LanguageLocaleKey__c,CareHub__r.PrivacyPolicyLink__c'
					+ ',CareHub__r.CountryIsoCode__c,CareHub__r.BackgroundImgLanding__c,CareHub__r.Language__c'
					+ ',CareHub__r.LanguageIsoCode__c,CareHub__r.Brand__c,CareHub__r.ValidationErrorMessage__c'
                , 'GCRChannelContent__c') + ' WHERE Id = \'' + chlContentId + '\'' ;
			chatChannelContent = (GCRChannelContent__c) Database.query(queryString).get(0);
            // ADDED TO CAPTURE CHAT URL FOR NO PRE CHAT FORM
            if (chatChannelContent.noPrechat__c) {
                retrieveChatPageUrl();
            }

        privacyPolicy2 = chatChannelContent.CareHub__r.Privacy_Policy_Label_2__c == null ? ' ' : chatChannelContent.CareHub__r.Privacy_Policy_Label_2__c; //CDOYs

        privacyPolicyFull = chatChannelContent.CareHub__r.PrivacyPolicyLabel__c + ' '+ privacyPolicy2; //CDOY
		}

        if(tempBoolean == null || tempBoolean) init(); return false;
    } private set; }
    
	/*
     * @author:         Accenture
     * @date:           25/08/2016
     * @description:    init method for chat controller
     * @input:			none
     * @output:			void
     */
    private void init() {
        isBusinessHrsActive = gcr_helperClass.isBusinessHoursActive(chatChannelContent.LiveAgentBusinessHour__c);
    }

	/*
     * @author:         Accenture
     * @date:           25/08/2016
     * @description:    method to retrieve chat page url which also sens chat page name in the url
     * @input:			none
     * @output:			void
     */
    public void retrieveChatPageUrl() {
        //WR552 Added to map Loyalty ID to the case 
        String strLoyaltyID = ApexPages.currentPage().getParameters().get('loyaltyID')!=NULL ? ApexPages.currentPage().getParameters().get('loyaltyID'):'';
		
		if (System.Site.getBaseUrl().contains('carehub')) {
            chatPageUrl = System.Site.getBaseUrl() + '/gcr_chatRedirectPage?';
        } else {
            chatPageUrl = System.Site.getBaseUrl() + '/apex/gcr_chatRedirectPage?';
        }
        if (!chatChannelContent.noPrechat__c) {
            if (String.isNotEmpty(strFirstName)) {
                chatPageUrl += 'fname=' + EncodingUtil.urlEncode(strFirstName, 'UTF-8');
            }
            if (String.isNotEmpty(strLastName)) {
                chatPageUrl += '&lname=' + EncodingUtil.urlEncode(strLastName, 'UTF-8');
            }
            if (String.isNotEmpty(strEmail)) {
                chatPageUrl += '&email=' + EncodingUtil.urlEncode(strEmail, 'UTF-8') + '&';
            }
        }
        //chatPageUrl += '&channel=' + chatChannelContent.Id;
        chatPageUrl += 'brand=' + chatChannelContent.CareHub__r.Brand__c;
        chatPageUrl += '&country=' + chatChannelContent.CareHub__r.CountryIsoCode__c;
        chatPageUrl += '&language=' + chatChannelContent.CareHub__r.LanguageIsoCode__c;
        chatPageUrl += '&type=Carehub';
        
        //WR552 Added to map Loyalty ID to the case 
        if (String.isNotEmpty(strLoyaltyID)) {
            chatPageUrl += '&loyaltyID=' + EncodingUtil.urlEncode(strLoyaltyID, 'UTF-8');
        }
        //End WR552
        isSubmitDisable = false;
    }
    
	/*
     * @author:         Accenture
     * @date:           25/08/2016
     * @description:    method to set disable submit chat button
     * @input:			none
     * @output:			void
     */
    public void disableSubmit() {
        isSubmitDisable = true;
    }
    
	/*
     * @author:         Accenture
     * @date:           25/08/2016
     * @description:    rempte action to validate email via strike iron api
     * @input:			String
     * @output:			Boolean
     */
    @RemoteAction
    global static Boolean validateEmail(String strEmailAddress) {
        return gcr_helperClass.isEmailAddressValid(strEmailAddress);
	}
}