src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CX_Advocacy_Comments_Q10__c</fullName>
        <label>CX Advocacy Comments (Q10)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CX_Agent_Score_Q1_2__c</fullName>
        <label>CX Agent Score (Q1-2)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_EasySimple_Score_Q4__c</fullName>
        <label>CX EasySimple Score (Q4)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_FeelValued_Score_Q5__c</fullName>
        <label>CX FeelValued Score (Q5)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Friendly_Welcoming_Score_Q1__c</fullName>
        <label>CX Friendly Welcoming Score (Q1)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_MetNeeds_Score_Q3__c</fullName>
        <label>CX MetNeeds Score (Q3)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Net_Promoter_Score_Q9__c</fullName>
        <label>CX Net Promoter Score (Q9)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Repurchase_Score_Q8__c</fullName>
        <label>CX Repurchase Score (Q8)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Service_Comments_Q6__c</fullName>
        <label>CX Service Comments (Q6)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CX_Trust_Score_Q7__c</fullName>
        <label>CX Trust Score (Q7)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_UnderstandsNeeds_Score_Q2__c</fullName>
        <label>CX UnderstandsNeeds Score (Q2)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <formula>Contact.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>Philippines</fullName>
                </value>
                <value>
                    <fullName>Taiwan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_not_send_survey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not send survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Not_Handled_Reason__c</fullName>
        <description>US620</description>
        <label>Not Handled Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hang Up; Hoax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Misdial</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Spam</fullName>
                </value>
                <value>
                    <fullName>Auto-Response</fullName>
                </value>
                <value>
                    <fullName>Divested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Repeater_Case__c</fullName>
        <label>Repeater Case</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fraudulent Case</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CSAT_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Page_Parameters__c</fullName>
        <label>Brand Page Parameters</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CX_Agent_Score_Q1_2__c</fullName>
        <formula>(CX_Friendly_Welcoming_Score_Q1__c +
CX_UnderstandsNeeds_Score_Q2__c) / 2</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX Agent Score (Q1-2)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_EasySimple_Score_Q4__c</fullName>
        <formula>IF( Q_MakeItEasySimple__c  &gt;= 40, 1, 
IF( Q_MakeItEasySimple__c  &lt;= 30, 0, 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX EasySimple Score (Q4)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_FeelValued_Score_Q5__c</fullName>
        <formula>IF(  Q_MakeFeelValued__c  &gt;= 40, 1, 
IF(  Q_MakeFeelValued__c   &lt;= 30, 0, 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX FeelValued Score (Q5)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Friendly_Welcoming_Score_Q1__c</fullName>
        <formula>IF( Q_FriendlyAndWelcoming__c   &gt;= 40, 1,  
IF( Q_FriendlyAndWelcoming__c   &lt;= 30, 0, 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX FriendlyWelcoming Score (Q1)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_MetNeeds_Score_Q3__c</fullName>
        <formula>IF(  Q_OfferSolutions__c  &gt;= 40, 1, 
IF( Q_OfferSolutions__c &lt;= 30, 0, 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX MetNeeds Score (Q3)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Net_Promoter_Score_Q9__c</fullName>
        <formula>IF(Q_LikelyToRecommendBrandToFriends__c &gt;= 9, 1, 
IF(Q_LikelyToRecommendBrandToFriends__c ==7 || Q_LikelyToRecommendBrandToFriends__c==8, 0,
IF(Q_LikelyToRecommendBrandToFriends__c &lt;= 6, -1,0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX Net Promoter Score (Q9)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Repurchase_Score_Q8__c</fullName>
        <formula>IF(ISPICKVAL(Q_LikelyToBuyBrand__c ,&quot;Definitely will buy&quot;) || 
ISPICKVAL(Q_LikelyToBuyBrand__c, &quot;Probably will buy&quot;), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX Repurchase Score (Q8)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_Trust_Score_Q7__c</fullName>
        <formula>IF(ISPICKVAL(Q_IsThisBrandYouCanTrust__c,&quot;Strongly Agree&quot;) || ISPICKVAL(Q_IsThisBrandYouCanTrust__c, &quot;Somewhat Agree&quot;), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX Trust Score (Q7)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CX_UnderstandsNeeds_Score_Q2__c</fullName>
        <formula>IF( Q_UnderstandSpecificNeeds__c   &gt;= 40, 1, 
IF( Q_UnderstandSpecificNeeds__c   &lt;= 30, 0, 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CX UnderstandsNeeds Score (Q2)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Case_Brand__c</fullName>
        <formula>TEXT(Case__r.Brand__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Country__c</fullName>
        <formula>TEXT(Case__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Language_Code__c</fullName>
        <formula>Case__r.Language_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Language Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Language__c</fullName>
        <formula>TEXT(Case__r.Language__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CSAT Surveys</relationshipLabel>
        <relationshipName>CSAT_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CSAT Surveys</relationshipLabel>
        <relationshipName>CSAT_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page_Parameters__c</fullName>
        <label>Page Parameters</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Id__c</fullName>
        <externalId>true</externalId>
        <label>Survey Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CSAT Survey</label>
    <nameField>
        <displayFormat>CSAT-{00000000}</displayFormat>
        <label>CSAT Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSAT Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_CSATSurveyHelper.cls
/**
* @author: salesforce.com, inc.
* @date: 02/05/2015
*
* @description: helper class for CSAT survey trigger
* 
*/

public without sharing class sf_CSATSurveyHelper {

    /**
    * @description Creates a unique ID which will be used in the URL to direct the user to the appropriate CSAT record.
    */
    public static void updateCSATId (List<CSAT_Survey__c> triggerNew) {
        for (CSAT_Survey__c csat : triggerNew) {
            String stringToHash = String.valueOf(csat.Case__c) + String.valueOf(csat.Contact__c);
            Blob b = Crypto.generateDigest('SHA-256', Blob.valueOf(stringToHash));
            csat.Survey_Id__c = EncodingUtil.convertToHex(b);

            csat.Brand_Page_Parameters__c = '&brand='+ EncodingUtil.urlEncode(csat.Case_Brand__c == null ? 'P&G' : csat.Case_Brand__c, 'UTF-8');//CDOY WR403 B

            csat.Page_Parameters__c = '?surveyid='+ csat.Survey_Id__c; 
            //CDOY WR403 csat.Page_Parameters__c += '&brand='+ EncodingUtil.urlEncode(csat.Case_Brand__c == null ? 'P&G' : csat.Case_Brand__c, 'UTF-8');
            csat.Page_Parameters__c += '&country='+ EncodingUtil.urlEncode(csat.Case_Country__c, 'UTF-8');
            csat.Page_Parameters__c += '&language='+ EncodingUtil.urlEncode(csat.Case_Language__c, 'UTF-8');
            csat.Page_Parameters__c += '&lang='+ EncodingUtil.urlEncode(csat.Case_Language_Code__c, 'UTF-8');
        }
    }

    /**
    * @description Creates a CSAT Survey record when a Case is closed.
    */
    public static void createCSATForClosedCases (List<Case> closedCases) {
        List <CSAT_Survey__c> csatToInsert = new List <CSAT_Survey__c> ();
        
        for (Case c: closedCases) {
            
            boolean createCSATforAll = false;
            //WR316 and updated for WR347 by ChrisM
            //Updated by ChrisD to include Hong Kong and Taiwan
            if(c.country__c == 'China' || c.country__c == 'Japan' || c.country__c == 'Korea' || c.country__c == 'Australia'
               || c.country__c == 'Indonesia' || c.country__c == 'Philippines' || c.Country__c == 'India' 
               || c.Country__c == 'Hong Kong' || c.Country__c == 'Taiwan' ){
            
                 createCSATforAll = True;
            }
                   
            if ((true == createCSATforAll
            || c.Contact_Email__c != null)
            && !c.Do_not_send_survey__c
            && c.Not_Handled_Reason__c == null
            && c.Repeater_Case__c == null){
 
                
                CSAT_Survey__c csat = new CSAT_Survey__c ();
                csat.Case__c = c.Id;
                csat.Contact__c = c.ContactId;

                csatToInsert.add(csat);
            }
        }

        Database.insert (csatToInsert, false); //some will fail if csat already exists
    }
    
    /**
    * @description Updates the Case's version of the CSAT fields when status = 'Submitted' for reporting purposes
    */
    public static void updateCaseCSATFields(Map<Id,CSAT_Survey__c> csatsOldMap, List<CSAT_Survey__c> csatsNew) {
        List<CSAT_Survey__c> csats = new List<CSAT_Survey__c> ();
        List<Id> caseIds = new List<Id>();
        Map<Id,Case> caseMap = new Map<Id,Case>();
        List<Case> cases = new List<Case>();
        
        for(CSAT_Survey__c csat : csatsNew) {
            if(csatsOldMap.get(csat.Id).Status__c != 'Submitted' && csat.Status__c == 'Submitted') {
                caseIds.add(csat.Case__c);
            }

        }
        if(caseIds.size() > 0) { 
            for (Case cs : [SELECT Id, CX_Friendly_Welcoming_Score_Q1__c, CX_UnderstandsNeeds_Score_Q2__c, CX_MetNeeds_Score_Q3__c, CX_EasySimple_Score_Q4__c, CX_FeelValued_Score_Q5__c,
                             CX_Service_Comments_Q6__c, CX_Trust_Score_Q7__c, CX_Repurchase_Score_Q8__c, CX_Net_Promoter_Score_Q9__c, CX_Advocacy_Comments_Q10__c,
                             CX_Agent_Score_Q1_2__c, CX_Overall_Score_Q1_5__c, CX_Last_Modified_Date__c, CX_Created_By_Name__c, CX_Created_By_Location__c
                             FROM Case
                             WHERE Id in :caseIds]) {
                caseMap.put(cs.Id, cs);
            }
                        
            for(CSAT_Survey__c csat : csatsNew) {
                system.debug('@@@csat.LastModifiedDate: ' + csat.LastModifiedDate);
                system.debug('@@@csat.Created_By_Name__c: ' + csat.Created_By_Name__c);
            
                Case csatCase = caseMap.get(csat.Case__c);
                csatCase.CX_Friendly_Welcoming_Score_Q1__c = csat.CX_Friendly_Welcoming_Score_Q1__c;
                csatCase.CX_UnderstandsNeeds_Score_Q2__c = csat.CX_UnderstandsNeeds_Score_Q2__c;
                csatCase.CX_MetNeeds_Score_Q3__c = csat.CX_MetNeeds_Score_Q3__c;
                csatCase.CX_EasySimple_Score_Q4__c = csat.CX_EasySimple_Score_Q4__c;
                csatCase.CX_FeelValued_Score_Q5__c = csat.CX_FeelValued_Score_Q5__c;
                csatCase.CX_Service_Comments_Q6__c = csat.Q_ConsumerCareTeamFeedback__c;
                csatCase.CX_Trust_Score_Q7__c = csat.CX_Trust_Score_Q7__c;
                csatCase.CX_Repurchase_Score_Q8__c = csat.CX_Repurchase_Score_Q8__c;
                csatCase.CX_Net_Promoter_Score_Q9__c = csat.CX_Net_Promoter_Score_Q9__c;
                csatCase.CX_Advocacy_Comments_Q10__c = csat.Q_ExplainReasonForScore__c;
                csatCase.CX_Agent_Score_Q1_2__c = csat.CX_Agent_Score_Q1_2__c;
                csatCase.CX_Overall_Score_Q1_5__c = csat.CX_Overall_Score_Q1_5__c;
                csatCase.CX_Last_Modified_Date__c = csat.LastModifiedDate;
                csatCase.CX_Created_By_Name__c = csat.Created_By_Name__c;
                csatCase.CX_Created_By_Location__c = csat.Created_By_Location__c;
                cases.add(csatCase);
            }

            if(cases.size() > 0) {
                update cases;
            }
        }
    }
    
}