src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CCM_Initial_Pull__c</fullName>
        <label>CCM Initial Pull</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact_s_Email_Bounced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be updated with a Workflow when a contact&apos;s email bounces.</description>
        <label>Contact&apos;s Email Bounced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_to_CCM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to CCM</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_Line_1__c</fullName>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <label>Primary Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <label>Primary State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_ContactHelperTest.cls
/**
* @author: Chris Southworth
* @date: 05/30/2014
* @description:  Test class for sf_ContactHelper.cls
*/

@isTest
private class sf_ContactHelperTest {
	
	@isTest static void flagCasesForBouncedContactEmailsTest() {
		Contact con = new Contact();
		con.LastName = 'TestLastName';
		con.FirstName = 'TestFirstName';
		con.Primary_Address_Line_1__c = 'Test Address';
		con.Primary_City__c = 'City';
		con.Primary_State_Province__c = 'ST';
		con.Primary_Postal_Code__c = '11111';
		con.EmailBouncedDate = null;
		insert con;

		Case caseRecord = new Case();
		caseRecord.Contact_s_Email_Bounced__c = false;
		caseRecord.ContactId = con.Id;
		caseRecord.Contact = con;
		insert caseRecord;

		Test.startTest();

			con.EmailBouncedDate = System.now();
			update con;

			caseRecord = [SELECT Id, Contact_s_Email_Bounced__c FROM Case WHERE Id =:CaseRecord.Id];
			System.assertEquals(true, caseRecord.Contact_s_Email_Bounced__c, 'Contact Bounced flag should be true on case');

			con.EmailBouncedDate = null;
			update con;

			caseRecord = [SELECT Id, Contact_s_Email_Bounced__c FROM Case WHERE Id =:CaseRecord.Id];
			System.assertEquals(false, caseRecord.Contact_s_Email_Bounced__c, 'Contact Bounced flag should be true on case');

		Test.stopTest();

	}
	
	/**
	* @author: Archana Sethuraman
	* @date: 08/29/2014
	* @description: 
	*	When a contact related to a case gets updated, update the Sent to CCM field on case to true
	* US428
	* 
	* DEPRECATED. replaced by synchronous process on contact info page.
	*/
	/*@isTest static void updateCaseTest() {
		
		List<Contact> contactList = new List<Contact>();
		for (Integer i =0; i <200;i++) {
			contactList.add(sf_TestDataUtility.createContact());
		}
		insert contactList;
		
		List<Case> caseList = new List<Case>();
		datetime timestamp = Datetime.now();
		for (Contact c: contactList) {
			Case caseRec = new Case(
				contactId = c.Id,
				ccm_initial_pull__c = timestamp
			);
			caseList.add(caseRec);
		}
		insert caseList;
		
		Test.startTest();

			for (Contact c: contactList) {
				c.FirstName = 'test';
			}
         
         update contactList;
			
			caseList = [
				SELECT 
					Sent_To_CCM__C  
				FROM 
					Case 
				WHERE 
					Id in: caseList 
				and 
					Sent_To_CCM__c =: true];

		Test.stopTest();

	}*/
	
}