src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Received Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <fields>
        <fullName>Level_3__c</fullName>
        <description>This is the 3rd level</description>
        <label>Level 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Path__c</fullName>
        <description>This is the full path for the product starting at Brand</description>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Level_3__c</fullName>
        <label>Level 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_CaseHighlightsPanelExtTest.cls
/**
* @author: Oleg Rikkers
* @date: 07/10/2014
*
* @description: 
* Test class
*/


@isTest
private class sf_CaseHighlightsPanelExtTest {
	@isTest static void testWithoutCase () {
		Case c = new Case ();
		sf_CaseHighlightsPanelExt ext = new sf_CaseHighlightsPanelExt (new ApexPages.StandardController (c));
	}

	@isTest static void testWithCase () {

		Case c = new Case ();
        c.Country__c = 'United States of America';
        c.Language__c = 'English-US';
        c.Status = 'Closed';
        c.Received_Date__c = System.now();
        insert c;

        Global_Product__c p = new Global_Product__c ();
        p.Path__c = 'test/test';
        insert p;
                
        Global_Comment_Code__c gcc = new Global_Comment_Code__c ();
        insert gcc;

        Local_Product__c lp = new Local_Product__c ();
        lp.Global_Product__c = p.Id;
        lp.Name = 'Test1';
        insert lp;
        
        Local_Product__c lp2 = new Local_Product__c ();
        lp2.Global_Product__c = p.Id;
        lp2.Name = 'Test2';
        insert lp2;
        
        Local_Product__c lp3 = new Local_Product__c ();
        lp3.Global_Product__c = p.Id;
        lp3.Name = 'Test3';
        insert lp3;

        Local_Comment_Code__c lcc = new Local_Comment_Code__c ();
        lcc.Global_Comment_Code__c = gcc.Id; 
        lcc.Level_3__c = 'TestLevel3-1';
        insert lcc;
        
        Local_Comment_Code__c lcc2 = new Local_Comment_Code__c ();
        lcc2.Global_Comment_Code__c = gcc.Id; 
        lcc2.Level_3__c = 'TestLevel3-2';
        insert lcc2;
        
        Local_Comment_Code__c lcc3 = new Local_Comment_Code__c ();
        lcc3.Global_Comment_Code__c = gcc.Id; 
        lcc3.Level_3__c = 'TestLevel3-3';
        insert lcc3;
        
		List<Case_Product__c> cpList = new List<Case_Product__c>();
        for (Integer i=0; i<3; i++) {
        	Case_Product__c cp = new Case_Product__c ();
        	cp.Case__c = c.Id;
        	cp.Local_Product__c = lp.Id;
        	cpList.add(cp);
        }
        Case_Product__c cp2 = new Case_Product__c();
        cp2.Case__c = c.Id;
        cp2.Local_Product__c = lp2.Id;
        cpList.add(cp2);
        
        Case_Product__c cp3 = new Case_Product__c();
        cp3.Case__c = c.Id;
        cp3.Local_Product__c = lp3.Id;
        cpList.add(cp3);
        
        insert cpList;

		List<Case_Comment_Code__c> cccList = new List<Case_Comment_Code__c>();
        for (Integer i=0; i<3; i++) {
        	Case_Comment_Code__c ccc = new Case_Comment_Code__c ();
	        ccc.Case__c = c.Id;
	        ccc.Case_Product__c = [SELECT Id FROM Case_Product__c LIMIT 1].Id;
	        ccc.Local_Comment_Code__c = lcc.Id;
	        cccList.add(ccc);
        }
        
    	Case_Comment_Code__c ccc2 = new Case_Comment_Code__c ();
        ccc2.Case__c = c.Id;
        ccc2.Case_Product__c = [SELECT Id FROM Case_Product__c LIMIT 1].Id;
        ccc2.Local_Comment_Code__c = lcc2.Id;
        cccList.add(ccc2);
        
    	Case_Comment_Code__c ccc3 = new Case_Comment_Code__c ();
        ccc3.Case__c = c.Id;
        ccc3.Case_Product__c = [SELECT Id FROM Case_Product__c LIMIT 1].Id;
        ccc3.Local_Comment_Code__c = lcc3.Id;
        cccList.add(ccc3);
        
        insert cccList;

        Test.startTest();

        sf_CaseHighlightsPanelExt ext = new sf_CaseHighlightsPanelExt (new ApexPages.StandardController (c));
        ext.getBrands();
        ext.getComments();
        //ext.getProducts();

        Test.stopTest();

	}
}