src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metadata_Survey_Trigger__c.object
<CustomObject>
    <description>This object will store information from the Global Product and Global Comment Code that will be used to trigger the correct survey.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Fieldset__c</fullName>
        <label>Survey Fieldset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Metadata Survey Trigger</label>
    <nameField>
        <displayFormat>MTN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Survey Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Safety_Assessment_Survey__c.object
<CustomObject>
    <description>Holds the questions(fields) and responses(field values) for all Adverse Event surveys.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>This is the Case that generated this AE Survey</description>
        <inlineHelpText>Please pick the case to which this survey relates to.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>AE_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Metadata_Survey_Trigger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metadata Survey Trigger</label>
        <referenceTo>Metadata_Survey_Trigger__c</referenceTo>
        <relationshipName>AE_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Owned by GSSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Safety Assessment Survey</label>
    <nameField>
        <displayFormat>SAS-{0000000}</displayFormat>
        <label>Safety Assessment Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Safety Assessment Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Comment_Product__c.object
<CustomObject>
    <description>A many to many relationship object between Safety Assessment Survey and Case Product.</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Survey Comment Products</relationshipLabel>
        <relationshipName>Survey_Comment_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <formula>CASESAFEID(Safety_Assessment_Survey__r.Case__c)</formula>
        <label>Case</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Safety_Assessment_Survey__c</fullName>
        <label>Safety Assessment Survey</label>
        <referenceTo>Safety_Assessment_Survey__c</referenceTo>
        <relationshipLabel>Survey Comment Products</relationshipLabel>
        <relationshipName>Survey_Comment_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <formula>Case_Product__r.Local_Product__r.Translated_Path__c</formula>
        <label>Translated Path</label>
        <type>Text</type>
    </fields>
    <label>Survey Comment Product</label>
    <nameField>
        <displayFormat>SCP-{0000}</displayFormat>
        <label>Survey Comment Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Comment Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_CaseSASQuestionsExtTest.cls
/*

Test class 

@author 	Oleg Rikkers
@date 		07/30/2014

*/

@isTest

private class sf_CaseSASQuestionsExtTest {
	public static testmethod void testController (){
		
		Profile agentProfile = [SELECT Id, Name FROM Profile WHERE Name = 'EU1 User'];
		User agentUser = new User(alias = 'agent', email='testAgent@test.com',
						emailencodingkey='UTF-8', firstname='Test', lastname='User', languagelocalekey='en_US',
						localesidkey='en_US', profileid = agentProfile.id,
						timezonesidkey='America/Los_Angeles', username='guest@testpkg.com');
		insert agentUser;
		
		System.runAs(agentUser){
			Test.StartTest();
				Case c = new Case ();
				c.Country__c = 'TestCountry';
				insert c;
				        
				Global_Product__c gp = new Global_Product__c();
				insert gp;
        		
				Local_Product__c lp = new Local_Product__c();
				lp.Name = 'Test';
				lp.Country__c = 'Test';
				lp.Translated_Path__c = 'Test';
				lp.Global_Product__c = gp.Id;
				insert lp;
				
				Case_Product__c cp = new Case_Product__c();
				cp.Case__c = c.Id;
				cp.Local_Product__c = lp.Id;
				cp.Status__c = 'Received';
				insert cp;
				
				Metadata_Survey_Trigger__c mst = new Metadata_Survey_Trigger__c ();
				mst.Survey_Fieldset__c = 'test';

				insert mst;

				Safety_Assessment_Survey__c sas = new Safety_Assessment_Survey__c ();
				sas.Metadata_Survey_Trigger__c = mst.Id;
				sas.Case__c = c.Id;
				insert sas;

				Survey_Comment_Product__c scp = new Survey_Comment_Product__c ();
				scp.Case_Product__c = cp.Id;
				scp.Safety_Assessment_Survey__c = sas.Id;
				insert scp;

				sf_CaseSASQuestionsExt ext = new sf_CaseSASQuestionsExt (new ApexPages.StandardController (c));
				ext.mstId = mst.Id;
				ext.sasId = sas.Id;

				ext.addSymptom();
				ext.removeSymptom();

				ext.getSurveyProducts();
				ext.getFieldSetMap();
				ext.createNewSas();
				ext.saveAllSas();
				ext.cloneSAS();
				
			
			Test.StopTest();
		}
	}
}