src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_1__c</fullName>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>This is the Country in the Mailing address</description>
        <label>Primary Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <label>Primary Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <label>Primary State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Fulfillment_Order__c.object
<CustomObject>
    <description>The Fulfillment Order object houses order details for Cases requiring a fulfillment order.  The Fulfillment Order represents the ‘Shopping Cart’ of items that complete a single order related to a Case.  The design supports the ability for a case to contain multiple Fulfillment Orders.  Fulfillment Orders can be both manually fulfilled or sent via integration to the P&amp;G Hermes application.  Fulfillment Orders contain a status field to indicate status of the current order.</description>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Comment Code</label>
        <referenceTo>Case_Comment_Code__c</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fulfillment Order</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Fulfillment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fulfillment_Order_Line_Item__c.object
<CustomObject>
    <description>The Fulfillment Order Line Item object has a master-detail relationship to the Fulfillment Order, and represents an individual item added to the Fulfillment Order ‘Shopping Cart’.  Fulfillment Order Line Items contain a lookup relationship to the Fulfillment Item table to associate an active item to the Line Item.  A custom search UI for fulfillment Items will run from the Fulfillment Order page layout to return available items.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Fulfillment Order Line Items</relationshipLabel>
        <relationshipName>Fulfillment_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Order__c</fullName>
        <label>Fulfillment Order</label>
        <referenceTo>Fulfillment_Order__c</referenceTo>
        <relationshipLabel>Fulfillment Order Line Items</relationshipLabel>
        <relationshipName>Fulfillment_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fulfillment Order Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000000}</displayFormat>
        <label>Fulfillment Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_FulfillmentOrderSubTabControllerTest.cls
/**
* @author: asethuraman@salesforce.com
* @date: 09/11/2014
* @description:  Test Class for  sf_FulfillmentOrderSubTabController
* order button
*/

@isTest
private class sf_FulfillmentOrderSubTabControllerTest {


  static testmethod void testCreateNewFulfilmentOrder() {
    
    Contact contactRec = sf_TestDatautility.createContact();
    contactRec.Primary_Address_Line_1__c = '123 Test Street';
    contactRec.Primary_City__c = 'Chicago';
    contactRec.Primary_State_Province__c = 'Illinois';
    contactRec.Primary_Postal_Code__c = '60661';
    contactRec.Primary_Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA;
    insert contactRec;
    Case caseRec = new Case ( contactId = contactRec.Id, Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA);
    insert caseRec;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    sf_FulfillmentOrderSubtabController.ReturnResults nextPage = sf_FulfillmentOrderSubtabController.createNewFulfillmentOrder(caseRec.Id);
    Test.stopTest();
    
    System.assertNotEquals(nextPage.returnURL,null);
  }
  
  static testmethod void testCreateNewFulfilmentOrderWithCaseProduct() {
    
    Contact contactRec = sf_TestDatautility.createContact();
    contactRec.Primary_Address_Line_1__c = '123 Test Street';
    contactRec.Primary_City__c = 'Chicago';
    contactRec.Primary_State_Province__c = 'Illinois';
    contactRec.Primary_Postal_Code__c = '60661';
    contactRec.Primary_Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA;
    insert contactRec;
    
    Case caseRec = new Case ( contactId = contactRec.Id, Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA);
    insert caseRec;
    
    sf_TestDataUtility.setupProducts(1);
    sf_TestDataUtility.setupComments(1);
    
    Case_Product__c cp = new Case_Product__c ();
      cp.Case__c = caseRec.Id;
      cp.Local_Product__c = [SELECT Id FROM Local_Product__c LIMIT 1].Id;
      insert cp;

      Case_Comment_Code__c ccc = new Case_Comment_Code__c ();
      ccc.Case__c = caseRec.Id;
      ccc.Case_Product__c = cp.Id;
      ccc.Local_Comment_Code__c = [SELECT Id FROM Local_Comment_Code__c LIMIT 1].Id;
      insert ccc;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    sf_FulfillmentOrderSubtabController.ReturnResults nextPage = sf_FulfillmentOrderSubtabController.createNewFulfillmentOrder(caseRec.Id);
    Test.stopTest();
    
    System.assertNotEquals(nextPage.returnURL,null);
  }
  
  static testmethod void testCreateNewFulfilmentOrderContactError() {
    
    
    Case caseRec = new Case ( Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA);
    insert caseRec;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    
    Test.setCurrentPage(Page.sf_FulfillmentOrderSubtab);
    sf_FulfillmentOrderSubtabController.ReturnResults nextPage = sf_FulfillmentOrderSubtabController.createNewFulfillmentOrder(caseRec.Id);
    Test.stopTest();
    
    System.assertEquals(nextPage.returnURL,null);
    
    List<Apexpages.Message> msgs = ApexPages.getMessages();
    System.assertEquals(nextPage.errorMessage,sf_FulfillmentOrderSubtabController.CONTACT_ERROR);
  }
  
  static testmethod void testCreateNewFulfilmentOrderAddrError() {
    
    Contact contactRec = sf_TestDatautility.createContact();
    insert contactRec;
    
    Case caseRec = new Case ( contactId = contactRec.Id,Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA);
    insert caseRec;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    
    Test.setCurrentPage(Page.sf_FulfillmentOrderSubtab);
    sf_FulfillmentOrderSubtabController.ReturnResults nextPage = sf_FulfillmentOrderSubtabController.createNewFulfillmentOrder(caseRec.Id);
    Test.stopTest();
    
    System.assertEquals(nextPage.returnURL,null);
    
    List<Apexpages.Message> msgs = ApexPages.getMessages();
    System.assertEquals(nextPage.errorMessage,sf_FulfillmentOrderSubtabController.ADDRESS_ERROR);
  }
  
  static testmethod void testCreateNewFulfilmentOrderCountryError() {
    
    Contact contactRec = sf_TestDatautility.createContact();
     contactRec.Primary_Address_Line_1__c = '123 Test Street';
    contactRec.Primary_City__c = 'Chicago';
    contactRec.Primary_State_Province__c = 'Illinois';
    contactRec.Primary_Postal_Code__c = '60661';
    contactRec.Primary_Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA;
    insert contactRec;
    
    Case caseRec = new Case ( contactId = contactRec.Id,Country__c = 'Greece');
    insert caseRec;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    
    Test.setCurrentPage(Page.sf_FulfillmentOrderSubtab);
    sf_FulfillmentOrderSubtabController.ReturnResults nextPage = sf_FulfillmentOrderSubtabController.createNewFulfillmentOrder(caseRec.Id);
    Test.stopTest();
    
    System.assertEquals(nextPage.returnURL,null);
    
    List<Apexpages.Message> msgs = ApexPages.getMessages();
    System.assertEquals(nextPage.errorMessage,sf_FulfillmentOrderSubtabController.COUNTRY_ERROR);
  }
  
  static testmethod void testGetFulfillmentOrders() {
    
    Contact contactRec = sf_TestDatautility.createContact();
     contactRec.Primary_Address_Line_1__c = '123 Test Street';
    contactRec.Primary_City__c = 'Chicago';
    contactRec.Primary_State_Province__c = 'Illinois';
    contactRec.Primary_Postal_Code__c = '60661';
    contactRec.Primary_Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA;
    insert contactRec;
    
    Case caseRec = new Case ( contactId = contactRec.Id,Country__c = 'Greece');
    insert caseRec;
    
    List<Fulfillment_Order__c> fulfillmentOrders = new List<Fulfillment_Order__c>();
    for (Integer i = 0; i < 200; i++) {
      Fulfillment_Order__c fo = sf_TestDataUtility.createFFOrder(caseRec.Id);
      fulfillmentOrders.add(fo);
    }
    insert fulfillmentOrders;
     
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    
    
    List<Fulfillment_Order__c> fOrders= fOrder.getFulfillmentOrders();
    System.assertEquals(forders.size(),200);
    Test.stopTest();
    
    
  }
  
  static testmethod void testGetFulfillmentOrderLineItems() {
    
    Contact contactRec = sf_TestDatautility.createContact();
     contactRec.Primary_Address_Line_1__c = '123 Test Street';
    contactRec.Primary_City__c = 'Chicago';
    contactRec.Primary_State_Province__c = 'Illinois';
    contactRec.Primary_Postal_Code__c = '60661';
    contactRec.Primary_Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA;
    insert contactRec;
    
    Case caseRec = new Case ( contactId = contactRec.Id,Country__c = 'Greece');
    insert caseRec;
    
    List<Fulfillment_Order__c> fulfillmentOrders = new List<Fulfillment_Order__c>();
    for (Integer i = 0; i < 200; i++) {
      Fulfillment_Order__c fo = sf_TestDataUtility.createFFOrder(caseRec.Id);
      fulfillmentOrders.add(fo);
    }
    insert fulfillmentOrders;
     
    List<Fulfillment_Order_Line_Item__c> fOrderLineItems = new List<Fulfillment_Order_Line_Item__c>();
    for (Fulfillment_Order__c fo: fulfillmentOrders) {
      
      fOrderLineItems.add(sf_TestDataUtility.createFFOrderLineItem(fo.Id));
    }
    insert fOrderLineItems;
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    
    
    List<Fulfillment_Order_Line_Item__c> fOrderLines= fOrder.getFulfillmentOrderLineItems();
    System.assertEquals(forderLines.size(),200);
    Test.stopTest();
    
    
  }
  
  static testmethod void testAddFulfillmentOrderLineItems() {
    
    Contact contactRec = sf_TestDatautility.createContact();
     contactRec.Primary_Address_Line_1__c = '123 Test Street';
    contactRec.Primary_City__c = 'Chicago';
    contactRec.Primary_State_Province__c = 'Illinois';
    contactRec.Primary_Postal_Code__c = '60661';
    contactRec.Primary_Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA;
    insert contactRec;
    
    Case caseRec = new Case ( contactId = contactRec.Id,Country__c = sf_Constants.COUNTRY_UNITED_STATES_AMERICA);
    insert caseRec;
    
    Fulfillment_Order__c fo = sf_TestDataUtility.createFFOrder(caseRec.Id);
    
    insert fo;
     
    
    ApexPages.StandardController sc = new ApexPages.StandardController(caseRec);
    sf_FulfillmentOrderSubtabController fOrder = new sf_FulfillmentOrderSubtabController(sc);
    
    Test.startTest();
    Test.setCurrentPage(Page.sf_FulfillmentOrderSubtab);
    System.currentPageReference().getParameters().put('fOrder', fo.Id);
    
    sf_FulfillmentOrderSubtabController.ReturnResults nextPage = sf_FulfillmentOrderSubtabController.addFulfillmentLineItem(fo.Id);
    
    Test.stopTest();
    System.assertNotEquals(nextPage.returnURL,null);
    
  }
}