src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>NA</fullName>
        <active>true</active>
        <businessProcess>Country Defaults</businessProcess>
        <description>NA Cases</description>
        <label>NA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                    <default>true</default>
                    <label>United States of America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fulfillment_Order__c.object
<CustomObject>
    <description>The Fulfillment Order object houses order details for Cases requiring a fulfillment order.  The Fulfillment Order represents the ‘Shopping Cart’ of items that complete a single order related to a Case.  The design supports the ability for a case to contain multiple Fulfillment Orders.  Fulfillment Orders can be both manually fulfilled or sent via integration to the P&amp;G Hermes application.  Fulfillment Orders contain a status field to indicate status of the current order.</description>
    <fields>
        <fullName>Above_Monetary_Threshold__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If &quot;True&quot; indicates creator or last user to modify has exceeded their monetary allowance.</inlineHelpText>
        <label>Above Monetary Threshold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approve_Amount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approve Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Country__c</fullName>
        <formula>TEXT(Case__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fullfillment_Amount_Roll_Up__c</fullName>
        <inlineHelpText>Sums amount of Fulfillment Line Item Monetary Values</inlineHelpText>
        <label>Fullfillment Amount Roll-Up</label>
        <summarizedField>Fulfillment_Order_Line_Item__c.Amount_Currency__c</summarizedField>
        <summaryForeignKey>Fulfillment_Order_Line_Item__c.Fulfillment_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Keep_Amount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Keep Amount?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fulfillment Order</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Fulfillment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fulfillment_Order_Line_Item__c.object
<CustomObject>
    <description>The Fulfillment Order Line Item object has a master-detail relationship to the Fulfillment Order, and represents an individual item added to the Fulfillment Order ‘Shopping Cart’.  Fulfillment Order Line Items contain a lookup relationship to the Fulfillment Item table to associate an active item to the Line Item.  A custom search UI for fulfillment Items will run from the Fulfillment Order page layout to return available items.</description>
    <fields>
        <fullName>Amount_Currency__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Fulfillment Order Line Items</relationshipLabel>
        <relationshipName>Fulfillment_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Order__c</fullName>
        <label>Fulfillment Order</label>
        <referenceTo>Fulfillment_Order__c</referenceTo>
        <relationshipLabel>Fulfillment Order Line Items</relationshipLabel>
        <relationshipName>Fulfillment_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Keep_Amount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Keep Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>CR</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DD</fullName>
                </value>
                <value>
                    <fullName>EL</fullName>
                </value>
                <value>
                    <fullName>ET</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FU</fullName>
                </value>
                <value>
                    <fullName>GI</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MP</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>RC</fullName>
                </value>
                <value>
                    <fullName>RE</fullName>
                </value>
                <value>
                    <fullName>RL</fullName>
                </value>
                <value>
                    <fullName>RP</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fulfillment Order Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000000}</displayFormat>
        <label>Fulfillment Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Monetary_Threshold__c</fullName>
        <description>Assigned Fulfillment Order Threshold</description>
        <label>Monetary Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FulfillmentUtilityTest.cls
/**
* @author: Chris Doyle
* @date: 02/11/2016
* @description: New code coverage class for SF_FulfillmentUtility.cls
*/
@isTest
public class FulfillmentUtilityTest {
    
    @testSetup
    Static void fulfillmentSetup() {
        Profile p = sf_FulfillmentOrderCtrlTest.createProfile();
        User userObj = sf_FulfillmentOrderCtrlTest.createUserFFUserOne(p);
        User userObjTwo = sf_FulfillmentOrderCtrlTest.createUserFFUserTwo(p);
        
        System.runAs(userObj){
            CustomSettingDataFactory.countryRegionSetup();
            Contact conObj = sf_FulfillmentOrderCtrlTest.createContact();
            Case caseObj = sf_FulfillmentOrderCtrlTest.createCase(conObj);

            //Brazil case and Contact
            Contact conObj2 = createBrazilContact();
            Case caseObj2 = createBrazilCase(conObj2);

        }
    }
    
    //Rule Criteria - Fullfillment_Amount_Roll_Up__c > CreatedBy.Monetary_Threshold__c
    static testMethod void FFUtilTest1(){

        case c = [SELECT id, ownerid FROM CASE LIMIT 1];
        user u = [SELECT id from User where UserName='Under@threshold.com' LIMIT 1];

        System.runAs(u){
            system.assertequals(u.id, c.OwnerId);
            
            test.startTest();
            sf_FulfillmentOrderCtrlTest.createTestDataCommentsProducts(c); //GP, LP, GCC, LCC, CP, PCC, CCC
            sf_FulfillmentOrderCtrlTest.createFulFillmentOrder(c); //FO, FOLI
            Fulfillment_Order_Line_Item__c foli = [SELECT id, Fulfillment_Order__c FROM Fulfillment_Order_Line_Item__c LIMIT 1];
            Fulfillment_Order__c fo = [SELECT id, status__c FROM Fulfillment_Order__c where id =: foli.Fulfillment_Order__c];
            System.assertEquals ( 'Draft', fo.Status__c); 
            
            test.stopTest();
        }
    }
    
    //Rule Criteria - AND ( Above_Monetary_Threshold__c ,(Fullfillment_Amount_Roll_Up__c < CreatedBy.Monetary_Threshold__c ),ISPICKVAL(Status__c,"Draft"))
    static testMethod void FFUtilTest2(){
        
        case c = [SELECT id, ownerid FROM CASE LIMIT 1];
        user underThreshold = [SELECT id from User where UserName='Under@threshold.com' LIMIT 1];
        test.startTest();
        
        Fulfillment_Order__c fo = new Fulfillment_Order__c();
        Fulfillment_Order_Line_Item__c foli = new Fulfillment_Order_Line_Item__c();
        System.runAs(underThreshold){
            system.assertequals(underThreshold.id, c.OwnerId);
            sf_FulfillmentOrderCtrlTest.createTestDataCommentsProducts(c); //GP, LP, GCC, LCC, CP, PCC, CCC
            sf_FulfillmentOrderCtrlTest.createFulFillmentOrder(c); //FO, FOLI
            
            foli = [SELECT id, Fulfillment_Order__c FROM Fulfillment_Order_Line_Item__c LIMIT 1];
            
            foli.Type__c = 'ET';
            foli.Quantity__c = 1;
            foli.Amount_Currency__c = 90.00;
            foli.Keep_amount__c = TRUE;
            
            update foli;
            
            fo = [SELECT id, status__c, Approve_Amount__c FROM Fulfillment_Order__c where id =: foli.Fulfillment_Order__c];

            System.assertEquals ( 'Open', fo.Status__c); 

        }
        test.stopTest();
    } 

    static testmethod void FFUtilTest3(){

        case c = [SELECT id, ownerid FROM CASE WHERE Country__c = 'United States of America' LIMIT 1];

        case c2 = [SELECT id, ownerid FROM Case WHERE Country__c = 'Brazil' LIMIT 1];

        user underThreshold = [SELECT id from User where UserName='Under@threshold.com' LIMIT 1];
        test.startTest();

        System.runAs(underThreshold){
            sf_FulfillmentOrderCtrlTest.createTestDataCommentsProducts(c); //GP, LP, GCC, LCC, CP, PCC, CCC

            list<Fulfillment_Order__c> listFO = new list<Fulfillment_Order__c>();
            Fulfillment_Order__c FF1 = new Fulfillment_Order__c(
                case__c = c.id
            );
            listFO.add(FF1);

            Fulfillment_Order__c FF2 = new Fulfillment_Order__c(
                case__c = c2.id
            );
            listFO.add(FF2);

            insert listFO;

            list<Fulfillment_Order_Line_Item__c> listLineItem = new list<Fulfillment_Order_Line_Item__c>();
            Fulfillment_Order_Line_Item__c FFLI1 = new Fulfillment_Order_Line_Item__c(
                
                fulfillment_Order__c = FF1.id,
                Case__c = c.id,
                Type__c = 'ET',
                Quantity__c = 1,
                Amount_Currency__c = 90.00,
                Keep_amount__c = TRUE

            );
            listLineItem.add(FFLI1);


            Fulfillment_Order_Line_Item__c FFLI2 = new Fulfillment_Order_Line_Item__c(
                
                fulfillment_Order__c = FF2.id,
                Case__c = c.id,
                Type__c = 'ET',
                Quantity__c = 1,
                Amount_Currency__c = 995.00,
                Keep_amount__c = TRUE

            );
            listLineItem.add(FFLI2);

            insert listLineItem;
            
            Fulfillment_Order__c fo = [SELECT id, status__c, Approve_Amount__c, Case_Country__c FROM Fulfillment_Order__c WHERE Case_Country__c = 'United States of America'];

            System.assertEquals ( 'Open', fo.Status__c); 

            Fulfillment_Order__c fo2 = [SELECT id, status__c, Approve_Amount__c, Case_Country__c FROM Fulfillment_Order__c WHERE Case_Country__c = 'Brazil'];

            System.assertEquals('Open', fo2.Status__c);
        }

        test.stopTest();

    }

    public static Case createBrazilCase(Contact conObj2){
        Case c2 = new Case();
        c2.Status = 'Open';
        c2.country__c = 'Brazil';
        c2.Language__c = 'English-US';
        c2.Contact_Center__c = 'NA';
        c2.ContactId = conObj2.Id;
        c2.Origin = 'Phone';
        c2.Brand__c='TestBrand';
        c2.Segment__c='TestSegment';
        insert c2;        
        return c2;
    }

    public static Contact createBrazilContact(){
        Contact conObj2 = new Contact();
        conObj2.FirstName='TestBrazil';
        conObj2.LastName='TestBrazil';
        conObj2.Country__c='Brazil';
        conObj2.Salutation='Mr.';
        insert conObj2;        
        return conObj2;
    }

    public static Case createChinaCase(Contact conObj3){
        Case c3 = new Case();
        c3.Status = 'Open';
        c3.country__c = 'Brazil';
        c3.Language__c = 'English-US';
        c3.Contact_Center__c = 'NA';
        c3.ContactId = conObj3.Id;
        c3.Origin = 'Phone';
        c3.Brand__c='TestBrand';
        c3.Segment__c='TestSegment';
        insert c3;        
        return c3;
    }

    public static Contact createChinaContact(){
        Contact conObj3 = new Contact();
        conObj3.FirstName='TestBrazil';
        conObj3.LastName='TestBrazil';
        conObj3.Country__c='Brazil';
        conObj3.Salutation='Mr.';
        insert conObj3;
        return conObj3;
    }
    
}