src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/triggerToggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Toggles supported triggers off/on as required.
*Note* Field names must match Trigger name.</description>
    <fields>
        <fullName>AccountTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Account Trigger</description>
        <inlineHelpText>Toggle for Account Trigger</inlineHelpText>
        <label>AccountTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseCommentCodeTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for CaseCommentCodeTrigger</description>
        <inlineHelpText>Toggle for CaseCommentCodeTrigger</inlineHelpText>
        <label>CaseCommentCodeTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseContactTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for CaseContactTrigger__c Trigger</description>
        <inlineHelpText>Toggle for CaseContactTrigger__c Trigger</inlineHelpText>
        <label>CaseContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Case Trigger</description>
        <inlineHelpText>Toggle for Case Trigger</inlineHelpText>
        <label>CaseTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContactTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Contact Trigger</description>
        <inlineHelpText>Toggle for Contact Trigger</inlineHelpText>
        <label>ContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FulfillmentOrderLineItem__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for FulfillmentOrderLineItem Trigger</description>
        <inlineHelpText>Toggle for FulfillmentOrderLineItem Trigger</inlineHelpText>
        <label>FulfillmentOrderLineItem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FulfillmentOrder__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for FulfillmentOrder Trigger</description>
        <inlineHelpText>Toggle for FulfillmentOrder Trigger</inlineHelpText>
        <label>FulfillmentOrder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SafetyAssessmentSurvey__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for SAS Trigger</description>
        <inlineHelpText>Toggle for SAS Trigger</inlineHelpText>
        <label>SafetyAssessmentSurvey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sf_EmailMessage__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for EmailMessage Trigger</description>
        <inlineHelpText>Toggle for EmailMessage Trigger</inlineHelpText>
        <label>sf_EmailMessage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sf_TaskTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Task Trigger</description>
        <inlineHelpText>Toggle for Task Trigger</inlineHelpText>
        <label>sf_TaskTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>triggerToggle</label>
</CustomObject>

src/classes/checkRecursive_Test.cls
@isTest
public class checkRecursive_Test {
    
    @testSetup
    static void dataSetup(){
        CustomSettingDataFactory.triggerToggleSetup();
    }
    
    @isTest
    static void triggerToggleAllTest(){
        //Check all supported triggers are enabled first
		system.assertEquals(True, checkRecursive.triggerStatus('AccountTrigger__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('CaseCommentCodeTrigger__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('CaseContactTrigger__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('CaseTrigger__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('ContactTrigger__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('FulfillmentOrder__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('FulfillmentOrderLineItem__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('SafetyAssessmentSurvey__c'));
 		system.assertEquals(True, checkRecursive.triggerStatus('sf_EmailMessage__c'));
		system.assertEquals(True, checkRecursive.triggerStatus('sf_TaskTrigger__c'));
		
		test.startTest();
        	//Toggle all supported triggers off
			checkRecursive.toggleAllTriggers(False);
            system.assertEquals(False, checkRecursive.triggerStatus('AccountTrigger__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('CaseCommentCodeTrigger__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('CaseContactTrigger__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('CaseTrigger__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('ContactTrigger__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('FulfillmentOrder__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('FulfillmentOrderLineItem__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('SafetyAssessmentSurvey__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('sf_EmailMessage__c'));
            system.assertEquals(False, checkRecursive.triggerStatus('sf_TaskTrigger__c'));
        	
        	//Toggle all supported triggers back on
        	checkRecursive.toggleAllTriggers(True);
            system.assertEquals(True, checkRecursive.triggerStatus('AccountTrigger__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('CaseCommentCodeTrigger__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('CaseContactTrigger__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('CaseTrigger__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('ContactTrigger__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('FulfillmentOrder__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('FulfillmentOrderLineItem__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('SafetyAssessmentSurvey__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('sf_EmailMessage__c'));
            system.assertEquals(True, checkRecursive.triggerStatus('sf_TaskTrigger__c'));        
		test.stopTest();      
    }
    
    @isTest
    static void triggerStatusEnabled_Test(){
        test.startTest();
        	system.assertEquals(True, checkRecursive.triggerStatus('caseTrigger__c'));
        test.stopTest();
    }
    
	@isTest
    static void triggerStatusDisabled_Test(){
        TriggerToggle__c tt = TriggerToggle__c.getInstance();
        tt.caseTrigger__c = false;
        upsert tt;
        
        test.startTest();
        	system.assertEquals(False, checkRecursive.triggerStatus('caseTrigger__c'));
        test.stopTest();
    }
    
    @isTest
    static void checkRecursive_isCaseInsert_Test(){
        Case testCase = new Case(
            Country__c = 'United States of America'
        );
        test.startTest();
        	insert testCase;
            system.assertEquals(True, checkRecursive.newCase);
        test.stopTest();
    }

}