src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is going to be the First Level Identifying the Type of Comment</description>
        <label>Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Complaints Other</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Product Quality Complaint</fullName>
                </value>
                <value>
                    <fullName>Testimonial</fullName>
                </value>
                <value>
                    <fullName>Unable to Classify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IPMS__c.object
<CustomObject>
    <description>This object holds the IPMS information</description>
    <fields>
        <fullName>Local_Product__c</fullName>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>IPMS</relationshipLabel>
        <relationshipName>IPMS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPMS</label>
    <nameField>
        <label>IPMS Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is the first level indicating the type of the comment code</description>
        <externalId>true</externalId>
        <label>Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Comment_Code__c.object
<CustomObject>
    <description>This hosts the Product and Comment Code Associations.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Global Comment Code that is linked to the Global Product related to this record.</description>
        <inlineHelpText>This is the Global Comment Code that is linked to the Global Product related to this record.</inlineHelpText>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Product Comment Codes</relationshipLabel>
        <relationshipName>Product_Comment_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Global Product associated with this record</description>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipLabel>Product Comment Codes (Global Product)</relationshipLabel>
        <relationshipName>Product_Comment_Codes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Comment Code</label>
    <nameField>
        <displayFormat>PCC-{0000}</displayFormat>
        <label>Product Comment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Comment Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_PopOutProductSearchConsoleCompTest.cls
@isTest
private class sf_PopOutProductSearchConsoleCompTest {
	
    public static testMethod void testAddProductComment () {

    	Case c = new Case ();
    	c.Country__c = 'China';
    	c.Language__c = 'Chinese';
    	insert c;

        Global_Product__c gp = new Global_Product__c();
        //gp.Name = 'test product';
        insert gp;

    	List <Local_Product__c> lpl = new List <Local_Product__c> ();

    	for (Integer i=0; i<200; i++) {
    		Local_Product__c lp = new Local_Product__c ();
	    	lp.Name = 'tester' + i;
	    	lp.Country__c = 'China';
	    	lp.Translated_Path__c = 'tester path ' + i;
            lp.Global_Product__c = gp.Id;

	    	lpl.add(lp);
    	}

    	insert lpl;

    	Global_Comment_Code__c gcc = new Global_Comment_Code__c ();
    	insert gcc;

    	Local_Comment_Code__c cc = new Local_Comment_Code__c ();
    	cc.Level_1__c = 'TestLevel1';
    	cc.Level_2__c = 'TestLevel2';
    	//cc.Name = 'test';
    	cc.Global_Comment_Code__c = gcc.Id;
    	cc.Translated_Language__c = 'Chinese';
    	cc.Inactive__c = false;
    	insert cc;
    	
    	Product_Comment_Code__c pcc = new Product_Comment_Code__c();
    	pcc.Global_Comment_Code__c = gcc.Id;
    	pcc.Global_Product__c = gp.Id;
    	pcc.Global_Product_Brand__c = 'TestBrand';
    	pcc.Global_Product_Segment__c = 'TestSegment';
    	insert pcc;

    	System.assertEquals(200, [SELECT Id FROM Local_Product__c].size(), 'Product was not created.');

    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_PopOutProductSearchConsoleCompCtrl ctrl = new sf_PopOutProductSearchConsoleCompCtrl (sc);

    	Test.startTest();

    	//verify object check
    	System.assertEquals('Case', sf_PopOutProductSearchConsoleCompCtrl.checkObjectId(c.Id), 'checkObjectId not returning Case');
    	
    	//verify case query by caseId
    	ctrl.caseId = c.Id;
    	ctrl.setCaseId();
    	System.assertEquals(ctrl.caseId, ctrl.caseRecord.Id, 'Case Id not set');

    	//verify language check
    	String caseLanguage = sf_PopOutProductSearchConsoleCompCtrl.getCaseLanguage(c.Id);
    	System.assertEquals('Chinese', caseLanguage, 'Case Language not set');
    	
    	//Verify product search results
		Id [] productResults = new Id[1];
   		productResults[0] = lpl[0].Id;
		Test.setFixedSearchResults(productResults);
    	List <sObject> lpList = sf_PopOutProductSearchConsoleCompCtrl.doSoslSearch('test', 'China', false);
    	System.assertEquals(1, lpList.size(), 'Search did not return expected results');
    	
    	//verify case comment code search
		Id [] commentResults = new Id[1];
   		commentResults[0] = cc.Id;
		Test.setFixedSearchResults(commentResults);
    	List <sObject> ccList = sf_PopOutProductSearchConsoleCompCtrl.doCaseCommentSoslSearch(gp.Id, 'TestBrand', 'TestSegment', 'test', 'China', c.Language__c, 'TestLevel1', 'TestLevel2');
    	//List <sObject> ccList2 = sf_PopOutProductSearchConsoleCompCtrl.doCaseCommentSoslSearch('', 'test', 'China', caseLanguage, 'TestLevel1', 'TestLevel2');
    	System.assertEquals(1, ccList.size(), 'Comment Code Search did not return expected results');

		//verify adding product
    	sf_PopOutProductSearchConsoleCompCtrl.addProduct([SELECT Id FROM Local_Product__c LIMIT 1].Id, c.Id);
    	System.assertEquals(1, [SELECT Id FROM Case_Product__c].size(), 'Product was not added.');
    	
    	//verify adding comment code
    	ctrl.refreshCaseProducts();
    	ctrl.localProductId = [SELECT Id FROM Case_Product__c LIMIT 1].Id;
    	sf_PopOutProductSearchConsoleCompCtrl.addCaseCommentCode(c.Id, cc.Id, ctrl.localProductId);
    	System.assertEquals(1, [SELECT Id FROM Case_Comment_Code__c].size(), 'Case Comment was not added.');
    	
    	//verify removing case comment code
    	ctrl.refreshCaseProducts();
    	ctrl.commentCodeId = [SELECT Id FROM Case_Comment_Code__c LIMIT 1].Id;
    	ctrl.removeCommentCode();
    	System.assertEquals(0, [SELECT Id FROM Case_Comment_Code__c].size(), 'Case Comment was not removed.');

    	//verify removing case product
    	ctrl.removeCaseProduct();
    	System.assertEquals(0, [SELECT Id FROM Case_Product__c].size(), 'Case Product was not removed.');

    	Test.stopTest();
    }


    public static testMethod void testExceptions () {

    	Case c = new Case ();
    	c.Country__c = 'China';
    	insert c;

    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_PopOutProductSearchConsoleCompCtrl ctrl = new sf_PopOutProductSearchConsoleCompCtrl (sc);

    	Test.startTest();

    	ctrl.removeCommentCode();
    	ctrl.removeCaseProduct();
    
    	ctrl.localProductId = 'sdas';
    	ctrl.commentCodeId = 'sdasd';
    	
    	ctrl.removeCommentCode();
    	ctrl.removeCaseProduct();

    	Test.stopTest();
    }	
    
    public static testMethod void testFilteringAndDictionary(){
    	Case c = new Case ();
    	c.Country__c = 'China';
    	c.Language__c = 'Chinese';
    	insert c;

        Global_Product__c gp = new Global_Product__c();
        insert gp;

    	Local_Product__c lp = new Local_Product__c ();
	    lp.Name = 'tester';
	    lp.Country__c = 'China';
	    lp.Translated_Path__c = 'tester path 1';
        lp.Global_Product__c = gp.Id;
    	insert lp;

    	Global_Comment_Code__c gcc = new Global_Comment_Code__c ();
    	insert gcc;

    	Local_Comment_Code__c lcc = new Local_Comment_Code__c();
    	lcc.Level_1__c = 'TestLevel1';
    	lcc.Level_2__c = 'TestLevel2';
    	lcc.Translated_Language__c = 'Chinese';
    	//cc.Name = 'test';
    	lcc.Global_Comment_Code__c = gcc.Id;
    	insert lcc;
    	
    	Product_Comment_Code__c pcc = new Product_Comment_Code__c();
    	pcc.Global_Comment_Code__c = gcc.Id;
    	pcc.Global_Product__c = gp.Id;
    	pcc.Global_Product_Brand__c = 'TestBrand';
    	pcc.Global_Product_Segment__c = 'TestSegment';
    	insert pcc;

    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_PopOutProductSearchConsoleCompCtrl ctrl = new sf_PopOutProductSearchConsoleCompCtrl (sc);

    	Test.startTest();

    	//verify object check
    	System.assertEquals('Case', sf_PopOutProductSearchConsoleCompCtrl.checkObjectId(c.Id), 'checkObjectId not returning Case');
    	
    	//Set filters
    	ctrl.levelOne = 'TestLevel1';
    	ctrl.levelTwo = 'TestLevel2';
    	
    	//verify case query by caseId
    	ctrl.caseId = c.Id;
    	ctrl.setCaseId();
    	System.assertEquals(ctrl.caseId, ctrl.caseRecord.Id, 'Case Id not set');
    	
    	//verify Map of filters are populated
    	System.assertEquals(true, ctrl.optionMap.size() > 0, 'Option Map is empty.');
    	List<SelectOption> levelOneOptions = ctrl.getLevelOneList();
    	System.assertEquals(true, levelOneOptions.size() > 0, 'Level 1 filter is empty');
    	
    	//Add a product and Add comment code through dictionary
    	sf_PopOutProductSearchConsoleCompCtrl.addProduct(lp.Id, c.Id);
    	ctrl.dictionaryProductId = [SELECT Id FROM Case_Product__c LIMIT 1].Id;
 		ctrl.addSelectedCommentCode();
 		System.assertEquals(1, [SELECT Id FROM Case_Comment_Code__c].size(), 'Case Comment was not added.');
 		
 		//Verify dictionary product name is found
 		ctrl.refreshCaseProducts();
 		ctrl.caseProductIndex = 0;
    	ctrl.openCommentCodeDictionary();
    	System.assertEquals('tester', ctrl.dictionaryProduct.Local_Product__r.Name, 'Dictionary Product Name not found');
    	
    	//verify comment code filtering by product
    	ctrl.globalProductId = gp.Id;
    	ctrl.levelOne = 'TestLevel1';
    	ctrl.levelTwo = 'TestLevel2';
    	ctrl.refreshCodeFilterList();
    	System.assertEquals(1, ctrl.localCodes.size(), 'Comment Code Filtering by Global Product results invalid');
    	
    	//verify sort direction flips to DESC
    	ctrl.sortBy = 'Level_1__c';
    	ctrl.lastSort = 'Level_1__c';
    	ctrl.sortDirection = 'ASC';
    	ctrl.setSortDirection();
    	System.assertEquals('DESC', ctrl.sortDirection, 'SortDirection should be DESC');
    	
    	//verify sort direction flips to ASC
    	ctrl.setSortDirection();
    	System.assertEquals('ASC', ctrl.sortDirection, 'SortDirection should be ASC');
    	
    	//verify sort resets on new field selection
    	ctrl.sortBy = 'Level_2__c';
    	ctrl.setSortDirection();
    	System.assertEquals('ASC', ctrl.sortDirection, 'SortDirection should be ASC');
    	System.assertEquals('Level_2__c', ctrl.lastSort, 'lastSort should be Level_2__c');
    	
    	//coverage for filter change
    	ctrl.globalProductId = '';
    	ctrl.levelOne = 'TestLevel1';
    	ctrl.levelTwo = 'TestLevel2';
    	ctrl.refreshCodeFilterList();
    	ctrl.filterByLevel1();
    	System.assertEquals('', ctrl.levelTwo, 'LevelTwo filter should be blank');

		Test.stopTest();
    }
    
    public static testMethod void testGtinAndIpmsSearch(){
    	Case c = new Case ();
    	c.Country__c = 'China';
    	c.Language__c = 'Chinese';
    	insert c;

        Global_Product__c gp = new Global_Product__c();
        insert gp;

    	Local_Product__c lp = new Local_Product__c ();
	    lp.Name = 'tester';
	    lp.Country__c = 'China';
	    lp.Translated_Path__c = 'tester path 1';
        lp.Global_Product__c = gp.Id;
        lp.GTIN_Number__c = '0000012345';
    	insert lp;
    	
    	Local_Product__c lp2 = new Local_Product__c ();
	    lp2.Name = '12345';
	    lp2.Country__c = 'China';
	    lp2.Translated_Path__c = 'tester path 1';
        lp2.Global_Product__c = gp.Id;
        lp2.GTIN_Number__c = '0000012345';
    	insert lp2;
    	
    	IPMS__c ipms = new IPMS__c();
    	ipms.Name = '12345';
    	ipms.Local_Product__c = lp.Id;
    	insert ipms;
    	
    	ApexPages.StandardController sc = new ApexPages.StandardController (c);
    	sf_PopOutProductSearchConsoleCompCtrl ctrl = new sf_PopOutProductSearchConsoleCompCtrl (sc);
    
    	test.startTest();
    		
    		//coverage for GTIN search
    		Id [] gtinResults = new Id[1];
       		gtinResults[0] = lp.Id;
    		Test.setFixedSearchResults(gtinResults);
    		List<Local_Product__c> gtinProdList = sf_PopOutProductSearchConsoleCompCtrl.doSoslSearch('12345', 'China', true);
    		System.assertEquals(1, gtinProdList.size(), 'Invalid results returned for GTIN search.');

			//Test IPMS search
			Id [] ipmsResults = new Id[3];
			ipmsResults[0] = ipms.Id;
       		ipmsResults[1] = lp.Id;
       		ipmsResults[2] = lp2.Id;
    		Test.setFixedSearchResults(ipmsResults);			
			List<Local_Product__c> ipmsProdList = sf_PopOutProductSearchConsoleCompCtrl.doSoslSearch('12345', 'China', false);
    		System.assertEquals(2, ipmsProdList.size(), 'Invalid results returned for IPMS search.');

    	test.stopTest();
    	
    }
}