src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <label>Case Comment Code</label>
        <summaryForeignKey>Case_Comment_Code__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Product_Return_Status__c</fullName>
        <description>Hidden field used by workflows to manage sending of reminders for product returns</description>
        <label>Product Return Reminder Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>WE</fullName>
        <active>true</active>
        <businessProcess>Country Defaults</businessProcess>
        <description>WE Cases</description>
        <label>WE</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Comment_Code__c.object
<CustomObject>
    <description>Master Detail relationship from Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master Detail relationship from Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Comment Code</label>
        <referenceTo>Local_Comment_Code__c</referenceTo>
        <relationshipLabel>Case Comment Code</relationshipLabel>
        <relationshipName>Case_Comment_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Comment Code</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Product__c.object
<CustomObject>
    <description>Junction table that relates a Product to a Case</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <label>ACR Info</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Local_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Product</label>
        <referenceTo>Local_Product__c</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_available_for_return__c</fullName>
        <label>Product available for return</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes - Product is available</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>No - Product cannot be returned</fullName>
                </value>
                <value>
                    <fullName>Unknown - Written communication</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Production_Code__c</fullName>
        <inlineHelpText>What is the production code?</inlineHelpText>
        <label>Production Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Requested - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Product Requested - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Not Received after 3 Attempts</fullName>
                </value>
                <value>
                    <fullName>Consumer has sent</fullName>
                </value>
                <value>
                    <fullName>Product Received</fullName>
                </value>
                <value>
                    <fullName>No - Consumer unwilling to return</fullName>
                </value>
                <value>
                    <fullName>No - Product discarded/unavailable</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 1</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 2</fullName>
                </value>
                <value>
                    <fullName>Photo - Attempt 3</fullName>
                </value>
                <value>
                    <fullName>Photo Received</fullName>
                </value>
                <value>
                    <fullName>Photo Sufficient</fullName>
                </value>
                <value>
                    <fullName>Product/Photo no longer needed</fullName>
                </value>
                <value>
                    <fullName>Photo Not Received</fullName>
                </value>
                <value>
                    <fullName>Photo - Final Attempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fulfillment_Item__c.object
<CustomObject>
    <description>This object provides a list of all active or inactive fulfillment items available in P&amp;G.  CR Agents will perform a search of this table to select the appropriate fulfillment items to send to Consumers.  Fulfillment item master data will be loaded my P&amp;G regional admins.</description>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Fulfillment Item</label>
    <nameField>
        <label>Fulfillment Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fulfillment_Order__c.object
<CustomObject>
    <description>The Fulfillment Order object houses order details for Cases requiring a fulfillment order.  The Fulfillment Order represents the ‘Shopping Cart’ of items that complete a single order related to a Case.  The design supports the ability for a case to contain multiple Fulfillment Orders.  Fulfillment Orders can be both manually fulfilled or sent via integration to the P&amp;G Hermes application.  Fulfillment Orders contain a status field to indicate status of the current order.</description>
    <fields>
        <fullName>ACR_Info__c</fullName>
        <description>For recording matching ACR info</description>
        <inlineHelpText>For recording matching ACR info</inlineHelpText>
        <label>ACR Info</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Comment_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Comment Code</label>
        <referenceTo>Case_Comment_Code__c</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Product</label>
        <referenceTo>Case_Product__c</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Fulfillment Orders</relationshipLabel>
        <relationshipName>Fulfillment_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fulfillment Order</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Fulfillment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fulfillment_Order_Line_Item__c.object
<CustomObject>
    <description>The Fulfillment Order Line Item object has a master-detail relationship to the Fulfillment Order, and represents an individual item added to the Fulfillment Order ‘Shopping Cart’.  Fulfillment Order Line Items contain a lookup relationship to the Fulfillment Item table to associate an active item to the Line Item.  A custom search UI for fulfillment Items will run from the Fulfillment Order page layout to return available items.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Fulfillment Order Line Items</relationshipLabel>
        <relationshipName>Fulfillment_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fulfillment Item</label>
        <referenceTo>Fulfillment_Item__c</referenceTo>
        <relationshipLabel>Fulfillment Order Line Items</relationshipLabel>
        <relationshipName>Fulfillment_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Order__c</fullName>
        <label>Fulfillment Order</label>
        <referenceTo>Fulfillment_Order__c</referenceTo>
        <relationshipLabel>Fulfillment Order Line Items</relationshipLabel>
        <relationshipName>Fulfillment_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fulfillment Order Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000000}</displayFormat>
        <label>Fulfillment Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Criticality__c</fullName>
        <description>This indicates if a Comment Code falls under Critical or Non-Critical</description>
        <inlineHelpText>If Checked indicates a critical type else non-critical</inlineHelpText>
        <label>Criticality</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Non-Critical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/trg_AutoComRuleHelper_Test.cls
/*
 * These tests were written for the trigger based approach
 * for newer ACR object
 * 
 */ 
@isTest
private class trg_AutoComRuleHelper_Test {
	
    private static final String COUNTRY = 'United States of America';
    private static final String LANGUAGE = 'English-US';
    private static final String ATTEMPT1 = 'Product Requested - Attempt 1';
    private static final String ATTEMPT2 = 'Product Requested - Attempt 2';
    private static final String ATTEMPT3 = 'Product Requested - Attempt 3';
    private static final String NOTRECEIVED = 'Not Received after 3 Attempts';
    
	@testSetup
    static void dataSetup(){
        checkrecursive.toggleAllTriggers(false);
        AutoComRuleHelper_datasetup_Test.dataSetup();
        checkrecursive.toggleAllTriggers(true);
    }   
    
	/****************************************
     * PRR Attempt 1						*
     ***************************************/
    @isTest
    static void prrFirstAttemptTest(){
        Case testCase = [SELECT Id, ContactId FROM Case WHERE Subject = 'CaseOnly' LIMIT 1];
        Local_Product__c testLP = [SELECT Id FROM Local_Product__c WHERE Name = 'Bag' LIMIT 1];
        Local_Comment_Code__c testCC = [SELECT Id FROM Local_Comment_Code__c WHERE Criticality__c = 'Critical' LIMIT 1];
        Fulfillment_Item__c firstAttemptFI = [SELECT Id FROM Fulfillment_Item__c WHERE SKU__c = '1stAttempt'];  
		
        test.startTest();
            //Create Case Product
            Case_Product__c testCP = new Case_Product__c(
                Case__c = testCase.Id,
                Local_Product__c = testLP.Id,
                Production_Code__c = 'randomvaluehere',
                Product_available_for_return__c = 'Yes - Product is available'     
            );
            insert testCP;
              
            //ChrisM Aug 2016 boolean deprecated
            checkRecursive.ACRprocessedIds.clear();
 
            Case_Comment_Code__c testCCC = new Case_Comment_Code__c(
                Case__c = testCase.Id,
                Local_Comment_Code__c = testCC.Id,
                Case_Product__c = testCP.Id
            );
            insert testCCC;
        
            //Has a FO been created?
            List<Fulfillment_Order__c> foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id ]);
            system.assertEquals(1, foList.size());
            
            //Assert expected FI has been used
            //ORDER BY Id DESC - as createddate not reliable - i.e. created in same second
            Fulfillment_Order_Line_Item__c foli1 = [SELECT Id, Fulfillment_Item__c FROM Fulfillment_Order_Line_Item__c WHERE Fulfillment_Order__c = :foList[0].Id ORDER BY Id DESC];
            system.assertEquals(firstAttemptFI.Id, foli1.Fulfillment_Item__c,'first attempt assert failed');        

        test.stopTest();
    }
    
 	/****************************************
     * PRR Attempt 2						*
     ***************************************/
    @isTest
    static void prrSecondAttemptTest(){
        Case testCase = [SELECT Id, ContactId FROM Case WHERE Subject = 'CaseOnly' LIMIT 1];
        Local_Product__c testLP = [SELECT Id FROM Local_Product__c WHERE Name = 'Bag' LIMIT 1];
        Local_Comment_Code__c testCC = [SELECT Id FROM Local_Comment_Code__c WHERE Criticality__c = 'Critical' LIMIT 1];
        Fulfillment_Item__c firstAttemptFI = [SELECT Id FROM Fulfillment_Item__c WHERE SKU__c = '1stAttempt'];  
        
        checkrecursive.toggleAllTriggers(false);
        	testCase.Product_Return_Status__c = ATTEMPT1;
			update testCase; 
        
            //Create Case Product
            Case_Product__c testCP = new Case_Product__c(
                Case__c = testCase.Id,
                Local_Product__c = testLP.Id,
                Production_Code__c = 'randomvaluehere',
                Product_available_for_return__c = 'Yes - Product is available',
                Status__c = ATTEMPT1
            );
        	insert testCP;
            
            Case_Comment_Code__c testCCC = new Case_Comment_Code__c(
                Case__c = testCase.Id,
                Local_Comment_Code__c = testCC.Id,
                Case_Product__c = testCP.Id
            );
        	insert testCCC;
        checkrecursive.toggleAllTriggers(true);
        
        List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id, Subject FROM EmailMessage WHERE ParentId = : testCase.Id]);
        system.assertEquals(0, caseEmails.size());    
		
        test.startTest();
        	checkRecursive.ACRprocessedIds.clear();
			testCP.Status__c = ATTEMPT2;
            update testCP;
        
            //FO should NOT be created - email sent instead!
            List<Fulfillment_Order__c> foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id]);
            system.assertEquals(0, foList.size(), 'match incorrectly found on second attempt');
            
			caseEmails = new List<EmailMessage>([SELECT Id, Subject FROM EmailMessage WHERE ParentId = : testCase.Id]);
            system.assertEquals(1, caseEmails.size(),'email not sent');    

        test.stopTest();
    }

 	/****************************************
     * PRR Attempt 3						*
     ***************************************/
    @isTest
    static void prrThirdAttemptTest(){
        Case testCase = [SELECT Id, ContactId FROM Case WHERE Subject = 'CaseOnly' LIMIT 1];
        Local_Product__c testLP = [SELECT Id FROM Local_Product__c WHERE Name = 'Bag' LIMIT 1];
        Local_Comment_Code__c testCC = [SELECT Id FROM Local_Comment_Code__c WHERE Criticality__c = 'Critical' LIMIT 1];
        Fulfillment_Item__c firstAttemptFI = [SELECT Id FROM Fulfillment_Item__c WHERE SKU__c = '1stAttempt'];  
        
        checkrecursive.toggleAllTriggers(false);
        	testCase.Product_Return_Status__c = ATTEMPT2;
			update testCase; 
        
            //Create Case Product
            Case_Product__c testCP = new Case_Product__c(
                Case__c = testCase.Id,
                Local_Product__c = testLP.Id,
                Production_Code__c = 'randomvaluehere',
                Product_available_for_return__c = 'Yes - Product is available',
                Status__c = ATTEMPT2
            );
        	insert testCP;
            
            Case_Comment_Code__c testCCC = new Case_Comment_Code__c(
                Case__c = testCase.Id,
                Local_Comment_Code__c = testCC.Id,
                Case_Product__c = testCP.Id
            );
        	insert testCCC;
        checkrecursive.toggleAllTriggers(true);
        
		List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id, Subject FROM EmailMessage WHERE ParentId = : testCase.Id]);
        system.assertEquals(0, caseEmails.size()); 
		
        test.startTest();
        	checkRecursive.ACRprocessedIds.clear();
			testCP.Status__c = ATTEMPT3;
            update testCP;
        
            //FO should NOT be created - email sent instead!
            List<Fulfillment_Order__c> foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id]);
            system.assertEquals(0, foList.size(), 'match incorrectly found on third attempt');
            
			caseEmails = new List<EmailMessage>([SELECT Id, Subject FROM EmailMessage WHERE ParentId = : testCase.Id]);
            system.assertEquals(1, caseEmails.size(),'email not sent');    

        test.stopTest();
    }
    
	/****************************************
     * Represents successful creation of FO	*
     * on 1st, 2nd and 3rd attempts			*
     ***************************************/
	@isTest
    static void productReturnFOTest(){
	//Query records we need
	Case testCase = [SELECT Id, ContactId FROM Case WHERE Subject = 'CaseOnly' LIMIT 1];
	Local_Product__c testLP = [SELECT Id FROM Local_Product__c WHERE Name = 'Bag' LIMIT 1];
	Local_Comment_Code__c testCC = [SELECT Id FROM Local_Comment_Code__c WHERE Criticality__c = 'Critical' LIMIT 1];
    Fulfillment_Item__c firstAttemptFI = [SELECT Id FROM Fulfillment_Item__c WHERE SKU__c = '1stAttempt'];
    Fulfillment_Item__c secondAttemptFI = [SELECT Id FROM Fulfillment_Item__c WHERE SKU__c = '2ndAttempt']; 
        
	//Create Case Product
    Case_Product__c testCP = new Case_Product__c(
        Case__c = testCase.Id,
        Local_Product__c = testLP.Id,
		Production_Code__c = 'randomvaluehere',
		Product_available_for_return__c = 'Yes - Product is available'     
    );
    insert testCP;
    
    //clear Contact email so FOs are sent instead of emails
    Contact testCon = [SELECT Id, Email FROM Contact WHERE Id = :testCase.ContactId];
    testCon.email = '';
    update testCon;
    
    test.startTest();
        
		//ChrisM Aug 2016 boolean deprecated
		checkRecursive.ACRprocessedIds.clear();
        
        //Create Case Comment Code
        Case_Comment_Code__c testCCC = new Case_Comment_Code__c(
            Case__c = testCase.Id,
			Local_Comment_Code__c = testCC.Id,
            Case_Product__c = testCP.Id
            //TBC if other fields need to be set
        );
        insert testCCC;
        
		//Has a FO been created?
        List<Fulfillment_Order__c> foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id ]);
        system.assertEquals(1, foList.size(),'No FO created');
        
		//Assert expected FI has been used
        //ORDER BY Id DESC - as createddate not reliable - i.e. created in same second
        Fulfillment_Order_Line_Item__c foli1 = [SELECT Id, Fulfillment_Item__c FROM Fulfillment_Order_Line_Item__c WHERE Fulfillment_Order__c = :foList[0].Id ORDER BY Id DESC];
        system.assertEquals(firstAttemptFI.Id, foli1.Fulfillment_Item__c,'first attempt FI assert failed');
        
        //Now set CP Status to 'Product Requested - Attempt 2' to fire 2nd Attempt

		//ChrisM Aug 2016 boolean deprecated
		checkRecursive.ACRprocessedIds.clear();
        
        testCP.Status__c = ATTEMPT2;
        update testCP;
        
        //Second FO should be created
		foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id]);
        system.assertEquals(2, foList.size(), 'no match found on second attempt');
        
		//Assert expected FI has been used
        Fulfillment_Order_Line_Item__c foli2 = [SELECT Id, Fulfillment_Item__c FROM Fulfillment_Order_Line_Item__c WHERE Fulfillment_Order__c = :foList[1].Id ORDER BY Id DESC];
        system.assertEquals(secondAttemptFI.Id, foli2.Fulfillment_Item__c,'second attempt FI assert failed');
        
        //Now set CP Status to 'Product Requested - Attempt 3' to fire 3rd Attempt
        
		//ChrisM Aug 2016 boolean deprecated
		checkRecursive.ACRprocessedIds.clear();
        
        testCP.Status__c = ATTEMPT3;
        update testCP;
        
		//Third FO should NOT be created - email sent intead!
		foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id]);
        system.assertEquals(3, foList.size(),'no match found on third attempt');
        
		//Assert expected FI has been used
        Fulfillment_Order_Line_Item__c foli3 = [SELECT Id, Fulfillment_Item__c FROM Fulfillment_Order_Line_Item__c WHERE Fulfillment_Order__c = :foList[2].Id ORDER BY Id DESC];
        system.assertEquals(secondAttemptFI.Id, foli3.Fulfillment_Item__c,'third attempt FI assert failed'); 
   	test.stopTest();
    }
    
	/****************************************
     * Medical QR							*
     ***************************************/
	@isTest
    static void medicalQRTest(){
	//Query records we need
	Case testCase = [SELECT Id, ContactId FROM Case WHERE Subject = 'CaseOnly' LIMIT 1];
        
    test.startTest();
        testCase.Medical_QR_Status__c = 'Questionnaire Requested - Attempt 1';
        update testCase;
        
		//Has a FO been created and no email sent?
        List<Fulfillment_Order__c> foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id ]);
        system.assertEquals(1, foList.size(),'No FO Created error'); 
        
		List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id, Subject FROM EmailMessage WHERE ParentId = : testCase.Id]);
        system.assertEquals(0, caseEmails.size(),'Email has been sent in error');
        
		testCase.Medical_QR_Status__c = 'Questionnaire Requested - Attempt 2';
        update testCase;
        
        //No new FO is created
		foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id ]);
        system.assertEquals(1, foList.size(),'New FO created in error'); 

    test.stopTest();  
    }
    
	/****************************************
     * Fraud Test							*
     ***************************************/
	@isTest
    static void repeaterFraudTest(){
	//Query records we need
	Case testCase = [SELECT Id, ContactId, AccountId FROM Case WHERE Subject = 'CaseOnly' LIMIT 1];
    Contact testCon = [SELECT Id FROM Contact WHERE Id = :testCase.ContactId];
    testCon.Repeater_Status__c = 'Known Repeater';
    update testCon;
    
    test.startTest();
		testCase.Repeater_Case__c = 'Fraudulent Case';
		Update testCase;
        
		//Create FO as ACR has no template name
        List<Fulfillment_Order__c> foList = new List<Fulfillment_Order__c>([SELECT Id, ACR_Info__c FROM Fulfillment_Order__c WHERE Case__c = : testCase.Id ]);
        system.assertEquals(1, foList.size(),'No FO created error');
        
		List<EmailMessage> caseEmails = new List<EmailMessage>([SELECT Id, Subject FROM EmailMessage WHERE ParentId = : testCase.Id]);
        system.assertEquals(0, caseEmails.size(),'Email created when expected FO');

    test.stopTest();
    }
    
}