src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Which Country is the consumer calling from?</description>
        <inlineHelpText>Please select the country where the call originated.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language spoken by the caller</description>
        <inlineHelpText>Please select the correct language.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Internal_Activity__c.object
<CustomObject>
    <description>Object storing agent feedback on articles.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Knowledge_Article_Suggestion_Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(Case__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Internal Activity</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Internal Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_InternalActivityExtTest.cls
@isTest
private class sf_InternalActivityExtTest {
	
	@isTest static void testInit() {
		Internal_Activity__c intAct = new Internal_Activity__c ();
        intAct.Comments__c = 'foo';
        //WR14 Test coverage improvements
        intAct.OwnerId = UserInfo.getUserId();
        
		Test.setCurrentPage(Page.sf_InternalActivity);
		ApexPages.currentPage().getParameters().put('retURL', 'www.google.com');
		ApexPages.currentPage().getParameters().put('clone', '1');


		sf_InternalActivityExt ext = new sf_InternalActivityExt (new ApexPages.StandardController (intAct));
		ext.saveAndReply();
		ext.save();
		ext.internalTypeItems();
	}

	@isTest static void testInitExisting() {

		Case c = new Case ();
    	c.Country__c = 'China';
    	c.Language__c = 'Chinese';
    	insert c;

		Internal_Activity__c intAct = new Internal_Activity__c ();
		intAct.Comments__c = 'foo';
		intAct.Case__c = c.Id;
		insert intAct;

		Test.setCurrentPage(Page.sf_InternalActivity);
		ApexPages.currentPage().getParameters().put('retURL', 'www.google.com');
        ApexPages.currentPage().getParameters().put('reply', '1');
        ApexPages.currentPage().getParameters().put('id', intAct.Id);

		sf_InternalActivityExt ext = new sf_InternalActivityExt (new ApexPages.StandardController (intAct));
		ext.save();
	}
	
}