src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_s_Email_Bounced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be updated with a Workflow when a contact&apos;s email bounces.</description>
        <label>Contact&apos;s Email Bounced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_Line_1__c</fullName>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_2__c</fullName>
        <label>Primary Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_3__c</fullName>
        <label>Primary Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>This is the Country in the Mailing address</description>
        <label>Primary Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <label>Primary Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <label>Primary State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_BatchBouncedEmailTest.cls
/*
* @author: Chris Southworth
* @date: 05/30/2014
* @description:  Test class for sf_BatchBouncedEmail.cls
*/

@isTest
private class sf_BatchBouncedEmailTest {
	public static testmethod void sf_BatchBouncedEmailTest() {

		Contact con = new Contact();
		con.LastName = 'TestLastName';
		con.FirstName = 'TestFirstName';
		con.Primary_Address_Line_1__c = 'Test Address 2';
		con.Primary_Address_Line_2__c = 'Test Address 2';
		con.Primary_Address_Line_3__c = 'Test Address 3';
		con.Primary_City__c = 'TestCity';
		con.Primary_Country__c = 'TestCountry';
		con.Primary_State_Province__c = 'TestState';
		con.Primary_Postal_Code__c = '12345';
		con.EmailBouncedDate = System.now();
		insert con;

		Case caseRecord = new Case();
		caseRecord.Contact_s_Email_Bounced__c = false;
		caseRecord.ContactId = con.Id;
		caseRecord.Contact = con;
		insert caseRecord;

		Test.startTest();

			sf_BatchBouncedEmail batch = new sf_BatchBouncedEmail();
			Database.executeBatch(batch);

		Test.stopTest();

		caseRecord = [SELECT Id, Contact_s_Email_Bounced__c FROM Case WHERE Id =:CaseRecord.Id];
		System.assertEquals(true, caseRecord.Contact_s_Email_Bounced__c, 'Contact Bounced flag should be true on case');
		
	}
}