src/objects/Contact_Us_Brand__c.object
<CustomObject>
    <description>This object is for configuring the brand options for the contact us page.</description>
    <label>Contact Us Brand</label>
    <nameField>
        <label>Contact Us Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Us_Brand_Language__c.object
<CustomObject>
    <description>Junction object storing brand- and language-specific settings and translations</description>
    <fields>
        <fullName>Contact_Us_Brand__c</fullName>
        <label>Contact Us Brand</label>
        <referenceTo>Contact_Us_Brand__c</referenceTo>
        <relationshipLabel>Contact Us Brands Languages</relationshipLabel>
        <relationshipName>Contact_Us_Brands_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Us_Language__c</fullName>
        <label>Contact Us Language</label>
        <referenceTo>Contact_Us_Language__c</referenceTo>
        <relationshipLabel>Contact Us Brands Languages</relationshipLabel>
        <relationshipName>Contact_Us_Brands_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Live_Agent_Button_Id__c</fullName>
        <label>Live Agent Button Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Agent_Deployment_Id__c</fullName>
        <label>Live Agent Deployment Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Us Brand Language</label>
    <nameField>
        <displayFormat>CBL-{0000}</displayFormat>
        <label>Contact Us Brand Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Us Brands Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Language__c.object
<CustomObject>
    <description>This object is for configuring the language/countries for the contact us page</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live_Agent_Button_Id__c</fullName>
        <label>Live Agent Button Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Agent_Deployment_Id__c</fullName>
        <label>Live Agent Deployment Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Us Language</label>
    <nameField>
        <label>Contact Us Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ContactUsURL__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>URL to the Contact Us page.</description>
    <fields>
        <fullName>CareHubUrl__c</fullName>
        <description>Site url for care hub</description>
        <label>Care Hub Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>ContactUsURL</label>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/classes/gcr_proChatApiTest.cls
/*
* @author:       Accenture
* @date:         13/10/2016
* @description:  CR392 - Proactive Chat: Test Class for proactive api class
* CHANGE LOG
* DATE          NAME                CHANGE DESCRIPTION
* 13/10/2016    Accenture           Initial Draft
*/
@isTest(SeeAllData = false)
public class gcr_proChatApiTest {
    
    /*
     * @author: 		Accenture
	 * @date: 		 	13/10/2016
	 * @description:  	TEST DATA SETUP METHOD
     */
    @testSetup
    static void setupTestData() {
        gcr_TestUtility.createCustomSettings();
        String brandConLangId = gcr_TestUtility.createContactUsObjectData();
    }

    /*
     * @author: 		Accenture
	 * @date: 		 	13/10/2016
	 * @description:  	TEST METHOD TO TEST PROACTIVE CHAT API IF CARE HUB EXISTS FOR SELECTED BRAND COUNTRY LANGUAGE
     */
    static testmethod void chatApiCareHubTest() {
        // CREATE CARE HUB DATA
        List<sObject> lBrandConLang = [ SELECT Id FROM Contact_Us_Brand_Language__c
                                  		WHERE Contact_Us_Brand__r.Name = :gcr_TestUtility.DEFAULT_BRAND 
                                 			AND Contact_Us_Language__r.Country__c = :gcr_TestUtility.DEFAULT_COUNTRY 
                                 			AND Contact_Us_Language__r.Language__c = :gcr_TestUtility.DEFAULT_LANGUAGE ];
        sObject careHub = gcr_TestUtility.getCareHubData(lBrandConLang.get(0).Id);
        Database.insert(careHub, true);
        List<sObject> lCareHubChannels = gcr_TestUtility.getCareHubChannels(careHub.Id);
        Database.insert(lCareHubChannels, true);
        
        // SET LIVE AGENT MOCK API 
        Test.setMock(HttpCalloutMock.class, new gcr_mockApiClass.gcr_liveAgentButton());
        
        Test.startTest();
        // INSTANTIATE REQUEST
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.requestUri = '/services/apexrest/chatAvailabilityDetail/v1';
        RestContext.request.httpMethod = 'GET';

        // SET REQUEST PARAMETERS
        RestContext.request.params.put('brand', gcr_TestUtility.DEFAULT_BRAND);
        RestContext.request.params.put('country', gcr_TestUtility.DEFAULT_COUNTRY_ISO);
        RestContext.request.params.put('language', gcr_TestUtility.DEFAULT_LANGUAGE_ISO);
        
        gcr_proChatResponse.gcr_availabilityDetail results 
            = (gcr_proChatResponse.gcr_availabilityDetail) gcr_proChatApi.isAgentAvailable();
        Test.stopTest();
        // VALIDATE RESPONSE
        SYSTEM.assertEquals(true, results.withinBusinessHours);
        SYSTEM.assertEquals(true, results.isAgentActive);
        SYSTEM.assertEquals(true, results.isSuccess);
        SYSTEM.assertEquals('http://chatimageurl.com', results.chatImage);
        SYSTEM.assertEquals(ContactUsURL__c.getInstance().CareHubUrl__c
                          + '/gcr_proChatRedirect?brand=' + gcr_TestUtility.DEFAULT_BRAND
                          + '&country=' + gcr_TestUtility.DEFAULT_COUNTRY_ISO
                          + '&language=' + gcr_TestUtility.DEFAULT_LANGUAGE_ISO
                          , results.chatUrl);
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	13/10/2016
	 * @description:  	TEST METHOD TO TEST PROACTIVE CHAT API IF V3 CONFIG EXISTS FOR SELECTED BRAND COUNTRY LANGUAGE
     */
    static testmethod void chatApiV3Test() {
        // SET LIVE AGENT MOCK API 
        Test.setMock(HttpCalloutMock.class, new gcr_mockApiClass.gcr_liveAgentButton());
        
        Test.startTest();
        // INSTANTIATE REQUEST
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.requestUri = 'https://pgconsumersupport.secure.force.com/carehub/services/apexrest/chatAvailabilityDetail/v1';
        RestContext.request.httpMethod = 'GET';

        // SET REQUEST PARAMETERS
        RestContext.request.params.put('brand', gcr_TestUtility.DEFAULT_BRAND);
        RestContext.request.params.put('country', gcr_TestUtility.DEFAULT_COUNTRY_ISO);
        RestContext.request.params.put('language', gcr_TestUtility.DEFAULT_LANGUAGE_ISO);
        // CALL API
        gcr_proChatResponse.gcr_proResponseInterface proChatResp = gcr_proChatApi.isAgentAvailable();
        Test.stopTest();
        // VALIDATE RESPONSE OBJECT TYPE
        SYSTEM.assert(proChatResp instanceof gcr_proChatResponse.gcr_availabilityDetail);
        gcr_proChatResponse.gcr_availabilityDetail results = (gcr_proChatResponse.gcr_availabilityDetail) proChatResp;
        // VALIDATE RESPONSE
        SYSTEM.assertEquals(true, results.withinBusinessHours);
        SYSTEM.assertEquals(true, results.isAgentActive);
        SYSTEM.assertEquals(true, results.isSuccess);
        SYSTEM.assertEquals('http://chatimageurl.com', results.chatImage);
        SYSTEM.assertEquals(ContactUsURL__c.getInstance().URL__c
                          + '/gcr_proChatRedirect?brand=' + gcr_TestUtility.DEFAULT_BRAND
                          + '&country=' + gcr_TestUtility.DEFAULT_COUNTRY_ISO
                          + '&language=' + gcr_TestUtility.DEFAULT_LANGUAGE_ISO
                          , results.chatUrl);
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	17/10/2016
	 * @description:  	TEST METHOD TO TEST PROACTIVE CHAT API IF NO PARAMETERS PASSED TO API
     */
    static testmethod void chatApiInvalidParamsTest() {
        // CREATE CARE HUB DATA
        List<sObject> lBrandConLang = [ SELECT Id FROM Contact_Us_Brand_Language__c
                                  		WHERE Contact_Us_Brand__r.Name = :gcr_TestUtility.DEFAULT_BRAND 
                                 			AND Contact_Us_Language__r.Country__c = :gcr_TestUtility.DEFAULT_COUNTRY 
                                 			AND Contact_Us_Language__r.Language__c = :gcr_TestUtility.DEFAULT_LANGUAGE ];
        sObject careHub = gcr_TestUtility.getCareHubData(lBrandConLang.get(0).Id);
        Database.insert(careHub, true);
        List<sObject> lCareHubChannels = gcr_TestUtility.getCareHubChannels(careHub.Id);
        Database.insert(lCareHubChannels, true);
        
        // SET LIVE AGENT MOCK API 
        Test.setMock(HttpCalloutMock.class, new gcr_mockApiClass.gcr_liveAgentButton());
        
        Test.startTest();
        // INSTANTIATE REQUEST
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.requestUri = '/services/apexrest/chatAvailabilityDetail/v1';
        RestContext.request.httpMethod = 'GET';
		// CALL API
        gcr_proChatResponse.gcr_proResponseInterface proChatResp = gcr_proChatApi.isAgentAvailable();
        Test.stopTest();
        // VALIDATE RESPONSE OBJECT TYPE
		SYSTEM.assert(proChatResp instanceof gcr_proChatResponse.gcr_errorResponse);
        gcr_proChatResponse.gcr_errorResponse results = (gcr_proChatResponse.gcr_errorResponse) proChatResp;
        // VALIDATE RESPONSE
        SYSTEM.assertEquals('INVALID_PARAMETERS', results.errorCode);
        SYSTEM.assertEquals(Label.errMsgNoExpParams, results.errorMessage);
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	17/10/2016
	 * @description:  	TEST METHOD TO TEST PROACTIVE CHAT API IF NO CARE HUB OR V3 FOUND
     */
    static testmethod void chatApiNoWebConfigTest() {
        // CREATE CARE HUB DATA
        List<sObject> lBrandConLang = [ SELECT Id FROM Contact_Us_Brand_Language__c
                                  		WHERE Contact_Us_Brand__r.Name = :gcr_TestUtility.DEFAULT_BRAND 
                                 			AND Contact_Us_Language__r.Country__c = :gcr_TestUtility.DEFAULT_COUNTRY 
                                 			AND Contact_Us_Language__r.Language__c = :gcr_TestUtility.DEFAULT_LANGUAGE ];
        sObject careHub = gcr_TestUtility.getCareHubData(lBrandConLang.get(0).Id);
        Database.insert(careHub, true);
        List<sObject> lCareHubChannels = gcr_TestUtility.getCareHubChannels(careHub.Id);
        Database.insert(lCareHubChannels, true);
        
        // SET LIVE AGENT MOCK API 
        Test.setMock(HttpCalloutMock.class, new gcr_mockApiClass.gcr_liveAgentButton());
        
        Test.startTest();
        // INSTANTIATE REQUEST
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.requestUri = '/services/apexrest/chatAvailabilityDetail/v1';
        RestContext.request.httpMethod = 'GET';

        // SET INVALID REQUEST PARAMETERS
        RestContext.request.params.put('brand', 'brand');
        RestContext.request.params.put('country', 'country');
        RestContext.request.params.put('language', 'language');
		// CALL API
        gcr_proChatResponse.gcr_proResponseInterface proChatResp = gcr_proChatApi.isAgentAvailable();
        Test.stopTest();
        // VALIDATE RESPONSE OBJECT TYPE
		SYSTEM.assert(proChatResp instanceof gcr_proChatResponse.gcr_errorResponse);
        gcr_proChatResponse.gcr_errorResponse results = (gcr_proChatResponse.gcr_errorResponse) proChatResp;
        // VALIDATE RESPONSE
        SYSTEM.assertEquals('CONFIG_NOT_SETUP', results.errorCode);
        SYSTEM.assertEquals(Label.errMsgNoWebConfig, results.errorMessage);
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	17/10/2016
	 * @description:  	TEST METHOD TO TEST PROACTIVE CHAT API IF NO CHAT CONFIG FOUND
     */
    static testmethod void chatApiNoChatConfigTest() {
        // CREATE CARE HUB DATA
        List<sObject> lBrandConLang = [ SELECT Id FROM Contact_Us_Brand_Language__c
                                  		WHERE Contact_Us_Brand__r.Name = :gcr_TestUtility.DEFAULT_BRAND 
                                 			AND Contact_Us_Language__r.Country__c = :gcr_TestUtility.DEFAULT_COUNTRY 
                                 			AND Contact_Us_Language__r.Language__c = :gcr_TestUtility.DEFAULT_LANGUAGE ];
        Contact_Us_Brand_Language__c tempVar = (Contact_Us_Brand_Language__c) lBrandConLang.get(0);
        tempVar.Live_Agent_Button_Id__c = null;
        tempVar.Live_Agent_Deployment_Id__c = null;
        Database.update(lBrandConLang, false);
        
        // SET LIVE AGENT MOCK API 
        Test.setMock(HttpCalloutMock.class, new gcr_mockApiClass.gcr_liveAgentButton());
        
        Test.startTest();
        // INSTANTIATE REQUEST
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.requestUri = '/services/apexrest/chatAvailabilityDetail/v1';
        RestContext.request.httpMethod = 'GET';

        // SET REQUEST PARAMETERS
        RestContext.request.params.put('brand', gcr_TestUtility.DEFAULT_BRAND);
        RestContext.request.params.put('country', gcr_TestUtility.DEFAULT_COUNTRY_ISO);
        RestContext.request.params.put('language', gcr_TestUtility.DEFAULT_LANGUAGE_ISO);
		// CALL API
        gcr_proChatResponse.gcr_proResponseInterface proChatResp = gcr_proChatApi.isAgentAvailable();
        Test.stopTest();
        // VALIDATE RESPONSE OBJECT TYPE
		SYSTEM.assert(proChatResp instanceof gcr_proChatResponse.gcr_errorResponse);
        gcr_proChatResponse.gcr_errorResponse results = (gcr_proChatResponse.gcr_errorResponse) proChatResp;
        // VALIDATE RESPONSE
        SYSTEM.assertEquals('CHAT_NOT_SETUP', results.errorCode);
        SYSTEM.assertEquals(Label.errMsgNoChatConfig, results.errorMessage);
    }
}