src/objects/Contact_Us_Brand__c.object
<CustomObject>
    <description>This object is for configuring the brand options for the contact us page.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>This is the brand that is to be configured.</description>
        <label>Brand</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Contact Us Brand</label>
    <nameField>
        <label>Contact Us Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Us_Brand_Language__c.object
<CustomObject>
    <description>Junction object storing brand- and language-specific settings and translations</description>
    <fields>
        <fullName>Contact_Us_Brand__c</fullName>
        <label>Contact Us Brand</label>
        <referenceTo>Contact_Us_Brand__c</referenceTo>
        <relationshipLabel>Contact Us Brands Languages</relationshipLabel>
        <relationshipName>Contact_Us_Brands_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Us_Language__c</fullName>
        <label>Contact Us Language</label>
        <referenceTo>Contact_Us_Language__c</referenceTo>
        <relationshipLabel>Contact Us Brands Languages</relationshipLabel>
        <relationshipName>Contact_Us_Brands_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Featured_Article_1__c</fullName>
        <description>Featured article to display in 1st (highest) position</description>
        <inlineHelpText>Featured article to display in 1st (highest) position</inlineHelpText>
        <label>Featured Article 1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Featured_Article_2__c</fullName>
        <description>Featured article to display in 2nd position</description>
        <inlineHelpText>Featured article to display in 2nd position</inlineHelpText>
        <label>Featured Article 2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Contact Us Brand Language</label>
    <nameField>
        <displayFormat>CBL-{0000}</displayFormat>
        <label>Contact Us Brand Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Us Brands Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Language__c.object
<CustomObject>
    <description>This object is for configuring the language/countries for the contact us page</description>
    <fields>
        <fullName>Article_Search_Button_Label__c</fullName>
        <label>Article Search Button Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Search_Label__c</fullName>
        <label>Article Search Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Back_to_Results__c</fullName>
        <label>Back to Results</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancel__c</fullName>
        <description>Cancel button label</description>
        <label>Cancel</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Characters_Remaining__c</fullName>
        <description>Text for &quot;xxx characters remaining&quot; dynamic label</description>
        <label>Characters Remaining</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Close_Window__c</fullName>
        <description>Link text to close feedback dialog</description>
        <label>Close Window</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Featured_Articles__c</fullName>
        <label>Featured Articles</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_Intro__c</fullName>
        <description>Intro text on feedback form</description>
        <label>Feedback Intro</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_Thanks__c</fullName>
        <description>Message display after article feedback is submitted</description>
        <label>Feedback Thanks</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_Title__c</fullName>
        <description>Title for feedback form</description>
        <label>Feedback Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Helpful_Links__c</fullName>
        <description>Label for Helpful Links section</description>
        <label>Helpful Links</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Helpful_No__c</fullName>
        <description>Negative response to &quot;Was this article helpful?&quot;</description>
        <label>Helpful No</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Helpful_Prompt__c</fullName>
        <description>Text to ask if an article was helpful</description>
        <label>Helpful Prompt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Helpful_Yes__c</fullName>
        <description>Positive response to &quot;Was this article helpful?&quot;</description>
        <label>Helpful Yes</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Locale_Key__c</fullName>
        <label>Language Locale Key</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next__c</fullName>
        <description>Next Link Label</description>
        <label>Next</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Results__c</fullName>
        <label>No Results</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PKB_Page_Intro__c</fullName>
        <label>PKB Page Intro</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous__c</fullName>
        <description>Previous link label</description>
        <label>Previous</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Placeholder__c</fullName>
        <description>Search placeholder text</description>
        <label>Search Placeholder</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Related__c</fullName>
        <description>Related articles label</description>
        <label>Search Related</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Results__c</fullName>
        <description>Search Results label</description>
        <label>Search Results</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Select_Brand_Label__c</fullName>
        <label>Select Brand Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submit__c</fullName>
        <description>Submit button label</description>
        <label>Submit</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Contact Us Language</label>
    <nameField>
        <label>Contact Us Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FAQ__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>sf_FAQArticleTemplate</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Frequently asked questions and their answers.</description>
    <fields>
        <fullName>Helpful_Links__c</fullName>
        <description>Helpful links for our Customers</description>
        <label>Helpful Links</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <label>FAQ</label>
    <pluralLabel>FAQS</pluralLabel>
</CustomObject>

src/classes/sf_ContactUsLanguageControllerTest.cls
/*
 * Changes:
 * 16-10-2015 Updated to use @testSetup - christopher.macduff@accenture.com
 * 16-10-2015 Updated to include featured articles coverage - christopher.macduff@accenture.com
 * 
*/ 
@isTest
public class sf_ContactUsLanguageControllerTest {
    
    private static Contact_Us_Brand__c defaultBrand;
    private static Contact_Us_Brand__c otherBrand;
    private static Contact_Us_Language__c defaultLanguage;
    private static Contact_Us_Language__c otherLanguage;
    private static Contact_Us_Brand_Language__c defaultBrandDefaultLanguage;
    private static Contact_Us_Brand_Language__c defaultBrandOtherLanguage;

    @testSetup static void setupTestData() {
    	defaultBrand = new Contact_Us_Brand__c (
    	    name = 'Default',
    	    Brand__c = 'P&G'
    	);
        otherBrand = new Contact_Us_Brand__c (
            name = 'Tide',
            Brand__c = 'Tide'
        );
    	insert new list<Contact_Us_Brand__c>{defaultBrand, otherBrand};

    	defaultLanguage = new Contact_Us_Language__c (
    	    name = 'Default',
    	    Country__c = 'United States of America',
    	    Language__c = 'English',
    	    Language_Locale_Key__c = 'en-US',
			Article_Search_Button_Label__c = 'Article Search Button Label',
			Article_Search_Label__c = 'Article Search Label',
			Back_to_Results__c = 'Back to Results',
			Featured_Articles__c = 'Featured Articles',
			PKB_Page_Intro__c = 'PKB Page Intro',
			Search_Related__c = 'Search Related',
			Search_Results__c = 'Search Results',
			Select_Brand_Label__c = 'Select Brand Label',
			Helpful_Prompt__c = 'Helpful Prompt',
			Helpful_Yes__c = 'Helpful Yes',
			Helpful_No__c = 'Helpful No',
			Feedback_Title__c = 'Feedback Title',
			Feedback_Intro__c = 'Feedback Intro',
			Characters_Remaining__c = 'Characters Remaining',
			Submit__c = 'Submit',
			Cancel__c = 'Cancel',
			Search_Placeholder__c = 'Search Placeholder',
			No_Results__c = 'No Results',
			Previous__c = 'Previous',
			Next__c = 'Next',
			Helpful_Links__c = 'Helpful Links',
			Feedback_Thanks__c = 'Feedback Thanks',
			Close_Window__c = 'Close Window'
    	);
        otherLanguage = new Contact_Us_Language__c (
            name = 'US Spanish',
            Country__c = 'United States of America',
            Language__c = 'Spanish',
            Language_Locale_Key__c = 'es',
            Article_Search_Button_Label__c = 'SP Article Search Button Label',
            Article_Search_Label__c = 'SP Article Search Label',
            Back_to_Results__c = 'SP Back to Results',
            Featured_Articles__c = 'SP Featured Articles',
            PKB_Page_Intro__c = 'SP PKB Page Intro',
            Search_Related__c = 'SP Search Related',
            Search_Results__c = 'SP Search Results',
            Select_Brand_Label__c = 'SP Select Brand Label',
            Helpful_Prompt__c = 'SP Helpful Prompt',
            Helpful_Yes__c = 'SP Helpful Yes',
            Helpful_No__c = 'SP Helpful No',
            Feedback_Title__c = 'SP Feedback Title',
            Feedback_Intro__c = 'SP Feedback Intro',
            Characters_Remaining__c = 'SP Characters Remaining',
            Submit__c = 'SP Submit',
            Cancel__c = 'SP Cancel',
            Search_Placeholder__c = 'SP Search Placeholder',
            No_Results__c = 'SP No Results',
            Previous__c = 'SP Previous',
            Next__c = 'SP Next',
            Helpful_Links__c = 'SP Helpful Links',
            Feedback_Thanks__c = 'SP Feedback Thanks',
            Close_Window__c = 'SP Close Window'
        );
        insert new list<Contact_Us_Language__c> { defaultLanguage, otherLanguage };

    	defaultBrandDefaultLanguage = new Contact_Us_Brand_Language__c (
            Featured_Article_1__c = '',
            Featured_Article_2__c = '',
            Featured_Article_3__c = '',
            Featured_Article_4__c = '',
            Featured_Article_5__c = '',
            Display_Summary__c = False,
    	    Contact_Us_Brand__c = defaultBrand.id,
    	    Contact_Us_Language__c = defaultLanguage.id,
			Logo_Hover_Text__c = 'Logo Hover Text',
			Link_URL_Community_Site__c = 'http://example.com',
			Show_Live_Chat_Tab__c = true,
			Age_Capture_Style__c = sf_ContactUsLanguageController.AGE_CAPTURE_MMYYYY,
			Case_Submit_Minimum_Age__c = 18,
			Case_Submit_Ask_gender__c = true,
			Link_URL_Facebook__c = 'http://example.com/facebook',
			Link_URL_Twitter__c = 'http://example.com/twitter',
			Link_URL_Pinterest__c = 'http://example.com/pinterest',
			Link_Hover_Text_Facebook__c = 'Link Hover Text Facebook',
			Link_Hover_Text_Twitter__c = 'Link Hover Text Twitter',
			Link_Hover_Text_Pinterest__c = 'Link Hover Text Pinterest'
    	);

        defaultBrandOtherLanguage = new Contact_Us_Brand_Language__c (
            Featured_Article_1__c = '',
            Featured_Article_2__c = '',
            Featured_Article_3__c = '',
            Featured_Article_4__c = '',
            Featured_Article_5__c = '',
            Display_Summary__c = True,
            Contact_Us_Brand__c = defaultBrand.id,
            Contact_Us_Language__c = otherLanguage.id,
            Logo_Hover_Text__c = 'SP Logo Hover Text',
            Show_Live_Chat_Tab__c = false,
            Age_Capture_Style__c = sf_ContactUsLanguageController.AGE_CAPTURE_RANGES,
            Case_Submit_Minimum_Age__c = 17,
            Case_Submit_Ask_gender__c = false
        );

        insert new list<Contact_Us_Brand_Language__c> { defaultBrandDefaultLanguage, defaultBrandOtherLanguage };

    }

    @isTest
	static void testDefault() {
    	sf_ContactUsLanguageController ctrl = new sf_ContactUsLanguageController(null, null, null);
    	system.assertEquals('en-US', ctrl.languageCode);
    }

    @isTest
	static void testLanguage() {
        sf_ContactUsLanguageController ctrl = new sf_ContactUsLanguageController('Spanish', 'United States of America', null);
        system.assertEquals('es', ctrl.languageCode);
    }

    @isTest
	static void testLanguageGetter() {
        sf_ContactUsLanguageController ctrl = new sf_ContactUsLanguageController('Spanish', 'United States of America', null);
		system.assertEquals( 'SP Article Search Button Label', ctrl.language_config.Article_Search_Button_Label__c);
    }

    @isTest
	static void testBrandLanguage() {
        sf_ContactUsLanguageController ctrl = new sf_ContactUsLanguageController(null, null, 'Default');

		system.assertEquals('Logo Hover Text', ctrl.brand_language_config.Logo_Hover_Text__c);
		system.assert(ctrl.bl_show_facebook_link);
		system.assert(ctrl.bl_show_twitter_link);
		system.assert(ctrl.bl_show_pinterest_link);
		system.assert(ctrl.bl_show_community_tab);
		system.assert(ctrl.bl_show_live_chat_tab);
		system.assert(ctrl.bl_show_age_mmyyyy);
		system.assert(! ctrl.bl_show_age_ranges);
		system.assert(ctrl.bl_show_ask_gender);
		system.assertEquals(18, ctrl.bl_case_minimum_age);
    }

    @isTest
	static void testBrandLanguageOther() {
        otherLanguage = [SELECT Id, Language__c, Country__c FROM Contact_Us_Language__c WHERE Name = 'US Spanish' LIMIT 1];
        sf_ContactUsLanguageController ctrl = new sf_ContactUsLanguageController(otherLanguage.Language__c, otherLanguage.Country__c, 'Default');

        system.assertEquals('SP Logo Hover Text', ctrl.brand_language_config.Logo_Hover_Text__c);
        system.assert(! ctrl.bl_show_facebook_link);
        system.assert(! ctrl.bl_show_twitter_link);
        system.assert(! ctrl.bl_show_pinterest_link);
        system.assert(! ctrl.bl_show_community_tab);
        system.assert(! ctrl.bl_show_live_chat_tab);
        system.assert(! ctrl.bl_show_age_mmyyyy);
        system.assert( ctrl.bl_show_age_ranges);
        system.assert(! ctrl.bl_show_ask_gender);
        system.assertEquals(17, ctrl.bl_case_minimum_age);
    }
    
	@isTest
	static void testFeaturedArticles() {
        otherLanguage = [SELECT Id, Language__c, Country__c,Language_Locale_Key__c FROM Contact_Us_Language__c WHERE Name = 'US Spanish' LIMIT 1];
        sf_ContactUsLanguageController ctrl = new sf_ContactUsLanguageController(otherLanguage.Language__c, otherLanguage.Country__c, 'Default');
        List<pkb_Controller.KnowledgeArticleData> kadList = new List<pkb_Controller.KnowledgeArticleData>(pkb_Controller.getFeaturedArticles());
        system.assertEquals(0, kadList.size());
        
        /*To test properly need to create an article with data categories
         * and update Contact_Us_Brand_Language__c.Featured_Article_1__c
         * to use this article number */
        List<FAQ__kav> kavsToInsert = new List<FAQ__kav>();
        FAQ__kav featuredKA1 = new FAQ__kav(
            Title = 'Featured test Article 1',
            UrlName = 'Featured-test-Article-1',
            Summary = 'This is the summary of the featured test article 1',
            Language = otherLanguage.Language_Locale_Key__c
        );
        kavsToInsert.add(featuredKA1);
        
		FAQ__kav featuredKA2 = new FAQ__kav(
            Title = 'Featured test Article 2',
            UrlName = 'Featured-test-Article-2',
            Summary = 'This is the summary of the featured test article 2',
            Language = otherLanguage.Language_Locale_Key__c
        );
        kavsToInsert.add(featuredKA2);
        insert kavsToInsert;
        
        //Set Data Categories so article will be returned in pkb_controller
        List<FAQ__DataCategorySelection> dcsToInsert = new List<FAQ__DataCategorySelection>();
        FAQ__DataCategorySelection dc1 = new FAQ__DataCategorySelection(
            ParentId = featuredKA1.Id,
            DataCategoryGroupName = 'Brand',
            DataCategoryName = 'Tide'
        );
        dcsToInsert.add(dc1);
        FAQ__DataCategorySelection dc2 = new FAQ__DataCategorySelection(
            ParentId = featuredKA1.Id,
            DataCategoryGroupName = 'Region',
            DataCategoryName = 'United_States'
        );
        dcsToInsert.add(dc2);
        FAQ__DataCategorySelection dc3 = new FAQ__DataCategorySelection(
            ParentId = featuredKA2.Id,
            DataCategoryGroupName = 'Brand',
            DataCategoryName = 'Tide'
        );
        dcsToInsert.add(dc3);
        FAQ__DataCategorySelection dc4 = new FAQ__DataCategorySelection(
            ParentId = featuredKA2.Id,
            DataCategoryGroupName = 'Region',
            DataCategoryName = 'United_States'
        );
        dcsToInsert.add(dc4);        
        insert dcsToInsert;

        //Requery article to get ArticleNumber & KnowledgeArticleId
        featuredKA1 = [SELECT Id, ArticleNumber, KnowledgeArticleId FROM FAQ__kav WHERE Id = :featuredKA1.Id LIMIT 1];
        featuredKA2 = [SELECT Id, ArticleNumber, KnowledgeArticleId FROM FAQ__kav WHERE Id = :featuredKA2.Id LIMIT 1];
        
        //Publish article
        KbManagement.PublishingService.publishArticle(featuredKA1.KnowledgeArticleId, true);
        KbManagement.PublishingService.publishArticle(featuredKA2.KnowledgeArticleId, true);
        
        test.startTest();

        
        //Update brand language object with new article numbers
        Contact_Us_Brand_Language__c cuBrandLang = [SELECT Id FROM Contact_Us_Brand_Language__c WHERE Logo_Hover_Text__c = 'SP Logo Hover Text'];
        cuBrandLang.Featured_Article_1__c = featuredKA1.ArticleNumber;
        cuBrandLang.Featured_Article_2__c = featuredKA2.ArticleNumber;
        cuBrandLang.Featured_Article_3__c = '999999992';
        cuBrandLang.Featured_Article_4__c = '999999993';
        cuBrandLang.Featured_Article_5__c = '999999994';
        update cuBrandLang;

        //Now test controller again and kadList should be
        ctrl = new sf_ContactUsLanguageController(otherLanguage.Language__c, otherLanguage.Country__c, 'Default');
        kadList = new List<pkb_Controller.KnowledgeArticleData>(pkb_Controller.getFeaturedArticles());
        system.assertEquals(true, ctrl.bl_display_featured);
        system.assertEquals(true, ctrl.bl_display_summary);
        system.assertEquals(2, kadList.size());
        test.stopTest();
    }
}