src/objects/Contact_Us_Brand__c.object
<CustomObject>
    <description>This object is for configuring the brand options for the contact us page.</description>
    <label>Contact Us Brand</label>
    <nameField>
        <label>Contact Us Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>BackgroundImgLanding__c</fullName>
        <description>Background image for landing page</description>
        <label>Landing Page Background Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <formula>TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Language__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language</label>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChannelHeader__c</fullName>
        <label>Channel Header</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country picklist from Global Picklist to fetch global picklist values</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Telephony__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Us_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Us Brand</label>
        <referenceTo>Contact_Us_Brand__c</referenceTo>
        <relationshipLabel>Telephony</relationshipLabel>
        <relationshipName>Telephony</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Has_1_Phone_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if the country uses the same phone number for all brands. Note, do not check if country uses the same phone number for multiple brands but not all</inlineHelpText>
        <label>Country Has 1 Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ITFS_Number__c</fullName>
        <label>ITFS Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ITFS_Status__c</fullName>
        <label>ITFS Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Crisis</fullName>
                </value>
                <value>
                    <fullName>Divested</fullName>
                </value>
                <value>
                    <fullName>Spare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albanian</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Armenian</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LocalOperationalHours__c</fullName>
        <label>Local Operational Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Charge_Type__c</fullName>
        <label>Phone Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Toll</fullName>
                </value>
                <value>
                    <fullName>Toll-Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visible_to_contact_us_pages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible to Contact Us Pages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLabelNotVisibleCareHub__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Label Not Visible to Care Hub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>localBrand__c</fullName>
        <label>Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Telephony</label>
    <nameField>
        <displayFormat>Tel-{00000}</displayFormat>
        <label>Telephony Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telephony</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/gcr_callusController.cls
/*
* @author:       Accenture
* @date:         01/06/2016
* @description:  Controller class for call us page component of GCR widget
* DATE					NAME					CHANGE DESCRIPTION
* 01/06/2016			Accenture				Initial Draft
* 10/11/2016			Accenture				Query for Ireland for United Kingdom
* 14/11/2016			Accenture				Get channel content from care hub channel
*/
public class gcr_callusController {    
    public String inBrand { public get; public set; }
    public String inCountry { public get; public set; }
    public String inLanguage { public get; public set; }
    public String channelId { public get; public set; }
    
    public Boolean isRightToLeft { get; set; }
    public GCRChannelContent__c channelContent { public get; private set; }
    
    // PUBLIC VARIABLES
    public String strOperationalHours { public get; private set; }
    public Map<String, List<Telephony__c>> mTelephoneNumbers { public get; private set; }
    public Boolean controlInit { public get {
       if(controlInit == null || !controlInit) init(); return false;
    } private set; }
    public void init() {
        setTelephony();
        getChannelContent();
    }
    
    private void getChannelContent() {
        channelContent = [ SELECT ChannelHeader__c
                          		, CareHub__r.BackgroundImgLanding__c
                           FROM GCRChannelContent__c 
                           WHERE Id = :channelId ];
    }
    
    private void setTelephony() {
        // PATCH FOR UNITED KINGDOM REQUIREMENT
        // GET TELEPHONY NUMBERS FROM UK AND IRELAND IF INCOMING COUNTRY IS UK
        Set<String> sCountry = new Set<String>();
        sCountry.add(inCountry);
        if (inCountry.equalsIgnoreCase('United Kingdom')) {
			sCountry.add('Ireland');
        }

        mTelephoneNumbers = new Map<String, List<Telephony__c>>();
        List<Telephony__c> lTelephony = [ SELECT Id
                                               , ITFS_Number__c
                                               , LocalOperationalHours__c
                                         	   , Phone_Charge_Type__c
                                               , localBrand__c
                                               , Country_Has_1_Phone_Number__c
                                         	   , isLabelNotVisibleCareHub__c
                                          FROM Telephony__c 
                                          WHERE Country__c IN :sCountry
                                            AND Visible_to_contact_us_pages__c = true
                                            AND ITFS_Status__c = 'Active'
                                            AND ITFS_Number__c != null
                                            AND (Country_Has_1_Phone_Number__c = true 
                                                OR (Language__c = :inLanguage
                                                    AND Contact_Us_Brand__r.Name = :inBrand))
                                          ORDER BY isLabelNotVisibleCareHub__c ];
        if(lTelephony != null && !lTelephony.isEmpty()) {
            for(Telephony__c eachTelephony : lTelephony) {
                strOperationalHours = String.isEmpty(strOperationalHours) && eachTelephony.Country_Has_1_Phone_Number__c ? 
                                        eachTelephony.LocalOperationalHours__c : '';
                
                    if (mTelephoneNumbers.get(eachTelephony.localBrand__c) != null) {
                        mTelephoneNumbers.get(eachTelephony.localBrand__c).add(eachTelephony);
                    } else {
                        if (!eachTelephony.isLabelNotVisibleCareHub__c) {
                        	mTelephoneNumbers.put(eachTelephony.localBrand__c, new List<Telephony__c>{eachTelephony});
                        } else {
                            mTelephoneNumbers.put('', new List<Telephony__c>{eachTelephony});
                        }
                    }
            }
            strOperationalHours = String.isEmpty(strOperationalHours) ? lTelephony.get(0).LocalOperationalHours__c : '';
        }      
    }
}