src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_Line_1__c</fullName>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_2__c</fullName>
        <label>Primary Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_3__c</fullName>
        <label>Primary Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>This is the Country in the Mailing address</description>
        <label>Primary Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <label>Primary Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <label>Primary State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this checkbox will cause all related Cases to be updated in order to trigger a pull to CCM.</description>
        <inlineHelpText>Checking this checkbox will cause all related Cases to be updated in order to trigger a pull to CCM.</inlineHelpText>
        <label>Update Cases</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_BatchDeletePiiTest.cls
/*
* @author: John Casimiro
* @date: 02/13/2015
* @description:  Test class for sf_BatchDeletePii.cls
*/
@isTest
private class sf_BatchDeletePiiTest {
	public static testmethod void sf_BatchDeletePiiTest() {

		Contact con = new Contact();
		con.LastName = 'TestLastName';
		con.FirstName = 'TestFirstName';
		con.Primary_Address_Line_1__c = 'Test Address 2';
		con.Primary_Address_Line_2__c = 'Test Address 2';
		con.Primary_Address_Line_3__c = 'Test Address 3';
		con.Primary_City__c = 'TestCity';
		con.Primary_Country__c = 'TestCountry';
		con.Primary_State_Province__c = 'TestState';
		con.Primary_Postal_Code__c = '12345';
		con.Update_Cases__c = TRUE;
		insert con;

		Case caseRecord = new Case();
		caseRecord.ContactId = con.Id;
		caseRecord.Status = 'Closed';
		insert caseRecord;

		System.debug(LoggingLevel.INFO, 'Created Test Case ' + caseRecord);

		Test.startTest();

			sf_BatchDeletePii batch = new sf_BatchDeletePii();
			Database.executeBatch(batch);

		Test.stopTest();

		caseRecord = [SELECT Id, createdDate, LastModifiedDate FROM Case WHERE Id =:CaseRecord.Id];
		//System.assertNotEquals(caseRecord.createdDate, caseRecord.LastModifiedDate, 'Case was not updated');
		System.debug('created date = ' + caseRecord.createdDate);
		System.debug('LastModifiedDate = ' + caseRecord.LastModifiedDate);
		
		
	}
}