src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the caller/contact</description>
        <inlineHelpText>Please select the language of the contact</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF (
FIND (&quot;/&quot;, Path__c) == 0, Path__c, 

LEFT(Path__c, FIND ( &quot;/&quot;, Path__c)-1)

)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <description>This is the full path for the product starting at Brand</description>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>IF (FIND(&quot;/&quot;, Path__c) == 0, &quot;&quot;, 

IF (FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1) == 0, 


RIGHT(Path__c, 
LEN (Path__c)
-
FIND(&quot;/&quot;, Path__c)

)

,


RIGHT(LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1), 
LEN (LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))
-
FIND(&quot;/&quot;, LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))

)



)

)</formula>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <externalId>true</externalId>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metadata_Survey_Trigger__c.object
<CustomObject>
    <description>This object will store information from the Global Product and Global Comment Code that will be used to trigger the correct survey.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Code_L1__c</fullName>
        <label>Comment Code L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Code_L2__c</fullName>
        <label>Comment Code L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Code_L3__c</fullName>
        <label>Comment Code L3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Method__c</fullName>
        <description>Values for this are dynamically taken from case object so that if a contact method is added it will be available automatically in the trigger admin page</description>
        <label>Contact Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <description>Direction is an option to trigger and it is multi-selectable. Shows picklist values from Case.Direction__c</description>
        <label>Direction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Fieldset__c</fullName>
        <label>Survey Fieldset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Metadata Survey Trigger</label>
    <nameField>
        <displayFormat>MTN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Survey Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MST_Action_Count__c.object
<CustomObject>
    <description>Roll up feature so that we can tell how many field set names have been shown. 
Count of how many times an Ad Hoc survey was used over a timeframe
Last 30, 60, 90 days (if need other duration needs to be defined now)
Lifetime

US592</description>
    <fields>
        <fullName>Date_Triggered__c</fullName>
        <label>Date Triggered</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Metadata_Survey_Trigger__c</fullName>
        <label>Metadata Survey Trigger</label>
        <referenceTo>Metadata_Survey_Trigger__c</referenceTo>
        <relationshipLabel>MST Action Counts</relationshipLabel>
        <relationshipName>MST_Action_Counts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Fieldset__c</fullName>
        <formula>Metadata_Survey_Trigger__r.Survey_Fieldset__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Fieldset</label>
        <type>Text</type>
    </fields>
    <label>MST Action Count</label>
    <nameField>
        <displayFormat>MSTAC-{000000000}</displayFormat>
        <label>Metadata Survey Trigger Action Count Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MST Action Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_OverrideMSTViewExt.cls
/*
* @author: orikkers@salesforce.com  
* @date: 06/30/2014
* @description:  controller extension for sf_OverrideMSTView page. 
*/



public with sharing class sf_OverrideMSTViewExt {
    
    private static final Integer DEFAULT_PAGE_SIZE = 10;
    private static final Integer LIMIT_QUERY_ROW = Limits.getLimitQueryRows();
    private static final String SPLIT_DELIMITER = '\\|';

    public Metadata_Survey_Trigger__c msTrigger {get; set;}

    public List <String> selectedFieldSets;
    public List <String> selectedCountries;
    public List <String> selectedLanguages;
    public List <String> selectedContactMethods;
    public List <String> selectedDirections;
    public List <String> selectedSegments;
    public List <String> selectedBrands;
    public List <String> selectedL1;
    public List <String> selectedL2;
    public List <String> selectedL3;

    
    public List <Local_Comment_Code__c> commentList {get; private set;}
    
    public Integer last30DaysCount {get; private set;}
    public Integer last60DaysCount {get; private set;}
    public Integer last90DaysCount {get; private set;}

    
    public sf_OverrideMSTViewExt(ApexPages.StandardController sc) {

        msTrigger = (Metadata_Survey_Trigger__c) sc.getRecord();
        if (msTrigger.Id != null) {
            last30DaysCount = 0;
            last60DaysCount = 0;
            last90DaysCount = 0;
            /*
            last30DaysCount = [SELECT count() FROM MST_Action_Count__c WHERE Date_Triggered__c = LAST_N_DAYS:30 AND Metadata_Survey_Trigger__c = :msTrigger.Id LIMIT :LIMIT_QUERY_ROW];
            last60DaysCount = [SELECT count() FROM MST_Action_Count__c WHERE Date_Triggered__c = LAST_N_DAYS:60 AND Metadata_Survey_Trigger__c = :msTrigger.Id LIMIT :LIMIT_QUERY_ROW];
            last90DaysCount = [SELECT count() FROM MST_Action_Count__c WHERE Date_Triggered__c = LAST_N_DAYS:90 AND Metadata_Survey_Trigger__c = :msTrigger.Id LIMIT :LIMIT_QUERY_ROW];
            */
        }
        
    }
    

    /* +++++++ SELECTED FIELDSETS ++++++++++++++*/
    public List <String> getSelectedFieldSets () {
        if (selectedFieldSets == null) {
            selectedFieldSets = new List <String> ();
            if (msTrigger.Survey_Fieldset__c != null)
            selectedFieldSets.addAll (msTrigger.Survey_Fieldset__c.split(SPLIT_DELIMITER));
        }
        return selectedFieldSets;
    }

    /* +++++++ SELECTED COUNTRIES ++++++++++++++*/
    public List <String> getSelectedCountries () {
        if (selectedCountries == null) {
            selectedCountries = new List <String> ();
            if (msTrigger.Country__c != null)
            selectedCountries.addAll (msTrigger.Country__c.split(SPLIT_DELIMITER));
        }
        return selectedCountries;
    }

    /* +++++++ SELECTED LANGUAGES ++++++++++++++*/

    public List <String> getSelectedLanguages () {
        if (selectedLanguages == null) {
            selectedLanguages = new List <String> ();
            if (msTrigger.Language__c != null)
            selectedLanguages.addAll (msTrigger.Language__c.split(SPLIT_DELIMITER));
        }
        return selectedLanguages;
    }

    /* +++++++ SELECTED CONTACT METHODS ++++++++++++++*/

    public List <String> getSelectedContactMethods () {
        if (selectedContactMethods == null) {
            selectedContactMethods = new List <String> ();
            if (msTrigger.Contact_Method__c != null)
            selectedContactMethods.addAll (msTrigger.Contact_Method__c.split(SPLIT_DELIMITER));
        }
        return selectedContactMethods;
    }

    /* +++++++ SELECTED DIRECTIONS ++++++++++++++*/

    public List <String> getSelectedDirections () {
        if (selectedDirections == null) {
            selectedDirections = new List <String> ();
            if (msTrigger.Direction__c != null)
            selectedDirections.addAll (msTrigger.Direction__c.split(SPLIT_DELIMITER));
        }
        return selectedDirections;
    }

     /* +++++++ SELECTED SEGMENTS ++++++++++++++*/

    public List <String> getSelectedSegments () {
        if (selectedSegments == null) {
            selectedSegments = new List <String> ();
            if (msTrigger.Segment__c != null)
            selectedSegments.addAll (msTrigger.Segment__c.split(SPLIT_DELIMITER));
        }
        return selectedSegments;
    }



    /* +++++++ SELECTED BRANDS ++++++++++++++*/

    public List <String> getSelectedBrands () {
        if (selectedBrands == null) {
            selectedBrands = new List <String> ();
            if (msTrigger.Brand__c != null)
            selectedBrands.addAll (msTrigger.Brand__c.split(SPLIT_DELIMITER));
        }
        return selectedBrands;
    }



    /* +++++++ SELECTED L1 ++++++++++++++*/

    public List <String> getSelectedL1 () {
        if (selectedL1 == null) {
            selectedL1 = new List <String> ();
            if (msTrigger.Comment_Code_L1__c != null)
            selectedL1.addAll (msTrigger.Comment_Code_L1__c.split(SPLIT_DELIMITER));
        }
        return selectedL1;
    }



    /* +++++++ SELECTED L2 ++++++++++++++*/

    public List <String> getSelectedL2 () {
        if (selectedL2 == null) {
            selectedL2 = new List <String> ();
            if (msTrigger.Comment_Code_L2__c != null)
            selectedL2.addAll (msTrigger.Comment_Code_L2__c.split(SPLIT_DELIMITER));
        }
        return selectedL2;
    }

   

    /* +++++++ SELECTED L3 ++++++++++++++*/

    public List <String> getSelectedL3 () {
        if (selectedL3 == null) {
            selectedL3 = new List <String> ();
            if (msTrigger.Comment_Code_L3__c != null)
            selectedL3.addAll (msTrigger.Comment_Code_L3__c.split(SPLIT_DELIMITER));
        }
        return selectedL3;
    }

    public List <Local_Product__c> getProducts () {
        String q = '';
        Set <String> countrySet = new Set <String> ();
        Set <String> brandSet = new Set <String> ();
        Set <String> segmentSet = new Set <String> ();
        
        
        String likeProductPath = '';
        
        q += 'SELECT Id, Name, Translated_Path__c, Global_Product__r.Path__c, Global_Product__r.Brand__c, Global_Product__r.Segment__c, Country__c FROM Local_Product__c WHERE Id != null ';

        if (msTrigger.Trigger_Type__c == 'Level') {
            
            if (!msTrigger.Country__c.contains('*') && !getSelectedCountries().isEmpty()) {
               
                q += ' AND Country__c IN (';
                
                for (String s: getSelectedCountries()) {
                    q += '\'' + s + '\',';
                }
                
                q = q.removeEnd(',');
                q += ') ';
            }
            
            if (!msTrigger.Brand__c.contains('*') && !getSelectedBrands().isEmpty()) {
               
                q += ' AND Global_Product__r.Brand__c IN (';
                
                for (String s: getSelectedBrands()) {
                    q += '\'' + s + '\',';
                }
                
                q = q.removeEnd(',');
                q += ') ';
            }

            if (!msTrigger.Segment__c.contains('*') && !getSelectedSegments().isEmpty()) {
               
                q += ' AND Global_Product__r.Segment__c IN (';
                
                for (String s: getSelectedSegments()) {
                    q += '\'' + s + '\',';
                }
                q = q.removeEnd(',');
                q += ') ';
            }
            
        } else if (msTrigger.Trigger_Type__c == 'Path') {
            likeProductPath = msTrigger.Product_Path__c + '%';

            q += ' AND Global_Product__r.Path__c LIKE :likeProductPath';
        }

        q += ' LIMIT 1000';

        System.debug(LoggingLevel.INFO, '##### Product query \n' + q);

        return (List <Local_Product__c>) Database.query(q);
    }
   
    public List <Local_Comment_Code__c> getComments () {
        String q = '';
        String likeCommentPath = '';
        q += 'SELECT Id, Global_Comment_Code__r.Full_Comment_Path__c, Name, Translated_Language__c, Level_1__c, Level_2__c, Level_3__c FROM Local_Comment_Code__c WHERE Id != null ';

        if (msTrigger.Trigger_Type__c == 'Level') {
            if (!msTrigger.Comment_Code_L1__c.contains('*') && !getSelectedL1().isEmpty()) {
               
                q += ' AND Global_Comment_Code__r.Level_1__c IN (';
                
                for (String s: getSelectedL1()) {
                    q += '\'' + s + '\',';
                }
                q = q.removeEnd(',');
                q += ') ';
            }

            if (!msTrigger.Comment_Code_L2__c.contains('*') && !getSelectedL2().isEmpty()) {
               
                q += ' AND Global_Comment_Code__r.Level_2__c IN (';
                
                for (String s: getSelectedL2()) {
                    q += '\'' + s + '\',';
                }
                q = q.removeEnd(',');
                q += ') ';
            }

            if (!msTrigger.Comment_Code_L3__c.contains('*') && !getSelectedL3().isEmpty()) {
               
                q += ' AND Global_Comment_Code__r.Level_3__c IN (';
                
                for (String s: getSelectedL3()) {
                    q += '\'' + s + '\',';
                }
                q = q.removeEnd(',');
                q += ') ';
            }

            if (!msTrigger.Language__c.contains('*') && !getSelectedLanguages().isEmpty()) {
                q += ' AND Translated_Language__c IN (';
                for (String s: getSelectedLanguages()) {
                     q += '\'' + s + '\',';
                }
                q = q.removeEnd(',');
                q += ') ';
            }

        } else if (msTrigger.Trigger_Type__c == 'Path') {
            likeCommentPath = msTrigger.Comment_Code_Path__c  + '%';
            q += ' AND Global_Comment_Code__r.Full_Comment_Path__c LIKE ' + '\'' + likeCommentPath + '\'';   
        }
        q += ' LIMIT 1000';
        System.debug(LoggingLevel.INFO, '##### Comment query \n' + q);

        return (List <Local_Comment_Code__c>)Database.query(q);
    }
}