src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_Line_1__c</fullName>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_2__c</fullName>
        <label>Primary Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Line_3__c</fullName>
        <label>Primary Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>This is the Country in the Mailing address</description>
        <label>Primary Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <label>Primary Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <label>Primary State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this checkbox will cause all related Cases to be updated in order to trigger a pull to CCM.</description>
        <inlineHelpText>Checking this checkbox will cause all related Cases to be updated in order to trigger a pull to CCM.</inlineHelpText>
        <label>Update Cases</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_CaseSummaryPopoutCompExtTest.cls
@isTest
private class sf_CaseSummaryPopoutCompExtTest {
	
	@isTest static void testInit() {
		


		Contact con = new Contact();
		con.LastName = 'TestLastName';
		con.FirstName = 'TestFirstName';
		con.Primary_Address_Line_1__c = '123 Main Street';
		con.Primary_Address_Line_2__c = 'apt 200';
		con.Primary_Address_Line_3__c = 'something';
		con.Primary_City__c = 'TestCity123';
		con.Primary_Country__c = 'United States';
		con.Primary_State_Province__c = 'Minnesota';
		con.Primary_Postal_Code__c = '55123';
		con.Update_Cases__c = TRUE;
		insert con;

		Case caseRecord = new Case();
		caseRecord.ContactId = con.Id;
		caseRecord.Status = 'Closed';
		insert caseRecord;


		sf_CaseSummaryPopoutCompExt ext = new sf_CaseSummaryPopoutCompExt (new ApexPages.StandardController (caseRecord));
		sf_CaseSummaryPopoutCompExt.checkObjectId(caseRecord.Id);
		ext.caseId = caseRecord.Id;
		ext.setCaseId();
		ext.saveSummary();
	}
	
}