src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country the contact is calling from</description>
        <inlineHelpText>Please pick the country where the contact is calling from</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                    <default>true</default>
                    <label>United States of America</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the caller/contact</description>
        <inlineHelpText>Please select the language of the contact</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Brand__c.object
<CustomObject>
    <description>This object is for configuring the brand options for the contact us page.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>This is the brand that is to be configured.</description>
        <label>Brand</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Contact Us Brand</label>
    <nameField>
        <label>Contact Us Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Us_Brand_Language__c.object
<CustomObject>
    <description>Junction object storing brand- and language-specific settings and translations</description>
    <fields>
        <fullName>Contact_Us_Brand__c</fullName>
        <label>Contact Us Brand</label>
        <referenceTo>Contact_Us_Brand__c</referenceTo>
        <relationshipLabel>Contact Us Brands Languages</relationshipLabel>
        <relationshipName>Contact_Us_Brands_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Us_Language__c</fullName>
        <label>Contact Us Language</label>
        <referenceTo>Contact_Us_Language__c</referenceTo>
        <relationshipLabel>Contact Us Brands Languages</relationshipLabel>
        <relationshipName>Contact_Us_Brands_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Us Brand Language</label>
    <nameField>
        <displayFormat>CBL-{0000}</displayFormat>
        <label>Contact Us Brand Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Us Brands Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Language__c.object
<CustomObject>
    <description>This object is for configuring the language/countries for the contact us page</description>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Chinese-T</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English-GB</fullName>
                </value>
                <value>
                    <fullName>English-US</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Farsi</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Flemish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Kazakh</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Malay</fullName>
                </value>
                <value>
                    <fullName>Maltese</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Us Language</label>
    <nameField>
        <label>Contact Us Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_ContactUsHeaderComponentCtrlTest.cls
/*
* @author: Lauren OMeara
* @date: 07/31/2014

* @description: sf_ContactUsHeaderComponentCtrl test
* US668 - re-architect contact us page
*
* @Updates
* 27-01-2016 - Updated to test multiple language, added asserts and @TestSetup - christopher.macduff@accenture.com
*/

@isTest
private class sf_ContactUsHeaderComponentCtrlTest {
    @TestSetup
    static void setupData(){
        List<Contact_Us_Language__c> langList = new List<Contact_Us_Language__c>();
        List<Contact_Us_Brand_Language__c> cublList = new List<Contact_Us_Brand_Language__c>();
        
        Contact_Us_Brand__c brand = new Contact_Us_Brand__c ();
		brand.Brand__c = sf_ContactUsHelperCtrl.DEFAULT_BRAND;
		insert brand;
        
        Contact_Us_Language__c lang1 = new Contact_Us_Language__c(
            Name = 'EnglishTest',
            Country__c = 'United States of America',
            Country_Picklist_Label__c = 'USA - United States of America',
            Language_Picklist_Label__c = 'English',
            Language__c = 'English-US',
            Language_Locale_Key__c = 'en_US'
        );
        langList.add(lang1);
        
		Contact_Us_Language__c lang2 = new Contact_Us_Language__c(
            Name = 'SpanishTest',
            Country__c = 'United States of America',
            Country_Picklist_Label__c = 'USA - United States of America',
            Language_Picklist_Label__c = 'Spanish',
            Language__c = 'Spanish',
            Language_Locale_Key__c = 'es'
        );
        langList.add(lang2);
        
        insert langList;
        
        Contact_Us_Brand_Language__c brandLang1 = new Contact_Us_Brand_Language__c(
            Contact_Us_Brand__c = brand.Id,
            Contact_Us_Language__c = lang1.Id
        );
        cublList.add(brandLang1);
        
		Contact_Us_Brand_Language__c brandLang2 = new Contact_Us_Brand_Language__c(
            Contact_Us_Brand__c = brand.Id,
            Contact_Us_Language__c = lang2.Id
        );
        cublList.add(brandLang2);
        
        insert cublList;
    }
	
	@isTest static void testInit() {
		sf_ContactUsHeaderComponentCtrl ctrl = new sf_ContactUsHeaderComponentCtrl ();

		ctrl.goPKB();
		ctrl.goEmailUs();
		ctrl.getCountryList();
        ctrl.selectedCountry = 'United States of America';

        List <SelectOption> langOptions = new List<SelectOption>(ctrl.getLanguageList());
        system.assertEquals(2, langOptions.size());

        List <SelectOption> brandOptions = new List<SelectOption>(ctrl.getBrandSelectList());
		system.assertEquals(1, brandOptions.size());

		ctrl.processCountrySelect();
		ctrl.processLanguageSelect();
		ctrl.processBrandSelect();
		ctrl.getChatStartUrl();
	}
}