src/objects/Country_Region_SMO__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Countries to Regions and SMOs</description>
    <fields>
        <fullName>Alternative_Contact_Info_Layout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To display the alternative layout  on the Contact Info tab, tick this checkbox</description>
        <inlineHelpText>Unchecked - Display standard Contact Info tab layout
Checked - Display alternative layout for the Contact Info tab. (Used for Asia cases)</inlineHelpText>
        <label>Alternative Contact Info Layout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Currency_ISO_Code__c</fullName>
        <description>http://www.currency-iso.org/en/home.html</description>
        <label>Currency ISO Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <description>Friendly readable name for Currency</description>
        <label>Currency Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisplayLabel__c</fullName>
        <description>Human friendly display text. Used on public facing pages - Where To Buy</description>
        <inlineHelpText>Human friendly display text. Used on public facing pages - Where To Buy</inlineHelpText>
        <label>DisplayLabel</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DistanceUnit__c</fullName>
        <description>Used on wtb page. valid inputs = &apos;miles&apos; or &apos;km&apos;.</description>
        <inlineHelpText>Used on wtb page. valid inputs = &apos;miles&apos; or &apos;km&apos;.</inlineHelpText>
        <label>DistanceUnit</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WTB_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true will appear on WTB search bar</description>
        <inlineHelpText>If true will appear on WTB search bar</inlineHelpText>
        <label>WTB Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Country Region SMO</label>
</CustomObject>

src/objects/Repeater_Threshold__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Per-language thresholds for Repeater detection logic</description>
    <fields>
        <fullName>Case_Count_Threshold__c</fullName>
        <inlineHelpText>Number of cases on an account (during the threshold period) that indicate a Suspected Repeater.  Evaluated independently of Reimbursement Value Threshold.  Can be blank if only a Reimbursement Value Threshold is needed.</inlineHelpText>
        <label>Case Count Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Value_Threshold__c</fullName>
        <inlineHelpText>Total Reimbursement Value of all cases on an account (during the threshold period) that indicates a Suspected Repeater.  Evaluated independently of Case Count Threshold.  Can be blank if only a Case Count Threshold is needed.</inlineHelpText>
        <label>Reimbursement Value Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Threshold_Period__c</fullName>
        <inlineHelpText>Number of days in threshold test period</inlineHelpText>
        <label>Threshold Period (Days)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Repeater Thresholds</label>
</CustomObject>

src/objects/triggerToggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Toggles supported triggers off/on as required.
*Note* Field names must match Trigger name.</description>
    <fields>
        <fullName>AccountTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Account Trigger</description>
        <inlineHelpText>Toggle for Account Trigger</inlineHelpText>
        <label>AccountTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Case Trigger</description>
        <inlineHelpText>Toggle for Case Trigger</inlineHelpText>
        <label>CaseTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContactTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Contact Trigger</description>
        <inlineHelpText>Toggle for Contact Trigger</inlineHelpText>
        <label>ContactTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FulfillmentOrderLineItem__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for FulfillmentOrderLineItem Trigger</description>
        <inlineHelpText>Toggle for FulfillmentOrderLineItem Trigger</inlineHelpText>
        <label>FulfillmentOrderLineItem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FulfillmentOrder__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for FulfillmentOrder Trigger</description>
        <inlineHelpText>Toggle for FulfillmentOrder Trigger</inlineHelpText>
        <label>FulfillmentOrder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SafetyAssessmentSurvey__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for SAS Trigger</description>
        <inlineHelpText>Toggle for SAS Trigger</inlineHelpText>
        <label>SafetyAssessmentSurvey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sf_EmailMessage__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for EmailMessage Trigger</description>
        <inlineHelpText>Toggle for EmailMessage Trigger</inlineHelpText>
        <label>sf_EmailMessage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sf_TaskTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Toggle for Task Trigger</description>
        <inlineHelpText>Toggle for Task Trigger</inlineHelpText>
        <label>sf_TaskTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>triggerToggle</label>
</CustomObject>

src/classes/CustomSettingDataFactory.cls
@isTest
public class CustomSettingDataFactory {
    
    //TODO: Check this is used/required?
    public static void triggerToggleSetup(){
        TriggerToggle__c tt = new TriggerToggle__c(
			AccountTrigger__c = True,
            CaseTrigger__c = True,
			ContactTrigger__c = True,
			FulfillmentOrder__c = True,
			FulfillmentOrderLineItem__c = True,
            SafetyAssessmentSurvey__c = True,
			sf_EmailMessage__c = True,
			sf_TaskTrigger__c = True
        );
        insert tt;
    }
    
    public static void repeaterThresholdSetup(){
        List<Repeater_Threshold__c> rtsToInsert = new List<Repeater_Threshold__c>();
        Repeater_Threshold__c rt = new Repeater_Threshold__c(
            name='United States of America',
            Threshold_Period__c=30,
            Case_Count_Threshold__c=5,
            Reimbursement_Value_Threshold__c=50.00
        );
        rtsToInsert.add(rt);
        insert rtsToInsert;
    }

    public static void countryRegionSetup(){

        List<Country_Region_SMO__c> countriesToInsert = new List<Country_Region_SMO__c>();
        
        //Add United States of America
        Country_Region_SMO__c USA = new Country_Region_SMO__c(
            name = 'UNITED STATES OF AMERICA',
            Currency_ISO_Code__c = 'USD',
            Currency_Name__c = 'United States dollar',
        	DisplayLabel__c = 'United States dollar',
            DistanceUnit__c = 'miles',
        	WTB_Enabled__c = FALSE
        );
        countriesToInsert.add(USA);
        
        //Add China
        Country_Region_SMO__c China = new Country_Region_SMO__c(
            name = 'CHINA',
            Currency_ISO_Code__c = 'CNY',
            Currency_Name__c = 'Chinese yuan',
        	DisplayLabel__c = 'Chinese yuan',
            DistanceUnit__c = 'miles',
        	WTB_Enabled__c = FALSE,
            Alternative_Contact_Info_Layout__c = TRUE
        );
        countriesToInsert.add(China);
        
        //Add Greece
        Country_Region_SMO__c Greece = new Country_Region_SMO__c(
            name = 'GREECE',
            Currency_ISO_Code__c = 'EUR',
            Currency_Name__c = 'Euro',
        	DisplayLabel__c = 'Euro',
            DistanceUnit__c = 'miles',
        	WTB_Enabled__c = FALSE
        );
        countriesToInsert.add(Greece);
        
        //Add Greece
        Country_Region_SMO__c Brazil = new Country_Region_SMO__c(
            name = 'Brazil',
            Currency_ISO_Code__c = 'BRL',
            Currency_Name__c = 'Brazilian real',
        	DisplayLabel__c = 'Brazilian real',
            DistanceUnit__c = 'miles',
        	WTB_Enabled__c = FALSE
        );
        countriesToInsert.add(Brazil);
        
        insert CountriesToInsert;
    
	}

}