src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Fulfillment_Item__c.object
<CustomObject>
    <description>This object provides a list of all active or inactive fulfillment items available in P&amp;G.  CR Agents will perform a search of this table to select the appropriate fulfillment items to send to Consumers.  Fulfillment item master data will be loaded my P&amp;G regional admins.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Country__c</fullName>
        <label>Contact Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Guatemala</fullName>
                </value>
                <value>
                    <fullName>Honduras</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Fulfillment Item</label>
    <nameField>
        <label>Fulfillment Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF (
FIND (&quot;/&quot;, Path__c) == 0, Path__c, 

LEFT(Path__c, FIND ( &quot;/&quot;, Path__c)-1)

)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if this Product is now inactive</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Path_Level__c</fullName>
        <formula>IF
(
FIND(&quot;/&quot;, Path__c) = 0,
&quot;BRAND&quot;,
IF
( 
AND 
(
FIND(&quot;/&quot;, Path__c, FIND(&quot;/&quot;, Path__c) + 1 ) = 0, 
FIND(&quot;/&quot;, Path__c) &gt; 0
),
&quot;SEGMENT&quot;,
&quot;LOWER-LEVEL&quot;
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Path Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>IF (FIND(&quot;/&quot;, Path__c) == 0, &quot;&quot;, 

IF (FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1) == 0, 


RIGHT(Path__c, 
LEN (Path__c)
-
FIND(&quot;/&quot;, Path__c)

)

,


RIGHT(LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1), 
LEN (LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))
-
FIND(&quot;/&quot;, LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))

)



)

)</formula>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <externalId>true</externalId>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for ContactUs page.</description>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Path_Level__c</fullName>
        <formula>IF
(
FIND(&quot;/&quot;, Translated_Path__c) = 0,
&quot;BRAND&quot;,
IF
(
AND
(
FIND(&quot;/&quot;, Translated_Path__c, FIND(&quot;/&quot;, Translated_Path__c) + 1 ) = 0,
FIND(&quot;/&quot;, Translated_Path__c) &gt; 0
),
&quot;SEGMENT&quot;,
&quot;LOWER-LEVEL&quot;
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Path Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Translated_Path__c</fullName>
        <label>Translated Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_CreateEditFulfillmentItemExt.cls
/*
* @author: Laure OMeara
* @date: 07/17/2014

* @description: 
* US496:
* This class supports the custom create/edit/clone page for Fulfillment Item objects
*/
public with sharing class sf_CreateEditFulfillmentItemExt {

    private Fulfillment_Item__c ffitem { get; set; }

    public sf_CreateEditFulfillmentItemExt(ApexPages.StandardController stdController) {
        ffitem = (Fulfillment_Item__c)stdController.getRecord();
    }
    
    
    public List<selectOption> getBrands() 
    {
        List<selectOption> brands = new List<selectOption>();
        brands.add(new selectOption('','--None--'));
        system.debug('********** Country: '+ffitem.Contact_Country__c);
        List <AggregateResult> lps = [select Name from Local_Product__c where 
            path_level__c = 'BRAND' AND
            Country__c = :ffitem.Contact_Country__c AND Inactive__c=false AND
            Name != null
            GROUP BY Name
            ORDER BY Name];
        for(AggregateResult lp : lps) {
            String brand = String.valueOf(lp.get('Name'));
            brands.add(new selectOption(brand, brand));
        }
        
        if(brands.size()>1) brands.add(1,new selectOption('ALL', 'ALL'));
        return brands;
    }
    
    
    public List<selectOption> getSegments() 
    {
        List<selectOption> segments = new List<selectOption>();
        Set<string> setSegs=new Set<string>();
        List<string> listSegs=new List<string>();
        segments.add(new selectOption('','--None--'));
        system.debug('********* brand is ' + ffitem.Brand__c);
        system.debug('********* size: '+segments.size());
        if(ffitem.Brand__c =='ALL'){
            //SELECT Id, Global_Product__r.Segment__c FROM Local_Product__c WHERE Global_Product__r.Product_Level__c = ‘Segment’ AND Country__c = ‘United States’ Group By Global_Product__r.Segment__c
            for(Local_Product__c lp : [SELECT Name FROM Local_Product__c 
                WHERE path_level__c = 'SEGMENT' AND country__c = :ffitem.Contact_Country__c 
                AND Inactive__c=false 
                ORDER BY Name ])  
            {
              setSegs.add(lp.Name);
            }
        }
        else {
            String path = ffitem.Brand__c + '/%';
            //for(Local_Product__c lp : [select Name from Product_Local_Brand_Segment__c where country__c = :ffitem.Contact_Country__c and path_Level__c = 'SEGMENT' and Inactive__c=false and translated_path__c LIKE :path order by Name])  
            for(Local_Product__c lp : [SELECT Name FROM Local_Product__c 
                WHERE path_level__c = 'SEGMENT' AND country__c = :ffitem.Contact_Country__c 
                AND Inactive__c=false 
                AND Translated_Path__c LIKE :path
                ORDER BY Name ]) 
            {
              setSegs.add(lp.Name);            }      
        }
        listSegs.addAll(setSegs);
        listSegs.sort();
        for(string seg:listSegs)
            segments.add(new selectOption(seg,seg));
        
        if(segments.size()>1) segments.add(1,new selectOption('ALL', 'ALL'));
        return segments;
        
     }
}