src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Global_Comment_Code__c.object
<CustomObject>
    <description>Master Detail with Local Comment Code</description>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is going to be the First Level Identifying the Type of Comment</description>
        <label>Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Complaints Other</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Product Quality Complaint</fullName>
                </value>
                <value>
                    <fullName>Testimonial</fullName>
                </value>
                <value>
                    <fullName>Unable to Classify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_2__c</fullName>
        <description>This indicates the next level of detail after the type of comment has been classified</description>
        <label>Level 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adverse Event</fullName>
                </value>
                <value>
                    <fullName>Alleged Contamination</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Consumer Preference / Dislikes</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Damage to Property</fullName>
                </value>
                <value>
                    <fullName>Dissatisfied with Product Performance</fullName>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Label, Insert Legibility or Confusing</fullName>
                </value>
                <value>
                    <fullName>Marketing Loyalty</fullName>
                </value>
                <value>
                    <fullName>Marketing Personal Information</fullName>
                </value>
                <value>
                    <fullName>Marketing Pricing</fullName>
                </value>
                <value>
                    <fullName>Marketing Promotion, Advertising</fullName>
                </value>
                <value>
                    <fullName>Marketing Shopping Experience</fullName>
                </value>
                <value>
                    <fullName>Missing Label, Coding, Insert</fullName>
                </value>
                <value>
                    <fullName>Moe</fullName>
                </value>
                <value>
                    <fullName>Packaging or Product Mix Up, Mislabel</fullName>
                </value>
                <value>
                    <fullName>Pet Health Effect</fullName>
                </value>
                <value>
                    <fullName>Product Information</fullName>
                </value>
                <value>
                    <fullName>Product or Packaging Malfunction Hazard</fullName>
                </value>
                <value>
                    <fullName>Product or Packaging Non Functioning or Damaged (Not Hazardous)</fullName>
                </value>
                <value>
                    <fullName>Product Usage</fullName>
                </value>
                <value>
                    <fullName>Safety Closure defect, child resistant closure</fullName>
                </value>
                <value>
                    <fullName>Sensory</fullName>
                </value>
                <value>
                    <fullName>Suspect Counterfeit</fullName>
                </value>
                <value>
                    <fullName>Suspect Tampering</fullName>
                </value>
                <value>
                    <fullName>Testimonial</fullName>
                </value>
                <value>
                    <fullName>Volume/Fill/Count/missing parts</fullName>
                </value>
                <value>
                    <fullName>Unable to Classify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Global Comment Code</label>
    <nameField>
        <displayFormat>GCC-{0000}</displayFormat>
        <label>Global Comment Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Comment Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Product__c.object
<CustomObject>
    <description>This hosts the global products</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF (
FIND (&quot;/&quot;, Path__c) == 0, Path__c, 

LEFT(Path__c, FIND ( &quot;/&quot;, Path__c)-1)

)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <description>This is the full path for the product starting at Brand</description>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>IF (FIND(&quot;/&quot;, Path__c) == 0, &quot;&quot;, 

IF (FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1) == 0, 


RIGHT(Path__c, 
LEN (Path__c)
-
FIND(&quot;/&quot;, Path__c)

)

,


RIGHT(LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1), 
LEN (LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))
-
FIND(&quot;/&quot;, LEFT(Path__c, FIND ( &quot;/&quot;, Path__c, FIND ( &quot;/&quot;, Path__c)+1)-1))

)



)

)</formula>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <label>Global Product</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Global Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Comment_Code__c.object
<CustomObject>
    <description>Localized versions of the Global Comment Codes.</description>
    <fields>
        <fullName>Global_Comment_Code__c</fullName>
        <description>Master Detail with Global Comment Code</description>
        <label>Global Comment Code</label>
        <referenceTo>Global_Comment_Code__c</referenceTo>
        <relationshipLabel>Local Comment Code</relationshipLabel>
        <relationshipName>Local_Comment_Code</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>This is the first level indicating the type of the comment code</description>
        <externalId>true</externalId>
        <label>Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_2__c</fullName>
        <description>This is the next level up once we know the type of Comment Code</description>
        <externalId>true</externalId>
        <label>Level 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Comment Code</label>
    <nameField>
        <displayFormat>LCC-{0000}</displayFormat>
        <label>Local Comment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Comment Code</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <externalId>true</externalId>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <externalId>true</externalId>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global Product</label>
        <referenceTo>Global_Product__c</referenceTo>
        <relationshipName>Local_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metadata_Survey_Trigger__c.object
<CustomObject>
    <description>This object will store information from the Global Product and Global Comment Code that will be used to trigger the correct survey.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This indicates this rule is Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Code_L1__c</fullName>
        <label>Comment Code L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Code_L2__c</fullName>
        <label>Comment Code L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Code_L3__c</fullName>
        <label>Comment Code L3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Code_Path__c</fullName>
        <label>Comment Code Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Method__c</fullName>
        <description>Values for this are dynamically taken from case object so that if a contact method is added it will be available automatically in the trigger admin page</description>
        <label>Contact Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <description>Direction is an option to trigger and it is multi-selectable. Shows picklist values from Case.Direction__c</description>
        <label>Direction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>This is the date after which this rule expires</description>
        <inlineHelpText>Please enter the date till which this rule is going to be valid.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Path__c</fullName>
        <label>Product Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Fieldset__c</fullName>
        <label>Survey Fieldset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Object__c</fullName>
        <description>Text area to enter the Survey Object</description>
        <label>Survey Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Type__c</fullName>
        <description>Level -  Allows creation of a survey trigger at the brand/segment level and L1,L2, and L3 levels of a comment code
Brand/Segment are refreshed in real time based on country entered
L1, L2, and L3 comment code levels are available for the admin.
Path - Allows creation of a survey trigger where a specific product and comment paths are required.
Paths will be copy and pasted into text fields by the admin.
Admin can enter 1 comment path and 1 product path per record</description>
        <inlineHelpText>Level -  Allows creation of a survey trigger at the brand/segment level and L1,L2, and L3 levels of a comment code

Path - Allows creation of a survey trigger where a specific product and comment paths are required.</inlineHelpText>
        <label>Trigger Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Path</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Metadata Survey Trigger</label>
    <nameField>
        <displayFormat>MTN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Survey Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Holds the questions(fields) and responses(field values) for all Probing and Ad hoc surveys.</description>
    <fields>
        <fullName>Metadata_Survey_Trigger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metadata Survey Trigger</label>
        <referenceTo>Metadata_Survey_Trigger__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Fieldset__c</fullName>
        <formula>Metadata_Survey_Trigger__r.Survey_Fieldset__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Fieldset</label>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_OverrideMSTViewExtTest.cls
/*
* @author: Oleg Rikkers
* @date: 07/01/2014

* @description: 
* Test class
*/

@isTest
private class sf_OverrideMSTViewExtTest {
    
    @isTest static void testNoSurvey() {
    	Metadata_Survey_Trigger__c mst = new Metadata_Survey_Trigger__c ();
        sf_OverrideMSTViewExt ext = new sf_OverrideMSTViewExt (new ApexPages.StandardController (mst));
      
    }
    
    @isTest static void testWithSurvey() {
        

        Global_Product__c p = new Global_Product__c ();
        p.Path__c = 'Testing/test';
        insert p;

        Global_Comment_Code__c gcc = new Global_Comment_Code__c ();
        gcc.Level_1__c = 'Testing';
        gcc.Level_2__c = 'Comments';
        insert gcc;

        Local_Product__c  lp = new Local_Product__c ();
        lp.Global_Product__c = p.Id;
        insert lp;

        Local_Comment_Code__c lcc = new Local_Comment_Code__c ();
        lcc.Global_Comment_Code__c = gcc.Id; 
        insert lcc;

        Metadata_Survey_Trigger__c mst = new Metadata_Survey_Trigger__c ();
        mst.Active__c = true;
        mst.Expiration_Date__c = System.today() + 10;
       
        mst.Country__c = 'United States of America';
        mst.Language__c = 'English-US';
        mst.Brand__c = 'test';
        mst.Segment__c = 'test';
        mst.Comment_Code_L1__c = 'test';
        mst.Comment_Code_L2__c = 'test';
        mst.Comment_Code_L3__c = 'test';
        mst.Contact_Method__c = 'test';
        mst.Direction__c = 'test';
        mst.Survey_Fieldset__c = 'test';
        mst.Survey_Object__c = 'Survey__c';
        mst.Trigger_Type__c = 'Path';
        mst.Product_Path__c = 'Testing';
        mst.Comment_Code_Path__c = 'Testing';

        insert mst;

        Metadata_Survey_Trigger__c mst1 = new Metadata_Survey_Trigger__c ();
        mst1.Active__c = true;
        mst1.Expiration_Date__c = System.today() + 10;
       
        mst1.Country__c = 'United States of America';
        mst1.Language__c = 'English-US';
        mst1.Brand__c = 'test';
        mst1.Segment__c = 'test';
        mst1.Comment_Code_L1__c = 'test';
        mst1.Comment_Code_L2__c = 'test';
        mst1.Comment_Code_L3__c = 'test';
        mst1.Contact_Method__c = 'test';
        mst1.Direction__c = 'test';
        mst1.Survey_Fieldset__c = 'test';
        mst1.Survey_Object__c = 'Survey__c';
        mst1.Trigger_Type__c = 'Level';
        mst1.Product_Path__c = 'Testing';
        mst1.Comment_Code_Path__c = 'Testing';

        insert mst1;

        Test.startTest();

        Test.setCurrentPage(Page.sf_CaseSurveyProbingQuestions);
        ApexPages.currentPage().getParameters().put ('id', mst.Id);
        sf_OverrideMSTViewExt ext = new sf_OverrideMSTViewExt (new ApexPages.StandardController (mst));
        ext.getSelectedCountries();
        ext.getSelectedBrands();
        ext.getSelectedDirections();
        ext.getSelectedL1();
        ext.getSelectedL2();
        ext.getSelectedL3();
        ext.getSelectedContactMethods();
        ext.getSelectedSegments();
        ext.getSelectedLanguages();
        ext.getProducts();
        ext.getComments();
        
       

        ApexPages.currentPage().getParameters().put ('id', mst1.Id);
        sf_OverrideMSTViewExt ext1 = new sf_OverrideMSTViewExt (new ApexPages.StandardController (mst1));
        ext1.getSelectedCountries();
        ext1.getSelectedBrands();
        ext1.getSelectedDirections();
        ext1.getSelectedL1();
        ext1.getSelectedL2();
        ext1.getSelectedL3();
        ext1.getSelectedContactMethods();
        ext1.getSelectedSegments();
        ext1.getSelectedLanguages();
        ext1.getProducts();
        ext1.getComments();



        Test.stopTest();
        
        
    }
}