src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List iso-3166-country-code</description>
    <label>Country</label>
</CustomObject>

src/objects/Telephony__c.object
<CustomObject>
    <fields>
        <fullName>Country_Has_1_Phone_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if the country uses the same phone number for all brands. Note, do not check if country uses the same phone number for multiple brands but not all</inlineHelpText>
        <label>Country Has 1 Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ITFS_Status__c</fullName>
        <label>ITFS Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Crisis</fullName>
                </value>
                <value>
                    <fullName>Divested</fullName>
                </value>
                <value>
                    <fullName>Spare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Telephony</label>
    <nameField>
        <displayFormat>Tel-{00000}</displayFormat>
        <label>Telephony Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telephony</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TelephonyTriggerHelper.cls
public  class TelephonyTriggerHelper {

    
   
    //handle when multiple telephonies exist and new one gets created with same country and
    //Country has 1 phone number set to true.
    //Results -- Block new entry
    public static void validateExistingRecords(List<Telephony__c> newTelephony,Map<Id,Telephony__c> oldMap){ 
        List<Telephony__c> results = [select id, Country_Has_1_Phone_Number__c ,Country__c, ITFS_Status__c from Telephony__c where ITFS_Status__c = 'Active' limit 50000];
        
        system.debug('@@@results: ' + results);
        
        Map<String, Telephony__c> countryDup = new Map<String, Telephony__c>(); 
        Map<String, Telephony__c> countryHasTrue = new Map<String, Telephony__c>(); 
      
        if(results.size() > 0){
            for(Telephony__c tel : results){
               countryDup.put(tel.Country__c,tel);
                if(tel.Country_Has_1_Phone_Number__c == true){
                    countryHasTrue.put(tel.Country__c,tel);
                }
            }
        }
        
        //inserting
        if(oldMap == null){
            for(Telephony__c tel : newTelephony){
                //check old records that have Country_Has_1_Phone_Number__c =true
                //check this one has Country_Has_1_Phone_Number__c = true and other records use same country
                
                system.debug('@@@countryDup.containsKey(tel.Country__c): ' + countryDup.containsKey(tel.Country__c));
                system.debug('@@@countryHasTrue.containsKey(tel.Country__c)): ' + countryHasTrue.containsKey(tel.Country__c));
                system.debug('@@@tel.Country_Has_1_Phone_Number__c: ' + tel.Country_Has_1_Phone_Number__c);
                system.debug('@@@countryDup.containsKey(tel.Country__c): ' + countryDup.containsKey(tel.Country__c));
                
                if(((countryDup.containsKey(tel.Country__c) && countryHasTrue.containsKey(tel.Country__c)) && tel.ITFS_Status__c == 'Active') || ((tel.Country_Has_1_Phone_Number__c == true && countryDup.containsKey(tel.Country__c) ) && tel.ITFS_Status__c == 'Active') ){ 
                    newTelephony[0].addError('Error: Country, '+newTelephony[0].Country__c + ' has been marked to have 1 telephony for all brands. Duplicate active records are not allowed.');
                }
            }
        }
        else if(oldMap != null){
           for(Telephony__c tel : newTelephony){
              if(countryDup.size() > 0 && newTelephony[0].Country_Has_1_Phone_Number__c == true && oldMap.get(newTelephony[0].id).Country_Has_1_Phone_Number__c == false && countryDup.get(tel.Country__c).id != newTelephony[0].id && tel.ITFS_Status__c == 'Active'){ 
                newTelephony[0].addError('Error: Country, '+newTelephony[0].Country__c + ' has been marked to have 1 telephony for all brands. Duplicates active records not allowed.');
              }
           }
        }
              
    }


}