src/objects/CSAT_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CSAT Surveys</relationshipLabel>
        <relationshipName>CSAT_Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSAT Survey</label>
    <nameField>
        <displayFormat>CSAT-{00000000}</displayFormat>
        <label>CSAT Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSAT Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_CSATSurveyHelperTest.cls
/**
* @author: salesforce.com, inc.
* @date: 02/05/2015
*
* @description: test class
*/

@isTest
private class sf_CSATSurveyHelperTest {
    
    @isTest static void testCSATSurvey() {
        //create a contact 
        Contact c = new Contact ();
        c.LastName = 'test';
        c.Email = 'test@test12312312312.com';
        insert c;

        Case ca = new Case ();
        ca.Status = 'New';
        ca.ContactId = c.Id;
        insert ca;

        ca.Status = 'Closed';
        update ca;
        
        List<CSAT_Survey__c> csat = [SELECT Id FROM CSAT_Survey__c WHERE Case__c = :ca.Id];
        csat[0].Status__c = 'Submitted';
        update csat;

        System.assertEquals(1, csat.size());
    }
    
}