src/objects/DAM_Brandstore_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>2000</defaultValue>
        <description>Enter a number between 1 and 2000</description>
        <label>Batch Size</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brandstore_Retrieval_Notification_Emails__c</fullName>
        <inlineHelpText>Comma separated emails. No spaces.</inlineHelpText>
        <label>Brandstore Retrieval Notification Emails</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dam_Image_Retrieval_Query__c</fullName>
        <description>Only add where clause. For example Last_Dam_Request__c = null. Single quotes need to be escaped. Leave empty for default query.</description>
        <label>Dam Image Retrieval Query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DAM Brandstore Settings</label>
</CustomObject>

src/objects/Local_Product__c.object
<CustomObject>
    <description>Localized versions of the Global Products.</description>
    <fields>
        <fullName>Do_Not_Override_Images__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used by DAM process when new images need to be added. Batch job from SFDC side excludes these records from the process that sends request to DAM</description>
        <inlineHelpText>This field is used by DAM process when new images need to be added. Batch job from SFDC side excludes these records from the process that sends request to DAM</inlineHelpText>
        <label>Do Not Override Images</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GTIN_Number__c</fullName>
        <description>This is the GTIN Number</description>
        <inlineHelpText>Please enter the GTIN Number</inlineHelpText>
        <label>GTIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Product</label>
    <nameField>
        <label>Local Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_DAMProcessImagesScheduleable.cls
/**
* @author: salesforce.com
* @date: 03/09/2015
*
* @description: Schedule process to send image url requests to DAM
* String jobID = system.schedule('DAM Image Retrieval', '0 18 * * * ?', new sf_DAMProcessImagesScheduleable ());
*
*/

global class sf_DAMProcessImagesScheduleable implements Schedulable {
	global void execute(SchedulableContext sc) {
		String notificationemails = DAM_Brandstore_Settings__c.getInstance().Brandstore_Retrieval_Notification_Emails__c;
		String queryString = !String.isEmpty(DAM_Brandstore_Settings__c.getInstance().Dam_Image_Retrieval_Query__c) ? 'SELECT Id, GTIN_Number__c, Do_Not_Override_Images__c FROM Local_Product__c WHERE ' + DAM_Brandstore_Settings__c.getInstance().Dam_Image_Retrieval_Query__c : '';
		List <String> emails = !String.isEmpty(notificationemails) ? notificationemails.split(',') : new List <String> {'orikkers+pgDAMprocess@salesforce.com'};
		

		Integer batchSize = DAM_Brandstore_Settings__c.getInstance().Batch_Size__c != null ? Integer.valueOf(DAM_Brandstore_Settings__c.getInstance().Batch_Size__c) : 2000;

		sf_DAMProcessImagesBatch b = new sf_DAMProcessImagesBatch (queryString, emails);
		Database.executebatch(b, batchSize);
	}
}