src/objects/FAQ__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>sf_FAQArticleTemplate</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Frequently asked questions and their answers.</description>
    <label>FAQ</label>
    <pluralLabel>FAQS</pluralLabel>
</CustomObject>

src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>BackgroundImgLanding__c</fullName>
        <description>Background image for landing page</description>
        <label>Landing Page Background Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRCountryIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAQCountry__c</fullName>
        <formula>IF(ISPICKVAL(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c, &apos;United States of America&apos;), &apos;United_States&apos;, SUBSTITUTE(TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c), &apos; &apos;, &apos;_&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FAQ Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRLanguageIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageLocaleKey__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.Language_Locale_Key__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Locale Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchMinCharMsg__c</fullName>
        <label>Search Minimum Character Message</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <recordTypes>
        <fullName>faq</fullName>
        <active>true</active>
        <description>Record type for faq</description>
        <label>faq</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GCRGenericProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains Generic Properties for GCR widget.</description>
    <fields>
        <fullName>value__c</fullName>
        <description>Field contains values for GCR widget Generic properties</description>
        <label>value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Care Hub Generic Properties</label>
</CustomObject>

src/objects/PKB_Article_Feedback_Deflection__c.object
<CustomObject>
    <description>Stores data about feedback provided to an article and any customer deflection the article may have contributed to.</description>
    <fields>
        <fullName>Article_ID__c</fullName>
        <label>Article ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>7000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deflection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deflection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Feedback_Source__c</fullName>
        <label>Feedback Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ContactUs</fullName>
                </value>
                <value>
                    <fullName>Search</fullName>
                </value>
                <value>
                    <fullName>RelatedArticle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keyword_Searched__c</fullName>
        <description>Keyword searched, if any, prior to the user entering this feedback or deflection.</description>
        <inlineHelpText>Keyword searched, if any, prior to the user entering this feedback or deflection.</inlineHelpText>
        <label>Keyword Searched</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_ID__c</fullName>
        <label>Session ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PKB Article Deflection</label>
    <nameField>
        <displayFormat>AFD-{0000000}</displayFormat>
        <label>PKB Article Feedback &amp; Deflection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PKB Article Deflection</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/gcr_knowledgeArticleController.cls
/*
* @author: 		 Accenture
* @date: 		 02/06/2016
* @description:  Controller class for faq component for gcr widget
* CHANGE LOG
* DATE				NAME				CHANGE DESCRIPTION
* 02/06/2016		Accenture			INITIAL DRAFT
* 18/11/2016		Accenture			Added new property "lastArticleId" to capture id of last article in list of articles to
*										to identify last article in the page .
*/
public class gcr_knowledgeArticleController {
    public Boolean feedbackInit { get; set; }
    public Boolean feedbackProvided { get; set; }
    public Boolean feedbackPositive { get; set; }
    public String strComments { get; set; }
    public Boolean isRightToLeft { get; set; }
    // PUBLIC URL FOR FAQ
    public String strFaqUrl { get; set; }
    public Boolean blnTempFeedback { get {
        if (sPrvArticleId != null) {
            if(!sPrvArticleId.contains(kArticleView.Id)) {
                feedbackProvided = false;
                feedbackInit = false;
                sPrvArticleId.add(kArticleView.Id);
            }
        } else {
            sPrvArticleId = new Set<String>();
        }
        return false;
    } set; }
    public Set<String> sPrvArticleId { get; set; }

    // ARTICLE SEARCH COMPONENT VARIABLES
    public String chlContentId { public get; public set; }
    public String strKaUrlName {  get; set; }
    // PATCH VARIABLE TO PATCH BACK TO FAQ FROM ARTICLE VIEW AFTER ORGANIC SEARCH
    private Boolean gotoLanding { private get; private set; }

    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	get method for channel content record this is here due to vf component limitation
	 * @input:			none
	 * @return:			void
     */
    public GCRChannelContent__c chlContentRec { get {
        if (chlContentRec == null) {
            String queryString = gcr_helperClass.createQueryString('SELECT'
                                                                 , gcr_helperClass.getAllFieldsForQuery('GCRChannelContent__c')
                                                                   + ',CareHub__r.BackgroundImgLanding__c'
                                                                   + ',CareHub__r.FAQCountry__c,CareHub__r.LanguageLocaleKey__c'
                                                                   + ',CareHub__r.CountryIsoCode__c,CareHub__r.LanguageIsoCode__c'
                                                                   + ',CareHub__r.Brand__c,CareHub__r.SearchMinCharMsg__c,RecordType.Name'
                                                                 , 'GCRChannelContent__c')
                + ' WHERE Id = \'' + chlContentId + '\'' ;
			chlContentRec = (GCRChannelContent__c) Database.query(queryString).get(0);
            strFaqUrl = '/' + chlContentRec.CareHub__r.Brand__c + '/' 
                + chlContentRec.CareHub__r.LanguageIsoCode__c + '-' + chlContentRec.CareHub__r.CountryIsoCode__c + '/faq/';
        }
        return chlContentRec;
    } set; }

    public Boolean blnTemp { get {
        // FLAG VARIABLE TO CHECK IF LANDING PAGE REQUESTED
        gotoLanding = gotoLanding == null ? true : gotoLanding; 
        if (String.isNotBlank(strKaUrlName) && gotoLanding) {
            if (kArticleView == null) {
            	kArticleView = gcr_helperClass.getArticleByUrlName(strKaUrlName, chlContentRec.CareHub__r.LanguageLocaleKey__c, true);
            }
            showArticleList = false;
        } else {
            if (blnTemp == null && lKnowledgeArticle == null) {
                lKnowledgeArticle = gcr_helperClass.getFeaturedArticleData(chlContentRec, chlContentRec.CareHub__r.Brand__c
                                                                         , chlContentRec.CareHub__r.LanguageLocaleKey__c);
                if (lKnowledgeArticle != null && !lKnowledgeArticle.isEmpty()) {
                	lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
                }
                showArticleList = true;
            }
        }
		return false; } set; }
    // FEATURED KNOWLEDGE ARTICELS
    public List<KnowledgeArticleVersion> lKnowledgeArticle { get; set; }
	// KNOWLEDGE ARTICLES SEARCH STRING
    public String strSearch { get; set; }
    public Boolean isMinCharError { get; set; }
	// SELECTED KNOWLEDGE ARTICLE TO VIEW
    public FAQ__kav kArticleView { get; set; }
    public Id kArticleId { get; set; }
    // BOOLEANS TO CONTROL THE LIST OF ARTICLES
    public Boolean showArticleList { get; set; }
    // DECEMBER CHANGE
    public Boolean isLanding { get; private set; }
    public String lastArticleId { get; private set; }
	// PAGINATION RELATED VARIABLES
    public Integer currentPage { get; set; }
    public Integer totalPages { get; private set; }
    public Integer offsetValue { get; private set; }
    public Integer totalSearchArticles { get; private set; }
    public Integer intPageSize { get; private set; }
    public List<Integer> lPageNumbers { get; private set; }
    // CONSTANTS FOR PAGINATION
    public final Integer TOTAL_VISIBLE_PAGES = 3;

    /*
     * @author: 		Accenture
	 * @date: 		 	02/06/2016
	 * @description:  	CONSTRUCTOR FOR PAGE CONTROLLER
     */
    public gcr_knowledgeArticleController() {
        isLanding = true;
        feedbackProvided = false;
        totalSearchArticles = 0;
        offsetValue = 0;
        totalPages = 0;
        currentPage = 1;
        isMinCharError = false;
        lPageNumbers = new List<Integer>();
        intPageSize = GCRGenericProperties__c.getInstance('FAQ_KASEARCH_PAGESIZE') != null ? 
            			   Integer.valueOf(GCRGenericProperties__c.getInstance('FAQ_KASEARCH_PAGESIZE').value__c) : 5;
    }
    
    public void getArticleDetail() {
        showArticleList = false;
        isLanding = false;
        lPageNumbers.clear();
        lKnowledgeArticle.clear();
        lKnowledgeArticle = new List<KnowledgeArticleVersion>();
        try {
        	kArticleView = gcr_helperClass.getArticleById(kArticleId, chlContentRec.CareHub__r.LanguageLocaleKey__c, true);
        } catch (Exception thrownException) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, LABEL.errMsgGeneric));
        }
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to get knowledge article search results based on entered string
	 * @input:			none
	 * @return:			void
     */
    public void getSearchResult() {
        //CDOY WR467. Changed the min search lenght from 3 to 2
        if (String.isNotBlank(strSearch) && strSearch.length() > 1) {
            isMinCharError = false;
            currentPage = 1;
            offsetValue = 0;
            // CLEAR PAGENUMBER LIST AND GET ARTICLES FOR SEARCH STRING
            lPageNumbers.clear();
            // GET SIZE OF TOTAL NUMBER OF ARTICLES RETURNED
            try {
                List<KnowledgeArticleVersion> lArticles = gcr_helperClass.getSearchedArticle(String.escapeSingleQuotes(strSearch), 0, 0
                                                                                           , chlContentRec.CareHub__r.LanguageLocaleKey__c
                                                                                           , chlContentRec.CareHub__r.Brand__c
                                                                                           , chlContentRec.CareHub__r.FAQCountry__c);
                if (lArticles != null && !lArticles.isEmpty()) {
                    totalSearchArticles = lArticles.size();
                    lArticles.clear();
                    showArticleList = true;
                    Integer pageSize = Integer.valueOf(GCRGenericProperties__c.getInstance('FAQ_KASEARCH_PAGESIZE').value__c);
                    lKnowledgeArticle = gcr_helperClass.getSearchedArticle(String.escapeSingleQuotes(strSearch)
                                                                         , offsetValue, pageSize
                                                                         , chlContentRec.CareHub__r.LanguageLocaleKey__c
                                                                         , chlContentRec.CareHub__r.Brand__c
                                                                         , chlContentRec.CareHub__r.FAQCountry__c);
                    // RETRIEVE PAGE RECORDS FROM STANDARD SET CONTROLLER
                    totalPages = Math.mod(totalSearchArticles, pageSize) > 0 ? (totalSearchArticles / pageSize) + 1 : totalSearchArticles / pageSize;
                    Integer itr = 1;
                    Integer lastPage = totalPages < 3 ? totalPages : 3;
                    while (itr <= lastPage) {
                        lPageNumbers.add(itr);
                        itr++;
                    }
                    lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
                } else {
                    totalSearchArticles = 0;
                    lKnowledgeArticle.clear();
                }
                isLanding = false;
            } catch (Exception caughtException) {
                SYSTEM.DEbug('EXCEPTION: ' + caughtException.getStackTraceString());
            }
        } else {
            isMinCharError = true;
        }
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to go back to search page from article view page
	 * @input:			none
	 * @return:			void
     */
    public void goToLanding() {
        strKaUrlName = null;
        gotoLanding = false;
        showArticleList = true;
        isLanding = true;
        strSearch = '';
        offsetValue = 0;
        lPageNumbers.clear();
        lKnowledgeArticle = gcr_helperClass.getFeaturedArticleData(chlContentRec
                                                                 , chlContentRec.CareHub__r.Brand__c
                                                                 , chlContentRec.CareHub__r.LanguageLocaleKey__c);
        if (lKnowledgeArticle != null && !lKnowledgeArticle.isEmpty()) {
        	lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
        }
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to display selected page via pagination
	 * @input:			none
	 * @return:			void
     */
    public void displaySelectedPage() {
        offsetValue = (intPageSize * currentPage) - intPageSize;
        lKnowledgeArticle = gcr_helperClass.getSearchedArticle(strSearch, offsetValue, intPageSize
                                                             , chlContentRec.CareHub__r.LanguageLocaleKey__c
                                                             , chlContentRec.CareHub__r.Brand__c
                                                             , chlContentRec.CareHub__r.FAQCountry__c);
        lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
        lPageNumbers.clear();
		// TODO: HERE "3" SHOULD REPLACE WITH TOTAL VISIBLE PAGES FROM CONFIGURATION
        Integer itr;
        Integer lastPage;
        if (totalPages > 3) {
            if (currentPage + 1 > totalPages) {
                itr = totalPages - 2;
                lastPage = totalPages;
            } else {
                if (currentPage - 1 > 0) {
                	itr = currentPage - 1;
                    lastPage = currentPage + 1;
                } else {
                    itr = 1;
                    lastPage = 3;
                }
            }
        } else {
            itr = 1;
            lastPage = totalPages;
        }
        while (itr <= lastPage) {
            lPageNumbers.add(itr);
            itr++;
        }
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to display previous page via pagination
	 * @input:			none
	 * @return:			void
     */
    public void previous() {
        offsetValue = offsetValue - intPageSize;
        currentPage--;
        lKnowledgeArticle = gcr_helperClass.getSearchedArticle(strSearch, offsetValue, intPageSize
                                                             , chlContentRec.CareHub__r.LanguageLocaleKey__c
                                                             , chlContentRec.CareHub__r.Brand__c
                                                             , chlContentRec.CareHub__r.FAQCountry__c);
        lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
        if (totalPages > 3) {
        	Integer intFirstPage = lPageNumbers.get(0);
            if (currentPage - intFirstPage < 1 && intFirstPage > 1) {
                lPageNumbers.add(0, intFirstPage - 1);
                lPageNumbers.remove(lPageNumbers.size() - 1);
            }
        }
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to display next page via pagination
	 * @input:			none
	 * @return:			void
     */
    public void next() {
        offsetValue = offsetValue + intPageSize;
        currentPage++;
        lKnowledgeArticle = gcr_helperClass.getSearchedArticle(strSearch, offsetValue, intPageSize
                                                             , chlContentRec.CareHub__r.LanguageLocaleKey__c
                                                             , chlContentRec.CareHub__r.Brand__c
                                                             , chlContentRec.CareHub__r.FAQCountry__c);
        lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
        if (totalSearchArticles > 3) {
        	Integer intLastPage = lPageNumbers.get(lPageNumbers.size() - 1);
            if (intLastPage - currentPage < 1 && intLastPage < totalPages) {
                lPageNumbers.add(intLastPage + 1);
                lPageNumbers.remove(0);
            }
        }
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to display first page via pagination
	 * @input:			none
	 * @return:			void
     */
    public void firstPage() {
		offsetValue = 0;
        currentPage = 1;
        lKnowledgeArticle = gcr_helperClass.getSearchedArticle(strSearch, offsetValue, intPageSize
                                                             , chlContentRec.CareHub__r.LanguageLocaleKey__c
                                                             , chlContentRec.CareHub__r.Brand__c
                                                             , chlContentRec.CareHub__r.FAQCountry__c);
        lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
        lPageNumbers.clear();
		Integer itr = 1;
        Integer lastPage = totalPages < 3 ? totalPages : 3;
		while (itr <= lastPage) {
			lPageNumbers.add(itr);
			itr++;
		}
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to display last page via pagination
	 * @input:			none
	 * @return:			void
     */
    public void lastPage() {
        offsetValue = (totalPages - 1) * intPageSize;
        currentPage = totalPages;
        lKnowledgeArticle = gcr_helperClass.getSearchedArticle(strSearch, offsetValue, intPageSize
                                                             , chlContentRec.CareHub__r.LanguageLocaleKey__c
                                                             , chlContentRec.CareHub__r.Brand__c
                                                             , chlContentRec.CareHub__r.FAQCountry__c);
        lastArticleId = lKnowledgeArticle.get(lKnowledgeArticle.size() - 1).KnowledgeArticleId;
        lPageNumbers.clear();
		Integer itr = totalPages > 3 ? totalPages - 2 : 1;
		while (itr <= totalPages) {
			lPageNumbers.add(itr);
			itr++;
		}
    }
    // FEEDBACK COMPONENT RELATED METHODS
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to display cancel feedback after initiating negative feedback
	 * @input:			none
	 * @return:			void
     */
    public void cancelFeedback() {
        feedbackProvided = false;
        feedbackInit = false;
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to initiate negative feedback
	 * @input:			none
	 * @return:			void
     */
    public void negativeFeedback() {
        feedbackInit = true;
        feedbackProvided = false;
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to submit negative feedback
	 * @input:			none
	 * @return:			void
     */
    public void submitNegativeFeedback() {
        recordFeeback(this.kArticleView, strComments, this.strSearch, 'Search', false);
        strComments = '';
    }

    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to submit positive feedback
	 * @input:			none
	 * @return:			void
     */
    public void positiveFeedback() {
        feedbackInit = true;
        recordFeeback(this.kArticleView, strComments, this.strSearch, 'Search', true);
        strComments = '';
    }
    
    /*
     * @author: 		Accenture
	 * @date: 		 	01/08/2016
	 * @description:  	method to record feedback and create feedback deflection record
	 * @input:			none
	 * @return:			void
     */
    private void recordFeeback(FAQ__kav kArticle, String strComments, String strSearch, String strSource, Boolean deflection) {
		PKB_Article_Feedback_Deflection__c aFbDeflection 
            = new PKB_Article_Feedback_Deflection__c (
                  Article_ID__c = kArticle.Id
                , Article_Number__c = kArticle.articleNumber
                , Article_Title__c = kArticle.title
                , Feedback_Source__c = strSource
                , Comments__c = strComments
                , Session_ID__c = ''
                , Deflection__c = deflection
                , Keyword_Searched__c = strSearch
    	);
        Database.saveResult saveResult = Database.insert(aFbDeflection, false);
        if (saveResult.isSuccess()) {
            feedbackProvided = true;
            sPrvArticleId.add(kArticle.Id);
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, GCRGenericProperties__c.getInstance('GCR_FATAL_ERRMSG').value__c));
        }
    }
}