src/objects/Fulfillment_Order__c.object
<CustomObject>
    <description>The Fulfillment Order object houses order details for Cases requiring a fulfillment order.  The Fulfillment Order represents the ‘Shopping Cart’ of items that complete a single order related to a Case.  The design supports the ability for a case to contain multiple Fulfillment Orders.  Fulfillment Orders can be both manually fulfilled or sent via integration to the P&amp;G Hermes application.  Fulfillment Orders contain a status field to indicate status of the current order.</description>
    <fields>
        <fullName>Letter_Body__c</fullName>
        <label>Letter Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Fulfillment Order</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Fulfillment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sf_FulfillmentOrderLetterEdit.cls
/**
* @author: Ashok Bommali
* @date: SEP-2014
* @description: 
* This controller is used for the conga template edit on fulfillment orders
*/
public class sf_FulfillmentOrderLetterEdit {
    public string editBox {get; set;}
    list<Fulfillment_Order__c> query;

    public sf_FulfillmentOrderLetterEdit(ApexPages.StandardController controller) {
        query =[select id ,Letter_Body__c from Fulfillment_Order__c where id =: ApexPages.currentPage().getParameters().get('id')];
        editBox = query[0].letter_body__c;
    }  
     
    public PageReference save1(){
        Fulfillment_Order__c fo = new Fulfillment_Order__c();
        fo.id = ApexPages.currentPage().getParameters().get('Id');
        fo.Letter_Body__c = editbox;
        update fo;
        
        PageReference pageRef = new PageReference('/'+ApexPages.currentPage().getParameters().get('Id'));
        pageRef.setRedirect(true);
        return pageRef;
    }
    
    public PageReference cancelBtn(){
        PageReference pageRef = new PageReference('/'+ApexPages.currentPage().getParameters().get('Id'));
        pageRef.setRedirect(true);
        return pageRef;
    }
}