src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRCountryIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRLanguageIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Iso Code</label>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field defines current active channels</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <recordTypes>
        <fullName>faq</fullName>
        <active>true</active>
        <description>Record type for faq</description>
        <label>faq</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/gcr_careHubSitemapIndexController.cls
/*
* @author:          Accenture
* @date:            17/01/2017
* @description:     Controller for carehub sitemap index page
* DATE              NAME                CHANGE DESCRIPTION
* 17/01/2017        Accenture           Initial Draft
*/
public class gcr_careHubSitemapIndexController {
    public Map<String, String> mSitemaps { public get; private set; }

    public gcr_careHubSitemapIndexController() {
        mSitemaps = new Map<String, String>();
        for(GCRChannelContent__c eachChCont :[ SELECT Id
                                                    , CareHub__r.Brand__c
                                                    , CareHub__r.CountryIsoCode__c
                                                    , CareHub__r.LanguageIsoCode__c
                                                    , LastModifiedDate
                                               FROM GCRChannelContent__c 
                                               WHERE RecordTypeId = :gcr_helperClass.getRecordTypeIdByDevName('GCRChannelContent__c', 'faq') 
                                                AND CareHub__c != null
                                                AND isActive__c = true ]) {
			String strBrand = 'gcr_careHubSiteMap?brand=' + eachChCont.CareHub__r.Brand__c;
			// REPLACE ESCAPED CHARACTERS
			strBrand = strBrand.replace('&', '&amp;');
			strBrand = strBrand.replace('\'', '&apos;');
			strBrand = strBrand.replace('"', '&quot;');
			strBrand = strBrand.replace('>', '&gt;');
			strBrand = strBrand.replace('<', '&lt;');
            mSitemaps.put(strBrand + '&amp;country=' + eachChCont.CareHub__r.CountryIsoCode__c 
                        + '&amp;language=' + eachChCont.CareHub__r.LanguageIsoCode__c
                      , String.valueOfGmt(eachChCont.LastModifiedDate).substring(0, 10));
        }
    }
}