src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRCountryIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAQCountry__c</fullName>
        <formula>IF(ISPICKVAL(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c, &apos;United States of America&apos;), &apos;United_States&apos;, SUBSTITUTE(TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c), &apos; &apos;, &apos;_&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FAQ Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageIsoCode__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.GCRLanguageIsoCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Iso Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageLocaleKey__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.Language_Locale_Key__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Locale Key</label>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field defines current active channels</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <recordTypes>
        <fullName>faq</fullName>
        <active>true</active>
        <description>Record type for faq</description>
        <label>faq</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/gcr_careHubSiteMapController.cls
/*
* @author:       Accenture
* @date:         16/01/2017
* @description:  Controller class of care hub sitemap
* DATE              NAME                CHANGE DESCRIPTION
* 16/01/2017       Accenture           Initial Draft
*/
public class gcr_careHubSiteMapController {
    public List<String> lKaExtUrl { get; set; }
    public String strDate { get; set; }
    /*
     * CONTROLLER CONSTRUCTOR
     */
    public gcr_careHubSiteMapController() {
        strDate = String.valueOfGmt(SYSTEM.now()).substring(0, 10);
        SYSTEM.DEBUG('BRAND : ' + ApexPages.currentPage().getParameters().get('brand'));
        SYSTEM.DEBUG('COUNTRY : ' + ApexPages.currentPage().getParameters().get('country'));
        SYSTEM.DEBUG('LANGUAGE : ' + ApexPages.currentPage().getParameters().get('language'));
        List<GCRChannelContent__c> lChannelContent = [ SELECT Id
                                                    , CareHub__r.Brand__c
                                                    , CareHub__r.FAQCountry__c
                                                    , CareHub__r.LanguageLocaleKey__c
                                                    , CareHub__r.LanguageIsoCode__c
                                                    , CareHub__r.CountryIsoCode__c
                                               FROM GCRChannelContent__c 
                                               WHERE RecordTypeId = :gcr_helperClass.getRecordTypeIdByDevName('GCRChannelContent__c', 'faq') 
                                                AND CareHub__c != null
                                                AND CareHub__r.Brand__c = :ApexPages.currentPage().getParameters().get('brand')
                                                AND CareHub__r.CountryIsoCode__c = :ApexPages.currentPage().getParameters().get('country')
                                                AND CareHub__r.LanguageIsoCode__c = :ApexPages.currentPage().getParameters().get('language')
                                                AND isActive__c = true ];
        if (lChannelContent != null && !lChannelContent.isEmpty()) {
            String bclUrl = '';
            lKaExtUrl = new List<String>();
            bclUrl += lChannelContent.get(0).CareHub__r.Brand__c;
            lKaExtUrl.add(bclUrl);
            bclUrl += '/' + lChannelContent.get(0).CareHub__r.LanguageIsoCode__c 
                    + '-' + lChannelContent.get(0).CareHub__r.CountryIsoCode__c;
            lKaExtUrl.add(bclUrl);
            bclUrl += '/faq';
            lKaExtUrl.add(bclUrl);
            List<KnowledgeArticleVersion> lKaVersion = Database.query(
                gcr_helperClass.prepareKAQueryString(lChannelContent.get(0).CareHub__r.FAQCountry__c
                                                   , lChannelContent.get(0).CareHub__r.Brand__c
                                                   , lChannelContent.get(0).CareHub__r.LanguageLocaleKey__c
                                                   , 'Online', null));
            for (KnowledgeArticleVersion eachKaVar :lKaVersion) {
                lKaExtUrl.add(bclUrl + '/' + eachKaVar.UrlName);
            }
        }
    }
}