src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>BackgroundImgLanding__c</fullName>
        <description>Background image for landing page</description>
        <label>Landing Page Background Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAQCountry__c</fullName>
        <formula>IF(ISPICKVAL(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c, &apos;United States of America&apos;), &apos;United_States&apos;, SUBSTITUTE(TEXT(BrandCountryLanguage__r.Contact_Us_Language__r.Country__c), &apos; &apos;, &apos;_&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FAQ Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LanguageLocaleKey__c</fullName>
        <formula>BrandCountryLanguage__r.Contact_Us_Language__r.Language_Locale_Key__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Language Locale Key</label>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/gcr_answerController.cls
/*
* @author:       Accenture
* @date:         10/11/2016
* @description:  Controller class for style component of GCR widget
* DATE					NAME					CHANGE DESCRIPTION
* 10/11/2016			Accenture				Initial Draft
*/
public class gcr_answerController {
	public String chlContentId { public get; public set; }
    public Boolean tempBln { get {
        if (channelContent == null) {
            String queryString = gcr_helperClass.createQueryString('SELECT'
                                                                 , gcr_helperClass.getAllFieldsForQuery('GCRChannelContent__c')
                                                                   + ',CareHub__r.BackgroundImgLanding__c,CareHub__r.FAQCountry__c,CareHub__r.LanguageLocaleKey__c'
                                                                   + ',CareHub__r.Brand__c'
                                                                 , 'GCRChannelContent__c')
                												+ ' WHERE Id = \'' + chlContentId + '\'' ;
			channelContent = (GCRChannelContent__c) Database.query(queryString).get(0);
        }
        return false;
    } set; }
    
    public GCRChannelContent__c channelContent { get; set; }
}