src/objects/GCRCareHub__c.object
<CustomObject>
    <description>Care hub object for contact us v4</description>
    <fields>
        <fullName>GCRLabelNext__c</fullName>
        <label>Next Page Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GCRLabelPrevious__c</fullName>
        <label>Previous Page Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Care Hub</label>
    <nameField>
        <displayFormat>SCH-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GCRChannelContent__c.object
<CustomObject>
    <description>Channel content data based on brand/country/language</description>
    <fields>
        <fullName>CareHub__c</fullName>
        <label>Care Hub</label>
        <referenceTo>GCRCareHub__c</referenceTo>
        <relationshipLabel>Care Hub Channel Contents</relationshipLabel>
        <relationshipName>GCRChannelContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default channel for country/brand/language</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DisplayName__c</fullName>
        <description>Display name for the channel same could vary based on country and name</description>
        <inlineHelpText>Please enter channel display name based on language and country</inlineHelpText>
        <label>Display Name</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisplayOrder__c</fullName>
        <description>Order on which icons should be shown on sidebar widget for selected brand, country and language</description>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field defines current active channels</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Care Hub Channel Content</label>
    <nameField>
        <displayFormat>GCR-{000000}</displayFormat>
        <label>Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Hub Channel Contents</pluralLabel>
    <recordTypes>
        <fullName>chat</fullName>
        <active>true</active>
        <description>Select this record type for chat channel</description>
        <label>chat</label>
    </recordTypes>
    <recordTypes>
        <fullName>faq</fullName>
        <active>true</active>
        <description>Record type for faq</description>
        <label>faq</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GCRChannelProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains Channel Properties for GCR widget.</description>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicate if channel is still active and used in the system</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Care Hub Channel Properties</label>
</CustomObject>

src/objects/GCRGenericProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains Generic Properties for GCR widget.</description>
    <fields>
        <fullName>value__c</fullName>
        <description>Field contains values for GCR widget Generic properties</description>
        <label>value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Care Hub Generic Properties</label>
</CustomObject>

src/classes/gcr_sidebarController.cls
/*
* @author: 		 Accenture
* @date: 		 05/19/2016
* @description:  Controller class for siderbar component of GCR widget
* DATE			NAME				CHANGE DESCRIPTION
* 05/19/2016	Accenture			INITIAL DRAFT
* 20/10/2016	Accenture			Additional processing for default chat channel added in method
									preparePageRecords(), where button availability required to be known before
									chat component render when chat is default channel.
*/
public class gcr_sidebarController {
    // ALL PUBLIC GETTER SETTER VARIABLES
    public gcr_WidgetHandshake iHandshake { public get; public set; }
    
    // ALL PUBLIC GETTER VARIABLES
    public List<GCRChannelProperties__c> lResourceData { public get; private set; }
    public Map<String, String> mDisplayName { public get; private set; }
    public Boolean controlConstructor { public get {
        if (controlConstructor == null) init();
        return false;
    } private set; }
    public String selectedChannel { get; set; }
    
    // PRIVATE VARIABLES
    private Integer totalRecords { private get; private set; }
    private Integer recordOffset { private get; private set; }

   /*
    * @date:		18/07/2016
    * @param:		none 
    * @return:		void
    * @description:	INIT METHOD OF CONTROLLER CUNSTRUCTOR
    */
    public void init() {
        this.recordOffset = 0;
        mDisplayName = new Map<String, String>();
        try {
            this.totalRecords = [ SELECT COUNT() FROM GCRChannelContent__c
                                  WHERE CareHub__r.Id = :iHandshake.lCareHub.get(0).Id AND isActive__c = true
                                  LIMIT :Limits.getLimitDMLRows() - Limits.getDMLRows() ];
            // GET ALL CHANNELS REQUIRED TO BE DISPLAYED ON PAGE
            // DEFAULT CHANNELS TO SHOW IS SET TO 5 IF NOT SET IN CUSTOM SETTINGS
            lResourceData = this.preparePageRecords(GCRGenericProperties__c.getInstance('gcr_ChannelCount') != null ?
                                                    Integer.valueOf(GCRGenericProperties__c.getInstance('gcr_ChannelCount').value__c) : 5
                                                  , this.recordOffset);
        } catch (Exception caughtException) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, GCRGenericProperties__c.getInstance('GCR_FATAL_ERRMSG').value__c));
            ApexPages.addMessages(caughtException);
        }
    }
    
   /*
    * @date:		18/07/2016
    * @param:		none 
    * @return:		void
    * @description:	ACTION METHOD FOR CHANNEL SELECTION, THIS METHOD EXECUTED WHEN USER CLICKS ON ANY CHANNEL ON THE PAGE
    */
    public void process() {
        iHandshake.gcrFunctionality = selectedChannel;
        if (selectedChannel.equalsIgnoreCase('chat')) {
            iHandshake.isChatVisited = gcr_helperClass.ischatBtnAvailable(iHandshake.mGcrContentId.get('chat'));
        }
    }
    
   /*
    * @date:		18/07/2016
    * @param:		none 
    * @return:		void
    * @description:	PAGINATION METHOD FOR CHANNELS TO GET NEXT SET OF CHANNELS
    */    
    public void next() {
        // GET TOTAL CHANNELS TO BE DISPLAYED ON THE SIDEBAR
        Integer pageSize = Integer.valueOf(GCRGenericProperties__c.getInstance('gcr_ChannelCount').value__c);
        recordOffset += this.totalRecords > pageSize ? (recordOffset < 1 ? pageSize - 1 : pageSize - 2) : pageSize;
        lResourceData = preparePageRecords(GCRGenericProperties__c.getInstance('gcr_ChannelCount') != null ?
                                                Integer.valueOf(GCRGenericProperties__c.getInstance('gcr_ChannelCount').value__c) : 5
                                           , this.recordOffset);
    }
    
   /*
    * @date:		18/07/2016
    * @param:		none 
    * @return:		void
    * @description:	PAGINATION METHOD FOR CHANNELS TO GET PREVIOUS SET OF CHANNELS
    */   
    public void previous() {
        Integer pageSize = Integer.valueOf(GCRGenericProperties__c.getInstance('gcr_ChannelCount').value__c);
        recordOffset -= recordOffset > pageSize - 1 ? pageSize - 2 : pageSize - 1;
        lResourceData = preparePageRecords(Integer.valueOf(GCRGenericProperties__c.getInstance('gcr_ChannelCount').value__c) != null ?
                                                Integer.valueOf(GCRGenericProperties__c.getInstance('gcr_ChannelCount').value__c) : 5
                                         , this.recordOffset);
    }
    
   /*
    * @date:		18/07/2016
    * @param:		Integer, Integer 
    * @return:		List<sObject>
    * @description:	METHOD TO PREPARE CHANNELD TO BE DISPLAYED ON THE PAGE
    */ 
    private List<GCRChannelProperties__c> preparePageRecords(Integer pageSize, Integer recordOffset) {
        List<GCRChannelProperties__c> retVal = new List<GCRChannelProperties__c>();
        Integer intQueryLimit = this.totalRecords > pageSize ? (recordOffset < 1 ? pageSize - 1 : pageSize - 2) : pageSize;
        if (recordOffset > 0) retVal.add(navigationIconData(false));
        for (GCRChannelContent__c eachContryLang :[ SELECT RecordType.Name, Name, DisplayName__c, Default__c FROM GCRChannelContent__c 
                         WHERE CareHub__r.Id = :iHandshake.lCareHub.get(0).Id AND isActive__c = true
						 ORDER BY DisplayOrder__c LIMIT :intQueryLimit OFFSET :recordOffset ]) {
			retVal.add(GCRChannelProperties__c.getInstance(eachContryLang.RecordType.Name));
			mDisplayName.put(eachContryLang.RecordType.Name, eachContryLang.DisplayName__c);
			// IF CHAT CHANNEL IS DEFAULT SET FUCNTIONALITY TO DEFAULTED CHANNEL
			if (eachContryLang.Default__c) {
				iHandshake.gcrFunctionality = eachContryLang.RecordType.Name;
                // IF CHAT CHANNEL IS DEFAULT GET CHAT BUTTON AVAILABILITY
                if (iHandshake.gcrFunctionality.equalsIgnoreCase('chat')) {
                    iHandshake.isChatVisited = gcr_helperClass.ischatBtnAvailable(iHandshake.mGcrContentId.get('chat'));
                }
            }
        }
        // IF ARTICLE DATA IS PASSED DEFAULT TO FAQ
		if (String.isNotEmpty(iHandshake.strKaUrlName)) {
			iHandshake.gcrFunctionality = 'faq';
		}
        if (recordOffset + pageSize < this.totalRecords) retVal.add(navigationIconData(true));
        controlConstructor = true;
        return retVal;
    }
    
   /*
    * @date:		18/07/2016
    * @param:		Boolean
    * @return:		sObject
    * @description:	METHOD TO PREPARE GET PAGINATION DATA (PREVIOUS OR NEXT) BASED ON PASSED PARAMETER
    */
    private GCRChannelProperties__c navigationIconData(Boolean isNext) {
        if(isNext) {
            mDisplayName.put('next', iHandshake.lCareHub.get(0).GCRLabelNext__c);
            return GCRChannelProperties__c.getInstance('next');
		} else {
			mDisplayName.put('previous', iHandshake.lCareHub.get(0).GCRLabelPrevious__c);
            return GCRChannelProperties__c.getInstance('previous');
		}
    }
}