src/objects/Internal_Activity__c.object
<CustomObject>
    <description>Object storing agent feedback on articles.</description>
    <fields>
        <fullName>Assessment_Close_Date__c</fullName>
        <label>Assessment Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assessment_Open_Date__c</fullName>
        <label>Assessment Open Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assessment_SLA_Flag__c</fullName>
        <label>Assessment SLA Flag</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reminder_Date__c</fullName>
        <label>Reminder Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Knowledge - Increase in Trends</fullName>
                </value>
                <value>
                    <fullName>Knowledge - Suggestion to Improve Knowledge</fullName>
                </value>
                <value>
                    <fullName>Knowledge - Missing, Incomplete Knowledge</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Research</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Management Review</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - For Information Only</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Recontact Consumer</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Internal Activity</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Internal Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_InternalActivityTriggerHandler.cls
public with sharing class sf_InternalActivityTriggerHandler {

	public void onBeforeUpdate(List<Internal_Activity__c> newInternalActivities, List<Internal_Activity__c> oldInternalActivities, Map<Id, Internal_Activity__c> newMap, Map<Id, Internal_Activity__c> oldMap){
	
		changeAssignedTo(newInternalActivities, oldInternalActivities, newMap, oldMap);
		
	}
	
	public void onAfterInsert(List<Internal_Activity__c> newInternalActivities){
	
		createReminder(newInternalActivities);
	
	}
	
	public void changeAssignedTo(List<Internal_Activity__c> newInternalActivities, List<Internal_Activity__c> oldInternalActivities, Map<Id, Internal_Activity__c> newMap, Map<Id, Internal_Activity__c> oldMap){
		
		for(Internal_Activity__c ia: newInternalActivities){
			if((ia.Type__c == sf_Constants.INTERNAL_ACTIVITY_TYPE_KNOWLEDGE_MISSING_INCOMPLETE_KNOWLEDGE 
	        	|| ia.Type__c== sf_Constants.INTERNAL_ACTIVITY_TYPE_KNOWLEDGE_INCREASE_IN_TRENDS
	        	|| ia.Type__c== sf_Constants.INTERNAL_ACTIVITY_TYPE_KNOWLEDGE_SERVICES) 
	        	&& ia.Assessment_Close_Date__c != null &&  ia.Assessment_Open_Date__c != null){
	        	
	            if((ia.Assessment_Close_Date__c.getTime() - ia.Assessment_Open_Date__c.getTime()) <7*24*60*60*1000){
	                ia.Assessment_SLA_Flag__c = sf_Constants.INTERNAL_ACTIVITY_SLA_FLAG_GREEN;
	            } else {
	            	ia.Assessment_SLA_Flag__c = sf_Constants.INTERNAL_ACTIVITY_SLA_FLAG_RED;
	            }     
	            	
	            
	            if(ia.Type__c == sf_Constants.INTERNAL_ACTIVITY_TYPE_KNOWLEDGE_MISSING_INCOMPLETE_KNOWLEDGE 
	            	&& oldMap.get(ia.Id).Assessment_Close_Date__c != newMap.get(ia.Id).Assessment_Close_Date__c){
	                	Internal_Activity__c temp=[Select createdbyid from internal_Activity__c where id=:ia.Id];
	                	ia.ownerid = temp.createdbyid;
	                	List<User> u = [select id, name from User where Id = :temp.createdbyid];
	                	if(u.size() > 0) ia.Assigned_To__c = u[0].name;
	            }
	        }
	    }
	}
	
	public void createReminder(List<Internal_Activity__c> newInternalActivities){
	
		List<Task> taskList=new List<Task>();
	    for(Internal_Activity__c ia: newInternalActivities)
	    {
	        if(ia.Reminder__c == true && ia.Reminder_Date__c != null)
	        {
	            Task task = new Task();
	            task.whatId = ia.Id;
	            task.subject = ia.subject__c;
	            task.ActivityDate = date.valueOf(ia.Due_date__c);
	            task.ReminderDateTime = ia.Reminder_Date__c;
	            task.IsReminderSet = true;
	            taskList.add(task);
	        }
	    }
	    
	    if(taskList.size()>0)
	    insert taskList;
	
	}
}