src/objects/Internal_Activity__c.object
<CustomObject>
    <description>Object storing agent feedback on articles.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Internal Activity</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Internal Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InternalActivityUtility.cls
global class InternalActivityUtility
{
    webservice static Integer CloseActivity(List<String> activityIds)
    {
        try
        {
            List<Internal_Activity__c> alist=new List<Internal_Activity__c>();
            for(String s:activityIds)
            {
                 Internal_activity__c ia=new Internal_Activity__c(id=s);
                 ia.Status__c='Closed';
                 alist.add(ia);   
            }
            update alist;
            return 1;
        }
        catch(Exception e)
        {
            return 0;
        }
    }
}