src/objects/Internal_Activity__c.object
<CustomObject>
    <description>Object storing agent feedback on articles.</description>
    <fields>
        <fullName>Article_ID__c</fullName>
        <label>Article ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Close_Date__c</fullName>
        <label>Assessment Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assessment_Open_Date__c</fullName>
        <label>Assessment Open Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Knowledge_Article_Suggestion_Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reminder_Date__c</fullName>
        <label>Reminder Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Knowledge - Increase in Trends</fullName>
                </value>
                <value>
                    <fullName>Knowledge - Suggestion to Improve Knowledge</fullName>
                </value>
                <value>
                    <fullName>Knowledge - Missing, Incomplete Knowledge</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Research</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Management Review</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - For Information Only</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Recontact Consumer</fullName>
                </value>
                <value>
                    <fullName>Operational Questions - Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Internal Activity</label>
    <nameField>
        <displayFormat>IA-{0000000000}</displayFormat>
        <label>Internal Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_InternalActivityTriggerHandlerTest.cls
@isTest
private class sf_InternalActivityTriggerHandlerTest {
	
	@isTest static void test_method_one() {

		Case c = new Case ();
		insert c;

		Internal_Activity__c ia = new Internal_Activity__c ();
		ia.Reminder__c = true;
		ia.Reminder_Date__c = System.today();
		ia.Case__c = c.Id;
		insert ia;

		ia.Article_ID__c = 'test';
		ia.Type__c = sf_Constants.INTERNAL_ACTIVITY_TYPE_KNOWLEDGE_MISSING_INCOMPLETE_KNOWLEDGE;
		update ia;


		
	}


	@isTest static void test_method_two() {

		Case c = new Case ();
		insert c;

		Internal_Activity__c ia = new Internal_Activity__c ();
		ia.Reminder__c = true;
		ia.Reminder_Date__c = System.today();
		ia.Assessment_Close_Date__c =  System.today() + 20;
		ia.Assessment_Open_Date__c =  System.today() + 3;
		ia.Case__c = c.Id;
		insert ia;

		ia.Article_ID__c = 'test';
		ia.Assessment_Close_Date__c = System.today() + 30;
		ia.Type__c = sf_Constants.INTERNAL_ACTIVITY_TYPE_KNOWLEDGE_MISSING_INCOMPLETE_KNOWLEDGE;
		update ia;
	}

	
}