src/objects/Metadata_Survey_Trigger__c.object
<CustomObject>
    <description>This object will store information from the Global Product and Global Comment Code that will be used to trigger the correct survey.</description>
    <fields>
        <fullName>Last_30_Day_Count__c</fullName>
        <label>Last 30 Day Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_60_Day_Count__c</fullName>
        <label>Last 60 Day Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_90_Day_Count__c</fullName>
        <label>Last 90 Day Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trigger_Count_Last_Updated__c</fullName>
        <description>Date 30/60/90 Days Trigger Count fields were last updated</description>
        <inlineHelpText>Date 30/60/90 Days Trigger Count fields were last updated</inlineHelpText>
        <label>Trigger Count Last Updated</label>
        <type>DateTime</type>
    </fields>
    <label>Metadata Survey Trigger</label>
    <nameField>
        <displayFormat>MTN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Survey Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MST_Action_Count__c.object
<CustomObject>
    <description>Roll up feature so that we can tell how many field set names have been shown. 
Count of how many times an Ad Hoc survey was used over a timeframe
Last 30, 60, 90 days (if need other duration needs to be defined now)
Lifetime

US592</description>
    <fields>
        <fullName>Date_Triggered__c</fullName>
        <label>Date Triggered</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Metadata_Survey_Trigger__c</fullName>
        <label>Metadata Survey Trigger</label>
        <referenceTo>Metadata_Survey_Trigger__c</referenceTo>
        <relationshipLabel>MST Action Counts</relationshipLabel>
        <relationshipName>MST_Action_Counts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MST Action Count</label>
    <nameField>
        <displayFormat>MSTAC-{000000000}</displayFormat>
        <label>Metadata Survey Trigger Action Count Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MST Action Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MSTCount.cls
//Use this to run in Execute Anonymous -> Id BatchJobMSTCount = Database.executeBatch(new MSTCount(), 1);
/*
* @author: Accenture - CD
* @date: 22/06/2017
* @description:  Batch job to update the MST Count figures per record. Batch size of 1 Only.
*/
global class MSTCount implements Database.Batchable<sObject>{

    private static final Integer LIMIT_QUERY_ROW = Limits.getLimitQueryRows();
    private static final Date TODAY_MINUS_30 = date.Today()-30;
    private static final Date TODAY_MINUS_60 = date.Today()-60;
    private integer thirtyDayCount = 0;
    private integer sixtyDayCount = 0;

    //START
    global Database.QueryLocator start(Database.BatchableContext BC){
        //String str ='SELECT Id FROM Metadata_Survey_Trigger__c WHERE createdDate = LAST_MONTH';
        String str ='SELECT Id, Last_90_Day_Count__c FROM Metadata_Survey_Trigger__c WHERE lastModifiedDate = LAST_N_DAYS:90';
        return Database.getQueryLocator(str);
    }
    
    //Execute Small Queries
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Metadata_Survey_Trigger__c> mstList = (List<Metadata_Survey_Trigger__c>)scope;
        
        //instanciate set of ids
        set <Id> mstIds = new set <id>();

        //in For loop add mst.id to your set of ids
        for (Metadata_Survey_Trigger__c mst : mstList){
            
            mstIds.add(mst.Id);
        }
        system.debug('***CDOY*** Size'+ mstIds.size());
 
        List<MST_Action_Count__c> MAC = [SELECT id, Date_Triggered__c FROM MST_Action_Count__c WHERE Date_Triggered__c = LAST_N_DAYS:90 AND Metadata_Survey_Trigger__c IN :mstIds LIMIT :LIMIT_QUERY_ROW]; 
        
        for(MST_Action_Count__c m : MAC){

            if(m.Date_Triggered__c >= TODAY_MINUS_30){
                thirtyDayCount++;
                sixtyDayCount++;
            }

            else if (m.Date_Triggered__c >= TODAY_MINUS_60){
                sixtyDayCount++;
            }
        }

        mstList[0].Last_90_Day_Count__c = MAC.size();
        mstList[0].Last_60_Day_Count__c = sixtyDayCount;
        mstList[0].Last_30_Day_Count__c = thirtyDayCount;
        mstList[0].Trigger_Count_Last_Updated__c = DateTime.now();

        if(mstList[0].Last_90_Day_Count__c != null){
         Database.SaveResult[] results = Database.Update(mstList, false); //update last modified date
        }
        
    } 

    //Finish
	global void finish(Database.BatchableContext BC){
   	}

}