src/objects/Metadata_Survey_Trigger__c.object
<CustomObject>
    <description>This object will store information from the Global Product and Global Comment Code that will be used to trigger the correct survey.</description>
    <fields>
        <fullName>Last_30_Day_Count__c</fullName>
        <label>Last 30 Day Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_60_Day_Count__c</fullName>
        <label>Last 60 Day Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_90_Day_Count__c</fullName>
        <label>Last 90 Day Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metadata Survey Trigger</label>
    <nameField>
        <displayFormat>MTN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Survey Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MST_Action_Count__c.object
<CustomObject>
    <description>Roll up feature so that we can tell how many field set names have been shown. 
Count of how many times an Ad Hoc survey was used over a timeframe
Last 30, 60, 90 days (if need other duration needs to be defined now)
Lifetime

US592</description>
    <fields>
        <fullName>Date_Triggered__c</fullName>
        <label>Date Triggered</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Metadata_Survey_Trigger__c</fullName>
        <label>Metadata Survey Trigger</label>
        <referenceTo>Metadata_Survey_Trigger__c</referenceTo>
        <relationshipLabel>MST Action Counts</relationshipLabel>
        <relationshipName>MST_Action_Counts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MST Action Count</label>
    <nameField>
        <displayFormat>MSTAC-{000000000}</displayFormat>
        <label>Metadata Survey Trigger Action Count Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MST Action Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MSTCountTest.cls
/*
* @author: Accenture - CD
* @date: 23/06/2017
* @description: Test Class for MSTCount
*/
@isTest
private class MSTCountTest {
	public static testmethod void MSTCountTest() {
	
		Metadata_Survey_Trigger__c mst = new Metadata_Survey_Trigger__c();
		insert mst;

		MST_Action_Count__c mac1 = new MST_Action_Count__c();
		mac1.date_triggered__c = date.Today()-30;
		mac1.Metadata_Survey_Trigger__c = mst.id;
		insert mac1;

		MST_Action_Count__c mac2 = new MST_Action_Count__c();
		mac2.date_triggered__c = date.Today()-60;
		mac2.Metadata_Survey_Trigger__c = mst.id;
		insert mac2;


		system.debug('mac2.date_triggered__c***'+mac2.date_triggered__c);

		Test.startTest();

			MSTCount batch = new MSTCount();
			Database.executeBatch(batch, 1);

		Test.stopTest();

		Metadata_Survey_Trigger__c mst_new = [SELECT Last_90_Day_Count__c, Last_60_Day_Count__c, Last_30_Day_Count__c FROM Metadata_Survey_Trigger__c where id =: mst.id ];

		system.assertEquals(2, mst_new.Last_90_Day_Count__c);
		system.assertEquals(2, mst_new.Last_60_Day_Count__c);
		system.assertEquals(1, mst_new.Last_30_Day_Count__c);

	}

}