src/objects/One_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Expected_Due_Date__c</fullName>
        <description>Value should default the Requested Due Date and be editable by person handling the ticket</description>
        <inlineHelpText>Value should default the Requested Due Date and be editable by person handling the ticket</inlineHelpText>
        <label>Actual Expected Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <formula>IF(now()&lt; Actual_Expected_Due_Date__c ,IMAGE(&apos;https://c.na6.content.force.com/servlet/servlet.FileDownload?file=01580000001szWG&amp;oid=&apos;+$Organization.Id,&apos;Green&apos;), IF( OR(Request_Closed_Date__c &lt; Actual_Expected_Due_Date__c, ISBLANK(Actual_Expected_Due_Date__c ) ) , IMAGE(&apos;https://c.na6.content.force.com/servlet/servlet.FileDownload?file=01580000001szWG&amp;oid=&apos;+$Organization.Id,&apos;Green&apos;), IMAGE(&apos;https://c.na6.content.force.com/servlet/servlet.FileDownload?file=01580000001szWL&amp;oid=&apos;+$Organization.Id,&apos;Red&apos;)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>RED Flag indicates that the current date time is exceeded &apos;Actual Expected Due Date&apos;, and still the request is not closed.</inlineHelpText>
        <label>Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Return to Requestor - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Return to Requestor - Clarification</fullName>
                </value>
                <value>
                    <fullName>Return to Infosys</fullName>
                </value>
                <value>
                    <fullName>Return to Approver - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Return to Approver - Clarification</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>1STOP</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OneStopHomeCon.cls
public class OneStopHomeCon{

    public OneStopHomeCon() {

    }


    //public OneStopHomeCon(ApexPages.StandardController controller) {

    //}


    public List<One_Stop__c> getmyrequests(){
        return [select Id,Name,Status__c,Priority__c,Flag__c,Actual_Expected_Due_Date__c,CreatedDate from One_Stop__c where status__c!='Closed' and ownerId=:UserInfo.getUserId() order by Actual_Expected_Due_Date__c asc limit 1000];
    }
    
    public List<One_Stop__c> getapprovedrequests(){
        Id OneSTOPApprovedQueueId = [select Id from Group where name = '1STOP Approved'].Id;
        return [select Id,Name,Status__c,Priority__c,Flag__c,Actual_Expected_Due_Date__c,CreatedDate from One_Stop__c where ownerId=:OneSTOPApprovedQueueId order by Actual_Expected_Due_Date__c asc limit 1000];
    }
    
    public List<One_Stop__c> gettobeapprovedrequests(){
        Id OneSTOPNeedsApprovalQueueId = [select Id from Group where name = '1STOP Needs Approval'].Id;
        return [select Id,Name,Status__c,Priority__c,Flag__c,Actual_Expected_Due_Date__c,CreatedDate from One_Stop__c where ownerId=:OneSTOPNeedsApprovalQueueId order by Actual_Expected_Due_Date__c asc limit 1000];
    }
    
    public List<One_Stop__c> getRequestsCreatedByMe(){
        return [select Id,Name,Status__c,Priority__c,Flag__c,Actual_Expected_Due_Date__c,CreatedDate from One_Stop__c where createdById=:UserInfo.getUserId() order by Actual_Expected_Due_Date__c asc limit 1000];
    }
    
    

}