src/objects/One_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Request_Closed_Date__c</fullName>
        <inlineHelpText>Date and Time when the request was closed</inlineHelpText>
        <label>Request Closed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>It includes Approver, Owner, Requestor and Additional To Emails. 
If this is a new request and needs approval, then notification includes members of queue.</inlineHelpText>
        <label>Send Notification To Everyone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Return to Requestor - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Return to Requestor - Clarification</fullName>
                </value>
                <value>
                    <fullName>Return to Infosys</fullName>
                </value>
                <value>
                    <fullName>Return to Approver - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Return to Approver - Clarification</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>1STOP</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OneSTOPComment__c.object
<CustomObject>
    <fields>
        <fullName>Comment1__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1STOP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>1STOP</label>
        <referenceTo>One_Stop__c</referenceTo>
        <relationshipName>X1STOPComments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>1STOPComment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>1STOPComment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOPComments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OneStopCloseCon.cls
public class OneStopCloseCon {

    One_Stop__c request;       
    ApexPages.StandardController currentcontroller;
    String status;
    public string xComment{get; set;}
    //public string NotificaComment {set; get;}
    
    public OneStopCloseCon(ApexPages.StandardController controller) {
        request = (One_Stop__c)controller.getRecord();
        status = [select Status__c from One_Stop__c where id=:request.Id].Status__c;  
        system.debug('################# Status: '+status);      
        currentcontroller = controller;
    }
    
    public PageReference Save(){
        if(request != null){
            if(status=='Closed'){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This request has already been closed'));
                return null;
            }
            else {
                OneSTOPComment__c req = new OneSTOPComment__c(X1STOP__c = request.Id );
                req.comment1__c = 'CLOSE REQUEST COMMENTS \n\n'+ xComment;
                req.name__c = UserInfo.getName();
                request.Status__c='Closed';
                request.Request_Closed_Date__c=System.now();
                request.Send_Email__c = true;
                
                insert req;
                update request;
                return currentcontroller.view();
            }
        }
        else return null;
    }

}