src/objects/One_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AutoResponse</fullName>
                </value>
                <value>
                    <fullName>Case Data</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>CX</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Internal Activities</fullName>
                </value>
                <value>
                    <fullName>Knowledge</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>System Troubleshooting</fullName>
                </value>
                <value>
                    <fullName>User Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Subcategory__c</fullName>
        <label>Request Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Add Queues</fullName>
                </value>
                <value>
                    <fullName>Add Source codes</fullName>
                </value>
                <value>
                    <fullName>Add Users to Queue</fullName>
                </value>
                <value>
                    <fullName>Advice/Questions/How to Use</fullName>
                </value>
                <value>
                    <fullName>Assign to email queue</fullName>
                </value>
                <value>
                    <fullName>Block Chat Visitor</fullName>
                </value>
                <value>
                    <fullName>Case Data Correction</fullName>
                </value>
                <value>
                    <fullName>Case Deletion</fullName>
                </value>
                <value>
                    <fullName>Change Case Country/Owner</fullName>
                </value>
                <value>
                    <fullName>Change Existing Template</fullName>
                </value>
                <value>
                    <fullName>Change User Permissions/Profile/Role</fullName>
                </value>
                <value>
                    <fullName>Create queue/groups</fullName>
                </value>
                <value>
                    <fullName>CX IVR Results Load</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
                <value>
                    <fullName>Deactivate User and remove from groups/queues</fullName>
                </value>
                <value>
                    <fullName>Delete queue/groups</fullName>
                </value>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>Edit/Corrections</fullName>
                </value>
                <value>
                    <fullName>Edit Existing AutoResponse</fullName>
                </value>
                <value>
                    <fullName>Featured Articles</fullName>
                </value>
                <value>
                    <fullName>GCR Training Website</fullName>
                </value>
                <value>
                    <fullName>Kardia System Error</fullName>
                </value>
                <value>
                    <fullName>Locked object data corrections</fullName>
                </value>
                <value>
                    <fullName>Mass Email</fullName>
                </value>
                <value>
                    <fullName>New AutoResponse</fullName>
                </value>
                <value>
                    <fullName>New Email Template</fullName>
                </value>
                <value>
                    <fullName>New PROD User</fullName>
                </value>
                <value>
                    <fullName>New Report/Dashboard</fullName>
                </value>
                <value>
                    <fullName>New TRAIN User</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Due_Date__c</fullName>
        <inlineHelpText>This date is the requested date and may change based on SLA agreement or priority against other work</inlineHelpText>
        <label>Requested Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1STOP_Approval__c</fullName>
        <label>1STOP Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Admin Handled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>1STOP</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OneStopSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Approval_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Needed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>1 to 5. high to low</description>
        <label>Priority</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <inlineHelpText>Insert in hours</inlineHelpText>
        <label>SLA</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub-Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OneStopSettings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>X1STOP_Approver__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Allow the user to approve 1STOP requests</inlineHelpText>
        <label>1STOP Approver</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_OneStopTrigger.cls
@isTest
private class Test_OneStopTrigger 
{
    public static testmethod void testOneStopTrigger1(){    
    
        OneStopSettings__c csobj=new OneStopSettings__c();
        csobj.Category__c='Other';
        csobj.Sub_Category__c='Other';
        csobj.Priority__c='1';
        csobj.SLA__c=120;
        csobj.name='Dataset1';
        csobj.Approval_Needed__c=false;
        insert csobj;
        
        OneStopSettings__c csobj2=new OneStopSettings__c();
        csobj2.Category__c='Email';
        csobj2.Sub_Category__c='Setup HTML email';
        csobj2.Priority__c='1';
        csobj2.SLA__c=120;
        csobj2.name='Dataset2';
        csobj2.Approval_Needed__c=true;
        insert csobj2;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = true,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg2.pandg.com');
                    
        User u2 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = false,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.pandg.com');
                    
        System.runAs(u1) {
            
            One_Stop__c obj=new One_Stop__c();
            obj.Request_Category__c='Other';
            obj.Request_Subcategory__c='Other';
            insert obj;
            
             One_Stop__c obj2=new One_Stop__c();
            obj2.Request_Category__c='Email';
            obj2.Request_Subcategory__c='Setup HTML email';
            insert obj2;
            
            One_Stop__c obj4=new One_Stop__c();
            obj4.Request_Category__c='Email';
            obj4.Request_Subcategory__c='Setup HTML email';
            obj4.Requested_Due_Date__c=system.now()-1;
            insert obj4;
            
            One_Stop__c obj5=new One_Stop__c();
            obj5.Request_Category__c='Email';
            obj5.Request_Subcategory__c='Setup HTML email';
            obj5.Requested_Due_Date__c=system.now()+100;
            insert obj5;
          

        }             
                    
        System.runAs(u2) {
            One_Stop__c obj3=new One_Stop__c();
            obj3.Request_Category__c='Email';
            obj3.Request_Subcategory__c='Setup HTML email';
            insert obj3;
            
             One_Stop__c obj2=new One_Stop__c();
            obj2.Request_Category__c='Email';
            obj2.Request_Subcategory__c='Setup HTML email';
            insert obj2;
            
            One_Stop__c obj4=new One_Stop__c();
            obj4.Request_Category__c='Email';
            obj4.Request_Subcategory__c='Setup HTML email';
            obj4.Requested_Due_Date__c=system.now()-1;
            insert obj4;
            
            One_Stop__c obj5=new One_Stop__c();
            obj5.Request_Category__c='Email';
            obj5.Request_Subcategory__c='Setup HTML email';
            obj5.Requested_Due_Date__c=system.now()+100;
            insert obj5;
            
          
        }

    }
    
     public static testmethod void testOneStopTrigger2(){    
    
        OneStopSettings__c csobj=new OneStopSettings__c();
        csobj.Category__c='Other';
        csobj.Sub_Category__c='Other';
        csobj.Priority__c='1';
        csobj.SLA__c=120;
        csobj.name='Dataset1';
        csobj.Approval_Needed__c=false;
        insert csobj;
        
        OneStopSettings__c csobj2=new OneStopSettings__c();
        csobj2.Category__c='Email';
        csobj2.Sub_Category__c='Setup HTML email';
        csobj2.Priority__c='1';
        csobj2.SLA__c=120;
        csobj2.name='Dataset2';
        csobj2.Approval_Needed__c=true;
        insert csobj2;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = true,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg2.pandg.com');
                    
        User u2 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = false,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.pandg.com');
                    
        System.runAs(u1) {
            One_Stop__c obj=new One_Stop__c();
            obj.Request_Category__c='Other';
            obj.Request_Subcategory__c='Other';
            insert obj;
            
            obj.X1STOP_Approval__c = 'Approved';
            update obj;
            
              One_Stop__c obj2=new One_Stop__c();
            obj2.Request_Category__c='Email';
            obj2.Request_Subcategory__c='Setup HTML email';
            insert obj2;
            
            obj2.X1STOP_Approval__c = 'Approved';
            update obj2;
            
            One_Stop__c obj4=new One_Stop__c();
            obj4.Request_Category__c='Email';
            obj4.Request_Subcategory__c='Setup HTML email';
            obj4.Requested_Due_Date__c=system.now()-1;
            insert obj4;
            
            obj4.X1STOP_Approval__c = 'Approved';
            update obj4;
            
            
            One_Stop__c obj5=new One_Stop__c();
            obj5.Request_Category__c='Email';
            obj5.Request_Subcategory__c='Setup HTML email';
            obj5.Requested_Due_Date__c=system.now()+100;
            insert obj5;
            
            obj5.X1STOP_Approval__c = 'Approved';
            update obj5;
        

        }             
                    
        System.runAs(u2) {
            One_Stop__c obj3=new One_Stop__c();
            obj3.Request_Category__c='Email';
            obj3.Request_Subcategory__c='Setup HTML email';
            insert obj3;
            
            system.runAs(u1){
                
            obj3.X1STOP_Approval__c = 'Approved';
            update obj3;
            }
            
          
        }

    }
    
    public static testmethod void testOneStopTrigger3(){    
    
        OneStopSettings__c csobj=new OneStopSettings__c();
        csobj.Category__c='Other';
        csobj.Sub_Category__c='Other';
        csobj.Priority__c='1';
        csobj.SLA__c=120;
        csobj.name='Dataset1';
        csobj.Approval_Needed__c=false;
        insert csobj;
        
        OneStopSettings__c csobj2=new OneStopSettings__c();
        csobj2.Category__c='Email';
        csobj2.Sub_Category__c='Setup HTML email';
        csobj2.Priority__c='1';
        csobj2.SLA__c=120;
        csobj2.name='Dataset2';
        csobj2.Approval_Needed__c=true;
        insert csobj2;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = true,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg2.pandg.com');
                    
        User u2 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = false,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.pandg.com');
                    
        
                    
        System.runAs(u2) {
            One_Stop__c obj3=new One_Stop__c();
            obj3.Request_Category__c='Email';
            obj3.Request_Subcategory__c='Setup HTML email';
            insert obj3;
            
            
            
            system.runAs(u1){
                
            obj3.X1STOP_Approval__c = 'Admin Handled';
            update obj3;
            }
        }

    }
    public static testmethod void testOneStopTrigger4(){    
    
        OneStopSettings__c csobj=new OneStopSettings__c();
        csobj.Category__c='Other';
        csobj.Sub_Category__c='Other';
        csobj.Priority__c='1';
        csobj.SLA__c=120;
        csobj.name='Dataset1';
        csobj.Approval_Needed__c=false;
        insert csobj;
        
        OneStopSettings__c csobj2=new OneStopSettings__c();
        csobj2.Category__c='Email';
        csobj2.Sub_Category__c='Setup HTML email';
        csobj2.Priority__c='1';
        csobj2.SLA__c=120;
        csobj2.name='Dataset2';
        csobj2.Approval_Needed__c=true;
        insert csobj2;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = true,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg2.pandg.com');
                    
        User u2 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, X1STOP_Approver__c = false,
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.pandg.com');
                    
        
                    
        System.runAs(u2) {
            One_Stop__c obj3=new One_Stop__c();
            obj3.Request_Category__c='Email';
            obj3.Request_Subcategory__c='Setup HTML email';
            insert obj3;
            
             system.runAs(u1){
                
           obj3.X1STOP_Approval__c = 'Rejected';
            update obj3;
            }
            
           
        }

    }
}