src/objects/One_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Reopened_Count__c</fullName>
        <description>It tells how many times a request has been reopened</description>
        <inlineHelpText>This number tells how many times the request has been reopened.</inlineHelpText>
        <label>Reopened Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>It includes Approver, Owner, Requestor and Additional To Emails. 
If this is a new request and needs approval, then notification includes members of queue.</inlineHelpText>
        <label>Send Notification To Everyone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Return to Requestor - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Return to Requestor - Clarification</fullName>
                </value>
                <value>
                    <fullName>Return to Infosys</fullName>
                </value>
                <value>
                    <fullName>Return to Approver - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Return to Approver - Clarification</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>1STOP</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OneSTOPComment__c.object
<CustomObject>
    <fields>
        <fullName>Comment1__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1STOP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>1STOP</label>
        <referenceTo>One_Stop__c</referenceTo>
        <relationshipName>X1STOPComments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>1STOPComment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>1STOPComment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOPComments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OneStopReopenCon.cls
public class OneStopReopenCon {
    public string xComment{get; set;}
    One_Stop__c request;
    ApexPages.StandardController currentcontroller;
    Decimal reopencount;
    
    public OneStopReopenCon(ApexPages.StandardController controller) {
        request = (One_Stop__c) controller.getRecord();
        reopencount = [select Reopened_Count__c, Status__c,Send_Email__c from One_Stop__c where id=:request.Id].Reopened_Count__c;        
        currentcontroller = controller;
    }
    
    public PageReference Save(){        
        OneSTOPComment__c req = new OneSTOPComment__c(X1STOP__c = request.Id );
        request.Status__c='Open';        
        req.Comment1__c='REQUEST HAS BEEN REOPENED. \n\n'+xComment;
        request.Send_Email__c=true;
        req.name__c = UserInfo.getName();
        if(reopencount==null) request.Reopened_Count__c=1;
        else request.Reopened_Count__c=reopencount+1;        
        insert req;
        update request;
        return currentcontroller.view();        
    }

}