src/objects/One_Stop__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Category__c</fullName>
        <label>Request Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AutoResponse</fullName>
                </value>
                <value>
                    <fullName>Case Data</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>CX</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Internal Activities</fullName>
                </value>
                <value>
                    <fullName>Knowledge</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>System Troubleshooting</fullName>
                </value>
                <value>
                    <fullName>User Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Subcategory__c</fullName>
        <label>Request Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Add Queues</fullName>
                </value>
                <value>
                    <fullName>Add Source codes</fullName>
                </value>
                <value>
                    <fullName>Add Users to Queue</fullName>
                </value>
                <value>
                    <fullName>Advice/Questions/How to Use</fullName>
                </value>
                <value>
                    <fullName>Assign to email queue</fullName>
                </value>
                <value>
                    <fullName>Block Chat Visitor</fullName>
                </value>
                <value>
                    <fullName>Case Data Correction</fullName>
                </value>
                <value>
                    <fullName>Case Deletion</fullName>
                </value>
                <value>
                    <fullName>Change Case Country/Owner</fullName>
                </value>
                <value>
                    <fullName>Change Existing Template</fullName>
                </value>
                <value>
                    <fullName>Change User Permissions/Profile/Role</fullName>
                </value>
                <value>
                    <fullName>Create queue/groups</fullName>
                </value>
                <value>
                    <fullName>CX IVR Results Load</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
                <value>
                    <fullName>Deactivate User and remove from groups/queues</fullName>
                </value>
                <value>
                    <fullName>Delete queue/groups</fullName>
                </value>
                <value>
                    <fullName>Deployment</fullName>
                </value>
                <value>
                    <fullName>Edit/Corrections</fullName>
                </value>
                <value>
                    <fullName>Edit Existing AutoResponse</fullName>
                </value>
                <value>
                    <fullName>Featured Articles</fullName>
                </value>
                <value>
                    <fullName>GCR Training Website</fullName>
                </value>
                <value>
                    <fullName>Kardia System Error</fullName>
                </value>
                <value>
                    <fullName>Locked object data corrections</fullName>
                </value>
                <value>
                    <fullName>Mass Email</fullName>
                </value>
                <value>
                    <fullName>New AutoResponse</fullName>
                </value>
                <value>
                    <fullName>New Email Template</fullName>
                </value>
                <value>
                    <fullName>New PROD User</fullName>
                </value>
                <value>
                    <fullName>New Report/Dashboard</fullName>
                </value>
                <value>
                    <fullName>New TRAIN User</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>1STOP</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OneStopSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>1 to 5. high to low</description>
        <label>Priority</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <inlineHelpText>Insert in hours</inlineHelpText>
        <label>SLA</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub-Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OneStopSettings</label>
</CustomObject>

src/classes/Test_OneStopHistoryRelatedListController.cls
@isTest
private class Test_OneStopHistoryRelatedListController 
{
    public static testmethod void testOneStopHistoryRelatedListController(){
        OneStopSettings__c csobj=new OneStopSettings__c();
        csobj.Category__c='Other';
        csobj.Sub_Category__c='Other';
        csobj.Priority__c='1';
        csobj.SLA__c=120;
        csobj.name='Dataset1';
        insert csobj;
        
        One_Stop__c obj=new One_Stop__c();
        obj.Request_Category__c='Other';
        obj.Request_Subcategory__c='Other';
        insert obj;
        
        OneStopHistoryRelatedListController.historyWrapper wrapper =new OneStopHistoryRelatedListController.historyWrapper('Test','TestOld','TestNew','updatedbywho',obj.Id,system.now(),'fldlabel');
        OneStopHistoryRelatedListController con=new OneStopHistoryRelatedListController();
        con.oneStop=new One_Stop__c();
        con.getHistoryDetails();
        con.returnFieldLabel('Request_Category__c');
        con.returnFieldLabel('Test');
    } 
}