src/objects/One_Stop__c.object
<CustomObject>
    <label>1STOP</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OneSTOPComment__c.object
<CustomObject>
    <fields>
        <fullName>Comment1__c</fullName>
        <label>Comment</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1STOP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>1STOP</label>
        <referenceTo>One_Stop__c</referenceTo>
        <relationshipName>X1STOPComments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>1STOPComment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>1STOPComment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>1STOPComments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OneSTOPCommentAddCom.cls
public class OneSTOPCommentAddCom {
   
    public string xComment {get;set;}   
   
    One_Stop__c request;       
    ApexPages.StandardController currentcontroller;    
    
   public OneSTOPCommentAddCom(ApexPages.StandardController controller) {
       request = (One_Stop__c)controller.getRecord();
        currentcontroller = controller;                    
    }
    
    public PageReference Save(){
       OneSTOPComment__c req = new OneSTOPComment__c(X1STOP__c = request.Id );              
                req.comment1__c = xComment;
                req.name__c = UserInfo.getName();
                insert req;
                update request;             
                return currentcontroller.view();
    }


}