src/objects/PIISitespageSettings__c.object
<CustomObject>
    <description>This object stores the selection made by the agent. It auto-generates a URL.</description>
    <fields>
        <fullName>Site_Id__c</fullName>
        <label>Site Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PIISitespageSettings</label>
    <nameField>
        <displayFormat>PII-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIISitespageSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sf_PIISitesPageSettingsTriggerHelper.cls
public with sharing class sf_PIISitesPageSettingsTriggerHelper {

public static void encodeSiteId(List<PIISitesPageSettings__c> piiSettings) {
   Blob blobRecId;
   string encodedRecId;
   List<PIISitespageSettings__c> objs = [select Id, Name from PIISitespageSettings__c where Id in: piiSettings];
   For(PIISitespageSettings__c obj : objs){
      blobRecId = Blob.valueOf(obj.Id);   
      encodedRecId = EncodingUtil.base64Encode(blobRecId);
      obj.Site_Id__c = encodedRecId;
   }
   update objs;
}
}